import type { Lesson } from './types';

/**
 * Banque CM2, mathématiques : dix-huit leçons qui couvrent les attendus de
 * fin de cycle 3 (grands nombres jusqu'au milliard, fractions et décimaux
 * jusqu'aux millièmes, opérations posées avec décimaux, division à deux
 * chiffres, proportionnalité et pourcentages, échelles et vitesse, tableaux
 * et graphiques, grandeurs, aires, durées, angles, volumes, géométrie plane,
 * symétrie, solides et repérage). Tout est neutre : l'univers habille à
 * l'affichage.
 */

const GRANDS_NOMBRES: Lesson = {
  id: 'cm2-maths-grands-nombres',
  title: "Les grands nombres jusqu'au milliard",
  subject: 'maths',
  source: 'numeration',
  level: 'CM2',
  notion: "Lire, écrire, décomposer et comparer les grands nombres jusqu'au milliard avec les classes des unités, des mille, des millions et des milliards",
  theme: 'nombres',
  attendu: "Lire, écrire, décomposer et comparer les grands nombres jusqu'au milliard.",
  attenduId: 'cm2-nb-grands',
  summary:
    "Un grand nombre se lit par classes de trois chiffres : milliards, millions, mille, unités. 2 345 600 000 se lit « deux milliards trois cent quarante-cinq millions six cent mille ». Un milliard, c'est mille millions : 1 000 000 000, un 1 suivi de neuf zéros.",
  minutes: 7,
  exercises: [
    {
      id: 'cm2-maths-grands-nombres-choice-1',
      kind: 'choice',
      prompt: "Comment s'écrit « trois millions deux cent mille cinquante » en chiffres ?",
      options: ['3 200 050', '3 020 050', '3 200 500'],
      answer: 0,
      explain: "Trois millions, c'est 3 dans la classe des millions. Deux cent mille, c'est 200 dans la classe des mille. Cinquante, c'est 050 dans la classe des unités : 3 200 050.",
    },
    {
      id: 'cm2-maths-grands-nombres-tf-1',
      kind: 'truefalse',
      statement: "Un milliard s'écrit avec un 1 suivi de neuf zéros.",
      answer: true,
      explain: "Oui : 1 000 000 000. Un milliard, c'est mille millions, et un million a déjà six zéros.",
    },
    {
      id: 'cm2-maths-grands-nombres-tap-1',
      kind: 'tapword',
      prompt: 'Touche le chiffre des unités de millions dans 48 325 760',
      words: ['4', '8', '3', '2', '5', '7', '6', '0'],
      answer: [1],
      explain: "La classe des millions, c'est 48 : le 8 compte les unités de millions et le 4 les dizaines de millions.",
    },
    {
      id: 'cm2-maths-grands-nombres-blanks-1',
      kind: 'blanks',
      prompt: 'Décompose le nombre',
      text: '7 405 230 = {{7 000 000}} + {{400 000}} + 5 000 + {{230}}',
      distractors: ['70 000 000', '40 000'],
      explain: "7 millions font 7 000 000, 4 centaines de mille font 400 000, 5 unités de mille font 5 000, et il reste 230.",
    },
    {
      id: 'cm2-maths-grands-nombres-sort-1',
      kind: 'sort',
      prompt: 'Range chaque nombre dans la bonne boîte',
      boxes: ["Moins d'un million", "Plus d'un million"],
      items: [
        { word: '999 999', box: 0 },
        { word: '1 000 001', box: 1 },
        { word: '850 000', box: 0 },
        { word: '12 000 000', box: 1 },
        { word: '100 000', box: 0 },
        { word: '2 500 000', box: 1 },
      ],
      explain: "Un million s'écrit avec sept chiffres. Un nombre à six chiffres ou moins est plus petit, un nombre à sept chiffres ou plus est plus grand.",
    },
    {
      id: 'cm2-maths-grands-nombres-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a mal écrit le nombre, corrige-le',
      words: ['Cinq', 'millions', 'trente', 'mille', '=', '5 300 000'],
      wrongIndex: 5,
      correct: '5 030 000',
      distractors: ['5 300 000', '530 000'],
      explain: "Cinq millions, c'est 5 000 000. Trente mille, c'est 030 dans la classe des mille. On écrit 5 030 000.",
    },
    {
      id: 'cm2-maths-grands-nombres-match-1',
      kind: 'match',
      prompt: 'Relie chaque nombre à son nom avant la fin du chrono',
      seconds: 50,
      pairs: [
        { a: '1 000 000 000', b: 'un milliard' },
        { a: '2 500 000', b: 'deux millions cinq cent mille' },
        { a: '60 000 000', b: 'soixante millions' },
        { a: '305 000', b: 'trois cent cinq mille' },
        { a: '12 000 000 000', b: 'douze milliards' },
      ],
      explain: "Lis chaque classe de trois chiffres avec son nom : milliards, millions, mille. Les zéros d'une classe entière ne se lisent pas.",
    },
    {
      id: 'cm2-maths-grands-nombres-choice-2',
      kind: 'choice',
      prompt: 'Quel est le plus grand de ces nombres ?',
      options: ['99 999 999', '100 000 000', '9 999 999'],
      answer: 1,
      explain: "100 000 000 a neuf chiffres, les autres en ont huit et sept. Plus un nombre a de chiffres, plus il est grand.",
    },
    {
      id: 'cm2-maths-grands-nombres-pairs-1',
      kind: 'pairs',
      prompt: 'Relie chaque nombre à son nombre de millions',
      pairs: [
        { a: '45 000 000', b: '45 millions' },
        { a: '4 500 000', b: '4 millions' },
        { a: '450 000 000', b: '450 millions' },
        { a: '1 000 000 000', b: '1 000 millions' },
      ],
      explain: "Le nombre de millions, ce sont tous les chiffres à gauche des six derniers. Un milliard, c'est mille millions.",
    },
    {
      id: 'cm2-maths-grands-nombres-tf-2',
      kind: 'truefalse',
      statement: '999 999 999 + 1 = 1 000 000 000.',
      answer: true,
      explain: "Oui : juste après 999 999 999 vient un milliard. Tous les 9 passent à 0 et un 1 apparaît devant.",
    },
  ],
};

const FRACTIONS: Lesson = {
  id: 'cm2-maths-fractions',
  title: 'Les fractions : comparer, encadrer, additionner',
  subject: 'maths',
  source: 'numeration',
  level: 'CM2',
  notion: "Comparer et encadrer des fractions, additionner des fractions de même dénominateur, écrire une fraction supérieure à 1 comme entier plus fraction",
  theme: 'nombres',
  attendu: 'Comparer, encadrer et additionner des fractions de même dénominateur ; écrire une fraction supérieure à 1 comme entier plus fraction.',
  attenduId: 'cm2-nb-fractions',
  summary:
    "Deux fractions de même dénominateur s'additionnent en ajoutant les numérateurs : deux cinquièmes plus un cinquième font trois cinquièmes. Une fraction plus grande que 1 s'écrit entier plus fraction : sept quarts, c'est quatre quarts plus trois quarts, donc 1 + 3/4. Pour l'encadrer, on cherche entre quels entiers elle se trouve : 7/4 est entre 1 et 2.",
  minutes: 7,
  exercises: [
    {
      id: 'cm2-maths-fractions-choice-1',
      kind: 'choice',
      prompt: 'Combien font deux cinquièmes plus un cinquième ?',
      options: ['trois dixièmes', 'trois cinquièmes', 'deux dixièmes'],
      answer: 1,
      explain: "Les parts sont des cinquièmes dans les deux fractions. On ajoute seulement les numérateurs : 2 + 1 = 3, cela fait trois cinquièmes. Le dénominateur ne change pas.",
    },
    {
      id: 'cm2-maths-fractions-tf-1',
      kind: 'truefalse',
      statement: "Sept quarts, c'est 1 plus trois quarts.",
      answer: true,
      explain: "Oui : quatre quarts font un entier. Il reste 7 − 4 = 3 quarts. Donc 7/4 = 1 + 3/4.",
    },
    {
      id: 'cm2-maths-fractions-line-1',
      kind: 'numberline',
      prompt: 'Place la fraction sept quarts',
      min: 0,
      max: 2,
      step: 0.25,
      answer: 1.75,
      explain: "Chaque graduation vaut un quart. Sept quarts, c'est 7 graduations après 0 : un entier et trois quarts.",
    },
    {
      id: 'cm2-maths-fractions-blanks-1',
      kind: 'blanks',
      prompt: 'Écris la fraction comme entier plus fraction',
      text: "Onze tiers, c'est {{3}} entiers plus {{deux tiers}}.",
      distractors: ['4', 'un tiers'],
      explain: "Trois tiers font un entier. Dans onze tiers, il y a 3 fois trois tiers, soit 9 tiers, et il reste 11 − 9 = 2 tiers.",
    },
    {
      id: 'cm2-maths-fractions-sort-1',
      kind: 'sort',
      prompt: 'Range chaque fraction dans la bonne boîte',
      boxes: ['Entre 0 et 1', 'Entre 1 et 2', 'Plus grande que 2'],
      items: [
        { word: 'trois quarts', box: 0 },
        { word: 'cinq quarts', box: 1 },
        { word: 'neuf quarts', box: 2 },
        { word: 'deux tiers', box: 0 },
        { word: 'sept cinquièmes', box: 1 },
        { word: 'sept tiers', box: 2 },
      ],
      explain: "Compare le numérateur au dénominateur : plus petit, la fraction est sous 1 ; entre une fois et deux fois le dénominateur, elle est entre 1 et 2 ; au-delà, elle dépasse 2.",
    },
    {
      id: 'cm2-maths-fractions-fix-1',
      kind: 'fix',
      prompt: "Gribouille s'est trompé, corrige-le",
      words: ['Trois', 'huitièmes', '+', 'deux', 'huitièmes', '=', 'cinq seizièmes'],
      wrongIndex: 6,
      correct: 'cinq huitièmes',
      distractors: ['cinq seizièmes', 'six huitièmes'],
      explain: "Quand les dénominateurs sont les mêmes, on additionne seulement les numérateurs : 3 + 2 = 5. Les parts restent des huitièmes.",
    },
    {
      id: 'cm2-maths-fractions-pairs-1',
      kind: 'pairs',
      prompt: 'Relie chaque fraction à son encadrement',
      pairs: [
        { a: 'sept quarts', b: 'entre 1 et 2' },
        { a: 'treize cinquièmes', b: 'entre 2 et 3' },
        { a: 'quatre dixièmes', b: 'entre 0 et 1' },
        { a: 'dix tiers', b: 'entre 3 et 4' },
      ],
      explain: "Cherche combien de fois le dénominateur entre dans le numérateur : 13 cinquièmes, c'est 2 entiers (10 cinquièmes) et il reste 3 cinquièmes.",
    },
    {
      id: 'cm2-maths-fractions-choice-2',
      kind: 'choice',
      prompt: 'Quelle fraction est la plus grande ?',
      options: ['cinq huitièmes', 'trois huitièmes', 'sept huitièmes'],
      answer: 2,
      explain: "Les parts sont toutes des huitièmes. Celle qui en prend le plus est la plus grande : sept huitièmes.",
    },
    {
      id: 'cm2-maths-fractions-line-2',
      kind: 'numberline',
      prompt: 'Place la fraction cinq quarts',
      min: 0,
      max: 2,
      step: 0.25,
      answer: 1.25,
      explain: "Cinq quarts, c'est quatre quarts, donc 1, plus un quart : une graduation après 1.",
    },
    {
      id: 'cm2-maths-fractions-tf-2',
      kind: 'truefalse',
      statement: 'Trois quarts est plus grand que trois cinquièmes.',
      answer: true,
      explain: "Oui : on prend 3 parts dans les deux cas, mais un quart est une part plus grande qu'un cinquième. Trois quarts, c'est 0,75 ; trois cinquièmes, c'est 0,6.",
    },
  ],
};

const DECIMAUX: Lesson = {
  id: 'cm2-maths-decimaux',
  title: "Les décimaux jusqu'aux millièmes",
  subject: 'maths',
  source: 'numeration',
  level: 'CM2',
  notion: "Lire, écrire, comparer et arrondir les nombres décimaux jusqu'aux millièmes ; passer de la fraction décimale à l'écriture à virgule",
  theme: 'nombres',
  attendu: "Lire, écrire, comparer, arrondir les nombres décimaux jusqu'aux millièmes ; passer de la fraction décimale à l'écriture à virgule.",
  attenduId: 'cm2-nb-decimaux',
  summary:
    "Après la virgule viennent les dixièmes, les centièmes, puis les millièmes : 2,345, c'est 2 + 3 dixièmes + 4 centièmes + 5 millièmes. Pour comparer, on regarde la partie entière, puis les dixièmes, puis les centièmes. Arrondir 3,47 au dixième donne 3,5, parce que 7 centièmes, c'est plus que la moitié d'un dixième.",
  minutes: 7,
  exercises: [
    {
      id: 'cm2-maths-decimaux-choice-1',
      kind: 'choice',
      prompt: "Comment s'écrit « quatre millièmes » avec une virgule ?",
      options: ['0,4', '0,04', '0,004'],
      answer: 2,
      explain: "Les millièmes sont au troisième rang après la virgule. Quatre millièmes, c'est 0,004. 0,4, c'est quatre dixièmes, cent fois plus.",
    },
    {
      id: 'cm2-maths-decimaux-tf-1',
      kind: 'truefalse',
      statement: 'Dans 5,208, le chiffre 8 est le chiffre des millièmes.',
      answer: true,
      explain: "Oui : après la virgule, 2 est aux dixièmes, 0 aux centièmes et 8 aux millièmes.",
    },
    {
      id: 'cm2-maths-decimaux-line-1',
      kind: 'numberline',
      prompt: 'Place le nombre 0,6',
      min: 0,
      max: 1,
      step: 0.1,
      answer: 0.6,
      explain: "Entre 0 et 1, chaque graduation vaut un dixième. 0,6, c'est 6 graduations après 0.",
    },
    {
      id: 'cm2-maths-decimaux-blanks-1',
      kind: 'blanks',
      prompt: 'Décompose le nombre',
      text: '3,472 = 3 + {{4}} dixièmes + {{7}} centièmes + {{2}} millièmes',
      distractors: ['47', '72'],
      explain: "Le premier chiffre après la virgule compte les dixièmes, le deuxième les centièmes, le troisième les millièmes.",
    },
    {
      id: 'cm2-maths-decimaux-sort-1',
      kind: 'sort',
      prompt: 'Range chaque nombre dans la bonne boîte',
      boxes: ['Plus petit que 2,5', 'Plus grand que 2,5'],
      items: [
        { word: '2,45', box: 0 },
        { word: '2,05', box: 0 },
        { word: '2,51', box: 1 },
        { word: '2,499', box: 0 },
        { word: '2,6', box: 1 },
        { word: '2,505', box: 1 },
      ],
      explain: "La partie entière est 2 partout, on compare donc les dixièmes : moins de 5, c'est plus petit. Avec 5 dixièmes, on regarde la suite : 2,499 est juste en dessous, 2,505 juste au-dessus.",
    },
    {
      id: 'cm2-maths-decimaux-fix-1',
      kind: 'fix',
      prompt: "Gribouille s'est trompé en arrondissant, corrige-le",
      words: ['12,37', 'arrondi', 'au', 'dixième', '=', '12,3'],
      wrongIndex: 5,
      correct: '12,4',
      distractors: ['12,3', '12,30'],
      explain: "12,37 est entre 12,3 et 12,4. Comme 7 centièmes, c'est plus que 5, on arrondit au-dessus : 12,4.",
    },
    {
      id: 'cm2-maths-decimaux-pairs-1',
      kind: 'pairs',
      prompt: 'Relie chaque fraction décimale à son écriture à virgule',
      pairs: [
        { a: 'vingt-cinq centièmes', b: '0,25' },
        { a: 'sept millièmes', b: '0,007' },
        { a: 'trois dixièmes', b: '0,3' },
        { a: 'cent vingt-cinq millièmes', b: '0,125' },
      ],
      explain: "Des dixièmes, c'est un chiffre après la virgule ; des centièmes, deux chiffres ; des millièmes, trois chiffres. On complète avec des zéros si besoin.",
    },
    {
      id: 'cm2-maths-decimaux-choice-2',
      kind: 'choice',
      prompt: 'Quel nombre est le plus grand ?',
      options: ['0,8', '0,75', '0,799'],
      answer: 0,
      explain: "On compare les dixièmes : 8, 7 et 7. Le plus grand est 0,8, même s'il a moins de chiffres. 0,799 est juste en dessous de 0,8.",
    },
    {
      id: 'cm2-maths-decimaux-line-2',
      kind: 'numberline',
      prompt: 'Place le nombre 2,3',
      min: 2,
      max: 3,
      step: 0.1,
      answer: 2.3,
      explain: "La droite va de 2 à 3 par dixièmes. 2,3, c'est 3 graduations après 2.",
    },
    {
      id: 'cm2-maths-decimaux-tf-2',
      kind: 'truefalse',
      statement: "7,82 arrondi à l'unité donne 8.",
      answer: true,
      explain: "Oui : 7,82 est entre 7 et 8, et comme 82 centièmes dépasse la moitié, il est plus proche de 8.",
    },
  ],
};

const CALCUL_MENTAL: Lesson = {
  id: 'cm2-maths-calcul-mental',
  title: 'Calcul mental avec les décimaux',
  subject: 'maths',
  source: 'calcul',
  level: 'CM2',
  notion: "Multiplier et diviser des décimaux par 10, 100, 1 000, multiplier par 0,5, estimer un ordre de grandeur",
  theme: 'calcul',
  attendu: 'Calculer mentalement avec des entiers et des décimaux : multiplier et diviser par 10, 100, 1 000, par 0,1 et 0,5, estimer un ordre de grandeur.',
  attenduId: 'cm2-calc-mental',
  summary:
    "Multiplier un décimal par 10, c'est décaler la virgule d'un rang vers la droite : 3,45 × 10 = 34,5. Diviser par 10, c'est la décaler vers la gauche : 27 : 10 = 2,7. Multiplier par 0,5, c'est prendre la moitié : 46 × 0,5 = 23. Avant de calculer, on estime l'ordre de grandeur : 49 × 21, c'est à peu près 50 × 20 = 1 000.",
  minutes: 6,
  exercises: [
    {
      id: 'cm2-maths-calcul-mental-choice-1',
      kind: 'choice',
      prompt: 'Combien font 3,45 × 10 ?',
      options: ['34,5', '3,450', '345'],
      answer: 0,
      explain: "Multiplier par 10, c'est décaler la virgule d'un rang vers la droite : 3,45 devient 34,5.",
    },
    {
      id: 'cm2-maths-calcul-mental-tf-1',
      kind: 'truefalse',
      statement: '27 : 10 = 2,7.',
      answer: true,
      explain: "Oui : diviser par 10, c'est décaler la virgule d'un rang vers la gauche. 27, c'est 27,0, qui devient 2,7.",
    },
    {
      id: 'cm2-maths-calcul-mental-blanks-1',
      kind: 'blanks',
      prompt: 'Complète les calculs',
      text: '2,5 × 100 = {{250}} et 480 : 100 = {{4,8}}.',
      distractors: ['25', '48'],
      explain: "Par 100, la virgule se décale de deux rangs : 2,5 devient 250 et 480 devient 4,80, c'est-à-dire 4,8.",
    },
    {
      id: 'cm2-maths-calcul-mental-pairs-1',
      kind: 'pairs',
      prompt: 'Relie chaque calcul à son résultat',
      pairs: [
        { a: '46 × 0,5', b: '23' },
        { a: '8 × 0,5', b: '4' },
        { a: '15 × 0,5', b: '7,5' },
        { a: '0,5 × 100', b: '50' },
      ],
      explain: "Multiplier par 0,5, c'est prendre la moitié. La moitié de 15, c'est 7,5. Et 0,5 × 100, c'est 0,5 avec la virgule décalée de deux rangs : 50.",
    },
    {
      id: 'cm2-maths-calcul-mental-fix-1',
      kind: 'fix',
      prompt: "Gribouille s'est trompé, corrige-le",
      words: ['6,2', '×', '1 000', '=', '620'],
      wrongIndex: 4,
      correct: '6 200',
      distractors: ['620', '62 000'],
      explain: "Par 1 000, la virgule se décale de trois rangs : 6,2 devient 62, puis 620, puis 6 200.",
    },
    {
      id: 'cm2-maths-calcul-mental-sort-1',
      kind: 'sort',
      prompt: "Sans calculer exactement, range chaque calcul selon son ordre de grandeur",
      boxes: ['Environ 100', 'Environ 1 000'],
      items: [
        { word: '49 × 2', box: 0 },
        { word: '51 × 19', box: 1 },
        { word: '198 + 805', box: 1 },
        { word: '1 004 − 897', box: 0 },
        { word: '11 × 9', box: 0 },
        { word: '2 × 498', box: 1 },
      ],
      explain: "On remplace chaque nombre par un nombre rond proche : 51 × 19, c'est presque 50 × 20 = 1 000 ; 1 004 − 897, c'est presque 1 000 − 900 = 100.",
    },
    {
      id: 'cm2-maths-calcul-mental-choice-2',
      kind: 'choice',
      prompt: "Quel est l'ordre de grandeur de 39 × 21 ?",
      options: ['environ 80', 'environ 800', 'environ 8 000'],
      answer: 1,
      explain: "39 est proche de 40 et 21 est proche de 20. 40 × 20 = 800. Le résultat exact est 819.",
    },
    {
      id: 'cm2-maths-calcul-mental-tap-1',
      kind: 'tapword',
      prompt: 'Touche le calcul qui est faux',
      words: ['1,5 × 10 = 15', '0,7 × 100 = 7', '3 : 10 = 0,3'],
      answer: [1],
      explain: "0,7 × 100 = 70, pas 7 : par 100, la virgule se décale de deux rangs. Les deux autres calculs sont justes.",
    },
    {
      id: 'cm2-maths-calcul-mental-speed-1',
      kind: 'speed',
      prompt: 'Calcul éclair : virgule qui bouge et moitiés',
      seconds: 60,
      target: 7,
      items: [
        { q: '4,5 × 10', a: 45 },
        { q: '320 : 10', a: 32 },
        { q: '0,8 × 100', a: 80 },
        { q: '12 × 0,5', a: 6 },
        { q: '2,5 × 1 000', a: 2500 },
        { q: '90 : 10', a: 9 },
        { q: '0,06 × 100', a: 6 },
        { q: '30 × 0,5', a: 15 },
        { q: '1 000 × 0,5', a: 500 },
        { q: '7,3 × 10', a: 73 },
      ],
      explain: "Pas grave : × 10, × 100, × 1 000 décalent la virgule vers la droite ; : 10 la décale vers la gauche ; × 0,5, c'est la moitié.",
    },
    {
      id: 'cm2-maths-calcul-mental-tf-2',
      kind: 'truefalse',
      statement: "Multiplier par 0,5, c'est la même chose que diviser par 2.",
      answer: true,
      explain: "Oui : 0,5, c'est un demi. Prendre un demi d'un nombre, c'est prendre sa moitié, donc le diviser par 2.",
    },
  ],
};

const OPERATIONS: Lesson = {
  id: 'cm2-maths-operations',
  title: 'Opérations posées avec les décimaux',
  subject: 'maths',
  source: 'calcul',
  level: 'CM2',
  notion: 'Poser une addition, une soustraction et une multiplication de nombres décimaux',
  theme: 'calcul',
  attendu: 'Poser addition, soustraction et multiplication de nombres décimaux.',
  attenduId: 'cm2-calc-operations',
  summary:
    "Pour additionner ou soustraire des décimaux, on aligne les virgules. Pour multiplier 3,2 × 4, on calcule 32 × 4 = 128, puis on remet la virgule : 3,2 a un chiffre après la virgule, donc le résultat aussi : 12,8. Pour 2,5 × 1,2, on calcule 25 × 12 = 300, puis on place deux chiffres après la virgule : 3,00, c'est 3.",
  minutes: 8,
  exercises: [
    {
      id: 'cm2-maths-operations-choice-1',
      kind: 'choice',
      prompt: 'Combien font 3,2 × 4 ?',
      options: ['12,8', '128', '1,28'],
      answer: 0,
      explain: "32 × 4 = 128. Il y a un chiffre après la virgule dans 3,2, donc un chiffre après la virgule dans le résultat : 12,8.",
    },
    {
      id: 'cm2-maths-operations-tf-1',
      kind: 'truefalse',
      statement: '2,5 × 1,2 = 3.',
      answer: true,
      explain: "Oui : 25 × 12 = 300. Un chiffre après la virgule dans 2,5 et un dans 1,2, cela fait deux chiffres : 3,00, c'est 3.",
    },
    {
      id: 'cm2-maths-operations-order-1',
      kind: 'order',
      prompt: "Remets dans l'ordre les étapes de la multiplication 4,6 × 3",
      lines: [
        'Je calcule sans la virgule : 46 × 3 = 138',
        'Je compte les chiffres après la virgule dans 4,6 : un seul',
        'Je place la virgule dans le résultat : 13,8',
        "Je vérifie l'ordre de grandeur : 4,6 × 3, c'est proche de 5 × 3 = 15",
      ],
      explain: "On multiplie d'abord comme avec des entiers, on compte ensuite les chiffres après la virgule, on place la virgule et on vérifie que le résultat est raisonnable.",
    },
    {
      id: 'cm2-maths-operations-blanks-1',
      kind: 'blanks',
      prompt: 'Complète les calculs',
      text: '7,35 + 2,8 = {{10,15}} et 9,4 − 3,65 = {{5,75}}.',
      distractors: ['10,43', '6,25'],
      explain: "On aligne les virgules : 7,35 + 2,80 = 10,15. Pour la soustraction, 9,40 − 3,65 : aux centièmes 10 − 5 = 5, aux dixièmes 13 − 6 = 7, aux unités 8 − 3 = 5. Résultat : 5,75.",
    },
    {
      id: 'cm2-maths-operations-fix-1',
      kind: 'fix',
      prompt: "Gribouille s'est trompé, corrige-le",
      words: ['1,5', '×', '6', '=', '90'],
      wrongIndex: 4,
      correct: '9',
      distractors: ['90', '0,9'],
      explain: "15 × 6 = 90, puis on remet la virgule : un chiffre après la virgule, donc 9,0, c'est 9. Et c'est logique : 1,5 × 6, c'est un peu plus que 1 × 6.",
    },
    {
      id: 'cm2-maths-operations-pairs-1',
      kind: 'pairs',
      prompt: 'Relie chaque calcul à son résultat',
      pairs: [
        { a: '0,25 × 4', b: '1' },
        { a: '1,5 × 1,5', b: '2,25' },
        { a: '12,5 + 7,5', b: '20' },
        { a: '10 − 2,75', b: '7,25' },
      ],
      explain: "Quatre quarts font 1. 15 × 15 = 225, avec deux chiffres après la virgule : 2,25. 12,5 + 7,5 = 20. 10 − 2,75 = 7,25.",
    },
    {
      id: 'cm2-maths-operations-choice-2',
      kind: 'choice',
      prompt: 'Combien font 24,6 × 2,5 ?',
      options: ['61,5', '615', '6,15'],
      answer: 0,
      explain: "246 × 25 = 6 150. Deux chiffres après la virgule en tout, donc 61,50, c'est 61,5. Ordre de grandeur : 25 × 2,5, c'est un peu plus de 60.",
    },
    {
      id: 'cm2-maths-operations-tap-1',
      kind: 'tapword',
      prompt: "Touche l'opération qui est juste",
      words: ['0,6 × 0,5 = 3', '0,6 × 0,5 = 0,3', '0,6 × 0,5 = 0,03'],
      answer: [1],
      explain: "6 × 5 = 30. Il y a deux chiffres après la virgule en tout, donc 0,30, c'est 0,3. C'est la moitié de 0,6.",
    },
    {
      id: 'cm2-maths-operations-tf-2',
      kind: 'truefalse',
      statement: '4,25 + 3,5 = 4,60.',
      answer: false,
      explain: "Il faut aligner les virgules : 4,25 + 3,50 = 7,75. L'erreur, c'est d'avoir ajouté 3,5 comme si c'était 35 centièmes.",
    },
    {
      id: 'cm2-maths-operations-choice-3',
      kind: 'choice',
      prompt: 'Un paquet de riz pèse 1,25 kg. Combien pèsent 4 paquets ?',
      options: ['4,100 kg', '5 kg', '4,25 kg'],
      answer: 1,
      explain: "125 × 4 = 500, avec deux chiffres après la virgule : 5,00 kg, c'est 5 kg. Quatre fois un kilo et quart, c'est cinq kilos.",
    },
  ],
};

const DIVISION: Lesson = {
  id: 'cm2-maths-division',
  title: 'La division à deux chiffres et le quotient décimal',
  subject: 'maths',
  source: 'calcul',
  level: 'CM2',
  notion: 'Poser une division à deux chiffres au diviseur et continuer la division après la virgule pour obtenir un quotient décimal',
  theme: 'calcul',
  attendu: 'Poser une division à deux chiffres au diviseur et une division décimale (quotient décimal).',
  attenduId: 'cm2-calc-division',
  summary:
    "Pour diviser par un nombre à deux chiffres, comme 345 : 15, on cherche combien de fois 15 dans 34 : 2 fois, il reste 4 ; on abaisse le 5, cela fait 45, et 15 × 3 = 45. Le quotient est 23. Quand il reste quelque chose, on peut continuer après la virgule : 13 : 4 = 3,25, car 13 = 4 × 3 + 1, et 1 partagé en 4, c'est 0,25.",
  minutes: 8,
  exercises: [
    {
      id: 'cm2-maths-division-choice-1',
      kind: 'choice',
      prompt: 'Combien font 13 : 4 ?',
      options: ['3,25', '3,1', '3,5'],
      answer: 0,
      explain: "4 × 3 = 12, il reste 1. On continue : 1, c'est 10 dixièmes, 10 : 4 = 2 et il reste 2 ; 2, c'est 20 centièmes, 20 : 4 = 5. Le quotient est 3,25.",
    },
    {
      id: 'cm2-maths-division-tf-1',
      kind: 'truefalse',
      statement: 'Dans 345 : 15, le quotient est 23.',
      answer: true,
      explain: "Oui : 15 × 23 = 15 × 20 + 15 × 3 = 300 + 45 = 345. Le reste est 0.",
    },
    {
      id: 'cm2-maths-division-blanks-1',
      kind: 'blanks',
      prompt: 'Complète la division de 552 par 24',
      text: '24 × {{2}} = 48, il reste 55 − 48 = 7. On abaisse le 2 : 72 = 24 × {{3}}. Le quotient est {{23}}.',
      distractors: ['4', '32'],
      explain: "Dans 55, il y a 2 fois 24, et 24 × 3 = 72 serait trop grand. Puis 72, c'est exactement 3 fois 24. On lit le quotient : 23.",
    },
    {
      id: 'cm2-maths-division-fix-1',
      kind: 'fix',
      prompt: "Gribouille s'est trompé, corrige-le",
      words: ['21', ':', '4', '=', '5,5'],
      wrongIndex: 4,
      correct: '5,25',
      distractors: ['5,5', '5,1'],
      explain: "4 × 5 = 20, il reste 1. Et 1 partagé en 4, c'est un quart, soit 0,25. Le quotient est 5,25. Vérification : 4 × 5,25 = 21.",
    },
    {
      id: 'cm2-maths-division-pairs-1',
      kind: 'pairs',
      prompt: 'Relie chaque division à son quotient décimal',
      pairs: [
        { a: '7 : 2', b: '3,5' },
        { a: '9 : 4', b: '2,25' },
        { a: '12 : 5', b: '2,4' },
        { a: '1 : 8', b: '0,125' },
      ],
      explain: "La moitié de 7, c'est 3,5. 9 : 4, c'est 2 et un quart. 12 : 5, c'est 2 et 2 cinquièmes, soit 2,4. Un huitième, c'est 0,125.",
    },
    {
      id: 'cm2-maths-division-sort-1',
      kind: 'sort',
      prompt: 'Range chaque division dans la bonne boîte',
      boxes: ['Reste 0', 'Reste différent de 0'],
      items: [
        { word: '144 : 12', box: 0 },
        { word: '150 : 12', box: 1 },
        { word: '225 : 15', box: 0 },
        { word: '200 : 15', box: 1 },
        { word: '400 : 25', box: 0 },
        { word: '410 : 25', box: 1 },
      ],
      explain: "Le reste est 0 quand le nombre est un multiple du diviseur : 144 = 12 × 12, 225 = 15 × 15, 400 = 25 × 16. Les autres tombent entre deux multiples.",
    },
    {
      id: 'cm2-maths-division-choice-2',
      kind: 'choice',
      prompt: 'On partage 5 € entre 4 enfants, à égalité. Combien reçoit chacun ?',
      options: ['1,20 €', '1,25 €', '1,40 €'],
      answer: 1,
      explain: "5 : 4 = 1,25. Chacun reçoit 1 €, et le dernier euro partagé en 4 donne 25 centimes à chacun.",
    },
    {
      id: 'cm2-maths-division-order-1',
      kind: 'order',
      prompt: "Remets dans l'ordre les étapes de la division posée 816 : 24",
      lines: [
        'Combien de fois 24 dans 81 ? 3 fois, car 24 × 3 = 72',
        'Il reste 81 − 72 = 9',
        "J'abaisse le 6 : cela fait 96",
        '96 = 24 × 4, il reste 0',
        'Le quotient est 34',
      ],
      explain: "On commence par les deux premiers chiffres, on soustrait, on abaisse le chiffre suivant, et on lit le quotient à la fin : 24 × 34 = 816.",
    },
    {
      id: 'cm2-maths-division-tf-2',
      kind: 'truefalse',
      statement: 'Dans 500 : 32, le quotient est 15 et le reste est 20.',
      answer: true,
      explain: "Oui : 32 × 15 = 480, et 500 − 480 = 20. Le reste 20 est bien plus petit que 32.",
    },
    {
      id: 'cm2-maths-division-tap-1',
      kind: 'tapword',
      prompt: "Touche l'égalité qui est juste",
      words: ['11 : 4 = 2,75', '11 : 4 = 2,5', '11 : 4 = 2,25'],
      answer: [0],
      explain: "4 × 2 = 8, il reste 3, et 3 quarts, c'est 0,75. Donc 11 : 4 = 2,75. Vérification : 4 × 2,75 = 11.",
    },
  ],
};

const PROPORTIONNALITE: Lesson = {
  id: 'cm2-maths-proportionnalite',
  title: 'Proportionnalité et pourcentages',
  subject: 'maths',
  source: 'calcul',
  level: 'CM2',
  notion: "Résoudre des problèmes de proportionnalité en passant par l'unité et calculer des pourcentages simples",
  theme: 'calcul',
  attendu: "Résoudre des problèmes de proportionnalité (passage par l'unité, pourcentages simples, échelles, vitesse) et des problèmes à plusieurs étapes.",
  attenduId: 'cm2-calc-problemes',
  summary:
    "Quand c'est proportionnel, on peut passer par l'unité : si 3 cahiers coûtent 7,50 €, un cahier coûte 2,50 €, donc 5 cahiers coûtent 12,50 €. Un pourcentage, c'est une part sur 100 : 50 %, c'est la moitié ; 25 %, c'est le quart ; 10 %, c'est un dixième. 10 % de 80, c'est 8.",
  minutes: 8,
  exercises: [
    {
      id: 'cm2-maths-proportionnalite-choice-1',
      kind: 'choice',
      prompt: '3 cahiers coûtent 7,50 €. Combien coûtent 5 cahiers ?',
      options: ['12,50 €', '10,50 €', '15 €'],
      answer: 0,
      explain: "On passe par l'unité : un cahier coûte 7,50 : 3 = 2,50 €. Cinq cahiers coûtent 5 × 2,50 = 12,50 €.",
    },
    {
      id: 'cm2-maths-proportionnalite-tf-1',
      kind: 'truefalse',
      statement: "25 % de 80, c'est 20.",
      answer: true,
      explain: "Oui : 25 %, c'est un quart. Le quart de 80, c'est 80 : 4 = 20.",
    },
    {
      id: 'cm2-maths-proportionnalite-blanks-1',
      kind: 'blanks',
      prompt: "Complète en passant par l'unité",
      text: '4 kg de pommes coûtent 10 €. Un kilo coûte {{2,50}} € et 7 kg coûtent {{17,50}} €.',
      distractors: ['2,25', '14'],
      explain: "10 : 4 = 2,50 € le kilo. Pour 7 kg : 7 × 2,50 = 17,50 €.",
    },
    {
      id: 'cm2-maths-proportionnalite-pairs-1',
      kind: 'pairs',
      prompt: 'Relie chaque pourcentage à sa valeur',
      pairs: [
        { a: '50 % de 60', b: '30' },
        { a: '10 % de 250', b: '25' },
        { a: '25 % de 40', b: '10' },
        { a: '100 % de 15', b: '15' },
      ],
      explain: "50 %, c'est la moitié ; 10 %, c'est un dixième ; 25 %, c'est un quart ; 100 %, c'est tout.",
    },
    {
      id: 'cm2-maths-proportionnalite-fix-1',
      kind: 'fix',
      prompt: "Gribouille s'est trompé, corrige-le",
      words: ['Pour', '2', 'personnes,', '150 g', 'de', 'riz.', 'Pour', '5', 'personnes,', '300 g'],
      wrongIndex: 9,
      correct: '375 g',
      distractors: ['300 g', '450 g'],
      explain: "Pour 1 personne, il faut 150 : 2 = 75 g. Pour 5 personnes, 5 × 75 = 375 g.",
    },
    {
      id: 'cm2-maths-proportionnalite-sort-1',
      kind: 'sort',
      prompt: 'Est-ce une situation de proportionnalité ? Range chaque phrase',
      boxes: ['Proportionnel', 'Pas proportionnel'],
      items: [
        { word: '2 stylos : 3 €, 6 stylos : 9 €', box: 0 },
        { word: '1 h : 60 km, 3 h : 180 km', box: 0 },
        { word: '5 ans : 110 cm, 10 ans : 220 cm', box: 1 },
        { word: '4 billets : 20 €, 8 billets : 36 €', box: 1 },
        { word: '3 L : 4,50 €, 1 L : 1,50 €', box: 0 },
      ],
      explain: "C'est proportionnel quand on multiplie les deux quantités par le même nombre. La taille ne double pas avec l'âge, et 8 billets devraient coûter 40 €, pas 36.",
    },
    {
      id: 'cm2-maths-proportionnalite-choice-2',
      kind: 'choice',
      prompt: 'Un jean coûte 60 €. Il est soldé de 10 %. Combien coûte-t-il après la remise ?',
      options: ['6 €', '54 €', '50 €'],
      answer: 1,
      explain: "10 % de 60, c'est 6 € de remise. Le jean coûte 60 − 6 = 54 €.",
    },
    {
      id: 'cm2-maths-proportionnalite-choice-3',
      kind: 'choice',
      prompt: '6 œufs coûtent 1,80 €. Combien coûtent 10 œufs ?',
      options: ['2,80 €', '3 €', '3,60 €'],
      answer: 1,
      explain: "Un œuf coûte 1,80 : 6 = 0,30 €. Dix œufs coûtent 10 × 0,30 = 3 €.",
    },
    {
      id: 'cm2-maths-proportionnalite-tf-2',
      kind: 'truefalse',
      statement: 'Si 12 bouteilles pèsent 18 kg, alors 4 bouteilles pèsent 6 kg.',
      answer: true,
      explain: "Oui : 4 bouteilles, c'est 3 fois moins que 12. La masse est aussi divisée par 3 : 18 : 3 = 6 kg.",
    },
    {
      id: 'cm2-maths-proportionnalite-tap-1',
      kind: 'tapword',
      prompt: 'Touche le calcul qui donne 50 % de 90',
      words: ['90 : 4', '90 : 2', '90 × 2'],
      answer: [1],
      explain: "50 %, c'est la moitié : 90 : 2 = 45. Diviser par 4 donnerait 25 %, et multiplier par 2 donnerait 200 %.",
    },
  ],
};

const ECHELLES_VITESSE: Lesson = {
  id: 'cm2-maths-echelles-vitesse',
  title: 'Échelles, vitesse et problèmes à étapes',
  subject: 'maths',
  source: 'calcul',
  level: 'CM2',
  notion: "Utiliser une échelle, raisonner avec une vitesse et résoudre un problème à plusieurs étapes",
  theme: 'calcul',
  attendu: "Résoudre des problèmes de proportionnalité (passage par l'unité, pourcentages simples, échelles, vitesse) et des problèmes à plusieurs étapes.",
  attenduId: 'cm2-calc-problemes',
  summary:
    "Sur un plan à l'échelle 1/100, 1 cm sur le papier vaut 100 cm en vrai, soit 1 m. La vitesse dit la distance parcourue en une heure : à 80 km/h, on fait 80 km en 1 h, 160 km en 2 h, 40 km en une demi-heure. Un problème à étapes se résout une étape après l'autre, en notant chaque résultat.",
  minutes: 8,
  exercises: [
    {
      id: 'cm2-maths-echelles-vitesse-choice-1',
      kind: 'choice',
      prompt: "Sur un plan à l'échelle 1/100, un mur mesure 5 cm. Quelle est sa vraie longueur ?",
      options: ['50 cm', '5 m', '50 m'],
      answer: 1,
      explain: "À l'échelle 1/100, tout est 100 fois plus grand en vrai : 5 × 100 = 500 cm, soit 5 m.",
    },
    {
      id: 'cm2-maths-echelles-vitesse-tf-1',
      kind: 'truefalse',
      statement: 'Une voiture qui roule à 80 km/h parcourt 160 km en 2 heures.',
      answer: true,
      explain: "Oui : 80 km chaque heure, donc 2 × 80 = 160 km en 2 heures.",
    },
    {
      id: 'cm2-maths-echelles-vitesse-blanks-1',
      kind: 'blanks',
      prompt: 'Complète avec la vitesse',
      text: 'Un train roule à 120 km/h. En 3 h, il parcourt {{360}} km. En une demi-heure, il parcourt {{60}} km.',
      distractors: ['240', '40'],
      explain: "3 × 120 = 360 km. Une demi-heure, c'est la moitié d'une heure, donc la moitié de 120 : 60 km.",
    },
    {
      id: 'cm2-maths-echelles-vitesse-order-1',
      kind: 'order',
      prompt: "Lucas achète 3 cahiers à 2,50 € et un stylo à 1,80 €. Il paie avec un billet de 10 €. Remets les étapes dans l'ordre",
      lines: [
        'Prix des cahiers : 3 × 2,50 = 7,50 €',
        'Total des achats : 7,50 + 1,80 = 9,30 €',
        'Monnaie rendue : 10 − 9,30 = 0,70 €',
        'Réponse : on lui rend 70 centimes',
      ],
      explain: "D'abord le prix des cahiers, puis le total, puis ce qui reste sur le billet, et on termine par la phrase réponse.",
    },
    {
      id: 'cm2-maths-echelles-vitesse-pairs-1',
      kind: 'pairs',
      prompt: 'Relie chaque mesure sur le plan à la vraie longueur',
      pairs: [
        { a: 'Échelle 1/100 : 3 cm', b: '3 m' },
        { a: 'Échelle 1/1 000 : 3 cm', b: '30 m' },
        { a: 'Échelle 1/10 : 3 cm', b: '30 cm' },
        { a: 'Échelle 1/100 000 : 3 cm', b: '3 km' },
      ],
      explain: "On multiplie par le nombre de l'échelle : 3 × 1 000 = 3 000 cm = 30 m ; 3 × 100 000 = 300 000 cm = 3 km.",
    },
    {
      id: 'cm2-maths-echelles-vitesse-fix-1',
      kind: 'fix',
      prompt: "Gribouille s'est trompé, corrige-le",
      words: ['À', '60 km/h,', 'en', '1 h 30,', 'on', 'parcourt', '120 km'],
      wrongIndex: 6,
      correct: '90 km',
      distractors: ['120 km', '75 km'],
      explain: "En 1 h, 60 km. En une demi-heure, la moitié : 30 km. En 1 h 30 : 60 + 30 = 90 km.",
    },
    {
      id: 'cm2-maths-echelles-vitesse-choice-2',
      kind: 'choice',
      prompt: 'Un cycliste parcourt 45 km en 3 heures, toujours à la même allure. Quelle est sa vitesse ?',
      options: ['15 km/h', '45 km/h', '135 km/h'],
      answer: 0,
      explain: "La vitesse, c'est la distance en une heure : 45 : 3 = 15 km chaque heure, donc 15 km/h.",
    },
    {
      id: 'cm2-maths-echelles-vitesse-sort-1',
      kind: 'sort',
      prompt: 'Le trajet dure-t-il moins ou plus de une heure ? Range chaque trajet',
      boxes: ["Moins d'une heure", "Plus d'une heure"],
      items: [
        { word: '50 km à 100 km/h', box: 0 },
        { word: '90 km à 60 km/h', box: 1 },
        { word: '30 km à 15 km/h', box: 1 },
        { word: '20 km à 80 km/h', box: 0 },
        { word: '120 km à 80 km/h', box: 1 },
        { word: '40 km à 60 km/h', box: 0 },
      ],
      explain: "Compare la distance à ce qu'on fait en une heure : si la distance est plus petite que la vitesse, le trajet dure moins d'une heure.",
    },
    {
      id: 'cm2-maths-echelles-vitesse-choice-3',
      kind: 'choice',
      prompt: "Une classe de 28 élèves part en sortie. Le car coûte 350 € et l'entrée coûte 4 € par élève. Chaque élève paie la même part. Combien paie chaque élève ?",
      options: ['12,50 €', '16,50 €', '20 €'],
      answer: 1,
      explain: "Les entrées : 28 × 4 = 112 €. Le total : 350 + 112 = 462 €. La part de chacun : 462 : 28 = 16,50 €.",
    },
    {
      id: 'cm2-maths-echelles-vitesse-tf-2',
      kind: 'truefalse',
      statement: "Sur une carte à l'échelle 1/100 000, 1 cm représente 1 km.",
      answer: true,
      explain: "Oui : 1 cm × 100 000 = 100 000 cm = 1 000 m = 1 km.",
    },
  ],
};

const TABLEAUX_GRAPHIQUES: Lesson = {
  id: 'cm2-maths-tableaux-graphiques',
  title: 'Tableaux et graphiques',
  subject: 'maths',
  source: 'lecon',
  level: 'CM2',
  notion: 'Lire un tableau à double entrée, lire et décrire un graphique en barres ou en courbe',
  theme: 'calcul',
  attendu: 'Lire et construire un tableau, un graphique en barres ou en courbe, et en tirer des informations.',
  attenduId: 'cm2-calc-organisation',
  summary:
    "Un tableau à double entrée se lit en croisant une ligne et une colonne. Un graphique en barres compare des quantités : la barre la plus haute, c'est la plus grande valeur. Un graphique en courbe montre une évolution dans le temps. Avant de lire un graphique, on regarde le titre, les axes et l'unité.",
  minutes: 7,
  exercises: [
    {
      id: 'cm2-maths-tableaux-graphiques-choice-1',
      kind: 'choice',
      prompt: 'Repas servis à la cantine : lundi 120, mardi 135, jeudi 98, vendredi 140. Quel jour y a-t-il eu le plus de repas ?',
      options: ['mardi', 'vendredi', 'lundi'],
      answer: 1,
      explain: "On compare les nombres : 140 est le plus grand, c'est vendredi. Sur un graphique en barres, ce serait la barre la plus haute.",
    },
    {
      id: 'cm2-maths-tableaux-graphiques-tf-1',
      kind: 'truefalse',
      statement: 'Dans un tableau à double entrée, on trouve une case en croisant une ligne et une colonne.',
      answer: true,
      explain: "Oui : on suit la ligne avec un doigt et la colonne avec l'autre, la case cherchée est au croisement.",
    },
    {
      id: 'cm2-maths-tableaux-graphiques-blanks-1',
      kind: 'blanks',
      prompt: 'Lis le tableau à double entrée et complète',
      text: 'Sports choisis. Filles : football 8, natation 12. Garçons : football 14, natation 6. Au total, {{22}} élèves font du football et {{18}} font de la natation.',
      distractors: ['20', '26'],
      explain: "Pour le total d'une colonne, on additionne les lignes : football 8 + 14 = 22, natation 12 + 6 = 18.",
    },
    {
      id: 'cm2-maths-tableaux-graphiques-sort-1',
      kind: 'sort',
      prompt: 'Quel graphique choisir ? Range chaque situation',
      boxes: ['Graphique en barres', 'Graphique en courbe'],
      items: [
        { word: "comparer le nombre d'élèves de chaque classe", box: 0 },
        { word: 'suivre la température chaque jour du mois', box: 1 },
        { word: "la taille d'un enfant d'année en année", box: 1 },
        { word: 'les sports préférés de la classe', box: 0 },
        { word: 'le nombre de livres lus par chaque élève', box: 0 },
      ],
      explain: "Les barres comparent des catégories séparées. La courbe montre comment une chose change au fil du temps.",
    },
    {
      id: 'cm2-maths-tableaux-graphiques-pairs-1',
      kind: 'pairs',
      prompt: 'Relie ce que tu vois à ce que cela veut dire',
      pairs: [
        { a: 'La barre la plus haute', b: 'la plus grande valeur' },
        { a: 'La courbe qui monte', b: 'la valeur augmente' },
        { a: 'Deux barres de même hauteur', b: 'deux valeurs égales' },
        { a: 'La courbe qui descend', b: 'la valeur diminue' },
      ],
      explain: "La hauteur d'une barre, c'est sa valeur. Sur une courbe, monter veut dire augmenter et descendre veut dire diminuer.",
    },
    {
      id: 'cm2-maths-tableaux-graphiques-choice-2',
      kind: 'choice',
      prompt: 'Un graphique en barres montre les animaux préférés : chien 10 votes, chat 8, lapin 5, poisson 2. Quelle phrase décrit bien le graphique ?',
      options: [
        'Le chien a deux fois plus de votes que le lapin.',
        'Le chat a plus de votes que le chien.',
        'Le poisson a autant de votes que le lapin.',
      ],
      answer: 0,
      explain: "10, c'est bien 2 × 5. Le chat a 8 votes, moins que le chien, et le poisson en a 2, moins que le lapin.",
    },
    {
      id: 'cm2-maths-tableaux-graphiques-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a mal lu le tableau, corrige-le',
      words: ['Pluie', 'en', 'mm', ':', 'janvier 60,', 'février 45,', 'mars 70.', 'Le', 'mois', 'le', 'plus', 'pluvieux', 'est', 'janvier'],
      wrongIndex: 13,
      correct: 'mars',
      distractors: ['janvier', 'février'],
      explain: "On compare 60, 45 et 70 : le plus grand est 70, c'est mars.",
    },
    {
      id: 'cm2-maths-tableaux-graphiques-tf-2',
      kind: 'truefalse',
      statement: "Sur une courbe des températures, un point plus haut qu'un autre veut dire qu'il a fait plus chaud ce jour-là.",
      answer: true,
      explain: "Oui : l'axe vertical porte les températures, plus le point est haut, plus la valeur est grande.",
    },
    {
      id: 'cm2-maths-tableaux-graphiques-tap-1',
      kind: 'tapword',
      prompt: "Ventes de glaces : juin 40, juillet 95, août 110, septembre 30. Touche le mois où les ventes ont le plus augmenté par rapport au mois d'avant",
      words: ['juillet', 'août', 'septembre'],
      answer: [0],
      explain: "De juin à juillet : 95 − 40 = 55 de plus. De juillet à août : seulement 15 de plus. En septembre, les ventes baissent.",
    },
    {
      id: 'cm2-maths-tableaux-graphiques-choice-3',
      kind: 'choice',
      prompt: "Un tableau donne les élèves par classe : CP 24, CE1 26, CE2 22, CM1 25, CM2 23. Combien d'élèves dans l'école ?",
      options: ['110', '120', '130'],
      answer: 1,
      explain: "On additionne toutes les cases : 24 + 26 = 50, 22 + 25 = 47, 50 + 47 + 23 = 120 élèves.",
    },
  ],
};

const LONGUEURS: Lesson = {
  id: 'cm2-maths-longueurs',
  title: 'Conversions et périmètre',
  subject: 'maths',
  source: 'lecon',
  level: 'CM2',
  notion: "Convertir des longueurs, des masses et des contenances avec des nombres décimaux ; calculer un périmètre, y compris celui du cercle",
  theme: 'grandeurs',
  attendu: 'Convertir des longueurs, des masses et des contenances avec des nombres décimaux ; calculer un périmètre, y compris celui du cercle (approche).',
  attenduId: 'cm2-gm-longueurs',
  summary:
    "Avec des décimaux, convertir revient à déplacer la virgule : 2,5 km = 2 500 m, 350 g = 0,35 kg, 1,2 L = 120 cL. Le périmètre, c'est la longueur du tour. Pour le cercle, il vaut un peu plus de 3 fois le diamètre : un cercle de 10 cm de diamètre a un tour d'environ 31 cm.",
  minutes: 7,
  exercises: [
    {
      id: 'cm2-maths-longueurs-choice-1',
      kind: 'choice',
      prompt: 'Combien de mètres dans 2,5 km ?',
      options: ['250 m', '2 500 m', '25 000 m'],
      answer: 1,
      explain: "1 km = 1 000 m. 2,5 × 1 000 = 2 500 m : la virgule se décale de trois rangs.",
    },
    {
      id: 'cm2-maths-longueurs-tf-1',
      kind: 'truefalse',
      statement: '350 g = 0,35 kg.',
      answer: true,
      explain: "Oui : 1 kg = 1 000 g. 350 : 1 000 = 0,35. Trois cent cinquante grammes, c'est un peu plus d'un tiers de kilo.",
    },
    {
      id: 'cm2-maths-longueurs-blanks-1',
      kind: 'blanks',
      prompt: 'Convertis',
      text: '1,2 L = {{120}} cL et 4,75 m = {{475}} cm.',
      distractors: ['12', '4 750'],
      explain: "1 L = 100 cL, donc 1,2 × 100 = 120 cL. 1 m = 100 cm, donc 4,75 × 100 = 475 cm.",
    },
    {
      id: 'cm2-maths-longueurs-pairs-1',
      kind: 'pairs',
      prompt: 'Relie les mesures égales',
      pairs: [
        { a: '0,5 kg', b: '500 g' },
        { a: '1,5 L', b: '150 cL' },
        { a: '0,8 km', b: '800 m' },
        { a: '25 mm', b: '2,5 cm' },
      ],
      explain: "Kilo, c'est mille ; centi, c'est un centième ; milli, c'est un millième. On décale la virgule du bon nombre de rangs.",
    },
    {
      id: 'cm2-maths-longueurs-sort-1',
      kind: 'sort',
      prompt: 'Range chaque masse dans la bonne boîte',
      boxes: ['Plus léger que 1 kg', 'Plus lourd que 1 kg'],
      items: [
        { word: '950 g', box: 0 },
        { word: '1,2 kg', box: 1 },
        { word: '0,99 kg', box: 0 },
        { word: '1 050 g', box: 1 },
        { word: '2 500 g', box: 1 },
        { word: '0,5 kg', box: 0 },
      ],
      explain: "Mets tout dans la même unité : 1 kg = 1 000 g. 950 g et 0,99 kg sont juste en dessous, 1 050 g et 1,2 kg juste au-dessus.",
    },
    {
      id: 'cm2-maths-longueurs-fix-1',
      kind: 'fix',
      prompt: "Gribouille s'est trompé, corrige-le",
      words: ['Rectangle', 'de', '6,5 cm', 'sur', '3 cm', ':', 'périmètre', '9,5 cm'],
      wrongIndex: 7,
      correct: '19 cm',
      distractors: ['9,5 cm', '19,5 cm'],
      explain: "6,5 + 3 = 9,5, mais c'est seulement la moitié du tour. Le périmètre, c'est 9,5 × 2 = 19 cm.",
    },
    {
      id: 'cm2-maths-longueurs-choice-2',
      kind: 'choice',
      prompt: 'Un cercle a un diamètre de 10 cm. Quel est à peu près son périmètre ?',
      options: ['environ 20 cm', 'environ 31 cm', 'environ 100 cm'],
      answer: 1,
      explain: "Le tour d'un cercle vaut un peu plus de 3 fois son diamètre : 3 × 10 = 30, donc environ 31 cm.",
    },
    {
      id: 'cm2-maths-longueurs-tf-2',
      kind: 'truefalse',
      statement: "Le périmètre d'un carré de 2,5 cm de côté est 10 cm.",
      answer: true,
      explain: "Oui : 4 côtés de 2,5 cm, donc 4 × 2,5 = 10 cm.",
    },
    {
      id: 'cm2-maths-longueurs-tap-1',
      kind: 'tapword',
      prompt: 'Touche la conversion qui est fausse',
      words: ['3,2 m = 320 cm', '0,75 L = 75 cL', '1,5 kg = 150 g'],
      answer: [2],
      explain: "1,5 kg = 1 500 g, pas 150 g : un kilo, c'est mille grammes. Les deux autres conversions sont justes.",
    },
    {
      id: 'cm2-maths-longueurs-choice-3',
      kind: 'choice',
      prompt: 'Un terrain rectangulaire mesure 12,5 m sur 8 m. Quelle longueur de grillage faut-il pour en faire le tour ?',
      options: ['20,5 m', '41 m', '100 m'],
      answer: 1,
      explain: "Le périmètre : (12,5 + 8) × 2 = 20,5 × 2 = 41 m. 100, ce serait l'aire en m², pas le tour.",
    },
  ],
};

const AIRES: Lesson = {
  id: 'cm2-maths-aires',
  title: 'Les aires',
  subject: 'maths',
  source: 'lecon',
  level: 'CM2',
  notion: "Calculer l'aire d'un carré, d'un rectangle et d'un triangle rectangle ; utiliser cm², m², km² et hectare",
  theme: 'grandeurs',
  attendu: "Calculer l'aire d'un carré, d'un rectangle et d'un triangle rectangle ; utiliser cm², m², km², ha.",
  attenduId: 'cm2-gm-aires',
  summary:
    "L'aire d'un rectangle, c'est longueur × largeur : 6 cm × 4 cm = 24 cm². Pour un carré, côté × côté. Un triangle rectangle, c'est la moitié d'un rectangle : son aire est longueur × largeur, divisé par 2. Les grandes aires se mesurent en m², en hectares (1 ha = 10 000 m²) ou en km².",
  minutes: 7,
  exercises: [
    {
      id: 'cm2-maths-aires-choice-1',
      kind: 'choice',
      prompt: "Quelle est l'aire d'un rectangle de 6 cm de long et 4 cm de large ?",
      options: ['20 cm²', '24 cm²', '10 cm²'],
      answer: 1,
      explain: "L'aire, c'est longueur × largeur : 6 × 4 = 24 cm². 20 cm, ce serait le périmètre.",
    },
    {
      id: 'cm2-maths-aires-tf-1',
      kind: 'truefalse',
      statement: "Un triangle rectangle dont les côtés de l'angle droit mesurent 6 cm et 4 cm a une aire de 12 cm².",
      answer: true,
      explain: "Oui : c'est la moitié du rectangle de 6 cm sur 4 cm. 24 : 2 = 12 cm².",
    },
    {
      id: 'cm2-maths-aires-count-1',
      kind: 'count',
      prompt: "Compte les carreaux de 1 cm² qui couvrent ce carré : c'est son aire",
      emoji: '🟩',
      answer: 16,
      options: [12, 16, 20],
      explain: "4 rangées de 4 carreaux : 4 × 4 = 16 carreaux, donc 16 cm². Le périmètre, lui, serait 16 cm.",
    },
    {
      id: 'cm2-maths-aires-blanks-1',
      kind: 'blanks',
      prompt: 'Complète les aires',
      text: 'Un carré de 5 cm de côté a une aire de {{25}} cm². Un rectangle de 8 cm sur 2,5 cm a une aire de {{20}} cm².',
      distractors: ['10', '21'],
      explain: "5 × 5 = 25 cm². 8 × 2,5 = 20 cm² : huit fois deux et demi, c'est 16 + 4.",
    },
    {
      id: 'cm2-maths-aires-pairs-1',
      kind: 'pairs',
      prompt: "Relie les unités d'aire égales",
      pairs: [
        { a: '1 ha', b: '10 000 m²' },
        { a: '1 m²', b: '10 000 cm²' },
        { a: '1 km²', b: '100 ha' },
        { a: '1 dm²', b: '100 cm²' },
      ],
      explain: "Un hectare, c'est un carré de 100 m de côté : 100 × 100 = 10 000 m². Un km², c'est 1 000 m × 1 000 m, soit 100 hectares.",
    },
    {
      id: 'cm2-maths-aires-fix-1',
      kind: 'fix',
      prompt: "Gribouille s'est trompé, corrige-le",
      words: ['Rectangle', 'de', '7 cm', 'sur', '3 cm', ':', 'aire', '20 cm²'],
      wrongIndex: 7,
      correct: '21 cm²',
      distractors: ['20 cm²', '10 cm²'],
      explain: "7 × 3 = 21 cm². 20 cm, ce serait le périmètre : (7 + 3) × 2.",
    },
    {
      id: 'cm2-maths-aires-sort-1',
      kind: 'sort',
      prompt: 'Aire ou périmètre ? Range chaque phrase',
      boxes: ['Aire', 'Périmètre'],
      items: [
        { word: 'la peinture pour couvrir un mur', box: 0 },
        { word: 'la frise collée tout autour de la pièce', box: 1 },
        { word: 'se mesure en m²', box: 0 },
        { word: 'la longueur de la clôture', box: 1 },
        { word: 'le gazon qui couvre le terrain', box: 0 },
        { word: 'se mesure en km', box: 1 },
      ],
      explain: "Ce qui recouvre, c'est l'aire, en m² ou en ha. Ce qui fait le tour, c'est le périmètre, en m ou en km.",
    },
    {
      id: 'cm2-maths-aires-choice-2',
      kind: 'choice',
      prompt: 'Un champ mesure 200 m sur 150 m. Quelle est son aire en hectares ?',
      options: ['3 ha', '30 ha', '300 ha'],
      answer: 0,
      explain: "200 × 150 = 30 000 m². Comme 1 ha = 10 000 m², cela fait 3 ha.",
    },
    {
      id: 'cm2-maths-aires-tf-2',
      kind: 'truefalse',
      statement: 'Un carré de 10 m de côté a une aire de 1 ha.',
      answer: false,
      explain: "10 × 10 = 100 m² seulement. Pour 1 ha, il faut un carré de 100 m de côté : 10 000 m².",
    },
    {
      id: 'cm2-maths-aires-choice-3',
      kind: 'choice',
      prompt: "Un triangle rectangle a des côtés de l'angle droit de 10 cm et 5 cm. Quelle est son aire ?",
      options: ['50 cm²', '25 cm²', '15 cm²'],
      answer: 1,
      explain: "Le rectangle de 10 cm sur 5 cm a une aire de 50 cm². Le triangle rectangle en est la moitié : 25 cm².",
    },
  ],
};

const DUREES: Lesson = {
  id: 'cm2-maths-durees',
  title: 'Durées et horaires',
  subject: 'maths',
  source: 'lecon',
  level: 'CM2',
  notion: 'Calculer des durées et des horaires avec des heures, des minutes et des secondes ; convertir',
  theme: 'grandeurs',
  attendu: 'Calculer des durées et des horaires avec des heures, minutes et secondes ; convertir.',
  attenduId: 'cm2-gm-durees',
  summary:
    "1 h = 60 min, 1 min = 60 s, donc 1 h = 3 600 s. Pour ajouter des durées, on fait attention à la retenue de 60 : 2 h 45 min + 30 min = 2 h 75 min = 3 h 15 min. Pour trouver une durée entre deux horaires, on passe par l'heure ronde : de 9 h 40 à 11 h 10, il y a 20 min puis 1 h 10, soit 1 h 30.",
  minutes: 7,
  exercises: [
    {
      id: 'cm2-maths-durees-choice-1',
      kind: 'choice',
      prompt: 'Combien font 2 h 45 min + 30 min ?',
      options: ['2 h 75 min', '3 h 15 min', '3 h 05 min'],
      answer: 1,
      explain: "45 + 30 = 75 min. Comme 60 min font une heure, 75 min, c'est 1 h 15 min. Donc 2 h + 1 h 15 = 3 h 15.",
    },
    {
      id: 'cm2-maths-durees-tf-1',
      kind: 'truefalse',
      statement: '1 h = 3 600 s.',
      answer: true,
      explain: "Oui : 1 h = 60 min, et chaque minute fait 60 s. 60 × 60 = 3 600 s.",
    },
    {
      id: 'cm2-maths-durees-blanks-1',
      kind: 'blanks',
      prompt: 'Complète',
      text: 'Le film commence à 20 h 35 et dure 1 h 50. Il se termine à {{22 h 25}}. Et 150 secondes, c\'est {{2}} min 30 s.',
      distractors: ['21 h 85', '3'],
      explain: "20 h 35 + 1 h 50 : 35 + 50 = 85 min, c'est 1 h 25. Donc 21 h + 1 h 25 = 22 h 25. Pour 150 s : 120 s font 2 min, il reste 30 s.",
    },
    {
      id: 'cm2-maths-durees-pairs-1',
      kind: 'pairs',
      prompt: 'Relie les durées égales',
      pairs: [
        { a: '90 min', b: '1 h 30' },
        { a: '2 h 15', b: '135 min' },
        { a: '180 s', b: '3 min' },
        { a: '1 h 05', b: '65 min' },
      ],
      explain: "Pour passer des heures aux minutes, on multiplie par 60 : 2 h = 120 min, plus 15, cela fait 135 min.",
    },
    {
      id: 'cm2-maths-durees-fix-1',
      kind: 'fix',
      prompt: "Gribouille s'est trompé, corrige-le",
      words: ['De', '9 h 40', 'à', '11 h 10,', 'il', 'y', 'a', '2 h 30'],
      wrongIndex: 7,
      correct: '1 h 30',
      distractors: ['2 h 30', '1 h 70'],
      explain: "De 9 h 40 à 10 h, il y a 20 min. De 10 h à 11 h 10, il y a 1 h 10. En tout : 1 h 30.",
    },
    {
      id: 'cm2-maths-durees-sort-1',
      kind: 'sort',
      prompt: 'Range chaque durée dans la bonne boîte',
      boxes: ["Moins d'une heure", "Plus d'une heure"],
      items: [
        { word: '59 min', box: 0 },
        { word: '3 500 s', box: 0 },
        { word: '65 min', box: 1 },
        { word: '3 700 s', box: 1 },
        { word: '45 min 30 s', box: 0 },
        { word: '1 h 01', box: 1 },
      ],
      explain: "Une heure, c'est 60 min ou 3 600 s. 3 500 s, c'est un peu moins ; 3 700 s, un peu plus.",
    },
    {
      id: 'cm2-maths-durees-choice-2',
      kind: 'choice',
      prompt: 'Léa part à 7 h 50 et arrive à 9 h 20. Combien de temps a duré le trajet ?',
      options: ['1 h 30', '2 h 30', '1 h 70'],
      answer: 0,
      explain: "De 7 h 50 à 8 h : 10 min. De 8 h à 9 h 20 : 1 h 20. En tout, 1 h 30.",
    },
    {
      id: 'cm2-maths-durees-order-1',
      kind: 'order',
      prompt: "Un train part à 14 h 25 et roule 2 h 50. Remets dans l'ordre les étapes pour trouver l'heure d'arrivée",
      lines: [
        "J'ajoute les heures : 14 h + 2 h = 16 h",
        "J'ajoute les minutes : 25 + 50 = 75 min",
        "75 min, c'est 1 h 15 min : je retiens 1 h",
        'Le train arrive à 17 h 15',
      ],
      explain: "On ajoute les heures, puis les minutes. Quand les minutes dépassent 60, on fait une retenue d'une heure.",
    },
    {
      id: 'cm2-maths-durees-tf-2',
      kind: 'truefalse',
      statement: "Un quart d'heure, c'est 25 minutes.",
      answer: false,
      explain: "Un quart d'heure, c'est 60 : 4 = 15 minutes. 25 minutes, c'est un peu plus qu'un tiers d'heure.",
    },
    {
      id: 'cm2-maths-durees-tap-1',
      kind: 'tapword',
      prompt: 'Touche la durée la plus longue',
      words: ['1 h 20', '75 min', '4 500 s'],
      answer: [0],
      explain: "1 h 20 = 80 min. 4 500 s = 75 min, car 4 500 : 60 = 75. La plus longue est donc 1 h 20.",
    },
  ],
};

const ANGLES: Lesson = {
  id: 'cm2-maths-angles',
  title: 'Les angles',
  subject: 'maths',
  source: 'lecon',
  level: 'CM2',
  notion: "Reconnaître et comparer les angles aigus, droits, obtus et plats ; utiliser l'équerre et le degré",
  theme: 'grandeurs',
  attendu: "Estimer et comparer des angles, reconnaître angle aigu, droit, obtus, plat ; utiliser l'équerre et l'idée de degré.",
  attenduId: 'cm2-gm-angles',
  summary:
    "Un angle droit mesure 90°, comme le coin d'une feuille. Un angle aigu est plus petit que l'angle droit, un angle obtus est plus grand. Un angle plat mesure 180° : c'est une ligne droite, deux angles droits côte à côte. On vérifie un angle droit avec l'équerre.",
  minutes: 6,
  exercises: [
    {
      id: 'cm2-maths-angles-choice-1',
      kind: 'choice',
      prompt: 'Combien mesure un angle plat ?',
      options: ['90°', '180°', '360°'],
      answer: 1,
      explain: "Un angle plat, c'est une ligne droite : deux angles droits côte à côte, 90° + 90° = 180°.",
    },
    {
      id: 'cm2-maths-angles-tf-1',
      kind: 'truefalse',
      statement: 'Un angle de 45° est un angle aigu.',
      answer: true,
      explain: "Oui : 45°, c'est moins que 90°. C'est même exactement la moitié d'un angle droit.",
    },
    {
      id: 'cm2-maths-angles-sort-1',
      kind: 'sort',
      prompt: 'Range chaque angle dans la bonne boîte',
      boxes: ['Aigu', 'Droit', 'Obtus'],
      items: [
        { word: '30°', box: 0 },
        { word: '90°', box: 1 },
        { word: '120°', box: 2 },
        { word: '89°', box: 0 },
        { word: '175°', box: 2 },
        { word: '60°', box: 0 },
      ],
      explain: "Moins de 90°, c'est aigu. Exactement 90°, c'est droit. Plus de 90° et moins de 180°, c'est obtus.",
    },
    {
      id: 'cm2-maths-angles-blanks-1',
      kind: 'blanks',
      prompt: 'Complète la règle',
      text: 'Deux angles droits côte à côte forment un angle {{plat}} de {{180}}°.',
      distractors: ['obtus', '90'],
      explain: "90° + 90° = 180°, et un angle de 180° est un angle plat : ses deux côtés forment une ligne droite.",
    },
    {
      id: 'cm2-maths-angles-fix-1',
      kind: 'fix',
      prompt: "Gribouille s'est trompé, corrige-le",
      words: ['Un', 'angle', 'de', '100°', 'est', 'un', 'angle', 'aigu'],
      wrongIndex: 7,
      correct: 'obtus',
      distractors: ['aigu', 'droit'],
      explain: "100°, c'est plus que 90° : l'angle est plus ouvert qu'un angle droit, il est obtus.",
    },
    {
      id: 'cm2-maths-angles-pairs-1',
      kind: 'pairs',
      prompt: 'Relie chaque angle à sa mesure',
      pairs: [
        { a: 'Angle droit', b: '90°' },
        { a: 'Angle plat', b: '180°' },
        { a: "Moitié d'un angle droit", b: '45°' },
        { a: "Tiers d'un angle plat", b: '60°' },
      ],
      explain: "90 : 2 = 45, et 180 : 3 = 60. Un triangle équilatéral a trois angles de 60°.",
    },
    {
      id: 'cm2-maths-angles-choice-2',
      kind: 'choice',
      prompt: "Dans un triangle rectangle, combien y a-t-il d'angles droits ?",
      options: ['un', 'deux', 'trois'],
      answer: 0,
      explain: "Un seul : c'est lui qui donne son nom au triangle rectangle. Les deux autres angles sont aigus.",
    },
    {
      id: 'cm2-maths-angles-tf-2',
      kind: 'truefalse',
      statement: "Les quatre angles d'un rectangle sont droits.",
      answer: true,
      explain: "Oui : c'est ce qui fait un rectangle. On peut le vérifier avec l'équerre à chaque coin.",
    },
    {
      id: 'cm2-maths-angles-tap-1',
      kind: 'tapword',
      prompt: 'Touche les angles obtus',
      words: ['95°', '15°', '90°', '150°'],
      answer: [0, 3],
      explain: "95° et 150° dépassent 90°, ils sont obtus. 15° est aigu et 90° est droit.",
    },
    {
      id: 'cm2-maths-angles-choice-3',
      kind: 'choice',
      prompt: "Un angle mesure 90° et on l'ouvre encore un peu. Que devient-il ?",
      options: ['aigu', 'obtus', 'plat'],
      answer: 1,
      explain: "En l'ouvrant, l'angle dépasse 90° : il devient obtus. Il faudrait l'ouvrir jusqu'à 180° pour qu'il soit plat.",
    },
  ],
};

const VOLUMES: Lesson = {
  id: 'cm2-maths-volumes',
  title: 'Les volumes',
  subject: 'maths',
  source: 'lecon',
  level: 'CM2',
  notion: "Approcher le volume d'un pavé en comptant des cubes ; relier le litre et le dm³",
  theme: 'grandeurs',
  attendu: "Approcher le volume d'un pavé en comptant des cubes ; relier litre et dm³.",
  attenduId: 'cm2-gm-volumes',
  summary:
    "Le volume, c'est la place qu'un objet prend. On le mesure en comptant des cubes : un pavé de 4 cubes de long, 3 de large et 2 de haut contient 4 × 3 × 2 = 24 cubes. Un cube de 1 dm de côté a un volume de 1 dm³, et il contient exactement 1 litre.",
  minutes: 7,
  exercises: [
    {
      id: 'cm2-maths-volumes-choice-1',
      kind: 'choice',
      prompt: 'Un pavé a 4 cubes de long, 3 cubes de large et 2 cubes de haut. Combien de cubes contient-il ?',
      options: ['9', '24', '12'],
      answer: 1,
      explain: "Un étage contient 4 × 3 = 12 cubes. Avec 2 étages, 2 × 12 = 24 cubes.",
    },
    {
      id: 'cm2-maths-volumes-tf-1',
      kind: 'truefalse',
      statement: '1 L = 1 dm³.',
      answer: true,
      explain: "Oui : un cube de 1 dm de côté, soit 10 cm, contient exactement un litre d'eau.",
    },
    {
      id: 'cm2-maths-volumes-count-1',
      kind: 'count',
      prompt: 'Compte les cubes posés sur la table',
      emoji: '🧱',
      answer: 15,
      options: [13, 15, 17],
      explain: "On peut compter par rangées : 3 rangées de 5 cubes font 15 cubes.",
    },
    {
      id: 'cm2-maths-volumes-blanks-1',
      kind: 'blanks',
      prompt: 'Complète',
      text: 'Un pavé a 5 cubes de long, 2 de large et 3 de haut. Un étage contient {{10}} cubes, et le pavé entier en contient {{30}}.',
      distractors: ['15', '25'],
      explain: "Un étage : 5 × 2 = 10 cubes. Trois étages : 3 × 10 = 30 cubes.",
    },
    {
      id: 'cm2-maths-volumes-pairs-1',
      kind: 'pairs',
      prompt: 'Relie les volumes égaux',
      pairs: [
        { a: '1 L', b: '1 dm³' },
        { a: '1 mL', b: '1 cm³' },
        { a: '1 m³', b: '1 000 L' },
        { a: '2 L', b: '2 dm³' },
      ],
      explain: "Un litre remplit un cube de 1 dm de côté. Un millilitre remplit un cube de 1 cm de côté. Un mètre cube, c'est 1 000 dm³, donc 1 000 L.",
    },
    {
      id: 'cm2-maths-volumes-fix-1',
      kind: 'fix',
      prompt: "Gribouille s'est trompé, corrige-le",
      words: ['Un', 'gros', 'cube', 'de', '3', 'petits', 'cubes', 'de', 'côté', 'contient', '9', 'petits', 'cubes'],
      wrongIndex: 10,
      correct: '27',
      distractors: ['9', '18'],
      explain: "Un étage contient 3 × 3 = 9 cubes, et il y a 3 étages : 3 × 9 = 27 petits cubes.",
    },
    {
      id: 'cm2-maths-volumes-sort-1',
      kind: 'sort',
      prompt: 'Range chaque volume dans la bonne boîte',
      boxes: ["Moins d'un litre", "Plus d'un litre"],
      items: [
        { word: '50 cL', box: 0 },
        { word: '1,5 dm³', box: 1 },
        { word: '800 cm³', box: 0 },
        { word: '2 dm³', box: 1 },
        { word: '25 cL', box: 0 },
        { word: '1 200 cm³', box: 1 },
      ],
      explain: "1 L = 1 dm³ = 1 000 cm³ = 100 cL. 800 cm³, c'est 0,8 L ; 1 200 cm³, c'est 1,2 L.",
    },
    {
      id: 'cm2-maths-volumes-choice-2',
      kind: 'choice',
      prompt: "Un aquarium a la forme d'un pavé : 5 dm de long, 2 dm de large et 3 dm de haut. Combien de litres contient-il quand il est plein ?",
      options: ['10 L', '30 L', '300 L'],
      answer: 1,
      explain: "5 × 2 × 3 = 30 cubes de 1 dm de côté, donc 30 dm³. Comme 1 dm³ = 1 L, cela fait 30 L.",
    },
    {
      id: 'cm2-maths-volumes-tf-2',
      kind: 'truefalse',
      statement: 'Deux pavés faits de 24 cubes ont forcément la même forme.',
      answer: false,
      explain: "Non : 4 × 3 × 2 et 6 × 2 × 2 donnent tous les deux 24 cubes, mais les pavés n'ont pas la même forme. Même volume ne veut pas dire même forme.",
    },
    {
      id: 'cm2-maths-volumes-choice-3',
      kind: 'choice',
      prompt: 'Un pavé de 2 cubes de haut contient 16 cubes. Combien de cubes y a-t-il dans un étage ?',
      options: ['8', '14', '32'],
      answer: 0,
      explain: "Deux étages identiques font 16 cubes, donc un étage en a 16 : 2 = 8.",
    },
  ],
};

const FIGURES: Lesson = {
  id: 'cm2-maths-figures',
  title: 'Triangles, quadrilatères et cercle',
  subject: 'maths',
  source: 'lecon',
  level: 'CM2',
  notion: 'Décrire et construire des triangles, des quadrilatères particuliers et le cercle ; propriétés des côtés et des diagonales ; programme de construction',
  theme: 'geometrie',
  attendu: 'Décrire, reproduire et construire des figures : triangles, quadrilatères particuliers, cercle ; propriétés des côtés et des diagonales ; programme de construction.',
  attenduId: 'cm2-geo-figures',
  summary:
    "Un parallélogramme a ses côtés opposés parallèles et de même longueur. Le losange a quatre côtés égaux et ses diagonales sont perpendiculaires. Le rectangle a quatre angles droits et des diagonales de même longueur. Le carré a tout cela à la fois. Un programme de construction dit, étape par étape, comment tracer la figure.",
  minutes: 8,
  exercises: [
    {
      id: 'cm2-maths-figures-choice-1',
      kind: 'choice',
      prompt: "Quel quadrilatère a ses quatre côtés égaux, mais pas forcément d'angle droit ?",
      options: ['le rectangle', 'le losange', 'le parallélogramme'],
      answer: 1,
      explain: "Le losange a quatre côtés de même longueur. Si en plus ses angles sont droits, c'est un carré.",
    },
    {
      id: 'cm2-maths-figures-tf-1',
      kind: 'truefalse',
      statement: "Les diagonales d'un losange sont perpendiculaires.",
      answer: true,
      explain: "Oui : les deux diagonales d'un losange se coupent en leur milieu en formant un angle droit.",
    },
    {
      id: 'cm2-maths-figures-sort-1',
      kind: 'sort',
      prompt: 'Range chaque propriété',
      boxes: ['Toujours vrai pour un rectangle', 'Pas toujours vrai pour un rectangle'],
      items: [
        { word: 'quatre angles droits', box: 0 },
        { word: 'quatre côtés égaux', box: 1 },
        { word: 'diagonales de même longueur', box: 0 },
        { word: 'côtés opposés parallèles', box: 0 },
        { word: 'diagonales perpendiculaires', box: 1 },
      ],
      explain: "Un rectangle a toujours quatre angles droits, des côtés opposés parallèles et des diagonales égales. Côtés tous égaux et diagonales perpendiculaires, c'est seulement pour le carré.",
    },
    {
      id: 'cm2-maths-figures-order-1',
      kind: 'order',
      prompt: "Remets dans l'ordre le programme de construction d'un carré ABCD de 4 cm de côté",
      lines: [
        'Trace un segment AB de 4 cm',
        'Trace la perpendiculaire à AB passant par A, puis celle passant par B',
        'Place D sur la première et C sur la deuxième, à 4 cm de A et de B, du même côté',
        'Relie D à C : ABCD est un carré',
      ],
      explain: "On trace d'abord un côté, puis les deux perpendiculaires, on reporte la longueur, et on ferme la figure.",
    },
    {
      id: 'cm2-maths-figures-blanks-1',
      kind: 'blanks',
      prompt: 'Complète avec le nom du triangle',
      text: 'Un triangle qui a trois côtés de même longueur est {{équilatéral}}. Un triangle qui a deux côtés de même longueur est {{isocèle}}.',
      distractors: ['rectangle', 'quelconque'],
      explain: "Équilatéral veut dire « côtés égaux » : les trois. Isocèle, c'est deux côtés égaux. Rectangle, c'est un angle droit.",
    },
    {
      id: 'cm2-maths-figures-fix-1',
      kind: 'fix',
      prompt: "Gribouille s'est trompé, corrige-le",
      words: ['Un', 'parallélogramme', 'a', 'ses', 'côtés', 'opposés', 'perpendiculaires'],
      wrongIndex: 6,
      correct: 'parallèles',
      distractors: ['perpendiculaires', 'inégaux'],
      explain: "Son nom le dit : les côtés opposés d'un parallélogramme sont parallèles, et ils ont la même longueur.",
    },
    {
      id: 'cm2-maths-figures-pairs-1',
      kind: 'pairs',
      prompt: 'Relie chaque mot à sa définition',
      pairs: [
        { a: 'Cercle', b: 'tous les points à la même distance du centre' },
        { a: 'Rayon', b: "du centre à un point du cercle" },
        { a: 'Diamètre', b: 'deux fois le rayon' },
        { a: 'Diagonale', b: 'relie deux sommets opposés' },
      ],
      explain: "Le rayon part du centre, le diamètre traverse le cercle en passant par le centre, la diagonale traverse un quadrilatère d'un sommet à l'autre.",
    },
    {
      id: 'cm2-maths-figures-choice-2',
      kind: 'choice',
      prompt: 'Un cercle a un rayon de 3,5 cm. Quel est son diamètre ?',
      options: ['1,75 cm', '7 cm', '10,5 cm'],
      answer: 1,
      explain: "Le diamètre, c'est deux rayons : 2 × 3,5 = 7 cm.",
    },
    {
      id: 'cm2-maths-figures-tf-2',
      kind: 'truefalse',
      statement: 'Un carré est aussi un rectangle, car il a quatre angles droits.',
      answer: true,
      explain: "Oui : un carré a tout ce qu'il faut pour être un rectangle, et en plus ses quatre côtés sont égaux.",
    },
    {
      id: 'cm2-maths-figures-tap-1',
      kind: 'tapword',
      prompt: 'Touche les figures qui ont forcément au moins un angle droit',
      words: ['carré', 'losange', 'triangle rectangle', 'rectangle'],
      answer: [0, 2, 3],
      explain: "Le carré et le rectangle ont quatre angles droits, le triangle rectangle en a un. Un losange peut ne pas en avoir du tout.",
    },
  ],
};

const SYMETRIE: Lesson = {
  id: 'cm2-maths-symetrie',
  title: 'La symétrie axiale',
  subject: 'maths',
  source: 'lecon',
  level: 'CM2',
  notion: "Construire le symétrique d'une figure par rapport à un axe ; reconnaître les axes de symétrie des figures usuelles",
  theme: 'geometrie',
  attendu: "Construire le symétrique d'une figure par rapport à un axe ; reconnaître les axes de symétrie des figures usuelles.",
  attenduId: 'cm2-geo-symetrie',
  summary:
    "Deux figures sont symétriques par rapport à un axe quand, en pliant la feuille sur l'axe, elles se superposent. Le symétrique d'un point est à la même distance de l'axe, de l'autre côté, sur la perpendiculaire à l'axe. Le carré a 4 axes de symétrie, le rectangle en a 2, le cercle en a une infinité.",
  minutes: 7,
  exercises: [
    {
      id: 'cm2-maths-symetrie-choice-1',
      kind: 'choice',
      prompt: "Combien d'axes de symétrie a un carré ?",
      options: ['2', '4', '1'],
      answer: 1,
      explain: "Quatre : les deux droites qui passent par les milieux des côtés opposés, et les deux diagonales.",
    },
    {
      id: 'cm2-maths-symetrie-tf-1',
      kind: 'truefalse',
      statement: 'Un rectangle a 4 axes de symétrie.',
      answer: false,
      explain: "Un rectangle n'en a que 2, ceux qui passent par les milieux des côtés. Ses diagonales ne sont pas des axes : en pliant dessus, les côtés ne se superposent pas.",
    },
    {
      id: 'cm2-maths-symetrie-sort-1',
      kind: 'sort',
      prompt: 'Range chaque figure dans la bonne boîte',
      boxes: ['Au moins un axe de symétrie', 'Aucun axe de symétrie'],
      items: [
        { word: 'la lettre A', box: 0 },
        { word: 'la lettre F', box: 1 },
        { word: 'le cercle', box: 0 },
        { word: 'un parallélogramme penché', box: 1 },
        { word: 'un triangle isocèle', box: 0 },
        { word: 'la lettre G', box: 1 },
      ],
      explain: "Imagine le pliage : le A, le cercle et le triangle isocèle se superposent. Le F, le G et le parallélogramme penché, non.",
    },
    {
      id: 'cm2-maths-symetrie-blanks-1',
      kind: 'blanks',
      prompt: 'Complète la règle',
      text: "Le symétrique d'un point est à la {{même}} distance de l'axe, de l'autre {{côté}}, sur la perpendiculaire à l'axe.",
      distractors: ['double', 'point'],
      explain: "Point et symétrique sont comme un reflet dans un miroir : même distance au miroir, mais chacun d'un côté.",
    },
    {
      id: 'cm2-maths-symetrie-fix-1',
      kind: 'fix',
      prompt: "Gribouille s'est trompé, corrige-le",
      words: ['Un', 'point', 'à', '3 cm', 'de', "l'axe", 'a', 'son', 'symétrique', 'à', '6 cm', 'de', "l'axe"],
      wrongIndex: 10,
      correct: '3 cm',
      distractors: ['6 cm', '1,5 cm'],
      explain: "Le symétrique est à la même distance de l'axe : 3 cm. Par contre, les deux points sont à 6 cm l'un de l'autre.",
    },
    {
      id: 'cm2-maths-symetrie-pairs-1',
      kind: 'pairs',
      prompt: "Relie chaque figure à son nombre d'axes de symétrie",
      pairs: [
        { a: 'Carré', b: '4 axes' },
        { a: 'Rectangle', b: '2 axes' },
        { a: 'Triangle équilatéral', b: '3 axes' },
        { a: 'Triangle isocèle', b: '1 axe' },
      ],
      explain: "Plus une figure est régulière, plus elle a d'axes. Le triangle isocèle n'en a qu'un, celui qui passe par son sommet principal.",
    },
    {
      id: 'cm2-maths-symetrie-choice-2',
      kind: 'choice',
      prompt: "Un point est posé sur l'axe de symétrie. Où est son symétrique ?",
      options: ['au même endroit', "de l'autre côté de l'axe", 'au centre de la figure'],
      answer: 0,
      explain: "Un point sur l'axe est à 0 cm de l'axe. Son symétrique est aussi à 0 cm : c'est lui-même.",
    },
    {
      id: 'cm2-maths-symetrie-tf-2',
      kind: 'truefalse',
      statement: "Le symétrique d'un segment de 5 cm est un segment de 5 cm.",
      answer: true,
      explain: "Oui : la symétrie ne change ni les longueurs ni les angles. La figure est juste retournée comme dans un miroir.",
    },
    {
      id: 'cm2-maths-symetrie-tap-1',
      kind: 'tapword',
      prompt: 'Touche les lettres majuscules qui ont un axe de symétrie',
      words: ['H', 'L', 'M', 'N', 'T'],
      answer: [0, 2, 4],
      explain: "H, M et T se plient en deux parfaitement. L et N n'ont pas d'axe : en les pliant, les traits ne se superposent pas.",
    },
    {
      id: 'cm2-maths-symetrie-choice-3',
      kind: 'choice',
      prompt: "Sur un quadrillage, le point A est 2 carreaux à gauche de l'axe vertical. Où est son symétrique ?",
      options: ["2 carreaux à droite de l'axe", "2 carreaux à gauche de l'axe", "4 carreaux à droite de l'axe"],
      answer: 0,
      explain: "Même distance, de l'autre côté : 2 carreaux à droite de l'axe, sur la même ligne horizontale.",
    },
  ],
};

const SOLIDES: Lesson = {
  id: 'cm2-maths-solides',
  title: 'Solides et patrons',
  subject: 'maths',
  source: 'lecon',
  level: 'CM2',
  notion: 'Reconnaître, décrire et construire des solides et leurs patrons : cube, pavé, prisme, pyramide, cylindre',
  theme: 'geometrie',
  attendu: 'Reconnaître, décrire et construire des solides et leurs patrons : cube, pavé, prisme, pyramide, cylindre.',
  attenduId: 'cm2-geo-solides',
  summary:
    "Un solide a des faces, des arêtes et des sommets. Le cube a 6 faces carrées, 12 arêtes et 8 sommets. Le pavé droit a 6 faces rectangulaires. Le prisme a deux bases identiques et des faces rectangulaires ; la pyramide a une base et des faces triangulaires qui se rejoignent en un sommet. Le patron, c'est le solide mis à plat, qu'on plie pour le fabriquer.",
  minutes: 7,
  exercises: [
    {
      id: 'cm2-maths-solides-choice-1',
      kind: 'choice',
      prompt: "Combien d'arêtes a un cube ?",
      options: ['6', '8', '12'],
      answer: 2,
      explain: "Un cube a 12 arêtes : 4 en haut, 4 en bas et 4 verticales. Il a 6 faces et 8 sommets.",
    },
    {
      id: 'cm2-maths-solides-tf-1',
      kind: 'truefalse',
      statement: 'Une pyramide à base carrée a 5 faces.',
      answer: true,
      explain: "Oui : la base carrée, plus 4 faces triangulaires qui montent vers le sommet.",
    },
    {
      id: 'cm2-maths-solides-sort-1',
      kind: 'sort',
      prompt: 'Prisme ou pyramide ? Range chaque phrase',
      boxes: ['Prisme', 'Pyramide'],
      items: [
        { word: 'deux bases identiques', box: 0 },
        { word: 'un seul sommet en haut', box: 1 },
        { word: 'faces latérales rectangulaires', box: 0 },
        { word: 'faces latérales triangulaires', box: 1 },
        { word: 'le pavé droit en est un', box: 0 },
      ],
      explain: "Le prisme, c'est deux bases pareilles reliées par des rectangles. La pyramide, c'est une base et des triangles qui se rejoignent en pointe.",
    },
    {
      id: 'cm2-maths-solides-blanks-1',
      kind: 'blanks',
      prompt: 'Complète la description du pavé droit',
      text: 'Un pavé droit a {{6}} faces, {{12}} arêtes et {{8}} sommets.',
      distractors: ['4', '10'],
      explain: "Comme le cube : 6 faces, 12 arêtes, 8 sommets. La différence, c'est que les faces du pavé sont des rectangles.",
    },
    {
      id: 'cm2-maths-solides-pairs-1',
      kind: 'pairs',
      prompt: 'Relie chaque solide à ses faces',
      pairs: [
        { a: 'Cube', b: '6 faces carrées' },
        { a: 'Cylindre', b: '2 disques et une face courbe' },
        { a: 'Pavé droit', b: '6 faces rectangulaires' },
        { a: 'Pyramide à base carrée', b: '1 carré et 4 triangles' },
      ],
      explain: "Pour reconnaître un solide, on regarde la forme de ses faces et on les compte.",
    },
    {
      id: 'cm2-maths-solides-fix-1',
      kind: 'fix',
      prompt: "Gribouille s'est trompé, corrige-le",
      words: ['Le', 'patron', "d'un", 'cube', 'a', '4', 'carrés'],
      wrongIndex: 5,
      correct: '6',
      distractors: ['4', '8'],
      explain: "Un cube a 6 faces, donc son patron a 6 carrés. Avec 4 carrés, il manquerait deux faces une fois plié.",
    },
    {
      id: 'cm2-maths-solides-choice-2',
      kind: 'choice',
      prompt: "Quel solide a un patron fait d'un rectangle et de deux disques ?",
      options: ['le cône', 'le cylindre', 'la pyramide'],
      answer: 1,
      explain: "Le rectangle s'enroule pour faire le tour, et les deux disques ferment le haut et le bas : c'est un cylindre, comme une boîte de conserve.",
    },
    {
      id: 'cm2-maths-solides-tf-2',
      kind: 'truefalse',
      statement: 'Six carrés alignés sur une seule ligne forment un patron de cube.',
      answer: false,
      explain: "En pliant six carrés en ligne, on obtient un tube ouvert qui se referme sur lui-même, pas un cube. Il faut des carrés de chaque côté pour fermer les faces.",
    },
    {
      id: 'cm2-maths-solides-flashcard-1',
      kind: 'flashcard',
      prompt: 'Réfléchis, puis retourne la carte',
      front: 'Combien de sommets a une pyramide à base carrée ?',
      back: '5 sommets : les 4 coins de la base et la pointe.',
      explain: "Les 4 coins du carré, plus le sommet où se rejoignent les triangles.",
    },
    {
      id: 'cm2-maths-solides-choice-3',
      kind: 'choice',
      prompt: 'Un prisme a pour bases deux triangles. Combien de faces a-t-il en tout ?',
      options: ['5', '6', '8'],
      answer: 0,
      explain: "Les 2 bases triangulaires, plus 3 faces rectangulaires, une pour chaque côté du triangle : 2 + 3 = 5 faces.",
    },
  ],
};

const REPERAGE: Lesson = {
  id: 'cm2-maths-reperage',
  title: 'Se repérer sur un plan',
  subject: 'maths',
  source: 'lecon',
  level: 'CM2',
  notion: "Se repérer sur un plan ou une carte avec une échelle et des coordonnées ; programmer un déplacement",
  theme: 'geometrie',
  attendu: "Se repérer sur un plan ou une carte à l'aide d'une échelle et de coordonnées ; programmer un déplacement.",
  attenduId: 'cm2-geo-reperage',
  summary:
    "Sur un plan, on repère une case avec une lettre et un nombre, comme à la bataille navale : la case C4. Sur un quadrillage, on donne les coordonnées d'un point : (3 ; 2), c'est 3 vers la droite et 2 vers le haut, toujours dans cet ordre. L'échelle dit combien vaut un centimètre sur le plan, et un programme de déplacement enchaîne des ordres : avance, tourne à droite.",
  minutes: 7,
  exercises: [
    {
      id: 'cm2-maths-reperage-choice-1',
      kind: 'choice',
      prompt: "Un point est 4 carreaux à droite et 1 carreau vers le haut de l'origine. Quelles sont ses coordonnées ?",
      options: ['(1 ; 4)', '(4 ; 1)', '(4 ; 4)'],
      answer: 1,
      explain: "On écrit d'abord le déplacement vers la droite, puis vers le haut : (4 ; 1). L'ordre compte.",
    },
    {
      id: 'cm2-maths-reperage-tf-1',
      kind: 'truefalse',
      statement: "Sur un plan à l'échelle 1/1 000, 1 cm représente 10 m.",
      answer: true,
      explain: "Oui : 1 cm × 1 000 = 1 000 cm, et 1 000 cm, c'est 10 m.",
    },
    {
      id: 'cm2-maths-reperage-blanks-1',
      kind: 'blanks',
      prompt: "Complète avec l'échelle de la carte",
      text: "Sur une carte à l'échelle 1/200 000, 1 cm représente {{2}} km. Deux villes séparées de 7 cm sur la carte sont donc à {{14}} km l'une de l'autre.",
      distractors: ['20', '9'],
      explain: "200 000 cm, c'est 2 000 m, soit 2 km. Pour 7 cm : 7 × 2 = 14 km.",
    },
    {
      id: 'cm2-maths-reperage-order-1',
      kind: 'order',
      prompt: "Le robot part de la case A1, face au nord. Remets les ordres dans l'ordre pour qu'il arrive en C3 en passant par A3",
      lines: [
        'Avance de 2 cases vers le nord : tu es en A3',
        "Tourne à droite : tu regardes vers l'est",
        'Avance de 2 cases : tu es en C3',
        'Tu es arrivé, stop',
      ],
      explain: "On monte d'abord de la ligne 1 à la ligne 3, puis on tourne vers l'est pour passer de la colonne A à la colonne C.",
    },
    {
      id: 'cm2-maths-reperage-pairs-1',
      kind: 'pairs',
      prompt: 'Relie chaque repère à sa signification',
      pairs: [
        { a: 'La case B3', b: 'colonne B, ligne 3' },
        { a: '(0 ; 0)', b: "l'origine du quadrillage" },
        { a: '(2 ; 5)', b: '2 à droite, 5 vers le haut' },
        { a: '(5 ; 2)', b: '5 à droite, 2 vers le haut' },
      ],
      explain: "Dans des coordonnées, le premier nombre est toujours le déplacement horizontal, le second le déplacement vertical.",
    },
    {
      id: 'cm2-maths-reperage-fix-1',
      kind: 'fix',
      prompt: "Gribouille s'est trompé, corrige-le",
      words: ['Le', 'point', '(3 ; 6)', 'est', 'à', '3', 'carreaux', 'à', 'droite', 'et', '3', 'vers', 'le', 'haut'],
      wrongIndex: 10,
      correct: '6',
      distractors: ['3', '9'],
      explain: "Le second nombre, 6, dit de combien on monte. Le point (3 ; 6) est 3 à droite et 6 vers le haut.",
    },
    {
      id: 'cm2-maths-reperage-sort-1',
      kind: 'sort',
      prompt: 'Range chaque point par rapport au point (2 ; 4)',
      boxes: ['Même ligne horizontale que (2 ; 4)', 'Même colonne que (2 ; 4)'],
      items: [
        { word: '(5 ; 4)', box: 0 },
        { word: '(2 ; 7)', box: 1 },
        { word: '(0 ; 4)', box: 0 },
        { word: '(2 ; 1)', box: 1 },
        { word: '(8 ; 4)', box: 0 },
        { word: '(2 ; 9)', box: 1 },
      ],
      explain: "Même hauteur, c'est le même second nombre : 4. Même colonne, c'est le même premier nombre : 2.",
    },
    {
      id: 'cm2-maths-reperage-choice-2',
      kind: 'choice',
      prompt: "Sur un plan à l'échelle 1/500, la cour mesure 8 cm. Quelle est sa vraie longueur ?",
      options: ['4 m', '40 m', '400 m'],
      answer: 1,
      explain: "8 × 500 = 4 000 cm, et 4 000 cm, c'est 40 m.",
    },
    {
      id: 'cm2-maths-reperage-tf-2',
      kind: 'truefalse',
      statement: 'En partant de (1 ; 1) et en avançant de 3 carreaux vers la droite, on arrive en (4 ; 1).',
      answer: true,
      explain: "Oui : on ajoute 3 au premier nombre, 1 + 3 = 4, et le second nombre ne change pas.",
    },
    {
      id: 'cm2-maths-reperage-tap-1',
      kind: 'tapword',
      prompt: "Touche le point qui est sur l'axe horizontal",
      words: ['(0 ; 3)', '(3 ; 0)', '(3 ; 3)'],
      answer: [1],
      explain: "Sur l'axe horizontal, on n'est pas monté du tout : le second nombre est 0. C'est le point (3 ; 0).",
    },
  ],
};

export const LESSONS: Lesson[] = [
  GRANDS_NOMBRES,
  FRACTIONS,
  DECIMAUX,
  CALCUL_MENTAL,
  OPERATIONS,
  DIVISION,
  PROPORTIONNALITE,
  ECHELLES_VITESSE,
  TABLEAUX_GRAPHIQUES,
  LONGUEURS,
  AIRES,
  DUREES,
  ANGLES,
  VOLUMES,
  FIGURES,
  SYMETRIE,
  SOLIDES,
  REPERAGE,
];
