import type { Lesson } from './types';

/**
 * Banque CP, mathématiques : quatorze leçons qui couvrent les attendus de
 * fin d'année (nombres, calcul, grandeurs et mesures, espace et géométrie).
 * Tout est neutre : l'univers habille à l'affichage. Les textes sont très
 * courts, car ils sont lus à voix haute à un enfant qui apprend à lire.
 */

const NOMBRES_20: Lesson = {
  id: 'cp-maths-nombres-20',
  title: "Les nombres jusqu'à 20",
  subject: 'maths',
  source: 'numeration',
  level: 'CP',
  notion: 'Lire, écrire et nommer les nombres jusqu\'à 20',
  theme: 'nombres',
  attendu: 'Lire, écrire et nommer les nombres jusqu\'à 100.',
  attenduId: 'cp-nb-lire',
  summary:
    'Après dix, on dit onze, douze, treize, quatorze, quinze, seize. Puis dix-sept, dix-huit, dix-neuf et vingt. Chaque nombre a un nom et des chiffres.',
  minutes: 6,
  exercises: [
    {
      id: 'cp-maths-nombres-20-choice-1',
      kind: 'choice',
      prompt: 'Quel nombre se dit « douze » ?',
      options: ['21', '12', '2'],
      answer: 1,
      explain: 'Douze, c\'est dix et deux : on écrit 12.',
    },
    {
      id: 'cp-maths-nombres-20-tf-1',
      kind: 'truefalse',
      statement: '15 se dit « quinze ».',
      answer: true,
      explain: 'Oui, 15 se dit quinze. C\'est dix et cinq.',
    },
    {
      id: 'cp-maths-nombres-20-match-1',
      kind: 'match',
      prompt: 'Relie chaque nombre à son nom',
      seconds: 60,
      pairs: [
        { a: '11', b: 'onze' },
        { a: '13', b: 'treize' },
        { a: '16', b: 'seize' },
        { a: '20', b: 'vingt' },
      ],
      explain: 'Pas grave. Onze, c\'est 11. Treize, c\'est 13. Seize, c\'est 16. Vingt, c\'est 20.',
    },
    {
      id: 'cp-maths-nombres-20-line-1',
      kind: 'numberline',
      prompt: 'Place le nombre 14',
      min: 0,
      max: 20,
      step: 1,
      answer: 14,
      explain: '14 vient juste après 13 et juste avant 15.',
    },
    {
      id: 'cp-maths-nombres-20-sort-1',
      kind: 'sort',
      prompt: 'Range chaque nombre dans la bonne boîte',
      boxes: ['Moins de 10', 'Plus de 10'],
      items: [
        { word: '7', box: 0 },
        { word: '15', box: 1 },
        { word: '3', box: 0 },
        { word: '18', box: 1 },
        { word: '9', box: 0 },
        { word: '12', box: 1 },
      ],
      explain: 'Un nombre à deux chiffres qui commence par 1, c\'est plus que 10.',
    },
    {
      id: 'cp-maths-nombres-20-blanks-1',
      kind: 'blanks',
      prompt: 'Complète avec le bon nombre',
      text: 'Dix-huit s\'écrit {{18}}. Dix-neuf s\'écrit {{19}}.',
      distractors: ['17', '81'],
      explain: 'Dix-huit, c\'est dix et huit : 18. Dix-neuf, c\'est dix et neuf : 19.',
    },
    {
      id: 'cp-maths-nombres-20-fix-1',
      kind: 'fix',
      prompt: 'Gribouille s\'est trompé, corrige-le',
      words: ['Seize', 's\'écrit', '61'],
      wrongIndex: 2,
      correct: '16',
      distractors: ['6', '61'],
      explain: 'Seize, c\'est dix et six : on écrit 16, le 1 d\'abord.',
    },
    {
      id: 'cp-maths-nombres-20-choice-2',
      kind: 'choice',
      prompt: 'Quel nombre vient juste après 19 ?',
      options: ['18', '21', '20'],
      answer: 2,
      explain: 'Après dix-neuf, on dit vingt : 20.',
    },
    {
      id: 'cp-maths-nombres-20-pairs-1',
      kind: 'pairs',
      prompt: 'Retrouve chaque nombre et son nom',
      pairs: [
        { a: '14', b: 'quatorze' },
        { a: '17', b: 'dix-sept' },
        { a: '10', b: 'dix' },
        { a: '15', b: 'quinze' },
      ],
      explain: 'Dix-sept, c\'est dix et sept : 17. Quatorze, c\'est 14.',
    },
  ],
};

const NOMBRES_100: Lesson = {
  id: 'cp-maths-nombres-100',
  title: "Les nombres jusqu'à 100",
  subject: 'maths',
  source: 'numeration',
  level: 'CP',
  notion: 'Lire et écrire les dizaines entières et les nombres jusqu\'à 100',
  theme: 'nombres',
  attendu: 'Lire, écrire et nommer les nombres jusqu\'à 100.',
  attenduId: 'cp-nb-lire',
  summary:
    'Dix, vingt, trente, quarante, cinquante, soixante : ce sont des dizaines. Pour lire 47, on dit la dizaine puis le reste : quarante-sept. Cent, c\'est 100.',
  minutes: 7,
  exercises: [
    {
      id: 'cp-maths-nombres-100-choice-1',
      kind: 'choice',
      prompt: 'Quel nombre se dit « trente » ?',
      options: ['13', '30', '3'],
      answer: 1,
      explain: 'Trente, c\'est trois dizaines : 30.',
    },
    {
      id: 'cp-maths-nombres-100-tf-1',
      kind: 'truefalse',
      statement: '50 se dit « cinquante ».',
      answer: true,
      explain: 'Oui, 50 c\'est cinq dizaines : cinquante.',
    },
    {
      id: 'cp-maths-nombres-100-pairs-1',
      kind: 'pairs',
      prompt: 'Retrouve chaque dizaine et son nom',
      pairs: [
        { a: '20', b: 'vingt' },
        { a: '40', b: 'quarante' },
        { a: '60', b: 'soixante' },
        { a: '100', b: 'cent' },
      ],
      explain: 'Vingt, c\'est 20. Quarante, 40. Soixante, 60. Cent, 100.',
    },
    {
      id: 'cp-maths-nombres-100-line-1',
      kind: 'numberline',
      prompt: 'Place le nombre 70',
      min: 0,
      max: 100,
      step: 10,
      answer: 70,
      explain: '70, c\'est sept dizaines : sept sauts après 0.',
    },
    {
      id: 'cp-maths-nombres-100-choice-2',
      kind: 'choice',
      prompt: 'Comment se lit 47 ?',
      options: ['quarante-sept', 'quatorze', 'soixante-sept'],
      answer: 0,
      explain: '47, c\'est quarante et sept : quarante-sept.',
    },
    {
      id: 'cp-maths-nombres-100-blanks-1',
      kind: 'blanks',
      prompt: 'Complète le nom du nombre',
      text: 'Le nombre 25 se dit {{vingt}}-cinq. Le nombre 63 se dit {{soixante}}-trois.',
      distractors: ['trente', 'cinquante'],
      explain: '25, c\'est vingt et cinq. 63, c\'est soixante et trois.',
    },
    {
      id: 'cp-maths-nombres-100-sort-1',
      kind: 'sort',
      prompt: 'Range chaque nombre dans la bonne boîte',
      boxes: ['Moins de 50', 'Plus de 50'],
      items: [
        { word: '32', box: 0 },
        { word: '71', box: 1 },
        { word: '19', box: 0 },
        { word: '58', box: 1 },
        { word: '45', box: 0 },
        { word: '90', box: 1 },
      ],
      explain: 'Regarde le chiffre de gauche. S\'il est plus petit que 5, c\'est moins de 50.',
    },
    {
      id: 'cp-maths-nombres-100-fix-1',
      kind: 'fix',
      prompt: 'Gribouille s\'est trompé, corrige-le',
      words: ['Trente-six', 's\'écrit', '63'],
      wrongIndex: 2,
      correct: '36',
      distractors: ['63', '306'],
      explain: 'Trente-six, c\'est trente et six. On écrit le 3 puis le 6 : 36.',
    },
    {
      id: 'cp-maths-nombres-100-tf-2',
      kind: 'truefalse',
      statement: '99 vient juste avant 100.',
      answer: true,
      explain: 'Oui. Après 99, on arrive à 100 : cent.',
    },
    {
      id: 'cp-maths-nombres-100-choice-3',
      kind: 'choice',
      prompt: 'Quel nombre s\'écrit « cinquante-deux » ?',
      options: ['25', '502', '52'],
      answer: 2,
      explain: 'Cinquante, c\'est 50. Avec deux de plus, c\'est 52.',
    },
  ],
};

const COMPTER: Lesson = {
  id: 'cp-maths-compter',
  title: 'Compter et comparer',
  subject: 'maths',
  source: 'numeration',
  level: 'CP',
  notion: 'Dénombrer une collection, comparer et ranger des nombres',
  theme: 'nombres',
  attendu: 'Dénombrer une collection, comparer et ranger des nombres jusqu\'à 100.',
  attenduId: 'cp-nb-denombrer',
  summary:
    'Pour compter, on touche chaque objet une seule fois. Le dernier nombre dit combien il y en a. Plus un nombre est loin sur la file, plus il est grand.',
  minutes: 7,
  exercises: [
    {
      id: 'cp-maths-compter-count-1',
      kind: 'count',
      prompt: 'Combien de pommes ?',
      emoji: '🍎',
      answer: 6,
      options: [5, 6, 7],
      explain: 'Compte une pomme à la fois : un, deux, trois… jusqu\'à six.',
    },
    {
      id: 'cp-maths-compter-count-2',
      kind: 'count',
      prompt: 'Combien d\'étoiles ?',
      emoji: '⭐',
      answer: 12,
      options: [11, 12, 13, 14],
      explain: 'Touche chaque étoile une seule fois. Il y en a douze.',
    },
    {
      id: 'cp-maths-compter-choice-1',
      kind: 'choice',
      prompt: 'Quel nombre est le plus grand ?',
      options: ['8', '14', '11'],
      answer: 1,
      explain: 'Le plus grand est le plus loin quand on compte : 14.',
    },
    {
      id: 'cp-maths-compter-tf-1',
      kind: 'truefalse',
      statement: '9 est plus petit que 6.',
      answer: false,
      explain: 'Non. On dit 6 avant 9 en comptant, donc 9 est plus grand.',
    },
    {
      id: 'cp-maths-compter-order-1',
      kind: 'order',
      prompt: 'Range les nombres du plus petit au plus grand',
      lines: ['4', '9', '13'],
      explain: 'On commence par le plus petit : 4, puis 9, puis 13.',
    },
    {
      id: 'cp-maths-compter-count-3',
      kind: 'count',
      prompt: 'Combien de briques ?',
      emoji: '🧱',
      answer: 17,
      options: [15, 16, 17, 18],
      explain: 'Compte par ligne, sans en oublier. Il y en a dix-sept.',
    },
    {
      id: 'cp-maths-compter-sort-1',
      kind: 'sort',
      prompt: 'Plus petit ou plus grand que 10 ?',
      boxes: ['Plus petit que 10', 'Plus grand que 10'],
      items: [
        { word: '6', box: 0 },
        { word: '13', box: 1 },
        { word: '2', box: 0 },
        { word: '19', box: 1 },
        { word: '11', box: 1 },
      ],
      explain: 'Les nombres qu\'on dit avant dix sont plus petits que 10.',
    },
    {
      id: 'cp-maths-compter-order-2',
      kind: 'order',
      prompt: 'Range les nombres du plus petit au plus grand',
      lines: ['12', '21', '30'],
      explain: '12, c\'est une dizaine. 21, deux dizaines. 30, trois dizaines.',
    },
    {
      id: 'cp-maths-compter-choice-2',
      kind: 'choice',
      prompt: 'Quel nombre est le plus petit ?',
      options: ['25', '52', '15'],
      answer: 2,
      explain: '15 n\'a qu\'une dizaine : c\'est le plus petit.',
    },
  ],
};

const DIZAINES: Lesson = {
  id: 'cp-maths-dizaines',
  title: 'Dizaines et unités',
  subject: 'maths',
  source: 'numeration',
  level: 'CP',
  notion: 'Comprendre les dizaines et les unités, décomposer un nombre à deux chiffres',
  theme: 'nombres',
  attendu: 'Comprendre les dizaines et les unités, décomposer un nombre à deux chiffres.',
  attenduId: 'cp-nb-dizaines',
  summary:
    'Dix unités font une dizaine. Dans 34, le 3 compte les dizaines et le 4 les unités. On peut écrire 34 = 30 + 4.',
  minutes: 7,
  exercises: [
    {
      id: 'cp-maths-dizaines-qty-1',
      kind: 'quantity',
      prompt: 'Fabrique le nombre 13 avec des barres de dix et des cubes',
      target: 13,
      tens: true,
      explain: '13, c\'est une barre de dix et trois cubes.',
    },
    {
      id: 'cp-maths-dizaines-qty-2',
      kind: 'quantity',
      prompt: 'Fabrique le nombre 34',
      target: 34,
      tens: true,
      explain: '34, c\'est trois barres de dix et quatre cubes.',
    },
    {
      id: 'cp-maths-dizaines-choice-1',
      kind: 'choice',
      prompt: 'Combien de dizaines dans 34 ?',
      options: ['4', '3', '34'],
      answer: 1,
      explain: 'Le chiffre de gauche compte les dizaines : 3 dizaines.',
    },
    {
      id: 'cp-maths-dizaines-blanks-1',
      kind: 'blanks',
      prompt: 'Décompose le nombre',
      text: '34 = {{30}} + {{4}}',
      distractors: ['3', '40'],
      explain: '3 dizaines font 30, et il reste 4 unités.',
    },
    {
      id: 'cp-maths-dizaines-tf-1',
      kind: 'truefalse',
      statement: 'Dans 25, il y a 2 dizaines.',
      answer: true,
      explain: 'Oui. 25, c\'est deux barres de dix et cinq cubes.',
    },
    {
      id: 'cp-maths-dizaines-qty-3',
      kind: 'quantity',
      prompt: 'Fabrique le nombre 52',
      target: 52,
      tens: true,
      explain: '52, c\'est cinq barres de dix et deux cubes.',
    },
    {
      id: 'cp-maths-dizaines-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a mal décomposé, corrige-le',
      words: ['46', '=', '4', '+', '6'],
      wrongIndex: 2,
      correct: '40',
      distractors: ['4', '400'],
      explain: 'Le 4 de 46 compte des dizaines : ça fait 40, pas 4.',
    },
    {
      id: 'cp-maths-dizaines-sort-1',
      kind: 'sort',
      prompt: 'Où est le 5 dans chaque nombre ?',
      boxes: ['Le 5 compte les unités', 'Le 5 compte les dizaines'],
      items: [
        { word: '15', box: 0 },
        { word: '51', box: 1 },
        { word: '45', box: 0 },
        { word: '58', box: 1 },
        { word: '25', box: 0 },
      ],
      explain: 'Le chiffre de droite compte les unités. Celui de gauche compte les dizaines.',
    },
    {
      id: 'cp-maths-dizaines-choice-2',
      kind: 'choice',
      prompt: 'Quel nombre vaut 20 + 7 ?',
      options: ['207', '27', '72'],
      answer: 1,
      explain: '2 dizaines et 7 unités : 27.',
    },
  ],
};

const SUITE: Lesson = {
  id: 'cp-maths-suite',
  title: 'La file des nombres',
  subject: 'maths',
  source: 'numeration',
  level: 'CP',
  notion: 'Compter de 2 en 2, de 5 en 5, de 10 en 10, trouver le nombre avant et après',
  theme: 'nombres',
  attendu: 'Compter de 1 en 1, de 2 en 2, de 5 en 5 et de 10 en 10 ; se repérer sur la file numérique.',
  attenduId: 'cp-nb-suite',
  summary:
    'Sur la file, chaque nombre a un voisin avant et un voisin après. On peut sauter de 2 en 2 : 2, 4, 6, 8. Ou de 10 en 10 : 10, 20, 30.',
  minutes: 7,
  exercises: [
    {
      id: 'cp-maths-suite-line-1',
      kind: 'numberline',
      prompt: 'Place le nombre 8',
      min: 0,
      max: 20,
      step: 1,
      answer: 8,
      explain: '8 vient juste après 7 et juste avant 9.',
    },
    {
      id: 'cp-maths-suite-choice-1',
      kind: 'choice',
      prompt: 'Quel nombre vient juste avant 12 ?',
      options: ['13', '11', '10'],
      answer: 1,
      explain: 'Juste avant 12, il y a 11. On recule d\'un seul pas.',
    },
    {
      id: 'cp-maths-suite-blanks-1',
      kind: 'blanks',
      prompt: 'Complète la suite de 2 en 2',
      text: '2, 4, {{6}}, 8, {{10}}, 12',
      distractors: ['7', '9'],
      explain: 'De 2 en 2, on saute un nombre à chaque fois : 2, 4, 6, 8, 10, 12.',
    },
    {
      id: 'cp-maths-suite-tf-1',
      kind: 'truefalse',
      statement: 'Juste après 19 vient 20.',
      answer: true,
      explain: 'Oui : 19, puis 20. On avance d\'un pas.',
    },
    {
      id: 'cp-maths-suite-order-1',
      kind: 'order',
      prompt: 'Remets la suite de 5 en 5 dans l\'ordre',
      lines: ['5', '10', '15', '20'],
      explain: 'De 5 en 5 : 5, 10, 15, 20. C\'est comme compter sur les doigts d\'une main.',
    },
    {
      id: 'cp-maths-suite-line-2',
      kind: 'numberline',
      prompt: 'Place le nombre 40',
      min: 0,
      max: 100,
      step: 10,
      answer: 40,
      explain: 'De 10 en 10 : 10, 20, 30, 40. Quatre sauts.',
    },
    {
      id: 'cp-maths-suite-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a sauté un nombre, corrige-le',
      words: ['10', '20', '30', '50'],
      wrongIndex: 3,
      correct: '40',
      distractors: ['35', '50'],
      explain: 'De 10 en 10, après 30 vient 40, pas 50.',
    },
    {
      id: 'cp-maths-suite-blanks-2',
      kind: 'blanks',
      prompt: 'Complète avec le nombre avant et le nombre après',
      text: '{{29}}, 30, {{31}}',
      distractors: ['20', '40'],
      explain: 'Juste avant 30, il y a 29. Juste après, il y a 31.',
    },
    {
      id: 'cp-maths-suite-speed-1',
      kind: 'speed',
      prompt: 'Calcul éclair : le nombre juste après',
      seconds: 60,
      target: 4,
      items: [
        { q: 'Après 4', a: 5 },
        { q: 'Après 9', a: 10 },
        { q: 'Après 15', a: 16 },
        { q: 'Après 11', a: 12 },
        { q: 'Après 19', a: 20 },
        { q: 'Après 6', a: 7 },
        { q: 'Après 13', a: 14 },
      ],
      explain: 'Pas grave : le nombre juste après, c\'est un de plus.',
    },
  ],
};

const ADDITIONS: Lesson = {
  id: 'cp-maths-additions',
  title: 'Les petites additions',
  subject: 'maths',
  source: 'calcul',
  level: 'CP',
  notion: 'Additionner de petits nombres jusqu\'à 20, connaître les compléments à 10',
  theme: 'calcul',
  attendu: 'Additionner et soustraire de petits nombres, connaître les compléments à 10.',
  attenduId: 'cp-calc-add',
  summary:
    'Ajouter, c\'est mettre ensemble. 3 + 4, c\'est 3 et encore 4 : 7. Les amis de 10 : 1 et 9, 2 et 8, 3 et 7, 4 et 6, 5 et 5.',
  minutes: 7,
  exercises: [
    {
      id: 'cp-maths-additions-count-1',
      kind: 'count',
      prompt: 'Compte les fleurs. Puis ajoute 2. Combien ?',
      emoji: '🌸',
      answer: 5,
      options: [3, 4, 5, 6],
      explain: 'Il y a 3 fleurs. 3 et encore 2 : 4, 5. Ça fait 5.',
    },
    {
      id: 'cp-maths-additions-choice-1',
      kind: 'choice',
      prompt: 'Combien font 3 + 4 ?',
      options: ['6', '7', '8'],
      answer: 1,
      explain: 'Pars de 3 et avance de 4 : 4, 5, 6, 7.',
    },
    {
      id: 'cp-maths-additions-match-1',
      kind: 'match',
      prompt: 'Relie chaque nombre à son ami de 10',
      seconds: 60,
      pairs: [
        { a: '3 + ?', b: '7' },
        { a: '8 + ?', b: '2' },
        { a: '5 + ?', b: '5' },
        { a: '9 + ?', b: '1' },
        { a: '4 + ?', b: '6' },
      ],
      explain: 'Pas grave. Les amis de 10 : 3 et 7, 8 et 2, 5 et 5, 9 et 1, 4 et 6.',
    },
    {
      id: 'cp-maths-additions-tf-1',
      kind: 'truefalse',
      statement: '6 + 4 = 10',
      answer: true,
      explain: 'Oui, 6 et 4 sont des amis de 10.',
    },
    {
      id: 'cp-maths-additions-blanks-1',
      kind: 'blanks',
      prompt: 'Complète les calculs',
      text: '5 + 3 = {{8}} et 2 + 7 = {{9}}',
      distractors: ['7', '10'],
      explain: '5 et 3 : 6, 7, 8. 2 et 7 : c\'est pareil que 7 et 2, donc 9.',
    },
    {
      id: 'cp-maths-additions-fix-1',
      kind: 'fix',
      prompt: 'Gribouille s\'est trompé, corrige-le',
      words: ['7', '+', '3', '=', '11'],
      wrongIndex: 4,
      correct: '10',
      distractors: ['11', '9'],
      explain: '7 et 3 sont des amis de 10. 7 + 3 = 10.',
    },
    {
      id: 'cp-maths-additions-sort-1',
      kind: 'sort',
      prompt: 'Est-ce que ça fait 10 ?',
      boxes: ['Ça fait 10', 'Ça ne fait pas 10'],
      items: [
        { word: '6 + 4', box: 0 },
        { word: '5 + 4', box: 1 },
        { word: '2 + 8', box: 0 },
        { word: '7 + 2', box: 1 },
        { word: '1 + 9', box: 0 },
      ],
      explain: 'Pense aux amis de 10 : 6 et 4, 2 et 8, 1 et 9.',
    },
    {
      id: 'cp-maths-additions-choice-2',
      kind: 'choice',
      prompt: 'Combien font 10 + 6 ?',
      options: ['16', '15', '17'],
      answer: 0,
      explain: 'Dix et six, c\'est seize : 16.',
    },
    {
      id: 'cp-maths-additions-speed-1',
      kind: 'speed',
      prompt: 'Calcul éclair : petites additions',
      seconds: 60,
      target: 5,
      items: [
        { q: '2 + 2', a: 4 },
        { q: '5 + 1', a: 6 },
        { q: '3 + 3', a: 6 },
        { q: '4 + 5', a: 9 },
        { q: '6 + 2', a: 8 },
        { q: '10 + 3', a: 13 },
        { q: '7 + 1', a: 8 },
        { q: '8 + 2', a: 10 },
      ],
      explain: 'Pas grave : pars du plus grand nombre et avance avec les doigts.',
    },
  ],
};

const SOUSTRACTIONS: Lesson = {
  id: 'cp-maths-soustractions',
  title: 'Les petites soustractions',
  subject: 'maths',
  source: 'calcul',
  level: 'CP',
  notion: 'Enlever, soustraire de petits nombres jusqu\'à 20',
  theme: 'calcul',
  attendu: 'Additionner et soustraire de petits nombres, connaître les compléments à 10.',
  attenduId: 'cp-calc-add',
  summary:
    'Soustraire, c\'est enlever. 7 moins 2 : j\'ai 7, j\'enlève 2, il reste 5. On peut reculer sur la file des nombres.',
  minutes: 7,
  exercises: [
    {
      id: 'cp-maths-soustractions-count-1',
      kind: 'count',
      prompt: 'Compte les ballons. Un ballon s\'envole. Combien il en reste ?',
      emoji: '🎈',
      answer: 4,
      options: [3, 4, 5, 6],
      explain: 'Il y a 5 ballons. On en enlève 1, il en reste 4.',
    },
    {
      id: 'cp-maths-soustractions-choice-1',
      kind: 'choice',
      prompt: 'Combien font 7 moins 2 ?',
      options: ['9', '4', '5'],
      answer: 2,
      explain: 'Pars de 7 et recule de 2 : 6, 5. Il reste 5.',
    },
    {
      id: 'cp-maths-soustractions-tf-1',
      kind: 'truefalse',
      statement: '10 moins 3 = 7',
      answer: true,
      explain: 'Oui : 3 et 7 sont des amis de 10. Si on enlève 3, il reste 7.',
    },
    {
      id: 'cp-maths-soustractions-line-1',
      kind: 'numberline',
      prompt: 'Pars de 9 et recule de 4. Place le résultat',
      min: 0,
      max: 20,
      step: 1,
      answer: 5,
      explain: 'Depuis 9, quatre pas en arrière : 8, 7, 6, 5.',
    },
    {
      id: 'cp-maths-soustractions-blanks-1',
      kind: 'blanks',
      prompt: 'Complète les calculs',
      text: '8 moins 3 = {{5}} et 6 moins 6 = {{0}}',
      distractors: ['6', '1'],
      explain: '8 moins 3, il reste 5. Si on enlève tout, il reste 0.',
    },
    {
      id: 'cp-maths-soustractions-sort-1',
      kind: 'sort',
      prompt: 'Est-ce qu\'on ajoute ou on enlève ?',
      boxes: ['On ajoute', 'On enlève'],
      items: [
        { word: 'Léa gagne 2 billes', box: 0 },
        { word: 'Tom mange 3 fraises', box: 1 },
        { word: 'Il reçoit 1 livre', box: 0 },
        { word: 'Un oiseau s\'envole', box: 1 },
        { word: 'Elle perd 4 cartes', box: 1 },
      ],
      explain: 'Gagner ou recevoir, c\'est ajouter. Manger, perdre ou partir, c\'est enlever.',
    },
    {
      id: 'cp-maths-soustractions-fix-1',
      kind: 'fix',
      prompt: 'Gribouille s\'est trompé, corrige-le',
      words: ['9', 'moins', '4', '=', '6'],
      wrongIndex: 4,
      correct: '5',
      distractors: ['6', '13'],
      explain: 'Depuis 9, on recule de 4 : 8, 7, 6, 5. Il reste 5.',
    },
    {
      id: 'cp-maths-soustractions-choice-2',
      kind: 'choice',
      prompt: 'Combien font 15 moins 5 ?',
      options: ['10', '20', '5'],
      answer: 0,
      explain: '15, c\'est 10 et 5. Si on enlève 5, il reste 10.',
    },
    {
      id: 'cp-maths-soustractions-pairs-1',
      kind: 'pairs',
      prompt: 'Retrouve chaque calcul et son résultat',
      pairs: [
        { a: '5 moins 2', b: '3' },
        { a: '10 moins 4', b: '6' },
        { a: '8 moins 1', b: '7' },
        { a: '12 moins 2', b: '10' },
      ],
      explain: 'Pour enlever, recule sur la file des nombres.',
    },
  ],
};

const DOUBLES: Lesson = {
  id: 'cp-maths-doubles',
  title: 'Les doubles et le calcul en ligne',
  subject: 'maths',
  source: 'calcul',
  level: 'CP',
  notion: 'Connaître les doubles jusqu\'à 10 + 10, ajouter des dizaines entières',
  theme: 'calcul',
  attendu: 'Connaître les doubles jusqu\'à 10 + 10 et calculer en ligne jusqu\'à 100.',
  attenduId: 'cp-calc-doubles',
  summary:
    'Le double, c\'est deux fois pareil : le double de 3, c\'est 3 + 3 = 6. Pour 30 + 20, on compte les dizaines : 3 et 2 font 5, donc 50.',
  minutes: 7,
  exercises: [
    {
      id: 'cp-maths-doubles-count-1',
      kind: 'count',
      prompt: 'Compte les cerises. Combien font le double ?',
      emoji: '🍒',
      answer: 8,
      options: [4, 6, 8, 10],
      explain: 'Il y a 4 cerises. Le double, c\'est 4 + 4 = 8.',
    },
    {
      id: 'cp-maths-doubles-choice-1',
      kind: 'choice',
      prompt: 'Quel est le double de 3 ?',
      options: ['5', '6', '9'],
      answer: 1,
      explain: 'Le double de 3, c\'est 3 + 3 = 6.',
    },
    {
      id: 'cp-maths-doubles-tf-1',
      kind: 'truefalse',
      statement: 'Le double de 5, c\'est 10.',
      answer: true,
      explain: 'Oui : 5 + 5 = 10. Deux mains, dix doigts.',
    },
    {
      id: 'cp-maths-doubles-pairs-1',
      kind: 'pairs',
      prompt: 'Retrouve chaque nombre et son double',
      pairs: [
        { a: '2', b: '4' },
        { a: '6', b: '12' },
        { a: '8', b: '16' },
        { a: '10', b: '20' },
      ],
      explain: 'Le double, c\'est le nombre ajouté à lui-même : 6 + 6 = 12.',
    },
    {
      id: 'cp-maths-doubles-blanks-1',
      kind: 'blanks',
      prompt: 'Complète les doubles',
      text: '7 + 7 = {{14}} et 9 + 9 = {{18}}',
      distractors: ['16', '17'],
      explain: '7 + 7 = 14. 9 + 9 = 18. Un peu moins que 10 + 10.',
    },
    {
      id: 'cp-maths-doubles-choice-2',
      kind: 'choice',
      prompt: 'Combien font 30 + 20 ?',
      options: ['40', '32', '50'],
      answer: 2,
      explain: '3 dizaines et 2 dizaines font 5 dizaines : 50.',
    },
    {
      id: 'cp-maths-doubles-fix-1',
      kind: 'fix',
      prompt: 'Gribouille s\'est trompé, corrige-le',
      words: ['40', '+', '10', '=', '41'],
      wrongIndex: 4,
      correct: '50',
      distractors: ['41', '30'],
      explain: 'On ajoute une dizaine entière : 4 dizaines et 1 dizaine, 50.',
    },
    {
      id: 'cp-maths-doubles-sort-1',
      kind: 'sort',
      prompt: 'Est-ce un double ?',
      boxes: ['C\'est un double', 'Ce n\'est pas un double'],
      items: [
        { word: '4 + 4', box: 0 },
        { word: '3 + 5', box: 1 },
        { word: '9 + 9', box: 0 },
        { word: '6 + 7', box: 1 },
        { word: '1 + 1', box: 0 },
      ],
      explain: 'Un double, c\'est deux fois le même nombre.',
    },
    {
      id: 'cp-maths-doubles-speed-1',
      kind: 'speed',
      prompt: 'Calcul éclair : des dizaines',
      seconds: 60,
      target: 4,
      items: [
        { q: '10 + 10', a: 20 },
        { q: '20 + 30', a: 50 },
        { q: '50 + 10', a: 60 },
        { q: '30 + 30', a: 60 },
        { q: '60 + 20', a: 80 },
        { q: '40 + 40', a: 80 },
        { q: '70 + 10', a: 80 },
      ],
      explain: 'Pas grave : compte les dizaines comme des petits nombres, puis ajoute un 0.',
    },
  ],
};

const PROBLEMES: Lesson = {
  id: 'cp-maths-problemes',
  title: 'Les petits problèmes',
  subject: 'maths',
  source: 'calcul',
  level: 'CP',
  notion: 'Résoudre des problèmes d\'ajout, de retrait et de partage en deux',
  theme: 'calcul',
  attendu: 'Résoudre des problèmes simples d\'ajout, de retrait et de partage.',
  attenduId: 'cp-calc-problemes',
  summary:
    'Un problème, c\'est une petite histoire avec des nombres. On cherche si on ajoute, si on enlève, ou si on partage. Puis on calcule.',
  minutes: 8,
  exercises: [
    {
      id: 'cp-maths-problemes-choice-1',
      kind: 'choice',
      prompt: 'Léa a 3 billes. Elle en gagne 2. Combien a-t-elle de billes ?',
      options: ['1', '5', '6'],
      answer: 1,
      explain: 'Elle gagne, donc on ajoute : 3 + 2 = 5 billes.',
    },
    {
      id: 'cp-maths-problemes-count-1',
      kind: 'count',
      prompt: 'Tom a ces bonbons. Il en mange 2. Combien il en reste ?',
      emoji: '🍬',
      answer: 4,
      options: [2, 4, 6, 8],
      explain: 'Il y a 6 bonbons. On en enlève 2, il en reste 4.',
    },
    {
      id: 'cp-maths-problemes-sort-1',
      kind: 'sort',
      prompt: 'Dans chaque histoire, on ajoute ou on enlève ?',
      boxes: ['On ajoute', 'On enlève'],
      items: [
        { word: 'Maman donne 2 gâteaux', box: 0 },
        { word: 'Le chat casse 1 bol', box: 1 },
        { word: 'Papa achète 3 pommes', box: 0 },
        { word: 'Lou offre 4 cartes à Max', box: 1 },
      ],
      explain: 'Donner à quelqu\'un ou casser, c\'est enlever. Recevoir ou acheter, c\'est ajouter.',
    },
    {
      id: 'cp-maths-problemes-tf-1',
      kind: 'truefalse',
      statement: 'Max a 8 cartes. Il en perd 3. Il lui reste 5 cartes.',
      answer: true,
      explain: 'Oui : il perd, donc on enlève. 8 moins 3 = 5.',
    },
    {
      id: 'cp-maths-problemes-blanks-1',
      kind: 'blanks',
      prompt: 'Complète l\'histoire',
      text: 'Nina a 6 fraises. Elle partage en deux avec Sam. Chacun a {{3}} fraises.',
      distractors: ['2', '4'],
      explain: 'Partager en deux, c\'est chercher la moitié : 3 + 3 = 6.',
    },
    {
      id: 'cp-maths-problemes-choice-2',
      kind: 'choice',
      prompt: 'Il y a 4 oiseaux. 5 oiseaux arrivent. Combien d\'oiseaux ?',
      options: ['9', '1', '8'],
      answer: 0,
      explain: 'Des oiseaux arrivent, donc on ajoute : 4 + 5 = 9.',
    },
    {
      id: 'cp-maths-problemes-fix-1',
      kind: 'fix',
      prompt: 'Gribouille s\'est trompé, corrige-le',
      words: ['Lou', 'a', '10', 'images.', 'Elle', 'en', 'donne', '4.', 'Il', 'lui', 'reste', '14.'],
      wrongIndex: 11,
      correct: '6.',
      distractors: ['14.', '4.'],
      explain: 'Elle donne, donc on enlève : 10 moins 4 = 6.',
    },
    {
      id: 'cp-maths-problemes-pairs-1',
      kind: 'pairs',
      prompt: 'Retrouve chaque histoire et son calcul',
      pairs: [
        { a: 'Sam a 2 livres, il en reçoit 3', b: '2 + 3' },
        { a: 'Ana a 7 billes, elle en perd 2', b: '7 moins 2' },
        { a: 'Il y a 5 chats, 4 chats arrivent', b: '5 + 4' },
        { a: 'Théo a 9 bonbons, il en mange 3', b: '9 moins 3' },
      ],
      explain: 'Recevoir ou arriver, c\'est plus. Perdre ou manger, c\'est moins.',
    },
    {
      id: 'cp-maths-problemes-choice-3',
      kind: 'choice',
      prompt: 'Il y a 10 gâteaux pour 2 enfants. Chacun en a combien ?',
      options: ['8', '5', '12'],
      answer: 1,
      explain: 'On partage en deux parts pareilles : 5 et 5 font 10.',
    },
  ],
};

const LONGUEURS: Lesson = {
  id: 'cp-maths-longueurs',
  title: 'Plus long, plus court',
  subject: 'maths',
  source: 'lecon',
  level: 'CP',
  notion: 'Comparer des longueurs et mesurer en centimètres avec la règle',
  theme: 'grandeurs',
  attendu: 'Comparer et mesurer des longueurs avec une règle, en centimètres.',
  attenduId: 'cp-gm-longueurs',
  summary:
    'Pour comparer, on met les deux objets côte à côte au même départ. Pour mesurer, on pose la règle au 0 et on lit le nombre au bout. Ça donne des centimètres.',
  minutes: 6,
  exercises: [
    {
      id: 'cp-maths-longueurs-choice-1',
      kind: 'choice',
      prompt: 'Qu\'est-ce qui est le plus long ?',
      options: ['un crayon', 'une gomme', 'un balai'],
      answer: 2,
      explain: 'Un balai est très long. Une gomme est toute petite.',
    },
    {
      id: 'cp-maths-longueurs-tf-1',
      kind: 'truefalse',
      statement: 'Une fourmi est plus longue qu\'un bus.',
      answer: false,
      explain: 'Non, pas grave. Un bus est très long. Une fourmi est minuscule.',
    },
    {
      id: 'cp-maths-longueurs-sort-1',
      kind: 'sort',
      prompt: 'Plus court ou plus long qu\'un crayon ?',
      boxes: ['Plus court qu\'un crayon', 'Plus long qu\'un crayon'],
      items: [
        { word: 'un trombone', box: 0 },
        { word: 'une corde à sauter', box: 1 },
        { word: 'une pièce', box: 0 },
        { word: 'une table', box: 1 },
        { word: 'un bouton', box: 0 },
      ],
      explain: 'Imagine l\'objet à côté d\'un crayon. Est-ce qu\'il dépasse ?',
    },
    {
      id: 'cp-maths-longueurs-blanks-1',
      kind: 'blanks',
      prompt: 'Complète la règle de mesure',
      text: 'Pour mesurer, je pose la règle sur le {{0}}. Je lis le nombre au {{bout}}.',
      distractors: ['1', 'milieu'],
      explain: 'On commence toujours au 0, sinon la mesure est fausse. On lit le nombre tout au bout.',
    },
    {
      id: 'cp-maths-longueurs-line-1',
      kind: 'numberline',
      prompt: 'Un trait va du 0 jusqu\'à 7. Place sa longueur sur la règle',
      min: 0,
      max: 20,
      step: 1,
      answer: 7,
      explain: 'Le trait s\'arrête au 7 : il mesure 7 centimètres.',
    },
    {
      id: 'cp-maths-longueurs-choice-2',
      kind: 'choice',
      prompt: 'Mon crayon va du 0 au 12 sur la règle. Il mesure combien ?',
      options: ['12 centimètres', '10 centimètres', '0 centimètre'],
      answer: 0,
      explain: 'Il part du 0 et finit au 12 : il mesure 12 centimètres.',
    },
    {
      id: 'cp-maths-longueurs-order-1',
      kind: 'order',
      prompt: 'Range du plus court au plus long',
      lines: ['3 centimètres', '8 centimètres', '15 centimètres'],
      explain: 'Plus le nombre est petit, plus c\'est court : 3, puis 8, puis 15.',
    },
    {
      id: 'cp-maths-longueurs-fix-1',
      kind: 'fix',
      prompt: 'Gribouille s\'est trompé, corrige-le',
      words: ['Un', 'bâton', 'de', '5', 'centimètres', 'est', 'plus', 'long', 'qu\'un', 'bâton', 'de', '9', 'centimètres.'],
      wrongIndex: 7,
      correct: 'court',
      distractors: ['long', 'lourd'],
      explain: '5 est plus petit que 9 : le bâton de 5 centimètres est plus court.',
    },
  ],
};

const TEMPS: Lesson = {
  id: 'cp-maths-temps-monnaie',
  title: 'Les jours et les heures',
  subject: 'maths',
  source: 'lecon',
  level: 'CP',
  notion: 'Se repérer dans la journée et la semaine, lire les heures pleines',
  theme: 'grandeurs',
  attendu: 'Se repérer dans la journée, la semaine, le mois ; lire les heures pleines.',
  attenduId: 'cp-gm-temps',
  summary:
    'La semaine a 7 jours : lundi, mardi, mercredi, jeudi, vendredi, samedi, dimanche. La journée a le matin, le midi, le soir. Sur l\'horloge, la petite aiguille donne l\'heure.',
  minutes: 7,
  exercises: [
    {
      id: 'cp-maths-temps-monnaie-order-1',
      kind: 'order',
      prompt: 'Remets les jours dans l\'ordre',
      lines: ['lundi', 'mardi', 'mercredi', 'jeudi'],
      explain: 'La semaine commence par lundi, puis mardi, mercredi, jeudi.',
    },
    {
      id: 'cp-maths-temps-monnaie-choice-1',
      kind: 'choice',
      prompt: 'Quel jour vient juste après vendredi ?',
      options: ['jeudi', 'samedi', 'dimanche'],
      answer: 1,
      explain: 'Après vendredi, c\'est samedi. Puis dimanche.',
    },
    {
      id: 'cp-maths-temps-monnaie-sort-1',
      kind: 'sort',
      prompt: 'Matin ou soir ?',
      boxes: ['Le matin', 'Le soir'],
      items: [
        { word: 'Je me réveille', box: 0 },
        { word: 'Je vais au lit', box: 1 },
        { word: 'Je prends mon petit-déjeuner', box: 0 },
        { word: 'Je mets mon pyjama', box: 1 },
        { word: 'Le soleil se lève', box: 0 },
      ],
      explain: 'Le matin, la journée commence. Le soir, elle se termine et on va dormir.',
    },
    {
      id: 'cp-maths-temps-monnaie-tf-1',
      kind: 'truefalse',
      statement: 'Il y a 7 jours dans une semaine.',
      answer: true,
      explain: 'Oui : lundi, mardi, mercredi, jeudi, vendredi, samedi, dimanche. Ça fait 7.',
    },
    {
      id: 'cp-maths-temps-monnaie-blanks-1',
      kind: 'blanks',
      prompt: 'Complète les jours',
      text: 'mardi, {{mercredi}}, jeudi, vendredi, {{samedi}}, dimanche',
      distractors: ['lundi', 'matin'],
      explain: 'Entre mardi et jeudi, c\'est mercredi. Entre vendredi et dimanche, c\'est samedi.',
    },
    {
      id: 'cp-maths-temps-monnaie-choice-2',
      kind: 'choice',
      prompt: 'La petite aiguille est sur le 3. La grande est sur le 12. Quelle heure est-il ?',
      options: ['12 heures', '3 heures', '6 heures'],
      answer: 1,
      explain: 'La petite aiguille donne l\'heure. Sur le 3, il est 3 heures.',
    },
    {
      id: 'cp-maths-temps-monnaie-fix-1',
      kind: 'fix',
      prompt: 'Gribouille s\'est trompé, corrige-le',
      words: ['Après', 'dimanche,', 'la', 'semaine', 'recommence', 'par', 'mardi.'],
      wrongIndex: 6,
      correct: 'lundi.',
      distractors: ['mardi.', 'samedi.'],
      explain: 'Après dimanche, on recommence au premier jour : lundi.',
    },
    {
      id: 'cp-maths-temps-monnaie-pairs-1',
      kind: 'pairs',
      prompt: 'Retrouve le moment de la journée',
      pairs: [
        { a: 'Je mange à la cantine', b: 'midi' },
        { a: 'Je me brosse les dents avant l\'école', b: 'matin' },
        { a: 'Je lis une histoire au lit', b: 'soir' },
      ],
      explain: 'Le matin, c\'est avant l\'école. Le midi, c\'est le repas. Le soir, c\'est avant de dormir.',
    },
    {
      id: 'cp-maths-temps-monnaie-choice-3',
      kind: 'choice',
      prompt: 'La petite aiguille est sur le 8. Il est huit heures. On est le matin. Que fait-on ?',
      options: ['on dort', 'on va à l\'école', 'on dîne'],
      answer: 1,
      explain: 'Huit heures du matin, c\'est l\'heure d\'aller à l\'école.',
    },
  ],
};

const MONNAIE: Lesson = {
  id: 'cp-maths-monnaie',
  title: 'Les pièces en euros',
  subject: 'maths',
  source: 'lecon',
  level: 'CP',
  notion: 'Reconnaître les pièces de 1 et 2 euros, composer une petite somme',
  theme: 'grandeurs',
  attendu: 'Reconnaître les pièces et les billets, composer une somme en euros.',
  attenduId: 'cp-gm-monnaie',
  summary:
    'Il y a des pièces de 1 euro et des pièces de 2 euros. Pour faire 5 euros, on peut mettre 2 + 2 + 1. On additionne les pièces.',
  minutes: 5,
  exercises: [
    {
      id: 'cp-maths-monnaie-count-1',
      kind: 'count',
      prompt: 'Compte les pièces de 1 euro. Ça fait combien d\'euros ?',
      emoji: '🪙',
      answer: 4,
      options: [3, 4, 5],
      explain: 'Chaque pièce vaut 1 euro. 4 pièces, ça fait 4 euros.',
    },
    {
      id: 'cp-maths-monnaie-choice-1',
      kind: 'choice',
      prompt: 'Deux pièces de 2 euros, ça fait combien ?',
      options: ['2 euros', '4 euros', '3 euros'],
      answer: 1,
      explain: '2 + 2 = 4. Ça fait 4 euros.',
    },
    {
      id: 'cp-maths-monnaie-tf-1',
      kind: 'truefalse',
      statement: 'Une pièce de 2 euros vaut plus qu\'une pièce de 1 euro.',
      answer: true,
      explain: 'Oui : 2 est plus grand que 1. La pièce de 2 euros vaut deux pièces de 1 euro.',
    },
    {
      id: 'cp-maths-monnaie-blanks-1',
      kind: 'blanks',
      prompt: 'Complète pour faire 5 euros',
      text: '2 euros + 2 euros + {{1}} euro = 5 euros',
      distractors: ['2', '3'],
      explain: '2 + 2 = 4. Pour aller à 5, il manque 1 euro.',
    },
    {
      id: 'cp-maths-monnaie-sort-1',
      kind: 'sort',
      prompt: 'Est-ce que ça fait 5 euros ?',
      boxes: ['Ça fait 5 euros', 'Ça ne fait pas 5 euros'],
      items: [
        { word: '2 + 2 + 1', box: 0 },
        { word: '2 + 2', box: 1 },
        { word: '1 + 1 + 1 + 1 + 1', box: 0 },
        { word: '2 + 1 + 1 + 1', box: 0 },
        { word: '2 + 2 + 2', box: 1 },
      ],
      explain: 'Additionne les pièces. Si tu trouves 5, c\'est bon.',
    },
    {
      id: 'cp-maths-monnaie-fix-1',
      kind: 'fix',
      prompt: 'Gribouille s\'est trompé, corrige-le',
      words: ['Trois', 'pièces', 'de', '2', 'euros', 'font', '5', 'euros.'],
      wrongIndex: 6,
      correct: '6',
      distractors: ['5', '3'],
      explain: '2 + 2 + 2 = 6. Trois pièces de 2 euros font 6 euros.',
    },
    {
      id: 'cp-maths-monnaie-choice-2',
      kind: 'choice',
      prompt: 'Un jouet coûte 3 euros. J\'ai une pièce de 2 euros. Il me manque combien ?',
      options: ['1 euro', '2 euros', '5 euros'],
      answer: 0,
      explain: '2 + 1 = 3. Il manque 1 euro.',
    },
  ],
};

const FORMES: Lesson = {
  id: 'cp-maths-formes-espace',
  title: 'Les formes et les solides',
  subject: 'maths',
  source: 'lecon',
  level: 'CP',
  notion: 'Reconnaître le carré, le rectangle, le triangle, le rond, le cube et la boule',
  theme: 'geometrie',
  attendu: 'Reconnaître le carré, le rectangle, le triangle, le rond, le cube et la boule.',
  attenduId: 'cp-geo-formes',
  summary:
    'Le carré a 4 côtés pareils. Le rectangle a 4 côtés, 2 longs et 2 courts. Le triangle a 3 côtés. Le rond n\'a pas de côté. Le cube et la boule sont des solides, on peut les tenir.',
  minutes: 7,
  exercises: [
    {
      id: 'cp-maths-formes-espace-choice-1',
      kind: 'choice',
      prompt: 'Quelle forme a 3 côtés ?',
      options: ['carré', 'triangle', 'rond'],
      answer: 1,
      explain: 'Le triangle a 3 côtés et 3 pointes. Tri, ça veut dire trois.',
    },
    {
      id: 'cp-maths-formes-espace-tf-1',
      kind: 'truefalse',
      statement: 'Le carré a 4 côtés pareils.',
      answer: true,
      explain: 'Oui, les 4 côtés du carré ont la même longueur.',
    },
    {
      id: 'cp-maths-formes-espace-sort-1',
      kind: 'sort',
      prompt: 'Range chaque objet avec sa forme',
      boxes: ['Rond', 'Carré ou rectangle', 'Triangle'],
      items: [
        { word: 'une assiette', box: 0 },
        { word: 'une porte', box: 1 },
        { word: 'une part de pizza', box: 2 },
        { word: 'une pièce', box: 0 },
        { word: 'une fenêtre', box: 1 },
        { word: 'un toit', box: 2 },
      ],
      explain: 'Une assiette est ronde. Une porte est un rectangle. Un toit pointu est un triangle.',
    },
    {
      id: 'cp-maths-formes-espace-blanks-1',
      kind: 'blanks',
      prompt: 'Complète',
      text: 'Le rectangle a {{4}} côtés. Le triangle a {{3}} côtés. Le rond n\'a pas de côté.',
      distractors: ['2', '5'],
      explain: 'Le rectangle a 4 côtés, comme le carré. Le triangle en a 3.',
    },
    {
      id: 'cp-maths-formes-espace-choice-2',
      kind: 'choice',
      prompt: 'Un ballon de foot a la forme d\'une…',
      options: ['boule', 'cube', 'carré'],
      answer: 0,
      explain: 'Un ballon roule dans tous les sens : c\'est une boule.',
    },
    {
      id: 'cp-maths-formes-espace-sort-2',
      kind: 'sort',
      prompt: 'Cube ou boule ?',
      boxes: ['Cube', 'Boule'],
      items: [
        { word: 'un dé', box: 0 },
        { word: 'une bille', box: 1 },
        { word: 'une orange', box: 1 },
        { word: 'un gros carton', box: 0 },
        { word: 'un ballon', box: 1 },
      ],
      explain: 'Le cube a des faces plates, comme un dé. La boule roule, comme une bille.',
    },
    {
      id: 'cp-maths-formes-espace-fix-1',
      kind: 'fix',
      prompt: 'Gribouille s\'est trompé, corrige-le',
      words: ['Le', 'rond', 'a', '4', 'côtés.'],
      wrongIndex: 3,
      correct: '0',
      distractors: ['4', '1'],
      explain: 'Le rond n\'a pas de côté du tout : 0 côté. Il est tout lisse.',
    },
    {
      id: 'cp-maths-formes-espace-pairs-1',
      kind: 'pairs',
      prompt: 'Retrouve chaque forme et sa description',
      pairs: [
        { a: 'carré', b: '4 côtés pareils' },
        { a: 'triangle', b: '3 côtés' },
        { a: 'rond', b: 'pas de côté' },
        { a: 'rectangle', b: '2 côtés longs et 2 courts' },
      ],
      explain: 'Compte les côtés : 4 pareils pour le carré, 3 pour le triangle, 0 pour le rond.',
    },
    {
      id: 'cp-maths-formes-espace-tf-2',
      kind: 'truefalse',
      statement: 'Un dé est un cube.',
      answer: true,
      explain: 'Oui. Un dé a 6 faces carrées : c\'est un cube.',
    },
  ],
};

const ESPACE: Lesson = {
  id: 'cp-maths-espace',
  title: 'Devant, derrière, gauche, droite',
  subject: 'maths',
  source: 'lecon',
  level: 'CP',
  notion: 'Se repérer dans l\'espace : devant, derrière, dessus, dessous, gauche, droite',
  theme: 'geometrie',
  attendu: 'Se repérer dans l\'espace : devant, derrière, dessus, dessous, gauche, droite ; se déplacer sur un quadrillage.',
  attenduId: 'cp-geo-espace',
  summary:
    'Dessus, c\'est en haut. Dessous, c\'est en bas. Devant, on le voit. Derrière, il est caché. La main gauche et la main droite ne sont pas du même côté.',
  minutes: 5,
  exercises: [
    {
      id: 'cp-maths-espace-choice-1',
      kind: 'choice',
      prompt: 'Le chat est sur la table. Il est…',
      options: ['dessous', 'dessus', 'derrière'],
      answer: 1,
      explain: 'Sur la table, c\'est dessus, en haut.',
    },
    {
      id: 'cp-maths-espace-tf-1',
      kind: 'truefalse',
      statement: 'Le ballon est caché derrière le mur. On ne le voit pas.',
      answer: true,
      explain: 'Oui : derrière, c\'est caché. Devant, on le verrait.',
    },
    {
      id: 'cp-maths-espace-sort-1',
      kind: 'sort',
      prompt: 'Dessus ou dessous ?',
      boxes: ['Dessus', 'Dessous'],
      items: [
        { word: 'le toit de la maison', box: 0 },
        { word: 'les racines de l\'arbre', box: 1 },
        { word: 'le chapeau sur la tête', box: 0 },
        { word: 'le tapis sous les pieds', box: 1 },
        { word: 'la lampe au plafond', box: 0 },
      ],
      explain: 'Dessus, c\'est en haut. Dessous, c\'est en bas.',
    },
    {
      id: 'cp-maths-espace-blanks-1',
      kind: 'blanks',
      prompt: 'Complète avec le bon mot',
      text: 'Le chien dort {{sous}} la table. L\'oiseau vole {{au-dessus}} de l\'arbre.',
      distractors: ['devant', 'entre'],
      explain: 'Le chien est en bas : sous. L\'oiseau est en haut : au-dessus.',
    },
    {
      id: 'cp-maths-espace-tapword-1',
      kind: 'tapword',
      prompt: 'Touche le mot qui dit où est le sac',
      words: ['Le', 'sac', 'est', 'devant', 'la', 'porte.'],
      answer: [3],
      explain: 'Devant, c\'est le mot qui dit où est le sac.',
    },
    {
      id: 'cp-maths-espace-fix-1',
      kind: 'fix',
      prompt: 'Gribouille s\'est trompé, corrige-le',
      words: ['Mon', 'cœur', 'bat', 'du', 'côté', 'de', 'ma', 'main', 'droite.'],
      wrongIndex: 8,
      correct: 'gauche.',
      distractors: ['droite.', 'dessus.'],
      explain: 'Le cœur bat à gauche. Pose ta main dessus : c\'est ta main gauche.',
    },
    {
      id: 'cp-maths-espace-choice-2',
      kind: 'choice',
      prompt: 'Sur l\'horloge, le 3 est de quel côté ?',
      options: ['à gauche', 'en bas', 'à droite'],
      answer: 2,
      explain: 'Le 3 est à droite, le 9 est à gauche.',
    },
  ],
};

export const LESSONS: Lesson[] = [
  NOMBRES_20,
  NOMBRES_100,
  COMPTER,
  DIZAINES,
  SUITE,
  ADDITIONS,
  SOUSTRACTIONS,
  DOUBLES,
  PROBLEMES,
  LONGUEURS,
  TEMPS,
  MONNAIE,
  FORMES,
  ESPACE,
];
