import type { Lesson } from './types';

/**
 * Banque de français, CM1. Dix-neuf leçons qui couvrent les attendus de fin
 * de CM1 : lecture, poésie, rédaction, orthographe, grammaire, conjugaison,
 * vocabulaire. Tous les textes sont originaux, sauf la fable de La Fontaine
 * (domaine public, reprise mot pour mot de poems.ts).
 */

const LIRE_FLUIDE: Lesson = {
  id: 'cm1-francais-lire-fluide',
  title: 'Lire avec fluidité',
  subject: 'francais',
  source: 'lecture',
  level: 'CM1',
  notion: 'Lire à voix haute avec fluidité et expression : liaisons, ponctuation, groupes de souffle',
  theme: 'lecture',
  attendu: "Lire à voix haute avec fluidité et expression un texte d'une page, en respectant la ponctuation.",
  attenduId: 'cm1-lect-fluide',
  summary:
    "Pour lire sans hacher, on découpe la phrase en groupes de souffle : on respire aux virgules et aux points, jamais au milieu d'un groupe de mots. On fait la liaison quand un mot finit par une lettre muette et que le suivant commence par une voyelle. Voici le texte : Ce matin-là, Nora et son frère Adam partent à la pêche avec leur grand-père. Le lac est encore couvert de brume, et les oiseaux se taisent. « Vous allez voir, dit grand-père, les poissons sont au rendez-vous ! » Adam lance sa ligne trop fort : le bouchon disparaît dans les roseaux. Nora rit, puis elle attend, immobile, les yeux fixés sur l'eau. Soudain, sa canne se plie ! Elle tire, grand-père l'aide, et un énorme brochet sort de l'eau en éclaboussant tout le monde. « On le remet à l'eau ? » demande Nora. Grand-père hoche la tête : les animaux aussi ont le droit de vivre. Le brochet file sous les nénuphars, et les trois pêcheurs rentrent trempés, mais heureux.",
  minutes: 7,
  exercises: [
    {
      id: 'cm1-francais-lire-fluide-tap-1',
      kind: 'tapword',
      prompt: 'Touche les deux mots après lesquels on fait une liaison',
      words: ['Le', 'lac', 'est', 'encore', 'couvert', 'de', 'brume,', 'et', 'les', 'oiseaux', 'se', 'taisent.'],
      answer: [2, 8],
      explain: "« Est encore » se dit « est-t-encore » et « les oiseaux » se dit « les-z-oiseaux » : la lettre muette se fait entendre devant la voyelle.",
    },
    {
      id: 'cm1-francais-lire-fluide-choice-1',
      kind: 'choice',
      prompt: 'Comment lit-on « Soudain, sa canne se plie ! »',
      options: ['Avec une voix lente et triste', 'Avec une voix vive, pleine de surprise', 'Avec une voix qui monte comme une question'],
      answer: 1,
      explain: "Le mot « soudain » et le point d'exclamation annoncent une surprise : la voix s'anime d'un coup.",
    },
    {
      id: 'cm1-francais-lire-fluide-tap-2',
      kind: 'tapword',
      prompt: 'Touche les deux mots après lesquels on reprend son souffle',
      words: ['Elle', 'tire,', 'grand-père', "l'aide,", 'et', 'un', 'énorme', 'brochet', 'sort', 'de', "l'eau."],
      answer: [1, 3],
      explain: "Les virgules après « tire » et « l'aide » découpent la phrase en trois groupes de souffle. On ne respire pas au milieu d'un groupe.",
    },
    {
      id: 'cm1-francais-lire-fluide-tf-1',
      kind: 'truefalse',
      statement: 'Dans « un énorme brochet », on fait la liaison entre « un » et « énorme ».',
      answer: true,
      explain: 'Oui : « un » finit par un n muet et « énorme » commence par une voyelle, on dit « un-n-énorme ».',
    },
    {
      id: 'cm1-francais-lire-fluide-sort-1',
      kind: 'sort',
      prompt: 'Range chaque phrase selon la façon de la lire',
      boxes: ['La voix monte (question)', 'La voix descend (point)', "La voix s'anime (exclamation)"],
      items: [
        { word: "On le remet à l'eau ?", box: 0 },
        { word: 'Les poissons sont au rendez-vous !', box: 2 },
        { word: 'Nora rit, puis elle attend.', box: 1 },
        { word: 'Le lac est couvert de brume.', box: 1 },
        { word: 'Soudain, sa canne se plie !', box: 2 },
      ],
      explain: "Point d'interrogation : la voix monte. Point : la voix descend et s'arrête. Point d'exclamation : la voix s'anime.",
    },
    {
      id: 'cm1-francais-lire-fluide-order-1',
      kind: 'order',
      prompt: "Remets les phrases du texte dans l'ordre",
      lines: [
        'Nora et son frère Adam partent à la pêche avec leur grand-père.',
        'Adam lance sa ligne trop fort : le bouchon disparaît dans les roseaux.',
        'Soudain, la canne de Nora se plie !',
        'Un énorme brochet sort de l\'eau en éclaboussant tout le monde.',
      ],
      explain: "D'abord le départ, puis le lancer raté d'Adam, puis la canne qui se plie, et enfin le brochet qui sort de l'eau.",
    },
    {
      id: 'cm1-francais-lire-fluide-choice-2',
      kind: 'choice',
      prompt: 'Que fait-on en lisant les deux-points dans « Adam lance sa ligne trop fort : le bouchon disparaît » ?',
      options: ['On fait une petite pause, car la suite explique ce qui arrive', 'On lit plus vite sans respirer', 'On monte la voix comme pour une question'],
      answer: 0,
      explain: 'Les deux-points annoncent une explication ou une conséquence : on marque une courte pause avant de continuer.',
    },
    {
      id: 'cm1-francais-lire-fluide-blanks-1',
      kind: 'blanks',
      prompt: 'Complète la phrase du texte',
      text: "Nora rit, {{puis}} elle attend, {{immobile}}, les yeux fixés sur l'eau.",
      distractors: ['car', 'debout'],
      explain: "« Puis » enchaîne les deux actions, et « immobile » veut dire qu'elle ne bouge plus du tout.",
    },
    {
      id: 'cm1-francais-lire-fluide-sentence-1',
      kind: 'sentence',
      prompt: "Remets les mots de la phrase dans l'ordre",
      words: ['Le', 'brochet', 'file', 'sous', 'les', 'nénuphars.'],
      explain: 'Le brochet, puis ce qu\'il fait : il file sous les nénuphars. Le point est sur le dernier mot.',
    },
    {
      id: 'cm1-francais-lire-fluide-tf-2',
      kind: 'truefalse',
      statement: "On lit « les trois pêcheurs rentrent trempés, mais heureux » d'une traite, sans aucune pause.",
      answer: false,
      explain: "Pas grave. La virgule avant « mais » demande une petite pause : elle prépare la surprise du mot « heureux ».",
    },
  ],
};

const COMPRENDRE_RECIT: Lesson = {
  id: 'cm1-francais-comprendre-recit',
  title: 'Comprendre un récit',
  subject: 'francais',
  source: 'lecture',
  level: 'CM1',
  notion: "Comprendre un récit : les personnages, leurs intentions, et ce que le texte ne dit pas mais qu'on devine",
  theme: 'lecture',
  attendu: 'Comprendre un récit et un texte documentaire : personnages, intentions, informations explicites et implicites.',
  attenduId: 'cm1-lect-comprendre',
  summary:
    "Lis bien l'histoire. Certaines réponses sont écrites noir sur blanc ; d'autres se devinent grâce aux indices : c'est ce qu'on appelle une inférence. Depuis une semaine, Camille passe devant la vieille maison du bout de la rue en pressant le pas. Les volets sont toujours fermés, sauf un, au premier étage. Ce mardi, en rentrant de l'école, elle entend un gémissement derrière la grille. Un petit chien aux oreilles tombantes est coincé, la patte prise dans le grillage. Camille regarde autour d'elle : personne. Elle s'agenouille, libère doucement la patte et lit sur la médaille : « Biscuit ». Elle hésite, puis elle sonne. Une vieille dame ouvre, s'appuie sur sa canne, et son visage s'éclaire en voyant le chien. « Biscuit ! Il s'est sauvé ce matin, je l'ai cherché partout. » Camille comprend que la maison n'est pas abandonnée du tout. Le lendemain, elle ne presse plus le pas en passant devant.",
  minutes: 7,
  exercises: [
    {
      id: 'cm1-francais-comprendre-recit-tf-1',
      kind: 'truefalse',
      statement: 'La maison du bout de la rue est abandonnée.',
      answer: false,
      explain: "Pas grave. Une vieille dame y habite avec son chien : le texte dit que la maison n'est pas abandonnée du tout.",
    },
    {
      id: 'cm1-francais-comprendre-recit-choice-1',
      kind: 'choice',
      prompt: "Pourquoi Camille presse-t-elle le pas devant la maison ? Ce n'est pas écrit, il faut deviner.",
      options: ['Elle est en retard pour l\'école', 'Elle a un peu peur de cette maison aux volets fermés', 'Elle veut faire du sport'],
      answer: 1,
      explain: 'Les volets toujours fermés et le pas pressé sont des indices : Camille trouve la maison inquiétante. On le devine, ce n\'est pas écrit.',
    },
    {
      id: 'cm1-francais-comprendre-recit-tap-1',
      kind: 'tapword',
      prompt: "Touche le mot qui dit quel jour se passe l'histoire",
      words: ['Ce', 'mardi,', 'en', 'rentrant', 'de', "l'école,", 'elle', 'entend', 'un', 'gémissement.'],
      answer: [1],
      explain: "C'est « mardi » qui donne le jour. « En rentrant de l'école » donne le moment de la journée.",
    },
    {
      id: 'cm1-francais-comprendre-recit-blanks-1',
      kind: 'blanks',
      prompt: 'Complète la phrase du texte',
      text: 'Un petit chien aux oreilles {{tombantes}} est coincé, la patte prise dans le {{grillage}}.',
      distractors: ['pointues', 'carton'],
      explain: "Le chien a les oreilles tombantes, et sa patte est prise dans le grillage de la grille.",
    },
    {
      id: 'cm1-francais-comprendre-recit-choice-2',
      kind: 'choice',
      prompt: "Pourquoi le visage de la vieille dame s'éclaire-t-il ?",
      options: ['Elle allume la lumière du couloir', 'Elle est soulagée de retrouver son chien', 'Elle reconnaît Camille'],
      answer: 1,
      explain: "Elle cherchait Biscuit depuis le matin : la joie de le revoir se lit sur son visage. C'est une inférence.",
    },
    {
      id: 'cm1-francais-comprendre-recit-sort-1',
      kind: 'sort',
      prompt: "Range : personnage de l'histoire, ou pas dans l'histoire",
      boxes: ["Dans l'histoire", "Pas dans l'histoire"],
      items: [
        { word: 'Camille', box: 0 },
        { word: 'le facteur', box: 1 },
        { word: 'Biscuit', box: 0 },
        { word: 'la vieille dame', box: 0 },
        { word: 'le frère de Camille', box: 1 },
        { word: 'la maîtresse', box: 1 },
      ],
      explain: "Camille, Biscuit et la vieille dame sont dans l'histoire. Il n'y a ni facteur, ni frère, ni maîtresse.",
    },
    {
      id: 'cm1-francais-comprendre-recit-order-1',
      kind: 'order',
      prompt: "Remets les événements dans l'ordre de l'histoire",
      lines: [
        'Camille entend un gémissement derrière la grille.',
        'Elle libère la patte du chien et lit « Biscuit » sur la médaille.',
        'Une vieille dame ouvre la porte.',
        'Le lendemain, Camille ne presse plus le pas.',
      ],
      explain: "D'abord le gémissement, puis le chien libéré, puis la dame qui ouvre, et enfin le lendemain.",
    },
    {
      id: 'cm1-francais-comprendre-recit-tf-2',
      kind: 'truefalse',
      statement: "Biscuit s'est sauvé il y a une semaine.",
      answer: false,
      explain: "Pas grave. La dame dit « Il s'est sauvé ce matin ». C'est Camille qui presse le pas depuis une semaine.",
    },
    {
      id: 'cm1-francais-comprendre-recit-choice-3',
      kind: 'choice',
      prompt: 'Pourquoi Camille ne presse-t-elle plus le pas le lendemain ?',
      options: ['Elle a changé de chemin', 'Elle n\'a plus peur : elle sait qui habite la maison', 'Elle a mal aux jambes'],
      answer: 1,
      explain: "Elle a rencontré la vieille dame et son chien : la maison n'a plus rien d'inquiétant. Le texte ne le dit pas, mais on le comprend.",
    },
    {
      id: 'cm1-francais-comprendre-recit-pairs-1',
      kind: 'pairs',
      prompt: 'Associe chaque personnage à ce qu\'il fait',
      pairs: [
        { a: 'Camille', b: 'libère la patte du chien' },
        { a: 'Biscuit', b: 'gémit derrière la grille' },
        { a: 'La vieille dame', b: "s'appuie sur sa canne" },
      ],
      explain: "Camille libère le chien, Biscuit gémit, et la vieille dame s'appuie sur sa canne.",
    },
  ],
};

const COMPRENDRE_DOCUMENTAIRE: Lesson = {
  id: 'cm1-francais-comprendre-documentaire',
  title: 'Lire un documentaire',
  subject: 'francais',
  source: 'lecture',
  level: 'CM1',
  notion: 'Comprendre un texte documentaire : titre, sous-titres, informations explicites et implicites',
  theme: 'lecture',
  attendu: 'Comprendre un récit et un texte documentaire : personnages, intentions, informations explicites et implicites.',
  attenduId: 'cm1-lect-comprendre',
  summary:
    "Un documentaire donne des informations vraies. Le titre dit de quoi il parle, les sous-titres aident à trouver vite ce qu'on cherche. Titre : Le hérisson, un petit voisin de nuit. Où vit-il ? Le hérisson habite les haies, les jardins et les lisières de forêt. Le jour, il dort roulé en boule sous un tas de feuilles. Que mange-t-il ? Dès la nuit tombée, il part chasser des limaces, des insectes, des escargots et parfois un fruit tombé. Un jardinier qui le voit passer a de la chance. Comment se défend-il ? Son dos est couvert d'environ cinq mille piquants. Face à un danger, il se roule en boule et attend. L'hiver : quand il fait moins de dix degrés, le hérisson s'endort pour plusieurs mois, c'est l'hibernation. Il a grossi tout l'automne pour tenir jusqu'au printemps.",
  minutes: 7,
  exercises: [
    {
      id: 'cm1-francais-comprendre-documentaire-choice-1',
      kind: 'choice',
      prompt: 'Quel est le titre du documentaire ?',
      options: ['Où vit-il ?', 'Le hérisson, un petit voisin de nuit', "L'hiver"],
      answer: 1,
      explain: 'Le titre annonce tout le texte. « Où vit-il ? » et « L\'hiver » sont des sous-titres : ils annoncent une partie seulement.',
    },
    {
      id: 'cm1-francais-comprendre-documentaire-tf-1',
      kind: 'truefalse',
      statement: 'Le hérisson chasse pendant la journée.',
      answer: false,
      explain: "Pas grave. Le jour, il dort sous un tas de feuilles ; il chasse dès la nuit tombée.",
    },
    {
      id: 'cm1-francais-comprendre-documentaire-tap-1',
      kind: 'tapword',
      prompt: 'Touche les trois animaux que mange le hérisson',
      words: ['Il', 'chasse', 'des', 'limaces,', 'des', 'insectes,', 'des', 'escargots', 'et', 'parfois', 'un', 'fruit', 'tombé.'],
      answer: [3, 5, 7],
      explain: 'Limaces, insectes et escargots sont des animaux. Le fruit, lui, n\'est pas un animal.',
    },
    {
      id: 'cm1-francais-comprendre-documentaire-sort-1',
      kind: 'sort',
      prompt: 'Range chaque information sous le bon sous-titre',
      boxes: ['Où vit-il ?', 'Que mange-t-il ?', 'Comment se défend-il ?'],
      items: [
        { word: 'dans les haies', box: 0 },
        { word: 'des limaces', box: 1 },
        { word: 'il se roule en boule', box: 2 },
        { word: 'sous un tas de feuilles', box: 0 },
        { word: 'des insectes', box: 1 },
        { word: 'cinq mille piquants', box: 2 },
      ],
      explain: "Les sous-titres servent à ça : chaque partie répond à une question précise.",
    },
    {
      id: 'cm1-francais-comprendre-documentaire-choice-2',
      kind: 'choice',
      prompt: "Pourquoi le jardinier a-t-il de la chance ? Ce n'est pas écrit, il faut deviner.",
      options: ['Le hérisson mange les petites bêtes qui abîment ses légumes', 'Le hérisson creuse les trous pour planter', 'Les hérissons portent bonheur'],
      answer: 0,
      explain: "Le texte dit que le hérisson mange limaces et insectes. On en déduit qu'il protège le potager : c'est une information implicite.",
    },
    {
      id: 'cm1-francais-comprendre-documentaire-blanks-1',
      kind: 'blanks',
      prompt: 'Complète avec les informations du texte',
      text: "Quand il fait moins de {{dix}} degrés, le hérisson s'endort pour plusieurs mois : c'est l'{{hibernation}}.",
      distractors: ['vingt', 'migration'],
      explain: "Le texte dit « moins de dix degrés ». L'hibernation, c'est le long sommeil d'hiver ; la migration, c'est un voyage, comme les oiseaux.",
    },
    {
      id: 'cm1-francais-comprendre-documentaire-choice-3',
      kind: 'choice',
      prompt: "Pourquoi le hérisson grossit-il pendant l'automne ?",
      options: ['Pour avoir plus chaud en été', 'Pour avoir des réserves pendant son long sommeil', 'Parce que les fruits sont trop sucrés'],
      answer: 1,
      explain: "Pendant l'hibernation, il ne mange pas : la graisse accumulée en automne lui permet de tenir jusqu'au printemps.",
    },
    {
      id: 'cm1-francais-comprendre-documentaire-tf-2',
      kind: 'truefalse',
      statement: 'Le titre « un petit voisin de nuit » nous dit que le hérisson vit surtout la nuit.',
      answer: true,
      explain: "Oui : « de nuit » dans le titre, et « dès la nuit tombée » dans le texte. Le hérisson est un animal nocturne.",
    },
    {
      id: 'cm1-francais-comprendre-documentaire-flashcard-1',
      kind: 'flashcard',
      prompt: 'Réponds dans ta tête, puis retourne la carte',
      front: 'Combien de piquants le hérisson a-t-il sur le dos ?',
      back: 'Environ cinq mille piquants.',
      explain: 'Le texte dit « environ cinq mille » : c\'est un nombre approximatif, pas exact.',
    },
    {
      id: 'cm1-francais-comprendre-documentaire-order-1',
      kind: 'order',
      prompt: "Remets les sous-titres dans l'ordre du texte",
      lines: ['Où vit-il ?', 'Que mange-t-il ?', 'Comment se défend-il ?', "L'hiver"],
      explain: "Le documentaire parle d'abord de l'habitat, puis de la nourriture, de la défense, et enfin de l'hiver.",
    },
  ],
};

const CORBEAU_RENARD: Lesson = {
  id: 'cm1-francais-corbeau-renard',
  title: 'Le Corbeau et le Renard',
  subject: 'francais',
  source: 'poesie',
  level: 'CM1',
  notion: 'Mémoriser et dire une fable en comprenant son sens',
  theme: 'poesie',
  attendu: 'Mémoriser et dire un poème ou une fable avec expression, en comprenant son sens.',
  attenduId: 'cm1-oral-memoriser',
  summary:
    "Une fable de Jean de La Fontaine. Le renard flatte le corbeau pour lui voler son fromage, et le corbeau se fait avoir. La morale : le flatteur vit aux dépens de celui qui l'écoute. Apprends-la par morceaux de quatre vers, en changeant de voix pour le renard.",
  minutes: 8,
  exercises: [
    {
      id: 'cm1-francais-corbeau-renard-order-1',
      kind: 'order',
      prompt: "Remets les quatre premiers vers dans l'ordre",
      lines: ['Maître Corbeau, sur un arbre perché,', 'Tenait en son bec un fromage.', "Maître Renard, par l'odeur alléché,", 'Lui tint à peu près ce langage :'],
      explain: "D'abord le corbeau et son fromage, puis le renard attiré par l'odeur, qui commence à parler.",
    },
    {
      id: 'cm1-francais-corbeau-renard-choice-1',
      kind: 'choice',
      prompt: "Que veut dire « par l'odeur alléché » ?",
      options: ['Dégoûté par l\'odeur', 'Attiré par la bonne odeur', 'Endormi par l\'odeur'],
      answer: 1,
      explain: '« Alléché » veut dire attiré, mis en appétit. Le renard a senti le fromage et il en a envie.',
    },
    {
      id: 'cm1-francais-corbeau-renard-blanks-1',
      kind: 'blanks',
      prompt: 'Complète les vers',
      text: 'Maître Corbeau, sur un arbre {{perché}},\nTenait en son {{bec}} un fromage.',
      distractors: ['caché', 'nid'],
      explain: 'Le corbeau est perché sur un arbre et tient le fromage dans son bec.',
    },
    {
      id: 'cm1-francais-corbeau-renard-order-2',
      kind: 'order',
      prompt: "Remets les vers 5 à 8 dans l'ordre",
      lines: ['« Hé ! bonjour, Monsieur du Corbeau.', 'Que vous êtes joli ! que vous me semblez beau !', 'Sans mentir, si votre ramage', 'Se rapporte à votre plumage,'],
      explain: 'Le renard salue, puis il complimente le corbeau sur sa beauté, puis sur son chant.',
    },
    {
      id: 'cm1-francais-corbeau-renard-choice-2',
      kind: 'choice',
      prompt: 'Quel mot rime avec « ramage » ?',
      options: ['corbeau', 'plumage', 'joie'],
      answer: 1,
      explain: 'Ramage et plumage finissent tous les deux par le son « age ». Le ramage, c\'est le chant ; le plumage, ce sont les plumes.',
    },
    {
      id: 'cm1-francais-corbeau-renard-flashcard-1',
      kind: 'flashcard',
      prompt: 'Récite le vers suivant, puis retourne la carte pour vérifier',
      front: 'Se rapporte à votre plumage,',
      back: 'Vous êtes le Phénix des hôtes de ces bois. »',
      explain: 'Le Phénix est un oiseau de légende, unique et magnifique : le renard exagère pour flatter.',
    },
    {
      id: 'cm1-francais-corbeau-renard-order-3',
      kind: 'order',
      prompt: "Remets les vers 10 à 13 dans l'ordre",
      lines: ['À ces mots le Corbeau ne se sent pas de joie ;', 'Et pour montrer sa belle voix,', 'Il ouvre un large bec, laisse tomber sa proie.', "Le Renard s'en saisit, et dit : « Mon bon Monsieur,"],
      explain: "Le corbeau est fou de joie, il veut chanter, il ouvre le bec et le fromage tombe : le renard l'attrape.",
    },
    {
      id: 'cm1-francais-corbeau-renard-tf-1',
      kind: 'truefalse',
      statement: 'Le Corbeau garde son fromage jusqu\'à la fin de la fable.',
      answer: false,
      explain: "Pas grave. En ouvrant le bec pour chanter, il laisse tomber sa proie, et le renard s'en saisit.",
    },
    {
      id: 'cm1-francais-corbeau-renard-blanks-2',
      kind: 'blanks',
      prompt: 'Complète la morale de la fable',
      text: "Apprenez que tout {{flatteur}}\nVit aux dépens de celui qui l'{{écoute}} :",
      distractors: ['menteur', 'admire'],
      explain: "Un flatteur fait des compliments pour obtenir quelque chose. Celui qui l'écoute se fait avoir.",
    },
    {
      id: 'cm1-francais-corbeau-renard-choice-3',
      kind: 'choice',
      prompt: 'Que jure le Corbeau à la fin ?',
      options: ['De se venger du Renard', 'Qu\'on ne le tromperait plus de cette façon', 'De ne plus jamais chanter'],
      answer: 1,
      explain: "« Jura, mais un peu tard, qu'on ne l'y prendrait plus » : il promet de ne plus se faire avoir, mais le fromage est déjà perdu.",
    },
  ],
};

const REDIGER_TEXTE: Lesson = {
  id: 'cm1-francais-rediger-texte',
  title: 'Rédiger un texte',
  subject: 'francais',
  source: 'lecon',
  level: 'CM1',
  notion: "Organiser un texte : ordre des phrases, connecteurs, ponctuation, éviter les répétitions",
  theme: 'grammaire',
  attendu: "Écrire un texte d'une dizaine de lignes bien construit : organisation, connecteurs, ponctuation, relecture.",
  attenduId: 'cm1-ecrit-rediger',
  summary:
    "Un bon texte raconte les choses dans l'ordre, avec des mots de liaison : d'abord, ensuite, enfin pour l'ordre ; mais pour une opposition ; car pour une cause. On évite de répéter le même nom en le remplaçant par un pronom (il, elle). Et on relit pour vérifier les majuscules et la ponctuation.",
  minutes: 7,
  exercises: [
    {
      id: 'cm1-francais-rediger-texte-order-1',
      kind: 'order',
      prompt: "Remets les phrases du paragraphe dans l'ordre",
      lines: [
        "D'abord, Lucas sort la farine, les œufs et le lait.",
        'Ensuite, il mélange tout dans un grand saladier.',
        'Puis il verse la pâte dans le moule.',
        'Enfin, il met le gâteau au four pendant trente minutes.',
      ],
      explain: "Les connecteurs donnent l'ordre : d'abord, ensuite, puis, enfin.",
    },
    {
      id: 'cm1-francais-rediger-texte-choice-1',
      kind: 'choice',
      prompt: 'Nous sommes restés à la maison ... il pleuvait à verse.',
      options: ['mais', 'car', 'ensuite'],
      answer: 1,
      explain: "« Car » donne la cause : pourquoi sommes-nous restés ? Parce qu'il pleuvait.",
    },
    {
      id: 'cm1-francais-rediger-texte-blanks-1',
      kind: 'blanks',
      prompt: "Complète avec les connecteurs d'ordre",
      text: "{{D'abord}}, Inès enfile son maillot. {{Ensuite}}, elle prend sa douche. {{Enfin}}, elle plonge dans le grand bassin.",
      distractors: ['Mais', 'Car'],
      explain: "D'abord, ensuite, enfin : trois mots pour raconter dans l'ordre. « Mais » et « car » ne disent pas l'ordre.",
    },
    {
      id: 'cm1-francais-rediger-texte-tap-1',
      kind: 'tapword',
      prompt: 'Touche le nom répété qu\'on devrait remplacer par « il »',
      words: ['Tom', 'prend', 'son', 'vélo.', 'Tom', 'roule', "jusqu'au", 'parc.'],
      answer: [4],
      explain: "Le deuxième « Tom » est une répétition : on écrit « Il roule jusqu'au parc ». Le lecteur sait de qui on parle.",
    },
    {
      id: 'cm1-francais-rediger-texte-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a répété un nom. Touche-le et remplace-le par un pronom',
      words: ['Sarah', 'ouvre', 'la', 'boîte.', 'Sarah', 'découvre', 'un', 'collier.'],
      wrongIndex: 4,
      correct: 'Elle',
      distractors: ['Il', 'Lui'],
      explain: 'Sarah est une fille : on la remplace par « Elle ». « Il » est pour un garçon.',
    },
    {
      id: 'cm1-francais-rediger-texte-sort-1',
      kind: 'sort',
      prompt: 'Range chaque connecteur selon ce qu\'il exprime',
      boxes: ["L'ordre", "L'opposition", 'La cause'],
      items: [
        { word: "d'abord", box: 0 },
        { word: 'mais', box: 1 },
        { word: 'car', box: 2 },
        { word: 'ensuite', box: 0 },
        { word: 'pourtant', box: 1 },
        { word: 'parce que', box: 2 },
        { word: 'enfin', box: 0 },
      ],
      explain: "D'abord, ensuite, enfin racontent dans l'ordre. Mais et pourtant opposent. Car et parce que expliquent.",
    },
    {
      id: 'cm1-francais-rediger-texte-sentence-1',
      kind: 'sentence',
      prompt: "Remets les mots de la phrase dans l'ordre",
      words: ['Il', 'voulait', 'sortir,', 'mais', 'il', 'pleuvait', 'à', 'verse.'],
      explain: "« Mais » relie les deux idées qui s'opposent : il voulait sortir, et pourtant il pleuvait.",
    },
    {
      id: 'cm1-francais-rediger-texte-fix-2',
      kind: 'fix',
      prompt: 'Gribouille a mis la mauvaise ponctuation. Touche le mot et corrige',
      words: ['Quelle', 'belle', 'journée.'],
      wrongIndex: 2,
      correct: 'journée !',
      distractors: ['journée ?', 'journée,'],
      explain: "« Quelle belle journée » exprime une émotion : la phrase se termine par un point d'exclamation.",
    },
    {
      id: 'cm1-francais-rediger-texte-tf-1',
      kind: 'truefalse',
      statement: "Un paragraphe développe une seule idée ; on va à la ligne pour en changer.",
      answer: true,
      explain: "Oui : un paragraphe par idée. Aller à la ligne aide le lecteur à suivre.",
    },
    {
      id: 'cm1-francais-rediger-texte-choice-2',
      kind: 'choice',
      prompt: 'Il fait très froid, ... Léo sort sans manteau.',
      options: ['car', 'mais', 'ensuite'],
      answer: 1,
      explain: "« Mais » marque l'opposition : il fait froid, et pourtant Léo ne met pas de manteau.",
    },
  ],
};

const HOMOPHONES_OU_LA_MES: Lesson = {
  id: 'cm1-francais-homophones-ou-la-mes',
  title: 'ou/où, la/là, mes/mais',
  subject: 'francais',
  source: 'lecon',
  level: 'CM1',
  notion: 'Distinguer les homophones ou / où, la / là, mes / mais',
  theme: 'orthographe',
  attendu: "Orthographier les mots fréquents et les homophones ou/où, ce/se, ces/ses, c'est/s'est, mes/mais, la/là.",
  attenduId: 'cm1-ortho-mots',
  summary:
    "« ou » veut dire « ou bien » ; « où » avec accent indique un lieu. « la » est un petit mot devant un nom (la table) ; « là » avec accent veut dire « ici, à cet endroit ». « mes » se remplace par « tes » (mes amis) ; « mais » veut dire « pourtant ».",
  minutes: 6,
  exercises: [
    {
      id: 'cm1-francais-homophones-ou-la-mes-choice-1',
      kind: 'choice',
      prompt: 'Tu préfères le chocolat ... la vanille ?',
      options: ['où', 'ou'],
      answer: 1,
      explain: "On peut dire « le chocolat ou bien la vanille » : c'est « ou » sans accent.",
    },
    {
      id: 'cm1-francais-homophones-ou-la-mes-choice-2',
      kind: 'choice',
      prompt: 'Voici la ville ... je suis né.',
      options: ['ou', 'où'],
      answer: 1,
      explain: "On ne peut pas dire « la ville ou bien je suis né » : c'est un lieu, donc « où » avec accent.",
    },
    {
      id: 'cm1-francais-homophones-ou-la-mes-tf-1',
      kind: 'truefalse',
      statement: 'Dans « mes chaussures sont mouillées », on peut remplacer « mes » par « tes ».',
      answer: true,
      explain: 'Oui : « tes chaussures sont mouillées ». Quand on peut dire « tes », on écrit « mes ».',
    },
    {
      id: 'cm1-francais-homophones-ou-la-mes-blanks-1',
      kind: 'blanks',
      prompt: 'Complète avec la ou là',
      text: "Pose {{la}} boîte {{là}}, sur l'étagère.",
      distractors: ["l'a"],
      explain: "« La boîte » : petit mot devant le nom, sans accent. « Là » veut dire « à cet endroit » : avec accent.",
    },
    {
      id: 'cm1-francais-homophones-ou-la-mes-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a fait une faute. Touche le mot faux et corrige',
      words: ['Je', 'voulais', 'venir,', 'mes', 'il', 'pleuvait.'],
      wrongIndex: 3,
      correct: 'mais',
      distractors: ['mets', 'met'],
      explain: "On ne peut pas dire « je voulais venir, tes il pleuvait » : c'est « mais », qui veut dire « pourtant ».",
    },
    {
      id: 'cm1-francais-homophones-ou-la-mes-sort-1',
      kind: 'sort',
      prompt: 'Range chaque phrase dans la bonne boîte',
      boxes: ['ou (ou bien)', 'où (un lieu)'],
      items: [
        { word: 'Fromage ___ dessert ?', box: 0 },
        { word: 'La rue ___ tu habites', box: 1 },
        { word: 'Rouge ___ bleu', box: 0 },
        { word: 'Le pays ___ il fait chaud', box: 1 },
        { word: 'Tu viens ___ tu restes ?', box: 0 },
        { word: "La maison ___ je suis né", box: 1 },
      ],
      explain: "Quand on peut dire « ou bien », c'est « ou ». Quand ça parle d'un endroit, c'est « où ».",
    },
    {
      id: 'cm1-francais-homophones-ou-la-mes-blanks-2',
      kind: 'blanks',
      prompt: 'Complète avec mes ou mais',
      text: '{{Mes}} parents sont fatigués, {{mais}} ils viennent quand même.',
      distractors: ['met', 'ou'],
      explain: "« Tes parents sont fatigués » marche, donc « Mes ». Puis « pourtant ils viennent » : c'est « mais ».",
    },
    {
      id: 'cm1-francais-homophones-ou-la-mes-tap-1',
      kind: 'tapword',
      prompt: 'Touche le mot qui veut dire « ou bien »',
      words: ['Tu', 'viens', 'à', 'pied', 'ou', 'en', 'vélo', '?'],
      answer: [4],
      explain: "« À pied ou bien en vélo » : c'est « ou » sans accent.",
    },
    {
      id: 'cm1-francais-homophones-ou-la-mes-fix-2',
      kind: 'fix',
      prompt: 'Gribouille a oublié un accent. Touche le mot faux et corrige',
      words: ['Je', 'ne', 'sais', 'pas', 'ou', 'tu', 'as', 'mis', 'mes', 'clés.'],
      wrongIndex: 4,
      correct: 'où',
      distractors: ['ou bien', 'ouh'],
      explain: "« Je ne sais pas à quel endroit tu as mis mes clés » : c'est un lieu, donc « où » avec accent.",
    },
    {
      id: 'cm1-francais-homophones-ou-la-mes-dictation-1',
      kind: 'dictation',
      word: 'là',
      sentence: 'Reste là, je reviens tout de suite.',
      explain: "« Reste ici » : c'est « là » avec un accent grave.",
    },
  ],
};

const HOMOPHONES_CE_SE: Lesson = {
  id: 'cm1-francais-homophones-ce-se',
  title: "ce/se, ces/ses, c'est/s'est",
  subject: 'francais',
  source: 'lecon',
  level: 'CM1',
  notion: "Distinguer les homophones ce / se, ces / ses, c'est / s'est",
  theme: 'orthographe',
  attendu: "Orthographier les mots fréquents et les homophones ou/où, ce/se, ces/ses, c'est/s'est, mes/mais, la/là.",
  attenduId: 'cm1-ortho-mots',
  summary:
    "« ce » se place devant un nom : ce chien, celui-là. « se » se place devant un verbe : il se lave. « ces » montre plusieurs choses : ces nuages, ceux-là. « ses » veut dire « les siens » : ses billes. « c'est » veut dire « cela est » ; « s'est » est suivi d'un participe passé : il s'est levé.",
  minutes: 7,
  exercises: [
    {
      id: 'cm1-francais-homophones-ce-se-choice-1',
      kind: 'choice',
      prompt: '... matin, il pleut.',
      options: ['Se', 'Ce'],
      answer: 1,
      explain: '« Ce matin » : « ce » est devant le nom « matin », on peut dire « ce matin-là ».',
    },
    {
      id: 'cm1-francais-homophones-ce-se-choice-2',
      kind: 'choice',
      prompt: 'Elle ... lave les mains.',
      options: ['ce', 'se'],
      answer: 1,
      explain: '« Se » est devant le verbe « lave » : elle se lave, je me lave, tu te laves.',
    },
    {
      id: 'cm1-francais-homophones-ce-se-tf-1',
      kind: 'truefalse',
      statement: 'Dans « ses chaussures », on peut dire « les siennes » : on écrit « ses » avec un s.',
      answer: true,
      explain: "Oui : « ses chaussures », ce sont les siennes. « Ces chaussures », ce serait « celles-là ».",
    },
    {
      id: 'cm1-francais-homophones-ce-se-sort-1',
      kind: 'sort',
      prompt: 'Range chaque groupe de mots dans la bonne boîte',
      boxes: ['ce (devant un nom)', 'se (devant un verbe)'],
      items: [
        { word: '___ chien', box: 0 },
        { word: 'il ___ promène', box: 1 },
        { word: '___ soir', box: 0 },
        { word: 'elle ___ dépêche', box: 1 },
        { word: '___ livre', box: 0 },
        { word: 'ils ___ regardent', box: 1 },
      ],
      explain: 'Chien, soir, livre sont des noms : « ce ». Promène, dépêche, regardent sont des verbes : « se ».',
    },
    {
      id: 'cm1-francais-homophones-ce-se-blanks-1',
      kind: 'blanks',
      prompt: 'Complète avec ces ou ses',
      text: 'Regarde {{ces}} nuages ! Paul a perdu {{ses}} clés.',
      distractors: ["c'est", "s'est"],
      explain: "« Ces nuages » : ceux-là, qu'on montre. « Ses clés » : les siennes, celles de Paul.",
    },
    {
      id: 'cm1-francais-homophones-ce-se-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a fait une faute. Touche le mot faux et corrige',
      words: ["C'est", "aujourd'hui", 'que', 'Nina', "c'est", 'inscrite', 'au', 'judo.'],
      wrongIndex: 4,
      correct: "s'est",
      distractors: ['ses', 'ces'],
      explain: "« Nina s'est inscrite » : « s'est » est suivi du participe passé « inscrite ». On peut dire « je me suis inscrite ».",
    },
    {
      id: 'cm1-francais-homophones-ce-se-tap-1',
      kind: 'tapword',
      prompt: "Touche le mot qu'on peut remplacer par « cela est »",
      words: ['Regarde,', "c'est", 'le', 'bus', 'qui', 'arrive.'],
      answer: [1],
      explain: "« Cela est le bus qui arrive » : c'est « c'est » avec un c.",
    },
    {
      id: 'cm1-francais-homophones-ce-se-blanks-2',
      kind: 'blanks',
      prompt: "Complète avec c'est ou s'est",
      text: "{{C'est}} le jour où mon frère {{s'est}} cassé le bras.",
      distractors: ['ses', 'ces'],
      explain: "« Cela est le jour » : c'est. « Mon frère s'est cassé » : je me suis cassé, il s'est cassé.",
    },
    {
      id: 'cm1-francais-homophones-ce-se-choice-3',
      kind: 'choice',
      prompt: 'Il ... passé quelque chose ?',
      options: ["c'est", "s'est"],
      answer: 1,
      explain: "« Il s'est passé » : « s'est » est suivi du participe passé « passé ». On ne peut pas dire « il cela est passé ».",
    },
    {
      id: 'cm1-francais-homophones-ce-se-pairs-1',
      kind: 'pairs',
      prompt: 'Associe chaque mot à son astuce',
      pairs: [
        { a: 'ce', b: 'ce livre-là' },
        { a: 'se', b: 'il se lève' },
        { a: 'ses', b: 'les siens' },
        { a: 'ces', b: 'ceux-là' },
        { a: "c'est", b: 'cela est' },
      ],
      explain: 'Chaque homophone a son astuce : ce livre-là, il se lève, les siens, ceux-là, cela est.',
    },
  ],
};

const ACCORDS_GN_ETRE: Lesson = {
  id: 'cm1-francais-accords-gn-etre',
  title: 'Accords du groupe nominal',
  subject: 'francais',
  source: 'lecon',
  level: 'CM1',
  notion: 'Accorder dans le groupe nominal et accorder le participe passé employé avec être',
  theme: 'orthographe',
  attendu: 'Accorder dans le groupe nominal, le verbe avec son sujet, et le participe passé employé avec être.',
  attenduId: 'cm1-ortho-accords',
  summary:
    "Dans le groupe nominal, le déterminant et l'adjectif prennent le genre et le nombre du nom : les petites maisons blanches. Avec l'auxiliaire être, le participe passé s'accorde avec le sujet : elles sont parties, ils sont venus. Avec avoir, il ne s'accorde pas avec le sujet : elles ont mangé.",
  minutes: 7,
  exercises: [
    {
      id: 'cm1-francais-accords-gn-etre-choice-1',
      kind: 'choice',
      prompt: 'Les ... fleurs du jardin',
      options: ['joli', 'jolies', 'jolis'],
      answer: 1,
      explain: '« Fleurs » est féminin pluriel : l\'adjectif prend un e et un s, « jolies ».',
    },
    {
      id: 'cm1-francais-accords-gn-etre-sort-1',
      kind: 'sort',
      prompt: 'Range chaque groupe nominal dans la bonne boîte',
      boxes: ['Masculin pluriel', 'Féminin pluriel'],
      items: [
        { word: 'des chevaux noirs', box: 0 },
        { word: 'des pommes vertes', box: 1 },
        { word: 'les grands arbres', box: 0 },
        { word: 'les belles maisons', box: 1 },
        { word: 'des gâteaux délicieux', box: 0 },
        { word: 'de jolies fleurs', box: 1 },
      ],
      explain: 'Chevaux, arbres, gâteaux sont masculins ; pommes, maisons, fleurs sont féminins. L\'adjectif suit le nom.',
    },
    {
      id: 'cm1-francais-accords-gn-etre-blanks-1',
      kind: 'blanks',
      prompt: 'Complète en accordant avec le nom « porte »',
      text: 'La {{grande}} porte {{verte}} est {{fermée}}.',
      distractors: ['grand', 'vert', 'fermé'],
      explain: '« Porte » est féminin singulier : grande, verte, fermée prennent un e.',
    },
    {
      id: 'cm1-francais-accords-gn-etre-tf-1',
      kind: 'truefalse',
      statement: "Avec l'auxiliaire être, le participe passé s'accorde avec le sujet.",
      answer: true,
      explain: 'Oui : elle est partie, ils sont partis, elles sont parties. Le participe suit le sujet.',
    },
    {
      id: 'cm1-francais-accords-gn-etre-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a oublié un accord. Touche le mot faux et corrige',
      words: ['Les', 'petites', 'filles', 'sont', 'parti', 'à', 'la', 'piscine.'],
      wrongIndex: 4,
      correct: 'parties',
      distractors: ['partis', 'partie'],
      explain: "Le sujet « les petites filles » est féminin pluriel et l'auxiliaire est « être » : parties, avec e et s.",
    },
    {
      id: 'cm1-francais-accords-gn-etre-tap-1',
      kind: 'tapword',
      prompt: "Touche les deux adjectifs et le participe passé qui s'accordent avec « voitures »",
      words: ['Ces', 'vieilles', 'voitures', 'rouges', 'sont', 'garées', 'devant', 'la', 'gare.'],
      answer: [1, 3, 5],
      explain: '« Vieilles », « rouges » et « garées » prennent le féminin pluriel de « voitures ».',
    },
    {
      id: 'cm1-francais-accords-gn-etre-choice-2',
      kind: 'choice',
      prompt: 'Marie et Lucie sont ... dans la neige.',
      options: ['tombé', 'tombés', 'tombées'],
      answer: 2,
      explain: 'Marie et Lucie : deux filles, donc féminin pluriel. Avec être, le participe prend e et s : tombées.',
    },
    {
      id: 'cm1-francais-accords-gn-etre-fix-2',
      kind: 'fix',
      prompt: 'Gribouille a mal accordé. Touche le mot faux et corrige',
      words: ['Mon', 'frère', 'et', 'moi', 'sommes', 'rentrées', 'tard.'],
      wrongIndex: 5,
      correct: 'rentrés',
      distractors: ['rentrée', 'rentré'],
      explain: "« Mon frère et moi » : il y a un garçon dans le groupe, donc masculin pluriel. On écrit « rentrés ».",
    },
    {
      id: 'cm1-francais-accords-gn-etre-blanks-2',
      kind: 'blanks',
      prompt: 'Complète en accordant',
      text: 'Les {{nouveaux}} voisins sont {{arrivés}} hier.',
      distractors: ['nouvelles', 'arrivées'],
      explain: "« Voisins » est masculin pluriel : nouveaux, et avec être, arrivés.",
    },
    {
      id: 'cm1-francais-accords-gn-etre-pairs-1',
      kind: 'pairs',
      prompt: 'Associe chaque nom à l\'adjectif bien accordé',
      pairs: [
        { a: 'un chat', b: 'noir' },
        { a: 'une chatte', b: 'noire' },
        { a: 'des chats', b: 'noirs' },
        { a: 'des chattes', b: 'noires' },
      ],
      explain: 'Masculin : noir ; féminin : noire ; pluriel : on ajoute un s.',
    },
  ],
};

const ACCORD_SUJET_VERBE: Lesson = {
  id: 'cm1-francais-accord-sujet-verbe',
  title: 'Accord sujet-verbe',
  subject: 'francais',
  source: 'lecon',
  level: 'CM1',
  notion: 'Accorder le verbe avec son sujet, même éloigné, inversé ou pronom',
  theme: 'orthographe',
  attendu: 'Accorder dans le groupe nominal, le verbe avec son sujet, et le participe passé employé avec être.',
  attenduId: 'cm1-ortho-accords',
  summary:
    "Le verbe s'accorde avec son sujet, même quand des mots les séparent : « Les enfants de la classe voisine chantent ». Parfois le sujet est après le verbe : « Sous le pont dorment les canards ». Pour le trouver, on demande « qui est-ce qui ? » devant le verbe.",
  minutes: 7,
  exercises: [
    {
      id: 'cm1-francais-accord-sujet-verbe-tap-1',
      kind: 'tapword',
      prompt: 'Touche le mot avec lequel le verbe « chantent » s\'accorde',
      words: ['Les', 'enfants', 'de', 'la', 'classe', 'voisine', 'chantent', 'fort.'],
      answer: [1],
      explain: 'Qui est-ce qui chante ? Les enfants. « Classe voisine » est juste à côté du verbe, mais ce n\'est pas le sujet.',
    },
    {
      id: 'cm1-francais-accord-sujet-verbe-choice-1',
      kind: 'choice',
      prompt: 'Les élèves, après la récréation, ... en classe.',
      options: ['rentre', 'rentrent'],
      answer: 1,
      explain: 'Qui est-ce qui rentre ? Les élèves, pluriel. Le verbe prend -ent, même si « la récréation » est juste avant.',
    },
    {
      id: 'cm1-francais-accord-sujet-verbe-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a oublié un accord. Touche le mot faux et corrige',
      words: ['Dans', 'le', 'jardin', 'pousse', 'des', 'roses.'],
      wrongIndex: 3,
      correct: 'poussent',
      distractors: ['poussé', 'pousses'],
      explain: "Qu'est-ce qui pousse ? Des roses : le sujet est après le verbe, et il est pluriel. On écrit « poussent ».",
    },
    {
      id: 'cm1-francais-accord-sujet-verbe-tf-1',
      kind: 'truefalse',
      statement: 'Dans « Sous le pont dorment les canards », le sujet est « les canards ».',
      answer: true,
      explain: 'Oui : qui est-ce qui dort ? Les canards. Le sujet est placé après le verbe, on dit qu\'il est inversé.',
    },
    {
      id: 'cm1-francais-accord-sujet-verbe-sort-1',
      kind: 'sort',
      prompt: 'Le verbe sera-t-il au singulier ou au pluriel ?',
      boxes: ['Singulier', 'Pluriel'],
      items: [
        { word: 'Le chien des voisins ___', box: 0 },
        { word: 'Les amis de Léa ___', box: 1 },
        { word: 'Elle ___', box: 0 },
        { word: 'Ils ___', box: 1 },
        { word: 'La maîtresse et les élèves ___', box: 1 },
        { word: 'Chacun ___', box: 0 },
      ],
      explain: 'Le chien, elle, chacun : singulier. Les amis, ils, la maîtresse et les élèves : pluriel.',
    },
    {
      id: 'cm1-francais-accord-sujet-verbe-blanks-1',
      kind: 'blanks',
      prompt: 'Complète avec les verbes bien accordés',
      text: 'Que {{font}} les voisins ? Où {{vont}}-ils ?',
      distractors: ['fait', 'va'],
      explain: 'Les voisins et ils sont pluriels, même placés après le verbe : font, vont.',
    },
    {
      id: 'cm1-francais-accord-sujet-verbe-choice-2',
      kind: 'choice',
      prompt: 'Tu ... à la fête samedi ?',
      options: ['viens', 'vient', 'vienne'],
      answer: 0,
      explain: 'Avec « tu », le verbe se termine presque toujours par un s : tu viens.',
    },
    {
      id: 'cm1-francais-accord-sujet-verbe-fix-2',
      kind: 'fix',
      prompt: 'Gribouille a oublié un accord. Touche le mot faux et corrige',
      words: ['Nous', 'allons', 'au', 'marché', 'et', 'nous', 'achetons', 'des', 'fruits', 'frais', 'chaque', 'semaine,', 'puis', 'nous', 'rentre', 'à', 'pied.'],
      wrongIndex: 14,
      correct: 'rentrons',
      distractors: ['rentrent', 'rentrez'],
      explain: 'Le sujet est « nous » : le verbe se termine par -ons, « nous rentrons ».',
    },
    {
      id: 'cm1-francais-accord-sujet-verbe-tap-2',
      kind: 'tapword',
      prompt: 'Touche les deux mots du sujet du verbe « arrivent »',
      words: ['Voici', 'le', 'quai', 'où', 'arrivent', 'les', 'voyageurs', 'fatigués.'],
      answer: [5, 6],
      explain: 'Qui est-ce qui arrive ? Les voyageurs. Le sujet est après le verbe.',
    },
    {
      id: 'cm1-francais-accord-sujet-verbe-sentence-1',
      kind: 'sentence',
      prompt: "Remets les mots de la phrase dans l'ordre",
      words: ['Sous', 'la', 'neige', 'dorment', 'les', 'petites', 'graines.'],
      explain: 'Le sujet « les petites graines » est après le verbe « dorment », qui est donc au pluriel.',
    },
  ],
};

const LETTRES_MUETTES_DOUBLES: Lesson = {
  id: 'cm1-francais-lettres-muettes-doubles',
  title: 'Lettres muettes et doubles',
  subject: 'francais',
  source: 'mots',
  level: 'CM1',
  notion: 'Trouver la lettre finale muette grâce à la famille de mots ; écrire -ail, -eil, -euil et les consonnes doubles',
  theme: 'orthographe',
  attendu: 'Trouver la lettre finale muette grâce aux mots de la même famille ; écrire les mots en -ail, -eil, -euil, et les consonnes doubles.',
  attenduId: 'cm1-ortho-lettres',
  summary:
    "Pour trouver la lettre muette à la fin d'un mot, cherche un mot de la même famille : grand, grandeur ; tapis, tapisserie. Les noms masculins finissent par -ail, -eil, -euil (un portail, un réveil, un fauteuil) ; les noms féminins par -aille, -eille, -euille (une bouteille, une feuille). Certains mots doublent une consonne : pomme, appeler, terre.",
  minutes: 7,
  exercises: [
    {
      id: 'cm1-francais-lettres-muettes-doubles-choice-1',
      kind: 'choice',
      prompt: 'Quelle lettre muette termine « gran... » ? Pense à « grandeur ».',
      options: ['t', 'd', 's'],
      answer: 1,
      explain: '« Grandeur », « grandir » : on entend le d. Donc « grand » finit par un d muet.',
    },
    {
      id: 'cm1-francais-lettres-muettes-doubles-tap-1',
      kind: 'tapword',
      prompt: 'Touche le mot de la même famille qui révèle la lettre finale de « tapis »',
      words: ['tableau', 'tapisserie', 'tapir'],
      answer: [1],
      explain: '« Tapisserie » fait entendre le s de « tapis ». « Tapir » est un animal, pas de la même famille.',
    },
    {
      id: 'cm1-francais-lettres-muettes-doubles-sort-1',
      kind: 'sort',
      prompt: 'Range chaque nom selon sa terminaison',
      boxes: ['-ail', '-eil', '-euil'],
      items: [
        { word: 'un portail', box: 0 },
        { word: 'un réveil', box: 1 },
        { word: 'un fauteuil', box: 2 },
        { word: 'un travail', box: 0 },
        { word: 'un orteil', box: 1 },
        { word: 'un chevreuil', box: 2 },
      ],
      explain: 'Ces noms sont masculins : ils finissent par un seul l, sans e.',
    },
    {
      id: 'cm1-francais-lettres-muettes-doubles-blanks-1',
      kind: 'blanks',
      prompt: 'Complète avec les mots en -eil et -euil',
      text: 'Le {{soleil}} se lève, un {{écureuil}} grimpe au chêne.',
      distractors: ['fauteuil', 'réveil'],
      explain: 'Le soleil se lève le matin, et l\'écureuil grimpe aux arbres. Tous deux sont masculins : un seul l.',
    },
    {
      id: 'cm1-francais-lettres-muettes-doubles-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a oublié une lettre. Touche le mot faux et corrige',
      words: ['Elle', 'a', 'mangé', 'une', 'pome', 'rouge.'],
      wrongIndex: 4,
      correct: 'pomme',
      distractors: ['paume', 'pomm'],
      explain: '« Pomme » prend deux m. « Paume », c\'est l\'intérieur de la main.',
    },
    {
      id: 'cm1-francais-lettres-muettes-doubles-flash-1',
      kind: 'flash',
      word: 'appeler',
      distractors: ['apeler', 'appeller'],
      explain: '« Appeler » prend deux p et un seul l. Astuce : « appeler » commence comme « apporter ».',
    },
    {
      id: 'cm1-francais-lettres-muettes-doubles-tf-1',
      kind: 'truefalse',
      statement: 'Pour trouver la lettre muette de « bavard », on peut penser à « bavarder ».',
      answer: true,
      explain: 'Oui : « bavarder » fait entendre le d. Un mot de la même famille révèle la lettre muette.',
    },
    {
      id: 'cm1-francais-lettres-muettes-doubles-choice-2',
      kind: 'choice',
      prompt: 'Quelle est la bonne écriture ?',
      options: ['une bouteil', 'une bouteille', 'une bouteile'],
      answer: 1,
      explain: '« Bouteille » est féminin : la terminaison est -eille, avec deux l et un e.',
    },
    {
      id: 'cm1-francais-lettres-muettes-doubles-dictation-1',
      kind: 'dictation',
      word: 'abricot',
      sentence: 'Un abricot bien mûr.',
      explain: 'Pense à « abricotier », l\'arbre : on entend le t. Donc « abricot » finit par un t muet.',
    },
    {
      id: 'cm1-francais-lettres-muettes-doubles-pairs-1',
      kind: 'pairs',
      prompt: 'Associe chaque mot au mot de sa famille qui fait entendre la lettre muette',
      pairs: [
        { a: 'un chat', b: 'un chaton' },
        { a: 'un camp', b: 'camper' },
        { a: 'le sang', b: 'sanguin' },
        { a: 'un rang', b: 'ranger' },
        { a: 'le lait', b: 'laitier' },
      ],
      explain: 'Chaton, camper, sanguin, ranger, laitier font entendre la lettre finale de chat, camp, sang, rang, lait.',
    },
  ],
};

const PHRASE_SIMPLE_COMPLEXE: Lesson = {
  id: 'cm1-francais-phrase-simple-complexe',
  title: 'Phrase simple, phrase complexe',
  subject: 'francais',
  source: 'grammaire',
  level: 'CM1',
  notion: 'Distinguer phrase simple et phrase complexe ; ponctuer un dialogue',
  theme: 'grammaire',
  attendu: 'Distinguer phrase simple et phrase complexe, types et formes de phrases, ponctuation du dialogue.',
  attenduId: 'cm1-gram-phrase',
  summary:
    "Une phrase simple a un seul verbe conjugué : « Le chat dort. » Une phrase complexe en a plusieurs : « Quand la cloche sonne, les enfants sortent. » Dans un dialogue, on ouvre les guillemets quand quelqu'un commence à parler, et on met un tiret chaque fois qu'un autre personnage prend la parole.",
  minutes: 7,
  exercises: [
    {
      id: 'cm1-francais-phrase-simple-complexe-choice-1',
      kind: 'choice',
      prompt: 'Combien y a-t-il de verbes conjugués dans « Quand le vent souffle, les volets claquent » ?',
      options: ['Un', 'Deux', 'Trois'],
      answer: 1,
      explain: '« Souffle » et « claquent » : deux verbes conjugués, donc c\'est une phrase complexe.',
    },
    {
      id: 'cm1-francais-phrase-simple-complexe-tf-1',
      kind: 'truefalse',
      statement: 'Une phrase simple a un seul verbe conjugué.',
      answer: true,
      explain: 'Oui : un seul verbe conjugué, c\'est une phrase simple, même si elle est longue.',
    },
    {
      id: 'cm1-francais-phrase-simple-complexe-sort-1',
      kind: 'sort',
      prompt: 'Range chaque phrase dans la bonne boîte',
      boxes: ['Phrase simple', 'Phrase complexe'],
      items: [
        { word: 'Le chat dort sur le canapé.', box: 0 },
        { word: 'Je lis pendant que tu dessines.', box: 1 },
        { word: 'Léa chante et Tom danse.', box: 1 },
        { word: 'Les élèves rangent leurs cahiers.', box: 0 },
        { word: 'Il pleut, alors nous restons dedans.', box: 1 },
        { word: 'Les enfants du quartier construisent une cabane.', box: 0 },
      ],
      explain: 'Compte les verbes conjugués : un seul, phrase simple ; plusieurs, phrase complexe.',
    },
    {
      id: 'cm1-francais-phrase-simple-complexe-tap-1',
      kind: 'tapword',
      prompt: 'Touche les deux verbes conjugués',
      words: ['Quand', 'la', 'cloche', 'sonne,', 'les', 'enfants', 'sortent', 'en', 'courant.'],
      answer: [3, 6],
      explain: '« Sonne » et « sortent » sont conjugués. « Courant » n\'est pas conjugué, c\'est un participe présent.',
    },
    {
      id: 'cm1-francais-phrase-simple-complexe-choice-2',
      kind: 'choice',
      prompt: 'Quel signe ouvre un dialogue ?',
      options: ['Les parenthèses', 'Le point-virgule', 'Les guillemets'],
      answer: 2,
      explain: 'On ouvre les guillemets « quand quelqu\'un commence à parler, et on les ferme » à la fin du dialogue.',
    },
    {
      id: 'cm1-francais-phrase-simple-complexe-order-1',
      kind: 'order',
      prompt: "Remets les répliques du dialogue dans l'ordre",
      lines: [
        '« Qui veut une crêpe ? » demande Mamie.',
        '— Moi ! crie Léo.',
        '— Moi aussi, dit Jade.',
        '— Alors, à table ! répond Mamie.',
      ],
      explain: 'Mamie pose la question, Léo répond, puis Jade, et Mamie conclut. Chaque tiret marque un nouveau personnage.',
    },
    {
      id: 'cm1-francais-phrase-simple-complexe-blanks-1',
      kind: 'blanks',
      prompt: 'Complète les phrases complexes avec le bon mot de liaison',
      text: 'Tom range sa chambre {{pendant que}} sa sœur fait ses devoirs. Il sourit {{quand}} elle le remercie.',
      distractors: ['donc', 'ni'],
      explain: '« Pendant que » dit que les deux actions ont lieu en même temps ; « quand » dit le moment.',
    },
    {
      id: 'cm1-francais-phrase-simple-complexe-choice-3',
      kind: 'choice',
      prompt: "Dans un dialogue, qu'est-ce qui montre qu'un nouveau personnage parle ?",
      options: ['Un tiret au début de la ligne', 'Une virgule', 'Un point'],
      answer: 0,
      explain: 'Chaque changement de personnage commence par un tiret, à la ligne.',
    },
    {
      id: 'cm1-francais-phrase-simple-complexe-sentence-1',
      kind: 'sentence',
      prompt: "Remets les mots de la réplique dans l'ordre",
      words: ['« Tu', 'as', 'vu', 'mon', 'cahier ? »', 'demande', 'Nora.'],
      explain: 'La parole est entre guillemets, puis on dit qui parle : « demande Nora ».',
    },
    {
      id: 'cm1-francais-phrase-simple-complexe-tap-2',
      kind: 'tapword',
      prompt: "Touche le tiret qui montre qu'un autre personnage parle",
      words: ['« Viens', 'jouer !', 'dit', 'Sam.', '—', 'Je', 'finis', "d'abord", 'mes', 'devoirs. »'],
      answer: [4],
      explain: 'Le tiret annonce la réponse d\'un autre personnage, sans rouvrir les guillemets.',
    },
  ],
};

const SUJET_VERBE_COD_COI: Lesson = {
  id: 'cm1-francais-sujet-verbe-cod-coi',
  title: 'Sujet, verbe, COD, COI',
  subject: 'francais',
  source: 'grammaire',
  level: 'CM1',
  notion: "Identifier le sujet, le verbe, le complément d'objet direct et le complément d'objet indirect",
  theme: 'grammaire',
  attendu: "Identifier le sujet, le verbe, les compléments d'objet et les compléments circonstanciels de lieu, de temps, de manière.",
  attenduId: 'cm1-gram-fonctions',
  summary:
    "Le sujet fait l'action : qui est-ce qui ? Le COD complète le verbe directement : on demande « quoi ? » ou « qui ? » après le verbe (Mathis lit un roman). Le COI est relié par « à » ou « de » : on demande « à qui ? », « de quoi ? » (Elle parle à sa voisine). On ne peut pas les supprimer sans changer le sens.",
  minutes: 7,
  exercises: [
    {
      id: 'cm1-francais-sujet-verbe-cod-coi-tap-1',
      kind: 'tapword',
      prompt: 'Touche les deux mots du sujet',
      words: ['Chaque', 'matin,', 'le', 'facteur', 'apporte', 'le', 'courrier.'],
      answer: [2, 3],
      explain: 'Qui est-ce qui apporte le courrier ? Le facteur. « Chaque matin » dit quand, ce n\'est pas le sujet.',
    },
    {
      id: 'cm1-francais-sujet-verbe-cod-coi-tap-2',
      kind: 'tapword',
      prompt: 'Touche les mots du COD',
      words: ['Mathis', 'lit', 'un', 'roman', 'passionnant.'],
      answer: [2, 3, 4],
      explain: 'Mathis lit quoi ? Un roman passionnant. C\'est le COD, collé au verbe sans « à » ni « de ».',
    },
    {
      id: 'cm1-francais-sujet-verbe-cod-coi-choice-1',
      kind: 'choice',
      prompt: 'Dans « Elle parle à sa voisine », « à sa voisine » est...',
      options: ['le sujet', 'un COD', 'un COI'],
      answer: 2,
      explain: 'Elle parle à qui ? À sa voisine. Le petit mot « à » montre que c\'est un COI.',
    },
    {
      id: 'cm1-francais-sujet-verbe-cod-coi-tf-1',
      kind: 'truefalse',
      statement: 'Le COD répond à la question « qui ? » ou « quoi ? » posée après le verbe.',
      answer: true,
      explain: 'Oui : Léa appelle qui ? Son frère. Tu écris quoi ? Une lettre. Ce sont des COD.',
    },
    {
      id: 'cm1-francais-sujet-verbe-cod-coi-sort-1',
      kind: 'sort',
      prompt: 'Le complément de chaque phrase est-il un COD ou un COI ?',
      boxes: ['COD (quoi ? qui ?)', 'COI (à qui ? de quoi ?)'],
      items: [
        { word: 'Nous regardons un film.', box: 0 },
        { word: 'Elle pense à ses vacances.', box: 1 },
        { word: 'Tu écris une lettre.', box: 0 },
        { word: 'Il parle de son chien.', box: 1 },
        { word: 'Léa appelle son frère.', box: 0 },
        { word: 'Je téléphone à Mamie.', box: 1 },
      ],
      explain: 'Un film, une lettre, son frère : COD. À ses vacances, de son chien, à Mamie : COI, avec « à » ou « de ».',
    },
    {
      id: 'cm1-francais-sujet-verbe-cod-coi-blanks-1',
      kind: 'blanks',
      prompt: 'Complète avec les bons groupes de mots',
      text: 'Dans « Papa offre un livre à Lucie », le COD est {{un livre}} et le COI est {{à Lucie}}.',
      distractors: ['Papa', 'offre'],
      explain: 'Papa offre quoi ? Un livre : COD. À qui ? À Lucie : COI. Papa est le sujet et offre est le verbe.',
    },
    {
      id: 'cm1-francais-sujet-verbe-cod-coi-choice-2',
      kind: 'choice',
      prompt: 'Quelle phrase contient un COI ?',
      options: ['Le chat attrape la souris.', 'Les enfants dorment.', 'Je pense à mon ami.'],
      answer: 2,
      explain: 'Je pense à qui ? À mon ami : COI. « La souris » est un COD, et « les enfants dorment » n\'a pas de complément.',
    },
    {
      id: 'cm1-francais-sujet-verbe-cod-coi-pairs-1',
      kind: 'pairs',
      prompt: 'Associe chaque question à la fonction qu\'elle permet de trouver',
      pairs: [
        { a: "Qui est-ce qui fait l'action ?", b: 'le sujet' },
        { a: 'Quoi ? Qui ? après le verbe', b: 'le COD' },
        { a: 'À qui ? De quoi ? après le verbe', b: 'le COI' },
        { a: 'Que fait le sujet ?', b: 'le verbe' },
      ],
      explain: 'Chaque fonction a sa question : c\'est le meilleur moyen de ne pas se tromper.',
    },
    {
      id: 'cm1-francais-sujet-verbe-cod-coi-tap-3',
      kind: 'tapword',
      prompt: 'Touche les mots du COI',
      words: ['Les', 'élèves', 'obéissent', 'à', 'la', 'maîtresse.'],
      answer: [3, 4, 5],
      explain: 'Les élèves obéissent à qui ? À la maîtresse. Le « à » annonce un COI.',
    },
    {
      id: 'cm1-francais-sujet-verbe-cod-coi-sentence-1',
      kind: 'sentence',
      prompt: "Remets les mots de la phrase dans l'ordre : sujet, verbe, COD, COI",
      words: ['Le', 'jardinier', 'offre', 'des', 'fleurs', 'à', 'sa', 'voisine.'],
      explain: 'Le jardinier (sujet) offre (verbe) des fleurs (COD) à sa voisine (COI).',
    },
  ],
};

const COMPLEMENTS_CIRCONSTANCIELS: Lesson = {
  id: 'cm1-francais-complements-circonstanciels',
  title: 'Compléments circonstanciels',
  subject: 'francais',
  source: 'grammaire',
  level: 'CM1',
  notion: 'Identifier les compléments circonstanciels de lieu, de temps et de manière',
  theme: 'grammaire',
  attendu: "Identifier le sujet, le verbe, les compléments d'objet et les compléments circonstanciels de lieu, de temps, de manière.",
  attenduId: 'cm1-gram-fonctions',
  summary:
    "Un complément circonstanciel donne une précision : le lieu (où ?), le temps (quand ?) ou la manière (comment ?). On peut souvent le déplacer ou le supprimer sans casser la phrase : « Ce matin, Léa range sa chambre avec soin. »",
  minutes: 7,
  exercises: [
    {
      id: 'cm1-francais-complements-circonstanciels-sort-1',
      kind: 'sort',
      prompt: 'Range chaque complément selon la question qu\'il répond',
      boxes: ['Lieu (où ?)', 'Temps (quand ?)', 'Manière (comment ?)'],
      items: [
        { word: 'dans la cour', box: 0 },
        { word: 'ce matin', box: 1 },
        { word: 'avec soin', box: 2 },
        { word: 'sous le lit', box: 0 },
        { word: 'demain', box: 1 },
        { word: 'lentement', box: 2 },
        { word: 'depuis une heure', box: 1 },
        { word: 'à la bibliothèque', box: 0 },
      ],
      explain: 'Où ? dans la cour, sous le lit, à la bibliothèque. Quand ? ce matin, demain, depuis une heure. Comment ? avec soin, lentement.',
    },
    {
      id: 'cm1-francais-complements-circonstanciels-tap-1',
      kind: 'tapword',
      prompt: 'Touche les deux mots du complément de temps',
      words: ['Hier', 'soir,', 'nous', 'avons', 'dîné', 'au', 'restaurant.'],
      answer: [0, 1],
      explain: 'Quand avons-nous dîné ? Hier soir. « Au restaurant » répond à « où ? ».',
    },
    {
      id: 'cm1-francais-complements-circonstanciels-choice-1',
      kind: 'choice',
      prompt: 'Dans « Le chat grimpe doucement sur le toit », « doucement » indique...',
      options: ['le lieu', 'le temps', 'la manière'],
      answer: 2,
      explain: 'Le chat grimpe comment ? Doucement. C\'est un complément de manière.',
    },
    {
      id: 'cm1-francais-complements-circonstanciels-tf-1',
      kind: 'truefalse',
      statement: 'Un complément circonstanciel peut souvent se déplacer ou se supprimer.',
      answer: true,
      explain: 'Oui : « Ce matin, Léa range sa chambre » devient « Léa range sa chambre ce matin » ou « Léa range sa chambre ».',
    },
    {
      id: 'cm1-francais-complements-circonstanciels-tap-2',
      kind: 'tapword',
      prompt: 'Touche les trois mots du complément de lieu',
      words: ['Pendant', 'la', 'récréation,', 'les', 'enfants', 'jouent', 'derrière', 'le', 'préau.'],
      answer: [6, 7, 8],
      explain: 'Les enfants jouent où ? Derrière le préau. « Pendant la récréation » dit quand.',
    },
    {
      id: 'cm1-francais-complements-circonstanciels-blanks-1',
      kind: 'blanks',
      prompt: 'Complète avec le complément de manière, puis de temps, puis de lieu',
      text: 'Les randonneurs marchent {{lentement}} ; {{ce soir}}, ils dormiront {{dans un refuge}}.',
      distractors: ['un sac', 'bleu'],
      explain: 'Comment ? Lentement. Quand ? Ce soir. Où ? Dans un refuge.',
    },
    {
      id: 'cm1-francais-complements-circonstanciels-fix-1',
      kind: 'fix',
      prompt: 'Le complément de temps ne va pas avec le verbe. Touche-le et corrige',
      words: ['Nous', 'irons', 'à', 'la', 'mer', 'hier.'],
      wrongIndex: 5,
      correct: 'demain.',
      distractors: ['avant-hier.', 'autrefois.'],
      explain: '« Nous irons » est au futur : le complément de temps doit parler de l\'avenir, comme « demain ».',
    },
    {
      id: 'cm1-francais-complements-circonstanciels-choice-2',
      kind: 'choice',
      prompt: 'Quelle question pose-t-on pour trouver un complément de lieu ?',
      options: ['Quand ?', 'Où ?', 'Comment ?'],
      answer: 1,
      explain: 'Où ? pour le lieu, quand ? pour le temps, comment ? pour la manière.',
    },
    {
      id: 'cm1-francais-complements-circonstanciels-sentence-1',
      kind: 'sentence',
      prompt: "Remets les mots de la phrase dans l'ordre",
      words: ['Ce', 'matin,', 'Léa', 'range', 'sa', 'chambre', 'avec', 'soin.'],
      explain: '« Ce matin » dit quand, « avec soin » dit comment. Entre les deux : Léa range sa chambre.',
    },
    {
      id: 'cm1-francais-complements-circonstanciels-pairs-1',
      kind: 'pairs',
      prompt: 'Associe chaque question au complément qui y répond',
      pairs: [
        { a: 'Où ?', b: 'dans le jardin' },
        { a: 'Quand ?', b: 'la semaine prochaine' },
        { a: 'Comment ?', b: 'avec courage' },
      ],
      explain: 'Dans le jardin : lieu. La semaine prochaine : temps. Avec courage : manière.',
    },
  ],
};

const CLASSES_DE_MOTS: Lesson = {
  id: 'cm1-francais-classes-de-mots',
  title: 'Les classes de mots',
  subject: 'francais',
  source: 'grammaire',
  level: 'CM1',
  notion: 'Reconnaître les classes de mots : nom, déterminant, adjectif, pronom, verbe, adverbe, préposition',
  theme: 'grammaire',
  attendu: 'Reconnaître les classes de mots : nom, déterminant, adjectif, pronom, verbe, adverbe, préposition.',
  attenduId: 'cm1-gram-classes',
  summary:
    "Chaque mot appartient à une classe. Le nom désigne une chose ou une personne (chapeau). Le déterminant le précède (le, une, mon). L'adjectif le décrit (bleu). Le pronom remplace un nom (il, nous). Le verbe dit l'action (sauter). L'adverbe précise le verbe et ne change jamais (vite, souvent). La préposition relie des mots (sur, avec, vers).",
  minutes: 7,
  exercises: [
    {
      id: 'cm1-francais-classes-de-mots-sort-1',
      kind: 'sort',
      prompt: 'Range chaque mot dans sa classe',
      boxes: ['Nom', 'Déterminant', 'Adjectif', 'Verbe'],
      items: [
        { word: 'maison', box: 0 },
        { word: 'les', box: 1 },
        { word: 'joli', box: 2 },
        { word: 'courir', box: 3 },
        { word: 'cette', box: 1 },
        { word: 'table', box: 0 },
        { word: 'rapide', box: 2 },
        { word: 'manger', box: 3 },
      ],
      explain: 'Maison et table sont des noms ; les et cette des déterminants ; joli et rapide des adjectifs ; courir et manger des verbes.',
    },
    {
      id: 'cm1-francais-classes-de-mots-choice-1',
      kind: 'choice',
      prompt: '« Elle » dans « Elle chante » est...',
      options: ['un nom', 'un pronom', 'un adverbe'],
      answer: 1,
      explain: '« Elle » remplace un nom, par exemple « Léa » : c\'est un pronom.',
    },
    {
      id: 'cm1-francais-classes-de-mots-tap-1',
      kind: 'tapword',
      prompt: 'Touche les deux adverbes',
      words: ['Le', 'train', 'roule', 'très', 'vite', 'dans', 'la', 'vallée.'],
      answer: [3, 4],
      explain: '« Vite » précise comment roule le train, et « très » renforce « vite ». Les adverbes ne changent jamais.',
    },
    {
      id: 'cm1-francais-classes-de-mots-tf-1',
      kind: 'truefalse',
      statement: "Un adjectif donne une information sur le nom : une robe rouge.",
      answer: true,
      explain: 'Oui : « rouge » décrit la robe. L\'adjectif s\'accorde avec le nom.',
    },
    {
      id: 'cm1-francais-classes-de-mots-tap-2',
      kind: 'tapword',
      prompt: 'Touche les deux prépositions',
      words: ['Le', 'chat', 'saute', 'sur', 'le', 'mur', 'et', 'court', 'vers', 'le', 'jardin.'],
      answer: [3, 8],
      explain: '« Sur » et « vers » relient le verbe à un lieu. « Et » est un mot de liaison, pas une préposition.',
    },
    {
      id: 'cm1-francais-classes-de-mots-sort-2',
      kind: 'sort',
      prompt: 'Range chaque mot dans sa classe',
      boxes: ['Pronom', 'Adverbe', 'Préposition'],
      items: [
        { word: 'nous', box: 0 },
        { word: 'souvent', box: 1 },
        { word: 'avec', box: 2 },
        { word: 'ils', box: 0 },
        { word: 'hier', box: 1 },
        { word: 'sous', box: 2 },
        { word: 'elle', box: 0 },
        { word: 'doucement', box: 1 },
      ],
      explain: 'Nous, ils, elle remplacent des noms. Souvent, hier, doucement précisent. Avec, sous relient des mots.',
    },
    {
      id: 'cm1-francais-classes-de-mots-blanks-1',
      kind: 'blanks',
      prompt: 'Complète avec le nom de chaque classe',
      text: 'Dans « Les petits oiseaux chantent joyeusement », « petits » est un {{adjectif}}, « chantent » est un {{verbe}} et « joyeusement » est un {{adverbe}}.',
      distractors: ['nom', 'pronom'],
      explain: '« Petits » décrit les oiseaux, « chantent » est l\'action, « joyeusement » dit comment ils chantent.',
    },
    {
      id: 'cm1-francais-classes-de-mots-fix-1',
      kind: 'fix',
      prompt: 'Gribouille s\'est trompé de classe. Touche le mot faux et corrige',
      words: ['Dans', '« il', 'mange »,', 'le', 'mot', '« il »', 'est', 'un', 'nom.'],
      wrongIndex: 8,
      correct: 'pronom.',
      distractors: ['adverbe.', 'verbe.'],
      explain: '« Il » remplace un nom (le chien, Paul...) : c\'est un pronom.',
    },
    {
      id: 'cm1-francais-classes-de-mots-choice-2',
      kind: 'choice',
      prompt: 'Quel mot est un déterminant ?',
      options: ['vite', 'mon', 'grand'],
      answer: 1,
      explain: '« Mon » se place devant un nom : mon vélo. « Vite » est un adverbe et « grand » un adjectif.',
    },
    {
      id: 'cm1-francais-classes-de-mots-pairs-1',
      kind: 'pairs',
      prompt: 'Associe chaque classe à un exemple',
      pairs: [
        { a: 'nom', b: 'chapeau' },
        { a: 'déterminant', b: 'une' },
        { a: 'adjectif', b: 'bleu' },
        { a: 'pronom', b: 'tu' },
        { a: 'verbe', b: 'sauter' },
        { a: 'adverbe', b: 'toujours' },
      ],
      explain: 'Chapeau est un nom, une un déterminant, bleu un adjectif, tu un pronom, sauter un verbe, toujours un adverbe.',
    },
  ],
};

const PRESENT_TROIS_GROUPES: Lesson = {
  id: 'cm1-francais-present-trois-groupes',
  title: 'Le présent des trois groupes',
  subject: 'francais',
  source: 'lecon',
  level: 'CM1',
  notion: 'Conjuguer au présent les verbes des trois groupes : finir, voir, prendre, venir, pouvoir, vouloir, aller, faire, dire',
  theme: 'conjugaison',
  attendu: 'Conjuguer au présent les verbes des 1er et 2e groupes et les verbes fréquents du 3e groupe.',
  attenduId: 'cm1-conj-present',
  summary:
    "Les verbes en -er sont du 1er groupe (je chante, nous chantons). Les verbes en -ir qui font « nous -issons » sont du 2e groupe (nous finissons). Les autres sont du 3e groupe et il faut les connaître par cœur : je peux, tu veux, il va, nous faisons, vous dites, ils voient, ils prennent, ils viennent.",
  minutes: 8,
  exercises: [
    {
      id: 'cm1-francais-present-trois-groupes-choice-1',
      kind: 'choice',
      prompt: 'Nous ... nos devoirs avant le dîner. (finir)',
      options: ['finissons', 'finions', 'finisons'],
      answer: 0,
      explain: '« Finir » est du 2e groupe : nous finissons, avec deux s. « Finions », c\'est l\'imparfait.',
    },
    {
      id: 'cm1-francais-present-trois-groupes-sort-1',
      kind: 'sort',
      prompt: 'Range chaque verbe dans son groupe',
      boxes: ['1er groupe (-er)', '2e groupe (-ir, nous -issons)', '3e groupe'],
      items: [
        { word: 'chanter', box: 0 },
        { word: 'finir', box: 1 },
        { word: 'prendre', box: 2 },
        { word: 'grandir', box: 1 },
        { word: 'venir', box: 2 },
        { word: 'jouer', box: 0 },
        { word: 'pouvoir', box: 2 },
        { word: 'choisir', box: 1 },
      ],
      explain: 'Chanter, jouer : -er. Finir, grandir, choisir : nous finissons, grandissons, choisissons. Prendre, venir, pouvoir : 3e groupe.',
    },
    {
      id: 'cm1-francais-present-trois-groupes-blanks-1',
      kind: 'blanks',
      prompt: 'Complète avec les verbes au présent',
      text: 'Tu {{prends}} ton sac et tu {{viens}} avec nous.',
      distractors: ['prend', 'vient'],
      explain: 'Avec « tu », les verbes prendre et venir finissent par un s : tu prends, tu viens.',
    },
    {
      id: 'cm1-francais-present-trois-groupes-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a mal conjugué. Touche le mot faux et corrige',
      words: ['Ils', 'voit', 'un', 'arc-en-ciel.'],
      wrongIndex: 1,
      correct: 'voient',
      distractors: ['voyent', 'voie'],
      explain: 'Avec « ils », le verbe voir s\'écrit « voient » : on garde le i et on ajoute -ent.',
    },
    {
      id: 'cm1-francais-present-trois-groupes-match-1',
      kind: 'match',
      prompt: 'Relie chaque verbe à sa forme au présent',
      pairs: [
        { a: 'je (pouvoir)', b: 'peux' },
        { a: 'nous (vouloir)', b: 'voulons' },
        { a: 'ils (aller)', b: 'vont' },
        { a: 'vous (faire)', b: 'faites' },
        { a: 'elle (dire)', b: 'dit' },
        { a: 'tu (venir)', b: 'viens' },
      ],
      seconds: 45,
      explain: 'Je peux, nous voulons, ils vont, vous faites, elle dit, tu viens : des verbes du 3e groupe à connaître par cœur.',
    },
    {
      id: 'cm1-francais-present-trois-groupes-tf-1',
      kind: 'truefalse',
      statement: '« Vous dites » est correct : le verbe dire fait « vous dites », et pas « vous disez ».',
      answer: true,
      explain: 'Oui : vous dites, vous faites, vous êtes. Ces trois verbes ne prennent pas -ez.',
    },
    {
      id: 'cm1-francais-present-trois-groupes-choice-2',
      kind: 'choice',
      prompt: 'Elles ... une glace à la fraise. (vouloir)',
      options: ['veut', 'veulent', 'voulent'],
      answer: 1,
      explain: 'Avec « elles », vouloir s\'écrit « veulent ». « Voulent » n\'existe pas, et « veut » est pour « elle ».',
    },
    {
      id: 'cm1-francais-present-trois-groupes-blanks-2',
      kind: 'blanks',
      prompt: 'Complète avec les verbes au présent',
      text: 'Je {{vais}} au marché, je {{fais}} les courses et je {{peux}} acheter des fraises.',
      distractors: ['va', 'fait', 'peut'],
      explain: 'Je vais, je fais, je peux. Va, fait, peut sont les formes avec « il » ou « elle ».',
    },
    {
      id: 'cm1-francais-present-trois-groupes-fix-2',
      kind: 'fix',
      prompt: 'Gribouille a mal conjugué. Touche le mot faux et corrige',
      words: ['Nous', 'faisons', 'un', 'gâteau', 'et', 'vous', 'faisez', 'la', 'vaisselle.'],
      wrongIndex: 6,
      correct: 'faites',
      distractors: ['fêtes', 'faisons'],
      explain: '« Faisez » n\'existe pas : avec « vous », le verbe faire s\'écrit « faites ».',
    },
    {
      id: 'cm1-francais-present-trois-groupes-tap-1',
      kind: 'tapword',
      prompt: 'Touche le verbe du 2e groupe',
      words: ['Les', 'fleurs', 'fleurissent', 'et', 'les', 'enfants', 'jouent', 'dehors.'],
      answer: [2],
      explain: '« Fleurir » fait « nous fleurissons » : 2e groupe. « Jouer » est du 1er groupe.',
    },
  ],
};

const IMPARFAIT_FUTUR: Lesson = {
  id: 'cm1-francais-imparfait-futur',
  title: "L'imparfait et le futur",
  subject: 'francais',
  source: 'lecon',
  level: 'CM1',
  notion: "Conjuguer à l'imparfait et au futur les verbes étudiés, y compris ceux du 3e groupe",
  theme: 'conjugaison',
  attendu: "Conjuguer à l'imparfait et au futur les verbes étudiés.",
  attenduId: 'cm1-conj-imparfait-futur',
  summary:
    "L'imparfait raconte le passé qui dure ou se répète : -ais, -ais, -ait, -ions, -iez, -aient, pour tous les verbes (j'étais, nous faisions, ils venaient). Le futur dit ce qui va arriver : -rai, -ras, -ra, -rons, -rez, -ront (je serai, tu iras, nous verrons, ils pourront).",
  minutes: 7,
  exercises: [
    {
      id: 'cm1-francais-imparfait-futur-choice-1',
      kind: 'choice',
      prompt: "Autrefois, les enfants ... à l'école à pied. (aller)",
      options: ['iront', 'allaient', 'allèrent'],
      answer: 1,
      explain: "« Autrefois » et une habitude qui dure : c'est l'imparfait, « allaient », avec -aient.",
    },
    {
      id: 'cm1-francais-imparfait-futur-blanks-1',
      kind: 'blanks',
      prompt: "Complète à l'imparfait",
      text: "Quand j'{{étais}} petit, je {{jouais}} dans la cour.",
      distractors: ['serai', 'jouerai'],
      explain: "J'étais, je jouais : la terminaison -ais marque l'imparfait avec « je ».",
    },
    {
      id: 'cm1-francais-imparfait-futur-fix-1',
      kind: 'fix',
      prompt: 'Le verbe ne va pas avec « demain ». Touche-le et corrige',
      words: ['Demain,', 'nous', 'partions', 'en', 'vacances.'],
      wrongIndex: 2,
      correct: 'partirons',
      distractors: ['partons', 'partirions'],
      explain: "« Demain » annonce l'avenir : le verbe est au futur, « nous partirons », avec -rons.",
    },
    {
      id: 'cm1-francais-imparfait-futur-sort-1',
      kind: 'sort',
      prompt: 'Imparfait ou futur ?',
      boxes: ['Imparfait', 'Futur'],
      items: [
        { word: 'tu chantais', box: 0 },
        { word: 'tu chanteras', box: 1 },
        { word: 'nous finissions', box: 0 },
        { word: 'ils viendront', box: 1 },
        { word: 'elle faisait', box: 0 },
        { word: 'vous prendrez', box: 1 },
        { word: 'je pourrai', box: 1 },
        { word: 'ils voyaient', box: 0 },
      ],
      explain: "Imparfait : -ais, -ait, -ions, -aient. Futur : un r juste avant la terminaison, -ras, -rez, -ront, -rai.",
    },
    {
      id: 'cm1-francais-imparfait-futur-tf-1',
      kind: 'truefalse',
      statement: "À l'imparfait, les terminaisons sont -ais, -ais, -ait, -ions, -iez, -aient pour tous les verbes.",
      answer: true,
      explain: "Oui, c'est le temps le plus régulier : même être et avoir suivent ces terminaisons (j'étais, j'avais).",
    },
    {
      id: 'cm1-francais-imparfait-futur-choice-2',
      kind: 'choice',
      prompt: "L'année prochaine, tu ... dix ans. (avoir)",
      options: ['avais', 'aura', 'auras'],
      answer: 2,
      explain: "« L'année prochaine » : futur. Avec « tu », la terminaison est -ras : tu auras.",
    },
    {
      id: 'cm1-francais-imparfait-futur-blanks-2',
      kind: 'blanks',
      prompt: 'Complète au futur',
      text: 'Dans dix ans, nous {{serons}} grands et nous {{ferons}} de longs voyages.',
      distractors: ['étions', 'faisions'],
      explain: 'Nous serons, nous ferons : le futur de être et faire, avec -rons. Étions et faisions sont à l\'imparfait.',
    },
    {
      id: 'cm1-francais-imparfait-futur-tap-1',
      kind: 'tapword',
      prompt: "Touche les deux verbes à l'imparfait",
      words: ['Il', 'pleuvait', 'et', 'le', 'vent', 'soufflait,', 'mais', 'demain', 'il', 'fera', 'beau.'],
      answer: [1, 5],
      explain: '« Pleuvait » et « soufflait » finissent par -ait : imparfait. « Fera » est au futur.',
    },
    {
      id: 'cm1-francais-imparfait-futur-match-1',
      kind: 'match',
      prompt: 'Relie chaque verbe à sa forme conjuguée',
      pairs: [
        { a: 'je (être, imparfait)', b: 'étais' },
        { a: 'tu (aller, futur)', b: 'iras' },
        { a: 'nous (voir, futur)', b: 'verrons' },
        { a: 'ils (venir, imparfait)', b: 'venaient' },
        { a: 'vous (pouvoir, futur)', b: 'pourrez' },
      ],
      seconds: 45,
      explain: "J'étais, tu iras, nous verrons, ils venaient, vous pourrez : le futur d'aller, voir et pouvoir change de radical.",
    },
    {
      id: 'cm1-francais-imparfait-futur-fix-2',
      kind: 'fix',
      prompt: 'Un verbe n\'est pas au bon temps. Touche-le et corrige',
      words: ['Hier,', 'elle', 'mangeait', 'une', 'glace', 'et', 'elle', 'lira', 'un', 'livre.'],
      wrongIndex: 7,
      correct: 'lisait',
      distractors: ['lisais', 'lisaient'],
      explain: "« Hier » et « mangeait » : tout est au passé. Avec « elle », l'imparfait de lire est « lisait ».",
    },
  ],
};

const PASSE_COMPOSE_SIMPLE: Lesson = {
  id: 'cm1-francais-passe-compose-simple',
  title: 'Passé composé et passé simple',
  subject: 'francais',
  source: 'lecon',
  level: 'CM1',
  notion: 'Conjuguer au passé composé et reconnaître le passé simple à la 3e personne dans un récit',
  theme: 'conjugaison',
  attendu: 'Conjuguer au passé composé et reconnaître le passé simple à la 3e personne dans un récit.',
  attenduId: 'cm1-conj-passe',
  summary:
    "Le passé composé se forme avec avoir ou être au présent, suivi du participe passé : j'ai mangé, elle est partie. Avec être, le participe s'accorde avec le sujet. Le passé simple se lit surtout dans les contes et les récits : il entra, elle vit, il fut, elle eut. Il suffit de le reconnaître.",
  minutes: 7,
  exercises: [
    {
      id: 'cm1-francais-passe-compose-simple-choice-1',
      kind: 'choice',
      prompt: "Hier, j'... une pomme. (manger)",
      options: ['ai manger', 'ai mangé', 'suis mangé'],
      answer: 1,
      explain: "Passé composé : avoir au présent et le participe passé « mangé », avec é. « Ai manger » est une faute fréquente.",
    },
    {
      id: 'cm1-francais-passe-compose-simple-sort-1',
      kind: 'sort',
      prompt: 'Avec quel auxiliaire est formé chaque passé composé ?',
      boxes: ['Avec avoir', 'Avec être'],
      items: [
        { word: 'il a fini', box: 0 },
        { word: 'elle est partie', box: 1 },
        { word: 'nous avons vu', box: 0 },
        { word: 'ils sont venus', box: 1 },
        { word: 'tu as pris', box: 0 },
        { word: 'je suis tombé', box: 1 },
      ],
      explain: "Partir, venir, tomber se conjuguent avec être, et le participe s'accorde : elle est partie, ils sont venus.",
    },
    {
      id: 'cm1-francais-passe-compose-simple-blanks-1',
      kind: 'blanks',
      prompt: 'Complète avec le bon auxiliaire',
      text: 'Nous {{avons}} joué au ballon, puis nous {{sommes}} rentrés.',
      distractors: ['sont', 'ont'],
      explain: 'Jouer prend avoir : nous avons joué. Rentrer prend être : nous sommes rentrés.',
    },
    {
      id: 'cm1-francais-passe-compose-simple-fix-1',
      kind: 'fix',
      prompt: "Gribouille s'est trompé d'auxiliaire. Touche le mot faux et corrige",
      words: ['Les', 'filles', 'ont', 'allées', 'au', 'cinéma.'],
      wrongIndex: 2,
      correct: 'sont',
      distractors: ['est', 'a'],
      explain: 'Aller se conjugue avec être : les filles sont allées. Le participe « allées » est accordé avec les filles.',
    },
    {
      id: 'cm1-francais-passe-compose-simple-tap-1',
      kind: 'tapword',
      prompt: 'Touche les trois verbes au passé simple',
      words: ['Le', 'loup', 'entra', 'dans', 'la', 'forêt,', 'regarda', 'autour', 'de', 'lui', 'et', 'hurla.'],
      answer: [2, 6, 11],
      explain: "Entra, regarda, hurla : le passé simple des verbes en -er finit par -a à la 3e personne du singulier.",
    },
    {
      id: 'cm1-francais-passe-compose-simple-tf-1',
      kind: 'truefalse',
      statement: 'Le passé simple se trouve surtout dans les récits écrits, comme les contes.',
      answer: true,
      explain: "Oui : « Il était une fois un roi qui eut trois fils... » À l'oral, on utilise plutôt le passé composé.",
    },
    {
      id: 'cm1-francais-passe-compose-simple-choice-2',
      kind: 'choice',
      prompt: '« Il prit son manteau et sortit. » Les verbes sont au...',
      options: ['passé composé', 'passé simple', 'imparfait'],
      answer: 1,
      explain: "« Prit » et « sortit » sont au passé simple : un seul mot, et pas la terminaison -ait de l'imparfait.",
    },
    {
      id: 'cm1-francais-passe-compose-simple-match-1',
      kind: 'match',
      prompt: 'Relie chaque verbe au passé simple à son infinitif',
      pairs: [
        { a: 'il fut', b: 'être' },
        { a: 'elle eut', b: 'avoir' },
        { a: 'il alla', b: 'aller' },
        { a: 'elle fit', b: 'faire' },
        { a: 'il vint', b: 'venir' },
        { a: 'elle dit', b: 'dire' },
      ],
      seconds: 45,
      explain: 'Fut, eut, alla, fit, vint, dit : des formes du passé simple à reconnaître dans les contes.',
    },
    {
      id: 'cm1-francais-passe-compose-simple-blanks-2',
      kind: 'blanks',
      prompt: 'Complète avec les verbes au passé simple',
      text: 'La princesse {{ouvrit}} la porte et {{vit}} un dragon endormi.',
      distractors: ['ouvert', 'vu'],
      explain: "Ouvrit, vit : passé simple. « Ouvert » et « vu » sont des participes passés, il leur manque l'auxiliaire.",
    },
    {
      id: 'cm1-francais-passe-compose-simple-pairs-1',
      kind: 'pairs',
      prompt: 'Associe chaque passé composé au passé simple du même verbe',
      pairs: [
        { a: 'il a chanté', b: 'il chanta' },
        { a: 'elle a fini', b: 'elle finit' },
        { a: 'il est parti', b: 'il partit' },
        { a: 'elle a pris', b: 'elle prit' },
      ],
      explain: 'Les deux temps racontent le passé : le passé composé en deux mots, le passé simple en un seul.',
    },
  ],
};

const SENS_DES_MOTS: Lesson = {
  id: 'cm1-francais-sens-des-mots',
  title: 'Synonymes, contraires, sens figuré',
  subject: 'francais',
  source: 'lecon',
  level: 'CM1',
  notion: 'Utiliser synonymes et antonymes, distinguer sens propre et sens figuré, reconnaître les niveaux de langue',
  theme: 'vocabulaire',
  attendu: 'Utiliser synonymes, antonymes, mots de sens voisin, sens propre et figuré, niveaux de langue.',
  attenduId: 'cm1-voc-sens',
  summary:
    "Un synonyme a presque le même sens (content, joyeux) ; un antonyme dit le contraire (chaud, froid). Un mot a un sens propre, le vrai (le lion dévore sa proie), et parfois un sens figuré, en image (Léa dévore son livre). Selon à qui on parle, on choisit un niveau de langue : familier (bagnole), courant (voiture), soutenu (automobile).",
  minutes: 7,
  exercises: [
    {
      id: 'cm1-francais-sens-des-mots-pairs-1',
      kind: 'pairs',
      prompt: 'Associe chaque mot à son synonyme',
      pairs: [
        { a: 'content', b: 'joyeux' },
        { a: 'énorme', b: 'gigantesque' },
        { a: 'peureux', b: 'craintif' },
        { a: 'bavarder', b: 'discuter' },
        { a: 'maison', b: 'demeure' },
      ],
      explain: 'Des synonymes ont presque le même sens : ils permettent de ne pas répéter toujours le même mot.',
    },
    {
      id: 'cm1-francais-sens-des-mots-choice-1',
      kind: 'choice',
      prompt: "Quel est l'antonyme de « courageux » ?",
      options: ['fort', 'peureux', 'gentil'],
      answer: 1,
      explain: "L'antonyme, c'est le contraire : courageux et peureux s'opposent.",
    },
    {
      id: 'cm1-francais-sens-des-mots-sort-1',
      kind: 'sort',
      prompt: 'Range chaque mot selon son niveau de langue',
      boxes: ['Familier', 'Courant', 'Soutenu'],
      items: [
        { word: 'bagnole', box: 0 },
        { word: 'voiture', box: 1 },
        { word: 'automobile', box: 2 },
        { word: 'bouffer', box: 0 },
        { word: 'manger', box: 1 },
        { word: 'se restaurer', box: 2 },
        { word: 'gosse', box: 0 },
        { word: 'enfant', box: 1 },
      ],
      explain: 'Familier entre copains, courant à l\'école, soutenu dans les livres ou les discours.',
    },
    {
      id: 'cm1-francais-sens-des-mots-tf-1',
      kind: 'truefalse',
      statement: "Dans « il a un cœur d'or », « cœur d'or » est au sens figuré.",
      answer: true,
      explain: "Oui : son cœur n'est pas vraiment en or. L'image veut dire qu'il est très généreux.",
    },
    {
      id: 'cm1-francais-sens-des-mots-choice-2',
      kind: 'choice',
      prompt: 'Dans quelle phrase « dévorer » est-il au sens propre ?',
      options: ['Léa dévore son livre.', 'Il dévore la vitrine des yeux.', 'Le lion dévore sa proie.'],
      answer: 2,
      explain: 'Le lion mange vraiment : sens propre. Léa ne mange pas son livre, elle le lit avec passion : sens figuré.',
    },
    {
      id: 'cm1-francais-sens-des-mots-match-1',
      kind: 'match',
      prompt: 'Relie chaque mot à son contraire',
      pairs: [
        { a: 'chaud', b: 'froid' },
        { a: 'lent', b: 'rapide' },
        { a: 'monter', b: 'descendre' },
        { a: 'début', b: 'fin' },
        { a: 'propre', b: 'sale' },
      ],
      seconds: 40,
      explain: 'Chaud et froid, lent et rapide, monter et descendre, début et fin, propre et sale : des antonymes.',
    },
    {
      id: 'cm1-francais-sens-des-mots-blanks-1',
      kind: 'blanks',
      prompt: 'Complète',
      text: "« Tomber dans les pommes » veut dire {{s'évanouir}} : c'est une expression au sens {{figuré}}.",
      distractors: ['propre', 'cueillir'],
      explain: "Personne ne tombe vraiment dans des pommes : l'expression est une image, donc au sens figuré.",
    },
    {
      id: 'cm1-francais-sens-des-mots-fix-1',
      kind: 'fix',
      prompt: 'Gribouille parle à la maîtresse en langage familier. Touche le mot et choisis le mot courant',
      words: ['Madame,', 'pouvez-vous', 'me', 'filer', 'un', 'stylo', '?'],
      wrongIndex: 3,
      correct: 'prêter',
      distractors: ['refiler', 'balancer'],
      explain: '« Filer » est familier. Pour parler à un adulte à l\'école, on choisit le mot courant : « prêter ».',
    },
    {
      id: 'cm1-francais-sens-des-mots-tap-1',
      kind: 'tapword',
      prompt: 'Touche le synonyme de « peur »',
      words: ['La', 'crainte', 'du', 'noir', 'est', 'fréquente', 'chez', 'les', 'enfants.'],
      answer: [1],
      explain: '« Crainte » veut dire « peur » : ce sont des synonymes.',
    },
    {
      id: 'cm1-francais-sens-des-mots-choice-3',
      kind: 'choice',
      prompt: 'Que signifie « avoir la tête dans les nuages » ?',
      options: ['Être très grand', 'Être distrait, rêveur', 'Être en avion'],
      answer: 1,
      explain: "C'est une image : la personne pense à autre chose, elle rêve. Sens figuré.",
    },
  ],
};

const FAMILLES_DE_MOTS: Lesson = {
  id: 'cm1-francais-familles-de-mots',
  title: 'Familles de mots et dictionnaire',
  subject: 'francais',
  source: 'lecon',
  level: 'CM1',
  notion: 'Construire des familles de mots avec radical, préfixes et suffixes ; utiliser le dictionnaire',
  theme: 'vocabulaire',
  attendu: 'Construire des familles de mots avec radical, préfixes et suffixes ; utiliser le dictionnaire.',
  attenduId: 'cm1-voc-familles',
  summary:
    "Les mots d'une même famille ont le même radical : terre, terrain, enterrer. Un préfixe se colle devant le radical et change le sens (refaire, défaire, invisible). Un suffixe se colle derrière (jardinet, jardinage, jardinier). Dans le dictionnaire, les mots sont rangés dans l'ordre alphabétique, lettre après lettre.",
  minutes: 7,
  exercises: [
    {
      id: 'cm1-francais-familles-de-mots-tap-1',
      kind: 'tapword',
      prompt: "Touche le mot qui n'est pas de la famille de « terre »",
      words: ['terrain', 'terrible', 'enterrer', 'terrasse'],
      answer: [1],
      explain: "« Terrible » commence pareil, mais il n'a rien à voir avec la terre : il veut dire effrayant.",
    },
    {
      id: 'cm1-francais-familles-de-mots-sort-1',
      kind: 'sort',
      prompt: 'Préfixe ou suffixe ?',
      boxes: ['Préfixe (devant)', 'Suffixe (derrière)'],
      items: [
        { word: 're- (refaire)', box: 0 },
        { word: '-ette (maisonnette)', box: 1 },
        { word: 'dé- (défaire)', box: 0 },
        { word: '-age (jardinage)', box: 1 },
        { word: 'in- (inconnu)', box: 0 },
        { word: '-eur (chanteur)', box: 1 },
      ],
      explain: 'Le préfixe se place devant le radical, le suffixe derrière.',
    },
    {
      id: 'cm1-francais-familles-de-mots-choice-1',
      kind: 'choice',
      prompt: 'Quel est le radical de « impossible » ?',
      options: ['im', 'possible', 'ible'],
      answer: 1,
      explain: '« Im- » est le préfixe qui dit le contraire ; « possible » est le radical, le mot de départ.',
    },
    {
      id: 'cm1-francais-familles-de-mots-blanks-1',
      kind: 'blanks',
      prompt: 'Complète avec les mots construits',
      text: 'Pour dire le contraire de « visible », j\'ajoute le préfixe in- : {{invisible}}. Pour dire « petit jardin », j\'ajoute un suffixe : {{jardinet}}.',
      distractors: ['revisible', 'jardinier'],
      explain: 'In- devant visible donne invisible. Le suffixe -et donne jardinet, un petit jardin. Le jardinier, c\'est la personne.',
    },
    {
      id: 'cm1-francais-familles-de-mots-order-1',
      kind: 'order',
      prompt: "Range les mots dans l'ordre du dictionnaire",
      lines: ['chaise', 'chameau', 'chanson', 'chat'],
      explain: 'Les mots commencent tous par « cha » : on regarde la lettre suivante. I, puis m, puis n, puis t.',
    },
    {
      id: 'cm1-francais-familles-de-mots-tf-1',
      kind: 'truefalse',
      statement: 'Dans le dictionnaire, « lune » vient avant « lundi ».',
      answer: false,
      explain: 'Pas grave. Les trois premières lettres sont les mêmes ; ensuite d vient avant e, donc « lundi » est avant « lune ».',
    },
    {
      id: 'cm1-francais-familles-de-mots-pairs-1',
      kind: 'pairs',
      prompt: 'Associe chaque préfixe à son sens',
      pairs: [
        { a: 're-', b: 'à nouveau' },
        { a: 'in-', b: 'le contraire' },
        { a: 'pré-', b: 'avant' },
        { a: 'tri-', b: 'trois' },
      ],
      explain: 'Refaire : faire à nouveau. Inconnu : pas connu. Préhistoire : avant l\'histoire. Tricycle : trois roues.',
    },
    {
      id: 'cm1-francais-familles-de-mots-choice-2',
      kind: 'choice',
      prompt: 'Quel mot est formé avec le suffixe -eur ?',
      options: ['meilleur', 'vendeur', 'cœur'],
      answer: 1,
      explain: 'Vendeur, c\'est vendre et le suffixe -eur : celui qui vend. Meilleur et cœur finissent pareil mais ne sont pas construits ainsi.',
    },
    {
      id: 'cm1-francais-familles-de-mots-flashcard-1',
      kind: 'flashcard',
      prompt: 'Réponds dans ta tête, puis retourne la carte',
      front: 'Que sont des mots de la même famille ?',
      back: 'Des mots construits sur le même radical : chant, chanter, chanteur, chanson.',
      explain: 'Le radical est le morceau commun à tous les mots de la famille.',
    },
    {
      id: 'cm1-francais-familles-de-mots-dictation-1',
      kind: 'dictation',
      word: 'invisible',
      sentence: "Le petit insecte est presque invisible dans l'herbe.",
      explain: 'Préfixe in-, puis le radical visible : invisible.',
    },
  ],
};

export const LESSONS: Lesson[] = [
  LIRE_FLUIDE,
  COMPRENDRE_RECIT,
  COMPRENDRE_DOCUMENTAIRE,
  CORBEAU_RENARD,
  REDIGER_TEXTE,
  HOMOPHONES_OU_LA_MES,
  HOMOPHONES_CE_SE,
  ACCORDS_GN_ETRE,
  ACCORD_SUJET_VERBE,
  LETTRES_MUETTES_DOUBLES,
  PHRASE_SIMPLE_COMPLEXE,
  SUJET_VERBE_COD_COI,
  COMPLEMENTS_CIRCONSTANCIELS,
  CLASSES_DE_MOTS,
  PRESENT_TROIS_GROUPES,
  IMPARFAIT_FUTUR,
  PASSE_COMPOSE_SIMPLE,
  SENS_DES_MOTS,
  FAMILLES_DE_MOTS,
];
