import type { Lesson } from './types';

/**
 * Banque de français, CE1. Quinze leçons qui couvrent les attendus de fin
 * de CE1 : lecture, poésie, orthographe, grammaire, conjugaison, vocabulaire.
 * Tous les textes sont originaux, sauf la fable de La Fontaine (domaine public).
 */

const LIRE_PONCTUATION: Lesson = {
  id: 'francais-lire-ponctuation',
  title: 'Lire avec la ponctuation',
  subject: 'francais',
  source: 'lecture',
  level: 'CE1',
  notion: 'Lire à voix haute en respectant le point, la virgule et le point d\'interrogation',
  theme: 'lecture',
  attendu: 'Lire à voix haute un texte adapté de façon fluide, en respectant la ponctuation.',
  attenduId: 'ce1-lect-fluide',
  summary:
    "Quand tu lis, la virgule te dit de faire une petite pause et le point de t'arrêter. Le point d'interrogation te dit de monter la voix, comme pour poser une question. Voici le texte : Ce matin, Lina part à l'école avec son frère Tom. Il pleut, alors ils prennent le grand parapluie. En chemin, ils croisent le chat de la voisine. Est-ce qu'il a peur de la pluie ? Non, il dort tranquillement sous le banc. Lina rit, puis elle court jusqu'à la grille.",
  minutes: 6,
  exercises: [
    {
      id: 'francais-lire-ponctuation-tap-1',
      kind: 'tapword',
      prompt: 'Touche le mot après lequel on fait une petite pause',
      words: ['Ce', 'matin,', 'Lina', 'part', 'à', "l'école", 'avec', 'son', 'frère', 'Tom.'],
      answer: [1],
      explain: 'Après « matin », il y a une virgule : on respire un petit coup avant de continuer.',
    },
    {
      id: 'francais-lire-ponctuation-tap-2',
      kind: 'tapword',
      prompt: "Touche le mot après lequel on s'arrête complètement",
      words: ['Il', 'pleut,', 'alors', 'ils', 'prennent', 'le', 'grand', 'parapluie.'],
      answer: [7],
      explain: "Après « parapluie », il y a un point : la phrase est finie, on s'arrête bien.",
    },
    {
      id: 'francais-lire-ponctuation-tf-1',
      kind: 'truefalse',
      statement: "Après une virgule, on s'arrête aussi longtemps qu'après un point.",
      answer: false,
      explain: "Pas grave. La virgule, c'est une petite pause ; le point, c'est un vrai arrêt.",
    },
    {
      id: 'francais-lire-ponctuation-choice-1',
      kind: 'choice',
      prompt: 'Comment lit-on « Est-ce qu\'il a peur de la pluie ? »',
      options: ['Sans changer de voix', 'En montant la voix à la fin, comme une question', 'En criant très fort'],
      answer: 1,
      explain: "Le point d'interrogation pose une question : la voix monte un peu à la fin.",
    },
    {
      id: 'francais-lire-ponctuation-order-1',
      kind: 'order',
      prompt: "Remets les phrases du texte dans l'ordre",
      lines: [
        "Ce matin, Lina part à l'école avec son frère Tom.",
        'Il pleut, alors ils prennent le grand parapluie.',
        'En chemin, ils croisent le chat de la voisine.',
        "Est-ce qu'il a peur de la pluie ?",
      ],
      explain: "D'abord ils partent, puis il pleut, puis ils croisent le chat, et on se demande s'il a peur.",
    },
    {
      id: 'francais-lire-ponctuation-tap-3',
      kind: 'tapword',
      prompt: 'Touche tous les mots après lesquels on fait une pause',
      words: ['En', 'chemin,', 'ils', 'croisent', 'le', 'chat', 'de', 'la', 'voisine.'],
      answer: [1, 8],
      explain: 'Une petite pause après la virgule de « chemin », un arrêt après le point de « voisine ».',
    },
    {
      id: 'francais-lire-ponctuation-sentence-1',
      kind: 'sentence',
      prompt: "Remets les mots de la dernière phrase dans l'ordre",
      words: ['Lina', 'rit,', 'puis', 'elle', 'court', "jusqu'à", 'la', 'grille.'],
      explain: 'La phrase commence par une majuscule, « Lina », et finit par le mot qui porte le point.',
    },
    {
      id: 'francais-lire-ponctuation-tf-2',
      kind: 'truefalse',
      statement: "Quand une phrase finit par un point d'interrogation, elle pose une question.",
      answer: true,
      explain: "C'est bien ça : le point d'interrogation est le signe des questions.",
    },
    {
      id: 'francais-lire-ponctuation-choice-2',
      kind: 'choice',
      prompt: 'Quel signe termine la phrase « Non, il dort tranquillement sous le banc » ?',
      options: ["Le point d'interrogation", 'La virgule', 'Le point'],
      answer: 2,
      explain: "Cette phrase raconte quelque chose, elle ne pose pas de question : elle finit par un point.",
    },
  ],
};

const COMPRENDRE_TEXTE: Lesson = {
  id: 'francais-comprendre-texte',
  title: 'Comprendre une histoire',
  subject: 'francais',
  source: 'lecture',
  level: 'CE1',
  notion: 'Comprendre une petite histoire : les personnages, le lieu, l\'ordre des événements',
  theme: 'lecture',
  attendu: 'Comprendre un texte lu seul : personnages, lieux, ordre des événements.',
  attenduId: 'ce1-lect-comprendre',
  summary:
    "Lis bien l'histoire, puis réponds aux questions. Samedi, Noé et sa grand-mère vont au marché. Noé porte le panier. Ils achètent des pommes, du pain et un gros bouquet de fleurs. Soudain, Noé ne voit plus sa grand-mère ! Il cherche partout, puis il entend sa voix près du marchand de fromage. Elle lui achète un petit morceau pour le rassurer. Ils rentrent à la maison en chantant.",
  minutes: 6,
  exercises: [
    {
      id: 'francais-comprendre-texte-choice-1',
      kind: 'choice',
      prompt: 'Qui va au marché avec Noé ?',
      options: ['Son grand-père', 'Sa grand-mère', 'Sa grande sœur'],
      answer: 1,
      explain: "Relis le début : « Noé et sa grand-mère vont au marché ».",
    },
    {
      id: 'francais-comprendre-texte-tap-1',
      kind: 'tapword',
      prompt: "Touche le mot qui dit quand se passe l'histoire",
      words: ['Samedi,', 'Noé', 'et', 'sa', 'grand-mère', 'vont', 'au', 'marché.'],
      answer: [0],
      explain: "C'est « samedi » qui dit le moment. Le mot qui dit l'endroit, c'est « marché ».",
    },
    {
      id: 'francais-comprendre-texte-tf-1',
      kind: 'truefalse',
      statement: "C'est Noé qui porte le panier.",
      answer: true,
      explain: 'Oui, le texte dit « Noé porte le panier ».',
    },
    {
      id: 'francais-comprendre-texte-choice-2',
      kind: 'choice',
      prompt: "Où se passe l'histoire ?",
      options: ["À l'école", 'À la piscine', 'Au marché'],
      answer: 2,
      explain: 'Ils vont au marché, là où on achète des pommes, du pain et du fromage.',
    },
    {
      id: 'francais-comprendre-texte-tf-2',
      kind: 'truefalse',
      statement: 'Noé et sa grand-mère achètent des bananes.',
      answer: false,
      explain: 'Pas grave. Ils achètent des pommes, du pain et des fleurs, mais pas de bananes.',
    },
    {
      id: 'francais-comprendre-texte-sort-1',
      kind: 'sort',
      prompt: 'Range : acheté au marché, ou pas acheté',
      boxes: ['Acheté au marché', 'Pas acheté'],
      items: [
        { word: 'des pommes', box: 0 },
        { word: 'des bonbons', box: 1 },
        { word: 'du pain', box: 0 },
        { word: 'des chaussures', box: 1 },
        { word: 'des fleurs', box: 0 },
        { word: 'du fromage', box: 0 },
      ],
      explain: 'Pommes, pain, fleurs, et à la fin un petit morceau de fromage. Rien d\'autre.',
    },
    {
      id: 'francais-comprendre-texte-order-1',
      kind: 'order',
      prompt: "Remets les événements dans l'ordre de l'histoire",
      lines: [
        'Noé et sa grand-mère arrivent au marché.',
        'Ils achètent des pommes, du pain et des fleurs.',
        'Noé ne voit plus sa grand-mère.',
        'Il la retrouve près du marchand de fromage.',
      ],
      explain: "D'abord les courses, ensuite Noé perd sa grand-mère, et enfin il la retrouve.",
    },
    {
      id: 'francais-comprendre-texte-choice-3',
      kind: 'choice',
      prompt: 'Pourquoi la grand-mère achète-t-elle un morceau de fromage ?',
      options: ['Pour rassurer Noé', "Parce que c'est l'anniversaire de Noé", 'Pour le donner au chat'],
      answer: 0,
      explain: "Noé a eu peur de l'avoir perdue, alors elle lui offre un petit morceau pour le rassurer.",
    },
    {
      id: 'francais-comprendre-texte-tf-3',
      kind: 'truefalse',
      statement: 'À la fin, ils rentrent à la maison en pleurant.',
      answer: false,
      explain: 'Non, tout finit bien : ils rentrent à la maison en chantant.',
    },
  ],
};

const CORBEAU_RENARD: Lesson = {
  id: 'francais-corbeau-renard',
  title: 'Le Corbeau et le Renard',
  subject: 'francais',
  source: 'poesie',
  level: 'CE1',
  notion: 'Mémoriser et réciter une fable',
  theme: 'poesie',
  attendu: 'Mémoriser et réciter un poème ou un texte court avec expression.',
  attenduId: 'ce1-oral-memoriser',
  summary:
    "Une fable de Jean de La Fontaine. Le renard fait des compliments au corbeau pour qu'il chante et laisse tomber son fromage. Apprends-la par morceaux de quatre vers.",
  minutes: 8,
  exercises: [
    {
      id: 'francais-corbeau-renard-order-1',
      kind: 'order',
      prompt: "Remets les quatre premiers vers dans l'ordre",
      lines: [
        'Maître Corbeau, sur un arbre perché,',
        'Tenait en son bec un fromage.',
        "Maître Renard, par l'odeur alléché,",
        'Lui tint à peu près ce langage :',
      ],
      explain: "D'abord le corbeau et son fromage, puis le renard qui arrive, attiré par l'odeur.",
    },
    {
      id: 'francais-corbeau-renard-blanks-1',
      kind: 'blanks',
      prompt: 'Complète les vers',
      text: 'Maître Corbeau, sur un arbre {{perché}},\nTenait en son bec un {{fromage}}.',
      distractors: ['caché', 'gâteau'],
      explain: 'Le corbeau est perché sur un arbre, et il tient un fromage dans son bec.',
    },
    {
      id: 'francais-corbeau-renard-choice-1',
      kind: 'choice',
      prompt: 'Quel mot rime avec « perché » ?',
      options: ['fromage', 'alléché', 'langage'],
      answer: 1,
      explain: 'Perché et alléché finissent tous les deux par le son « é ».',
    },
    {
      id: 'francais-corbeau-renard-order-2',
      kind: 'order',
      prompt: "Remets les vers 5 à 8 dans l'ordre",
      lines: [
        '« Hé ! bonjour, Monsieur du Corbeau.',
        'Que vous êtes joli ! que vous me semblez beau !',
        'Sans mentir, si votre ramage',
        'Se rapporte à votre plumage,',
      ],
      explain: 'Le renard dit bonjour, puis il fait des compliments : joli, beau, et ensuite le ramage et le plumage.',
    },
    {
      id: 'francais-corbeau-renard-flashcard-1',
      kind: 'flashcard',
      prompt: 'Récite le vers suivant, puis retourne la carte pour vérifier',
      front: "Maître Renard, par l'odeur alléché,",
      back: 'Lui tint à peu près ce langage :',
      explain: 'Le renard « tient un langage », ça veut dire qu\'il parle au corbeau.',
    },
    {
      id: 'francais-corbeau-renard-choice-2',
      kind: 'choice',
      prompt: 'Quel mot rime avec « ramage » ?',
      options: ['beau', 'plumage', 'bois'],
      answer: 1,
      explain: 'Ramage et plumage finissent par « age ». Le ramage, c\'est le chant de l\'oiseau ; le plumage, ce sont ses plumes.',
    },
    {
      id: 'francais-corbeau-renard-order-3',
      kind: 'order',
      prompt: "Remets les vers 9 à 12 dans l'ordre",
      lines: [
        'Vous êtes le Phénix des hôtes de ces bois. »',
        'À ces mots le Corbeau ne se sent pas de joie ;',
        'Et pour montrer sa belle voix,',
        'Il ouvre un large bec, laisse tomber sa proie.',
      ],
      explain: 'Le renard finit son compliment, le corbeau est fou de joie, il ouvre le bec et le fromage tombe.',
    },
    {
      id: 'francais-corbeau-renard-blanks-2',
      kind: 'blanks',
      prompt: 'Complète les vers',
      text: 'À ces mots le Corbeau ne se sent pas de {{joie}} ;\nEt pour montrer sa belle {{voix}},\nIl ouvre un large {{bec}}, laisse tomber sa proie.',
      distractors: ['peur', 'queue'],
      explain: "Le corbeau est tellement content qu'il veut chanter : il ouvre le bec et perd son fromage.",
    },
    {
      id: 'francais-corbeau-renard-tf-1',
      kind: 'truefalse',
      statement: 'Le Renard veut vraiment écouter la belle voix du Corbeau.',
      answer: false,
      explain: 'Pas grave. Le renard fait semblant : ce qu\'il veut, c\'est le fromage.',
    },
    {
      id: 'francais-corbeau-renard-blanks-3',
      kind: 'blanks',
      prompt: 'Complète la fin de la fable',
      text: "Le Corbeau, honteux et {{confus}},\nJura, mais un peu tard, qu'on ne l'y prendrait {{plus}}.",
      distractors: ['content', 'jamais'],
      explain: 'Le corbeau a honte, et il promet qu\'on ne le trompera plus. Mais c\'est un peu tard !',
    },
  ],
};

const SONS_OU_ON_AN_IN: Lesson = {
  id: 'francais-sons-ou-on-an-in',
  title: 'Les sons ou, on, an, in',
  subject: 'francais',
  source: 'mots',
  level: 'CE1',
  notion: 'Écrire les sons ou, on, an/en, in/ain',
  theme: 'orthographe',
  attendu: 'Écrire correctement les sons complexes (ou, on, an, in, oi, eau, ch, gn...).',
  attenduId: 'ce1-ortho-sons',
  summary:
    "Le son « ou » s'écrit o-u comme dans poule. Le son « on » s'écrit o-n comme dans ballon. Le son « an » s'écrit a-n ou e-n comme dans maman et enfant. Le son « in » s'écrit i-n ou a-i-n comme dans lapin et pain.",
  minutes: 7,
  exercises: [
    {
      id: 'francais-sons-ou-on-an-in-sort-1',
      kind: 'sort',
      prompt: 'Dans quelle boîte va chaque mot ?',
      boxes: ['ou', 'on', 'an / en', 'in / ain'],
      items: [
        { word: 'poule', box: 0 },
        { word: 'ballon', box: 1 },
        { word: 'maman', box: 2 },
        { word: 'lapin', box: 3 },
        { word: 'route', box: 0 },
        { word: 'pont', box: 1 },
        { word: 'enfant', box: 2 },
        { word: 'matin', box: 3 },
      ],
      explain: 'Dis le mot tout doucement et écoute le son : pou-le, bal-lon, ma-man, la-pin.',
    },
    {
      id: 'francais-sons-ou-on-an-in-flash-1',
      kind: 'flash',
      word: 'mouton',
      distractors: ['mooton', 'mouten'],
      explain: 'Mou-ton : le son « ou » s\'écrit o-u, le son « on » s\'écrit o-n.',
    },
    {
      id: 'francais-sons-ou-on-an-in-scramble-1',
      kind: 'scramble',
      word: 'ballon',
      explain: 'Bal-lon : deux l au milieu, et le son « on » à la fin.',
    },
    {
      id: 'francais-sons-ou-on-an-in-choice-1',
      kind: 'choice',
      prompt: 'Comment s\'écrit le son « in » dans le mot « main » ?',
      options: ['i-n', 'e-n', 'a-i-n'],
      answer: 2,
      explain: 'Dans « main », le son « in » s\'écrit a-i-n, comme dans pain et train.',
    },
    {
      id: 'francais-sons-ou-on-an-in-dict-1',
      kind: 'dictation',
      word: 'lapin',
      sentence: 'Le lapin saute dans le jardin.',
      explain: 'Lapin : l-a-p-i-n, le son « in » s\'écrit i-n.',
    },
    {
      id: 'francais-sons-ou-on-an-in-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a fait une faute, corrige-le',
      words: ['Le', 'jardan', 'de', 'Papa', 'est', 'grand.'],
      wrongIndex: 1,
      correct: 'jardin',
      distractors: ['jardein', 'jarden'],
      explain: 'Jardin finit par le son « in », qui s\'écrit i-n. Dans « grand », c\'est le son « an ».',
    },
    {
      id: 'francais-sons-ou-on-an-in-flash-2',
      kind: 'flash',
      word: 'enfant',
      distractors: ['anfant', 'enfan'],
      explain: 'En-fant : le premier « an » s\'écrit e-n, le deuxième a-n, et un t muet à la fin.',
    },
    {
      id: 'francais-sons-ou-on-an-in-sort-2',
      kind: 'sort',
      prompt: 'Son « an » ou son « in » ?',
      boxes: ['an / en', 'in / ain'],
      items: [
        { word: 'dent', box: 0 },
        { word: 'pain', box: 1 },
        { word: 'vent', box: 0 },
        { word: 'train', box: 1 },
        { word: 'chambre', box: 0 },
        { word: 'sapin', box: 1 },
      ],
      explain: 'Dent, vent et chambre font « an ». Pain, train et sapin font « in ».',
    },
    {
      id: 'francais-sons-ou-on-an-in-dict-2',
      kind: 'dictation',
      word: 'maman',
      sentence: 'Maman chante une chanson.',
      explain: 'Maman : m-a-m-a-n, le son « an » s\'écrit a-n.',
    },
    {
      id: 'francais-sons-ou-on-an-in-fix-2',
      kind: 'fix',
      prompt: 'Gribouille a fait une faute, corrige-le',
      words: ['Je', 'mange', 'du', 'pin', 'avec', 'du', 'beurre.'],
      wrongIndex: 3,
      correct: 'pain',
      distractors: ['pein', 'pan'],
      explain: 'Le pain qu\'on mange s\'écrit p-a-i-n. Le pin avec un i tout seul, c\'est un arbre.',
    },
  ],
};

const SONS_OI_EAU_CH_GN: Lesson = {
  id: 'francais-sons-oi-eau-ch-gn',
  title: 'Les sons oi, eau, ch, gn, ph',
  subject: 'francais',
  source: 'mots',
  level: 'CE1',
  notion: 'Écrire les sons oi, eau/au, ch, gn, ph',
  theme: 'orthographe',
  attendu: 'Écrire correctement les sons complexes (ou, on, an, in, oi, eau, ch, gn...).',
  attenduId: 'ce1-ortho-sons',
  summary:
    "Le son « oi » s'écrit o-i comme dans roi. Le son « o » de bateau s'écrit e-a-u ou a-u. Le son « ch » comme dans chat, le son « gn » comme dans montagne, et le son « f » de photo qui s'écrit p-h.",
  minutes: 7,
  exercises: [
    {
      id: 'francais-sons-oi-eau-ch-gn-sort-1',
      kind: 'sort',
      prompt: 'Dans quelle boîte va chaque mot ?',
      boxes: ['oi', 'eau / au', 'ch', 'gn'],
      items: [
        { word: 'roi', box: 0 },
        { word: 'bateau', box: 1 },
        { word: 'chat', box: 2 },
        { word: 'montagne', box: 3 },
        { word: 'poire', box: 0 },
        { word: 'jaune', box: 1 },
        { word: 'vache', box: 2 },
        { word: 'ligne', box: 3 },
      ],
      explain: 'Dis le mot doucement : roi et poire font « oi », bateau et jaune font « o », chat et vache font « ch », montagne et ligne font « gn ».',
    },
    {
      id: 'francais-sons-oi-eau-ch-gn-scramble-1',
      kind: 'scramble',
      word: 'bateau',
      explain: 'Ba-teau : le son « o » de la fin s\'écrit e-a-u.',
    },
    {
      id: 'francais-sons-oi-eau-ch-gn-flash-1',
      kind: 'flash',
      word: 'montagne',
      distractors: ['montane', 'montagn'],
      explain: 'Mon-ta-gne : le son « gn » s\'écrit g-n, et il y a un e muet à la fin.',
    },
    {
      id: 'francais-sons-oi-eau-ch-gn-choice-1',
      kind: 'choice',
      prompt: 'Quelle est la bonne écriture ?',
      speak: 'éléphant',
      options: ['éléfant', 'éléphant', 'élefan'],
      answer: 1,
      explain: 'Dans éléphant, le son « f » s\'écrit p-h, comme dans photo et pharmacie.',
    },
    {
      id: 'francais-sons-oi-eau-ch-gn-dict-1',
      kind: 'dictation',
      word: 'chapeau',
      sentence: 'Il porte un grand chapeau.',
      explain: 'Cha-peau : c-h au début, e-a-u à la fin.',
    },
    {
      id: 'francais-sons-oi-eau-ch-gn-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a fait une faute, corrige-le',
      words: ['Mon', 'frère', 'compte', 'les', 'étouales', 'du', 'ciel.'],
      wrongIndex: 4,
      correct: 'étoiles',
      distractors: ['étoilles', 'étoales'],
      explain: 'É-toi-les : le son « oi » s\'écrit o-i, avec un seul l.',
    },
    {
      id: 'francais-sons-oi-eau-ch-gn-flash-2',
      kind: 'flash',
      word: 'oiseau',
      distractors: ['oizeau', 'oiso'],
      explain: 'Oi-seau : « oi » au début, « eau » à la fin. Deux sons compliqués dans un seul mot !',
    },
    {
      id: 'francais-sons-oi-eau-ch-gn-tf-1',
      kind: 'truefalse',
      statement: 'Dans le mot « photo », le son « f » s\'écrit p-h.',
      answer: true,
      explain: 'Oui : photo, phoque, éléphant, le son « f » s\'écrit p-h.',
    },
    {
      id: 'francais-sons-oi-eau-ch-gn-dict-2',
      kind: 'dictation',
      word: 'cheval',
      sentence: 'Le cheval galope dans le pré.',
      explain: 'Che-val : le son « ch » s\'écrit c-h.',
    },
    {
      id: 'francais-sons-oi-eau-ch-gn-pairs-1',
      kind: 'pairs',
      prompt: 'Associe chaque son à un mot où on l\'entend',
      pairs: [
        { a: 'oi', b: 'voiture' },
        { a: 'eau', b: 'gâteau' },
        { a: 'ch', b: 'chemin' },
        { a: 'gn', b: 'peigne' },
        { a: 'ph', b: 'phoque' },
      ],
      explain: 'Voi-ture, gâ-teau, che-min, pei-gne, phoque : chaque mot cache un des sons de la leçon.',
    },
  ],
};

const PLURIEL: Lesson = {
  id: 'francais-pluriel',
  title: 'Singulier et pluriel',
  subject: 'francais',
  source: 'lecon',
  level: 'CE1',
  notion: 'Écrire le pluriel du nom : s, x, et les déterminants le/les, un/des',
  theme: 'orthographe',
  attendu: 'Faire les accords dans le groupe nominal (le, la, les ; singulier, pluriel) et entre le sujet et le verbe.',
  attenduId: 'ce1-ortho-accords',
  summary:
    "Quand il y a un seul objet, c'est le singulier : un chat, le chat. Quand il y en a plusieurs, c'est le pluriel : des chats, les chats. Le plus souvent on ajoute un s. Pour les mots en eau et en eu, on ajoute un x : des bateaux, des jeux.",
  minutes: 7,
  exercises: [
    {
      id: 'francais-pluriel-sort-1',
      kind: 'sort',
      prompt: 'Un seul, ou plusieurs ?',
      boxes: ['Un seul (singulier)', 'Plusieurs (pluriel)'],
      items: [
        { word: 'le chat', box: 0 },
        { word: 'les chats', box: 1 },
        { word: 'des bateaux', box: 1 },
        { word: 'un jeu', box: 0 },
        { word: 'les jeux', box: 1 },
        { word: 'une fleur', box: 0 },
      ],
      explain: 'Regarde le petit mot devant : le, un, une pour un seul ; les, des pour plusieurs.',
    },
    {
      id: 'francais-pluriel-choice-1',
      kind: 'choice',
      prompt: 'Une fleur, des…',
      options: ['fleurx', 'fleurs', 'fleur'],
      answer: 1,
      explain: 'Le plus souvent, au pluriel on ajoute un s : des fleurs.',
    },
    {
      id: 'francais-pluriel-tap-1',
      kind: 'tapword',
      prompt: "Touche les deux mots qui montrent qu'il y a plusieurs chiens",
      words: ['Les', 'chiens', 'courent', 'dans', 'le', 'parc.'],
      answer: [0, 1],
      explain: '« Les » dit qu\'il y en a plusieurs, et « chiens » prend un s pour aller avec.',
    },
    {
      id: 'francais-pluriel-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a fait une faute, corrige-le',
      words: ['Je', 'range', 'mes', 'jouet', 'dans', 'le', 'coffre.'],
      wrongIndex: 3,
      correct: 'jouets',
      distractors: ['jouetx', 'joués'],
      explain: '« Mes » dit qu\'il y a plusieurs jouets : il faut un s à jouets.',
    },
    {
      id: 'francais-pluriel-blanks-1',
      kind: 'blanks',
      prompt: 'Complète avec le ou les',
      text: '{{Les}} enfants jouent. {{Le}} chat dort. {{Les}} oiseaux chantent.',
      distractors: ['Un'],
      explain: 'Enfants et oiseaux ont un s : ils sont plusieurs, on écrit « les ». Chat est tout seul : « le ».',
    },
    {
      id: 'francais-pluriel-tf-1',
      kind: 'truefalse',
      statement: 'Au pluriel, « un jeu » devient « des jeux ».',
      answer: true,
      explain: 'Oui, les mots en « eu » prennent un x au pluriel : des jeux, des cheveux.',
    },
    {
      id: 'francais-pluriel-choice-2',
      kind: 'choice',
      prompt: 'Un bateau, des…',
      options: ['bateaus', 'bateau', 'bateaux'],
      answer: 2,
      explain: 'Les mots en « eau » prennent un x au pluriel : des bateaux, des gâteaux.',
    },
    {
      id: 'francais-pluriel-fix-2',
      kind: 'fix',
      prompt: 'Gribouille a fait une faute, corrige-le',
      words: ['Il', 'y', 'a', 'des', 'gâteau', 'sur', 'la', 'table.'],
      wrongIndex: 4,
      correct: 'gâteaux',
      distractors: ['gâteaus', 'gâteau'],
      explain: '« Des » dit qu\'il y a plusieurs gâteaux, et gâteau finit par « eau » : on ajoute un x.',
    },
    {
      id: 'francais-pluriel-dict-1',
      kind: 'dictation',
      word: 'bateaux',
      sentence: "Les bateaux flottent sur l'eau.",
      explain: 'Bateaux : b-a-t-e-a-u-x, avec un x à la fin parce qu\'il y en a plusieurs.',
    },
    {
      id: 'francais-pluriel-sentence-1',
      kind: 'sentence',
      prompt: "Remets les mots dans l'ordre",
      words: ['Les', 'enfants', 'mangent', 'des', 'pommes.'],
      explain: '« Les » va avec « enfants », « des » va avec « pommes » : tout est au pluriel.',
    },
  ],
};

const ACCORD_SUJET_VERBE: Lesson = {
  id: 'francais-accord-sujet-verbe',
  title: "L'accord du verbe avec le sujet",
  subject: 'francais',
  source: 'grammaire',
  level: 'CE1',
  notion: 'Accorder le verbe avec son sujet : il chante, ils chantent',
  theme: 'orthographe',
  attendu: 'Faire les accords dans le groupe nominal (le, la, les ; singulier, pluriel) et entre le sujet et le verbe.',
  attenduId: 'ce1-ortho-accords',
  summary:
    "Le verbe s'accorde avec son sujet. Quand le sujet est une seule personne, le verbe finit par e : il chante, elle chante. Quand ils sont plusieurs, le verbe finit par ent : ils chantent, les enfants chantent. Le « ent » ne s'entend pas, mais il s'écrit.",
  minutes: 6,
  exercises: [
    {
      id: 'francais-accord-sujet-verbe-choice-1',
      kind: 'choice',
      prompt: 'Il … dans la cour.',
      options: ['jouent', 'joue', 'joues'],
      answer: 1,
      explain: '« Il » est tout seul : le verbe finit par e, il joue.',
    },
    {
      id: 'francais-accord-sujet-verbe-tap-1',
      kind: 'tapword',
      prompt: 'Touche le verbe qui va avec « elles »',
      words: ['Elles', 'chantent', 'une', 'jolie', 'chanson.'],
      answer: [1],
      explain: '« Elles » sont plusieurs, alors le verbe chantent finit par ent.',
    },
    {
      id: 'francais-accord-sujet-verbe-tf-1',
      kind: 'truefalse',
      statement: 'Quand le sujet est « ils », le verbe finit par ent.',
      answer: true,
      explain: 'Oui : ils mangent, ils jouent, ils regardent. On n\'entend pas le ent, mais on l\'écrit.',
    },
    {
      id: 'francais-accord-sujet-verbe-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a fait une faute, corrige-le',
      words: ['Les', 'enfants', 'mange', 'à', 'la', 'cantine.'],
      wrongIndex: 2,
      correct: 'mangent',
      distractors: ['manges', 'mangeons'],
      explain: 'Qui est-ce qui mange ? Les enfants, ils sont plusieurs : mangent avec ent.',
    },
    {
      id: 'francais-accord-sujet-verbe-blanks-1',
      kind: 'blanks',
      prompt: 'Complète avec la bonne forme du verbe',
      text: 'Elle {{regarde}} la télé. Ils {{regardent}} un film.',
      distractors: ['regardes'],
      explain: 'Elle est seule, regarde avec e. Ils sont plusieurs, regardent avec ent.',
    },
    {
      id: 'francais-accord-sujet-verbe-choice-2',
      kind: 'choice',
      prompt: 'Quelle phrase est bien écrite ?',
      options: ['Les chats dort.', 'Le chat dorment.', 'Les chats dorment.'],
      answer: 2,
      explain: 'Les chats sont plusieurs, alors le verbe prend la marque du pluriel : dorment.',
    },
    {
      id: 'francais-accord-sujet-verbe-tap-2',
      kind: 'tapword',
      prompt: 'Touche le sujet du verbe « arrivent »',
      words: ['Les', 'invités', 'arrivent', 'à', 'midi.'],
      answer: [0, 1],
      explain: 'Qui est-ce qui arrive ? Les invités. Ils sont plusieurs, donc arrivent finit par ent.',
    },
    {
      id: 'francais-accord-sujet-verbe-fix-2',
      kind: 'fix',
      prompt: 'Gribouille a fait une faute, corrige-le',
      words: ['Mon', 'frère', 'et', 'ma', 'sœur', 'joue', 'au', 'ballon.'],
      wrongIndex: 5,
      correct: 'jouent',
      distractors: ['joues', 'joue'],
      explain: 'Mon frère et ma sœur, ça fait deux personnes : le verbe se met au pluriel, jouent.',
    },
    {
      id: 'francais-accord-sujet-verbe-blanks-2',
      kind: 'blanks',
      prompt: 'Complète avec la bonne forme du verbe',
      text: 'Le chien {{aboie}}. Les chiens {{aboient}}.',
      distractors: ['aboies'],
      explain: 'Un chien, aboie. Plusieurs chiens, aboient : on ajoute nt.',
    },
  ],
};

const MOTS_INVARIABLES: Lesson = {
  id: 'francais-mots-invariables',
  title: 'Les mots invariables',
  subject: 'francais',
  source: 'mots',
  level: 'CE1',
  notion: 'Orthographier douze mots invariables fréquents',
  theme: 'orthographe',
  attendu: 'Orthographier les mots fréquents et les mots invariables appris.',
  attenduId: 'ce1-ortho-mots',
  summary:
    "Les mots invariables s'écrivent toujours pareil, ils ne changent jamais. Douze mots à savoir par cœur : toujours, jamais, beaucoup, aussi, avec, dans, pour, mais, puis, alors, très, chez.",
  minutes: 7,
  exercises: [
    {
      id: 'francais-mots-invariables-flash-1',
      kind: 'flash',
      word: 'toujours',
      distractors: ['toujour', 'toujoure'],
      explain: 'Toujours finit toujours par un s, même si on ne l\'entend pas.',
    },
    {
      id: 'francais-mots-invariables-scramble-1',
      kind: 'scramble',
      word: 'beaucoup',
      explain: 'Beau-coup : « beau » comme un beau jour, puis « coup » avec un p muet.',
    },
    {
      id: 'francais-mots-invariables-flash-2',
      kind: 'flash',
      word: 'jamais',
      distractors: ['jamai', 'jammais'],
      explain: 'Jamais : un seul m, et un s à la fin qu\'on n\'entend pas.',
    },
    {
      id: 'francais-mots-invariables-dict-1',
      kind: 'dictation',
      word: 'aussi',
      sentence: 'Moi aussi, je veux jouer.',
      explain: 'Aussi : a-u-s-s-i, avec deux s au milieu.',
    },
    {
      id: 'francais-mots-invariables-blanks-1',
      kind: 'blanks',
      prompt: 'Complète avec les mots invariables',
      text: 'Je joue {{avec}} mon frère {{dans}} le jardin, {{puis}} nous rentrons.',
      distractors: ['pour', 'chez'],
      explain: 'On joue avec quelqu\'un, dans un endroit, puis on fait autre chose.',
    },
    {
      id: 'francais-mots-invariables-scramble-2',
      kind: 'scramble',
      word: 'alors',
      explain: 'A-lors : le s de la fin ne s\'entend pas, mais il est bien là.',
    },
    {
      id: 'francais-mots-invariables-flash-3',
      kind: 'flash',
      word: 'très',
      distractors: ['trés', 'trais'],
      explain: 'Très : un accent grave sur le e, et un s muet à la fin.',
    },
    {
      id: 'francais-mots-invariables-dict-2',
      kind: 'dictation',
      word: 'puis',
      sentence: 'Je mange, puis je me brosse les dents.',
      explain: 'Puis : p-u-i-s, avec un s muet à la fin.',
    },
    {
      id: 'francais-mots-invariables-blanks-2',
      kind: 'blanks',
      prompt: 'Complète avec les mots invariables',
      text: 'Il pleut, {{mais}} je sors quand même. Je vais {{chez}} ma mamie {{pour}} goûter.',
      distractors: ['très', 'alors'],
      explain: '« Mais » montre que c\'est contraire, « chez » dit chez qui on va, « pour » dit pourquoi.',
    },
    {
      id: 'francais-mots-invariables-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a fait une faute, corrige-le',
      words: ['Je', 'mange', 'beaucou', 'de', 'fraises.'],
      wrongIndex: 2,
      correct: 'beaucoup',
      distractors: ['bocoup', 'beaucou'],
      explain: 'Beaucoup finit par un p muet : b-e-a-u-c-o-u-p.',
    },
  ],
};

const LA_PHRASE: Lesson = {
  id: 'francais-la-phrase',
  title: 'La phrase',
  subject: 'francais',
  source: 'grammaire',
  level: 'CE1',
  notion: 'Reconnaître une phrase et ses formes : affirmative, négative, interrogative',
  theme: 'grammaire',
  attendu: 'Reconnaître la phrase, sa ponctuation, et les formes affirmative, négative, interrogative.',
  attenduId: 'ce1-gram-phrase',
  summary:
    "Une phrase commence par une majuscule, finit par un point et veut dire quelque chose. Une phrase négative dit non avec « ne… pas » : je ne joue pas. Une phrase interrogative pose une question et finit par un point d'interrogation.",
  minutes: 7,
  exercises: [
    {
      id: 'francais-la-phrase-tf-1',
      kind: 'truefalse',
      statement: 'Une phrase commence par une majuscule et finit par un point.',
      answer: true,
      explain: 'Oui, c\'est la règle de la phrase : une majuscule au début, un point à la fin.',
    },
    {
      id: 'francais-la-phrase-choice-1',
      kind: 'choice',
      prompt: 'Laquelle est une vraie phrase ?',
      options: ['le chat sur dort tapis', 'Le chat dort sur le tapis.', 'chat le dort'],
      answer: 1,
      explain: 'Une phrase a une majuscule, un point, et les mots dans un ordre qui veut dire quelque chose.',
    },
    {
      id: 'francais-la-phrase-sort-1',
      kind: 'sort',
      prompt: 'Phrase, ou pas phrase ?',
      boxes: ['Phrase', 'Pas une phrase'],
      items: [
        { word: "Il fait beau aujourd'hui.", box: 0 },
        { word: 'mange la pomme Léa', box: 1 },
        { word: 'Nous allons à la plage.', box: 0 },
        { word: 'avec vite le', box: 1 },
      ],
      explain: 'Pour être une phrase, il faut une majuscule, un point, et que ça veuille dire quelque chose.',
    },
    {
      id: 'francais-la-phrase-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a oublié quelque chose, corrige-le',
      words: ['le', 'soleil', 'brille', 'ce', 'matin.'],
      wrongIndex: 0,
      correct: 'Le',
      distractors: ['Les', 'La'],
      explain: 'Le premier mot d\'une phrase prend une majuscule : Le soleil brille.',
    },
    {
      id: 'francais-la-phrase-tap-1',
      kind: 'tapword',
      prompt: 'Touche les deux petits mots qui disent non',
      words: ['Tom', 'ne', 'mange', 'pas', 'de', 'légumes.'],
      answer: [1, 3],
      explain: '« Ne » et « pas » entourent le verbe : c\'est la phrase négative.',
    },
    {
      id: 'francais-la-phrase-sort-2',
      kind: 'sort',
      prompt: 'Phrase affirmative, ou phrase négative ?',
      boxes: ['Affirmative (oui)', 'Négative (non)'],
      items: [
        { word: 'Je range ma chambre.', box: 0 },
        { word: 'Je ne range pas ma chambre.', box: 1 },
        { word: "Il n'aime pas le froid.", box: 1 },
        { word: 'Elle chante bien.', box: 0 },
      ],
      explain: 'Cherche « ne… pas » ou « n\'… pas » : si tu les trouves, la phrase est négative.',
    },
    {
      id: 'francais-la-phrase-sentence-1',
      kind: 'sentence',
      prompt: "Remets la phrase négative dans l'ordre",
      words: ['Nous', 'ne', 'sortons', 'pas', 'ce', 'soir.'],
      explain: '« Ne » se place avant le verbe, « pas » juste après : nous ne sortons pas.',
    },
    {
      id: 'francais-la-phrase-choice-2',
      kind: 'choice',
      prompt: 'Quelle phrase pose une question ?',
      options: ['Il pleut fort.', "Est-ce qu'il pleut ?", 'Il pleut !'],
      answer: 1,
      explain: 'La phrase interrogative pose une question et finit par un point d\'interrogation.',
    },
    {
      id: 'francais-la-phrase-blanks-1',
      kind: 'blanks',
      prompt: 'Complète la phrase négative',
      text: 'Léa {{ne}} veut {{pas}} dormir.',
      distractors: ['non', 'rien'],
      explain: 'Pour dire non, on met « ne » avant le verbe et « pas » après.',
    },
    {
      id: 'francais-la-phrase-tf-2',
      kind: 'truefalse',
      statement: '« Tu viens avec moi ? » est une phrase interrogative.',
      answer: true,
      explain: 'Oui, elle pose une question et finit par un point d\'interrogation.',
    },
  ],
};

const NOM_DETERMINANT: Lesson = {
  id: 'francais-nom-determinant',
  title: 'Le nom, le déterminant, l\'adjectif, le pronom',
  subject: 'francais',
  source: 'grammaire',
  level: 'CE1',
  notion: 'Reconnaître le nom, le déterminant, l\'adjectif et le pronom',
  theme: 'grammaire',
  attendu: "Reconnaître le nom, le déterminant, l'adjectif et le pronom.",
  attenduId: 'ce1-gram-nom',
  summary:
    "Le nom désigne une personne, un animal ou une chose : chat, table, maman. Le déterminant est le petit mot devant le nom : le, la, un, des, mon. L'adjectif dit comment est le nom : un gros chat. Le pronom remplace le nom : il, elle, nous, ils.",
  minutes: 7,
  exercises: [
    {
      id: 'francais-nom-determinant-tap-1',
      kind: 'tapword',
      prompt: 'Touche le nom',
      words: ['La', 'voiture', 'roule', 'vite.'],
      answer: [1],
      explain: 'La voiture est une chose : c\'est le nom. « La » est son déterminant.',
    },
    {
      id: 'francais-nom-determinant-tap-2',
      kind: 'tapword',
      prompt: 'Touche le déterminant',
      words: ['Mon', 'chien', 'aboie', 'fort.'],
      answer: [0],
      explain: 'Le déterminant est le petit mot juste devant le nom : mon chien.',
    },
    {
      id: 'francais-nom-determinant-choice-1',
      kind: 'choice',
      prompt: "Dans « le gros chien », quel mot est l'adjectif ?",
      options: ['le', 'chien', 'gros'],
      answer: 2,
      explain: 'L\'adjectif dit comment est le chien : il est gros.',
    },
    {
      id: 'francais-nom-determinant-sort-1',
      kind: 'sort',
      prompt: 'Range chaque mot dans sa boîte',
      boxes: ['Nom', 'Déterminant', 'Adjectif', 'Pronom'],
      items: [
        { word: 'table', box: 0 },
        { word: 'les', box: 1 },
        { word: 'petit', box: 2 },
        { word: 'elle', box: 3 },
        { word: 'jardin', box: 0 },
        { word: 'une', box: 1 },
        { word: 'rouge', box: 2 },
        { word: 'nous', box: 3 },
      ],
      explain: 'Table et jardin sont des choses. Les et une vont devant un nom. Petit et rouge disent comment c\'est. Elle et nous remplacent des personnes.',
    },
    {
      id: 'francais-nom-determinant-tap-3',
      kind: 'tapword',
      prompt: 'Touche le pronom',
      words: ['Demain,', 'nous', 'irons', 'au', 'parc.'],
      answer: [1],
      explain: '« Nous », c\'est un pronom : il remplace les personnes qui vont au parc.',
    },
    {
      id: 'francais-nom-determinant-tf-1',
      kind: 'truefalse',
      statement: 'Dans « une jolie fleur », le mot « jolie » est un nom.',
      answer: false,
      explain: 'Pas grave. « Jolie » dit comment est la fleur : c\'est un adjectif. Le nom, c\'est « fleur ».',
    },
    {
      id: 'francais-nom-determinant-tap-4',
      kind: 'tapword',
      prompt: 'Touche les deux noms',
      words: ['Le', 'chat', 'dort', 'sur', 'le', 'lit.'],
      answer: [1, 5],
      explain: 'Le chat est un animal, le lit est une chose : ce sont les deux noms.',
    },
    {
      id: 'francais-nom-determinant-pairs-1',
      kind: 'pairs',
      prompt: 'Associe chaque mot à ce qu\'il est',
      pairs: [
        { a: 'maison', b: 'nom' },
        { a: 'des', b: 'déterminant' },
        { a: 'grand', b: 'adjectif' },
        { a: 'il', b: 'pronom' },
      ],
      explain: 'Maison est une chose, « des » va devant un nom, « grand » dit comment c\'est, « il » remplace quelqu\'un.',
    },
    {
      id: 'francais-nom-determinant-choice-2',
      kind: 'choice',
      prompt: 'Par quel pronom peut-on remplacer « Marie » dans « Marie chante » ?',
      options: ['Il', 'Nous', 'Elle'],
      answer: 2,
      explain: 'Marie est une fille, une seule personne : on la remplace par « elle ».',
    },
  ],
};

const PRESENT_ER: Lesson = {
  id: 'francais-present-er',
  title: 'Le présent des verbes en -er',
  subject: 'francais',
  source: 'lecon',
  level: 'CE1',
  notion: 'Conjuguer au présent les verbes en -er à toutes les personnes',
  theme: 'conjugaison',
  attendu: 'Conjuguer au présent les verbes en -er, être, avoir, aller, faire, dire, venir.',
  attenduId: 'ce1-conj-present',
  summary:
    "Au présent, les verbes en -er comme chanter changent de terminaison : je chante, tu chantes, il chante, nous chantons, vous chantez, ils chantent. Attention à « nous mangeons », avec un e pour garder le son « j ».",
  minutes: 7,
  exercises: [
    {
      id: 'francais-present-er-choice-1',
      kind: 'choice',
      prompt: 'Je … une chanson.',
      options: ['chantes', 'chante', 'chantent'],
      answer: 1,
      explain: 'Avec « je », le verbe finit par e : je chante.',
    },
    {
      id: 'francais-present-er-blanks-1',
      kind: 'blanks',
      prompt: 'Complète avec la bonne forme du verbe jouer',
      text: 'Tu {{joues}} au ballon. Nous {{jouons}} ensemble.',
      distractors: ['joue', 'jouer'],
      explain: 'Tu, c\'est es : tu joues. Nous, c\'est ons : nous jouons.',
    },
    {
      id: 'francais-present-er-match-1',
      kind: 'match',
      prompt: 'Relie chaque pronom à sa forme du verbe manger',
      pairs: [
        { a: 'je', b: 'mange' },
        { a: 'tu', b: 'manges' },
        { a: 'nous', b: 'mangeons' },
        { a: 'vous', b: 'mangez' },
        { a: 'ils', b: 'mangent' },
      ],
      seconds: 40,
      explain: 'e, es, e, eons, ez, ent : c\'est la chanson des verbes en -er.',
    },
    {
      id: 'francais-present-er-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a fait une faute, corrige-le',
      words: ['Vous', 'jouer', 'dans', 'la', 'cour.'],
      wrongIndex: 1,
      correct: 'jouez',
      distractors: ['jouons', 'joues'],
      explain: 'Avec « vous », le verbe finit par ez : vous jouez.',
    },
    {
      id: 'francais-present-er-tf-1',
      kind: 'truefalse',
      statement: 'Avec « tu », le verbe chanter finit par es : tu chantes.',
      answer: true,
      explain: 'Oui, « tu » prend toujours un s à la fin du verbe : tu chantes, tu joues.',
    },
    {
      id: 'francais-present-er-choice-2',
      kind: 'choice',
      prompt: 'Quelle forme est bien écrite ?',
      options: ['nous mangons', 'nous mangeon', 'nous mangeons'],
      answer: 2,
      explain: 'On garde un e après le g pour faire le son « j » : nous mangeons.',
    },
    {
      id: 'francais-present-er-tap-1',
      kind: 'tapword',
      prompt: 'Touche le verbe conjugué avec « ils »',
      words: ['Le', 'soir,', 'ils', 'regardent', 'les', 'étoiles.'],
      answer: [3],
      explain: 'Ils regardent : avec « ils », le verbe finit par ent.',
    },
    {
      id: 'francais-present-er-blanks-2',
      kind: 'blanks',
      prompt: 'Complète avec la bonne forme du verbe chanter',
      text: 'Je {{chante}} sous la douche. Elles {{chantent}} à la chorale.',
      distractors: ['chantes', 'chantons'],
      explain: 'Je chante avec e, elles chantent avec ent.',
    },
    {
      id: 'francais-present-er-dict-1',
      kind: 'dictation',
      word: 'jouons',
      sentence: 'Nous jouons aux cartes.',
      explain: 'Jouons : j-o-u-o-n-s, la terminaison de « nous » est ons.',
    },
  ],
};

const PRESENT_ETRE_AVOIR: Lesson = {
  id: 'francais-present-etre-avoir',
  title: 'Le présent de être, avoir, aller, faire, dire, venir',
  subject: 'francais',
  source: 'lecon',
  level: 'CE1',
  notion: 'Conjuguer au présent être, avoir, aller, faire, dire, venir',
  theme: 'conjugaison',
  attendu: 'Conjuguer au présent les verbes en -er, être, avoir, aller, faire, dire, venir.',
  attenduId: 'ce1-conj-present',
  summary:
    "Ces verbes ne suivent pas la règle des verbes en -er, il faut les apprendre par cœur. Être : je suis, tu es, il est, nous sommes, vous êtes, ils sont. Avoir : j'ai, tu as, il a, nous avons, vous avez, ils ont. Aller : je vais, nous allons, ils vont.",
  minutes: 8,
  exercises: [
    {
      id: 'francais-present-etre-avoir-blanks-1',
      kind: 'blanks',
      prompt: 'Complète avec le verbe être',
      text: 'Je {{suis}} content. Tu {{es}} mon ami.',
      distractors: ['est', 'sommes'],
      explain: 'Je suis, tu es : le verbe être change beaucoup selon la personne.',
    },
    {
      id: 'francais-present-etre-avoir-choice-1',
      kind: 'choice',
      prompt: 'Nous … faim.',
      options: ['avons', 'avez', 'ont'],
      answer: 0,
      explain: 'Avec « nous », le verbe avoir donne avons : nous avons faim.',
    },
    {
      id: 'francais-present-etre-avoir-pairs-1',
      kind: 'pairs',
      prompt: 'Associe chaque pronom à sa forme du verbe être',
      pairs: [
        { a: 'je', b: 'suis' },
        { a: 'il', b: 'est' },
        { a: 'nous', b: 'sommes' },
        { a: 'vous', b: 'êtes' },
        { a: 'ils', b: 'sont' },
      ],
      explain: 'Je suis, il est, nous sommes, vous êtes, ils sont : à répéter comme une chanson.',
    },
    {
      id: 'francais-present-etre-avoir-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a fait une faute, corrige-le',
      words: ['Ils', 'a', 'un', 'gros', 'chien.'],
      wrongIndex: 1,
      correct: 'ont',
      distractors: ['avons', 'as'],
      explain: 'Avec « ils », le verbe avoir donne ont : ils ont un gros chien.',
    },
    {
      id: 'francais-present-etre-avoir-blanks-2',
      kind: 'blanks',
      prompt: 'Complète avec le verbe aller',
      text: "Je {{vais}} à l'école. Nous {{allons}} à la piscine.",
      distractors: ['va', 'vont'],
      explain: 'Je vais, nous allons : le verbe aller change de forme, mais c\'est toujours lui.',
    },
    {
      id: 'francais-present-etre-avoir-choice-2',
      kind: 'choice',
      prompt: 'Tu … tes devoirs.',
      options: ['fait', 'font', 'fais'],
      answer: 2,
      explain: 'Avec « tu », le verbe faire prend un s : tu fais.',
    },
    {
      id: 'francais-present-etre-avoir-tf-1',
      kind: 'truefalse',
      statement: '« Ils disent bonjour » est bien conjugué.',
      answer: true,
      explain: 'Oui : je dis, tu dis, il dit, nous disons, vous dites, ils disent.',
    },
    {
      id: 'francais-present-etre-avoir-blanks-3',
      kind: 'blanks',
      prompt: 'Complète avec le verbe venir',
      text: 'Elle {{vient}} chez moi. Vous {{venez}} aussi ?',
      distractors: ['viens', 'viennent'],
      explain: 'Elle vient avec un t, vous venez avec ez.',
    },
    {
      id: 'francais-present-etre-avoir-sort-1',
      kind: 'sort',
      prompt: 'Verbe être, ou verbe avoir ?',
      boxes: ['Être', 'Avoir'],
      items: [
        { word: 'suis', box: 0 },
        { word: 'ai', box: 1 },
        { word: 'sommes', box: 0 },
        { word: 'avez', box: 1 },
        { word: 'sont', box: 0 },
        { word: 'as', box: 1 },
      ],
      explain: 'Suis, sommes, sont viennent de être. Ai, as, avez viennent de avoir.',
    },
    {
      id: 'francais-present-etre-avoir-dict-1',
      kind: 'dictation',
      word: 'sont',
      sentence: 'Les enfants sont à la plage.',
      explain: 'Sont : s-o-n-t, c\'est le verbe être avec « ils » ou « elles ».',
    },
  ],
};

const FUTUR_IMPARFAIT: Lesson = {
  id: 'francais-futur-imparfait',
  title: 'Le futur et l\'imparfait',
  subject: 'francais',
  source: 'lecon',
  level: 'CE1',
  notion: 'Conjuguer au futur et à l\'imparfait les verbes en -er, être et avoir',
  theme: 'conjugaison',
  attendu: 'Conjuguer au futur et à l\'imparfait les verbes en -er, être et avoir.',
  attenduId: 'ce1-conj-futur',
  summary:
    "Le futur, c'est demain : je chanterai, tu chanteras, nous chanterons. L'imparfait, c'est hier : je chantais, tu chantais, nous chantions. Pour être : je serai demain, j'étais hier. Pour avoir : j'aurai demain, j'avais hier.",
  minutes: 8,
  exercises: [
    {
      id: 'francais-futur-imparfait-sort-1',
      kind: 'sort',
      prompt: 'Hier, ou demain ?',
      boxes: ['Hier (imparfait)', 'Demain (futur)'],
      items: [
        { word: 'je chantais', box: 0 },
        { word: 'je chanterai', box: 1 },
        { word: 'nous étions', box: 0 },
        { word: 'nous serons', box: 1 },
        { word: 'tu avais', box: 0 },
        { word: 'tu auras', box: 1 },
      ],
      explain: 'L\'imparfait finit souvent par ais ou ions. Le futur finit par rai, ras, rons.',
    },
    {
      id: 'francais-futur-imparfait-choice-1',
      kind: 'choice',
      prompt: 'Demain, je … au parc.',
      options: ['jouais', 'joue', 'jouerai'],
      answer: 2,
      explain: '« Demain », c\'est le futur : je jouerai.',
    },
    {
      id: 'francais-futur-imparfait-blanks-1',
      kind: 'blanks',
      prompt: 'Complète avec le verbe jouer',
      text: 'Hier, tu {{jouais}} dehors. Demain, tu {{joueras}} à la maison.',
      distractors: ['joues', 'jouera'],
      explain: 'Hier, imparfait : tu jouais. Demain, futur : tu joueras.',
    },
    {
      id: 'francais-futur-imparfait-tf-1',
      kind: 'truefalse',
      statement: '« Nous serons » est le futur du verbe être.',
      answer: true,
      explain: 'Oui : demain, nous serons en vacances. Hier, nous étions à l\'école.',
    },
    {
      id: 'francais-futur-imparfait-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a fait une faute, corrige-le',
      words: ['Demain,', 'nous', 'mangions', 'une', 'glace.'],
      wrongIndex: 2,
      correct: 'mangerons',
      distractors: ['mangions', 'mangeons'],
      explain: '« Demain » demande le futur : nous mangerons. « Mangions », c\'est hier.',
    },
    {
      id: 'francais-futur-imparfait-choice-2',
      kind: 'choice',
      prompt: 'Hier, ils … très sages.',
      options: ['étaient', 'seront', 'sont'],
      answer: 0,
      explain: '« Hier », c\'est l\'imparfait : ils étaient.',
    },
    {
      id: 'francais-futur-imparfait-blanks-2',
      kind: 'blanks',
      prompt: 'Complète avec le verbe avoir',
      text: "L'année dernière, j'{{avais}} six ans. L'année prochaine, j'{{aurai}} huit ans.",
      distractors: ['ai', 'aura'],
      explain: 'L\'année dernière, c\'est le passé : j\'avais. L\'année prochaine, c\'est le futur : j\'aurai.',
    },
    {
      id: 'francais-futur-imparfait-tap-1',
      kind: 'tapword',
      prompt: 'Touche le verbe au futur',
      words: ['Ce', 'soir,', 'nous', 'regarderons', 'un', 'film.'],
      answer: [3],
      explain: 'Regarderons finit par rons : c\'est le futur avec « nous ».',
    },
    {
      id: 'francais-futur-imparfait-sentence-1',
      kind: 'sentence',
      prompt: "Remets les mots dans l'ordre",
      words: ['Demain,', 'elle', 'chantera', 'à', 'la', 'fête.'],
      explain: 'Demain, elle chantera : le verbe au futur finit par ra.',
    },
    {
      id: 'francais-futur-imparfait-tf-2',
      kind: 'truefalse',
      statement: '« Je chantais » veut dire que je chante demain.',
      answer: false,
      explain: 'Pas grave. « Je chantais », c\'est l\'imparfait, donc hier. Demain, ce serait « je chanterai ».',
    },
  ],
};

const SYNONYMES_CONTRAIRES: Lesson = {
  id: 'francais-synonymes-contraires',
  title: 'Synonymes, contraires, familles de mots',
  subject: 'francais',
  source: 'lecon',
  level: 'CE1',
  notion: 'Trouver des synonymes, des contraires et des mots de la même famille',
  theme: 'vocabulaire',
  attendu: 'Trouver des synonymes, des contraires, des mots de la même famille.',
  attenduId: 'ce1-voc-sens',
  summary:
    "Deux synonymes veulent dire presque la même chose : content et joyeux. Deux contraires veulent dire l'inverse : chaud et froid. Les mots d'une même famille se ressemblent et parlent de la même chose : dent, dentiste, dentifrice.",
  minutes: 7,
  exercises: [
    {
      id: 'francais-synonymes-contraires-pairs-1',
      kind: 'pairs',
      prompt: 'Retrouve les paires de synonymes',
      pairs: [
        { a: 'content', b: 'joyeux' },
        { a: 'grand', b: 'immense' },
        { a: 'jolie', b: 'belle' },
        { a: 'rapide', b: 'vite' },
      ],
      explain: 'Des synonymes, ce sont deux mots différents qui veulent dire presque pareil.',
    },
    {
      id: 'francais-synonymes-contraires-choice-1',
      kind: 'choice',
      prompt: 'Quel mot est un synonyme de « petit » ?',
      options: ['géant', 'minuscule', 'lourd'],
      answer: 1,
      explain: 'Minuscule veut dire très petit. Géant, c\'est le contraire.',
    },
    {
      id: 'francais-synonymes-contraires-match-1',
      kind: 'match',
      prompt: 'Relie chaque mot à son contraire',
      pairs: [
        { a: 'chaud', b: 'froid' },
        { a: 'grand', b: 'petit' },
        { a: 'jour', b: 'nuit' },
        { a: 'ouvert', b: 'fermé' },
        { a: 'propre', b: 'sale' },
      ],
      seconds: 40,
      explain: 'Le contraire, c\'est l\'inverse : quand ce n\'est pas chaud, c\'est froid.',
    },
    {
      id: 'francais-synonymes-contraires-choice-2',
      kind: 'choice',
      prompt: 'Quel est le contraire de « monter » ?',
      options: ['grimper', 'sauter', 'descendre'],
      answer: 2,
      explain: 'Monter et descendre sont des contraires. Grimper est un synonyme de monter.',
    },
    {
      id: 'francais-synonymes-contraires-sort-1',
      kind: 'sort',
      prompt: 'Range les mots dans leur famille',
      boxes: ['Famille de dent', 'Famille de chant'],
      items: [
        { word: 'dentiste', box: 0 },
        { word: 'chanson', box: 1 },
        { word: 'dentifrice', box: 0 },
        { word: 'chanteur', box: 1 },
        { word: 'dent', box: 0 },
        { word: 'chanter', box: 1 },
      ],
      explain: 'Les mots d\'une même famille ont un bout en commun : dent, chant.',
    },
    {
      id: 'francais-synonymes-contraires-tf-1',
      kind: 'truefalse',
      statement: '« Dent » et « dentiste » sont de la même famille.',
      answer: true,
      explain: 'Oui, le dentiste soigne les dents, et les deux mots commencent par « dent ».',
    },
    {
      id: 'francais-synonymes-contraires-sort-2',
      kind: 'sort',
      prompt: 'Synonyme de content, ou contraire de content ?',
      boxes: ['Synonyme de content', 'Contraire de content'],
      items: [
        { word: 'joyeux', box: 0 },
        { word: 'triste', box: 1 },
        { word: 'heureux', box: 0 },
        { word: 'malheureux', box: 1 },
      ],
      explain: 'Joyeux et heureux, c\'est comme content. Triste et malheureux, c\'est l\'inverse.',
    },
    {
      id: 'francais-synonymes-contraires-choice-3',
      kind: 'choice',
      prompt: 'Quel mot n\'est pas de la famille de « jardin » ?',
      options: ['jardinier', 'jambon', 'jardinage'],
      answer: 1,
      explain: 'Jambon commence par ja, mais il n\'a rien à voir avec le jardin. Jardinier et jardinage, si.',
    },
    {
      id: 'francais-synonymes-contraires-tf-2',
      kind: 'truefalse',
      statement: '« Rapide » et « lent » sont des synonymes.',
      answer: false,
      explain: 'Pas grave. Rapide et lent veulent dire l\'inverse : ce sont des contraires.',
    },
    {
      id: 'francais-synonymes-contraires-blanks-1',
      kind: 'blanks',
      prompt: 'Complète avec le contraire',
      text: 'Le contraire de grand, c\'est {{petit}}. Le contraire de léger, c\'est {{lourd}}.',
      distractors: ['gros', 'haut'],
      explain: 'Grand et petit, léger et lourd : des paires de contraires.',
    },
  ],
};

const ORDRE_ALPHABETIQUE: Lesson = {
  id: 'francais-ordre-alphabetique',
  title: "L'ordre alphabétique",
  subject: 'francais',
  source: 'lecon',
  level: 'CE1',
  notion: 'Ranger des mots dans l\'ordre alphabétique et chercher dans le dictionnaire',
  theme: 'vocabulaire',
  attendu: 'Ranger des mots dans l\'ordre alphabétique et chercher dans le dictionnaire.',
  attenduId: 'ce1-voc-ordre',
  summary:
    "Pour ranger des mots dans l'ordre alphabétique, on regarde la première lettre : a, b, c, d… Si deux mots commencent par la même lettre, on regarde la deuxième lettre. Dans le dictionnaire, les mots sont rangés comme ça.",
  minutes: 6,
  exercises: [
    {
      id: 'francais-ordre-alphabetique-order-1',
      kind: 'order',
      prompt: "Range les mots dans l'ordre alphabétique",
      lines: ['abeille', 'chat', 'lion', 'zèbre'],
      explain: 'a, puis c, puis l, puis z : on suit l\'alphabet avec la première lettre.',
    },
    {
      id: 'francais-ordre-alphabetique-choice-1',
      kind: 'choice',
      prompt: 'Quelle lettre vient juste après le m ?',
      options: ['l', 'o', 'n'],
      answer: 2,
      explain: 'l, m, n, o : après le m vient le n.',
    },
    {
      id: 'francais-ordre-alphabetique-tf-1',
      kind: 'truefalse',
      statement: 'Dans l\'alphabet, la lettre b vient avant la lettre d.',
      answer: true,
      explain: 'a, b, c, d : le b est bien avant le d.',
    },
    {
      id: 'francais-ordre-alphabetique-order-2',
      kind: 'order',
      prompt: "Range les fruits dans l'ordre alphabétique",
      lines: ['banane', 'fraise', 'poire', 'raisin'],
      explain: 'b, f, p, r : la première lettre suffit, elles sont toutes différentes.',
    },
    {
      id: 'francais-ordre-alphabetique-choice-2',
      kind: 'choice',
      prompt: 'Quel mot vient en premier dans le dictionnaire ?',
      options: ['tigre', 'souris', 'vache'],
      answer: 1,
      explain: 's vient avant t et avant v : souris est en premier.',
    },
    {
      id: 'francais-ordre-alphabetique-sort-1',
      kind: 'sort',
      prompt: 'Le mot commence par une lettre avant le m, ou après le m ?',
      boxes: ['Avant le m', 'Après le m'],
      items: [
        { word: 'arbre', box: 0 },
        { word: 'nuage', box: 1 },
        { word: 'fleur', box: 0 },
        { word: 'table', box: 1 },
        { word: 'gâteau', box: 0 },
        { word: 'soleil', box: 1 },
      ],
      explain: 'a, f, g sont avant le m. n, s, t sont après.',
    },
    {
      id: 'francais-ordre-alphabetique-tf-2',
      kind: 'truefalse',
      statement: 'Pour ranger « lune » et « lait », on regarde la deuxième lettre.',
      answer: true,
      explain: 'Les deux commencent par l, alors on regarde la deuxième lettre : a avant u, lait vient avant lune.',
    },
    {
      id: 'francais-ordre-alphabetique-order-3',
      kind: 'order',
      prompt: 'Ces mots commencent tous par c : range-les avec la deuxième lettre',
      lines: ['cadeau', 'cerise', 'chien', 'cube'],
      explain: 'Deuxième lettre : a, e, h, u. Cadeau, cerise, chien, cube.',
    },
    {
      id: 'francais-ordre-alphabetique-choice-3',
      kind: 'choice',
      prompt: 'Entre « mouton » et « marteau », lequel vient en premier dans le dictionnaire ?',
      options: ['mouton', 'marteau'],
      answer: 1,
      explain: 'Les deux commencent par m. Deuxième lettre : a avant o, donc marteau vient en premier.',
    },
    {
      id: 'francais-ordre-alphabetique-order-4',
      kind: 'order',
      prompt: 'Range ces mots en p avec la deuxième lettre',
      lines: ['papa', 'pêche', 'pomme', 'prune'],
      explain: 'Deuxième lettre : a, ê, o, r. Papa, pêche, pomme, prune.',
    },
  ],
};

export const LESSONS: Lesson[] = [
  LIRE_PONCTUATION,
  COMPRENDRE_TEXTE,
  CORBEAU_RENARD,
  SONS_OU_ON_AN_IN,
  SONS_OI_EAU_CH_GN,
  PLURIEL,
  ACCORD_SUJET_VERBE,
  MOTS_INVARIABLES,
  LA_PHRASE,
  NOM_DETERMINANT,
  PRESENT_ER,
  PRESENT_ETRE_AVOIR,
  FUTUR_IMPARFAIT,
  SYNONYMES_CONTRAIRES,
  ORDRE_ALPHABETIQUE,
];
