import type { Lesson } from './types';

/**
 * Banque CM1, mathématiques : dix-huit leçons qui couvrent les attendus de
 * début de cycle 3 (grands nombres jusqu'au million, fractions et décimaux,
 * opérations posées, proportionnalité, grandeurs, aires, angles, géométrie
 * plane, symétrie, solides et repérage). Tout est neutre : l'univers habille
 * à l'affichage.
 */

const GRANDS_NOMBRES: Lesson = {
  id: 'cm1-maths-grands-nombres',
  title: "Les grands nombres jusqu'au million",
  subject: 'maths',
  source: 'numeration',
  level: 'CM1',
  notion: "Lire, écrire et décomposer les grands nombres jusqu'au million avec les classes des unités et des mille",
  theme: 'nombres',
  attendu: "Lire, écrire, nommer et décomposer les grands nombres jusqu'au million (classes des unités et des mille).",
  attenduId: 'cm1-nb-grands',
  summary:
    "Un grand nombre se lit par classes de trois chiffres : la classe des mille à gauche, la classe des unités à droite. Dans 325 604, il y a 325 milliers et 604 unités : « trois cent vingt-cinq mille six cent quatre ». Un million, c'est 1 000 000, mille milliers.",
  minutes: 7,
  exercises: [
    {
      id: 'cm1-maths-grands-nombres-choice-1',
      kind: 'choice',
      prompt: "Comment s'écrit « trois cent vingt-cinq mille six cent quatre » en chiffres ?",
      options: ['32 564', '325 604', '325 064'],
      answer: 1,
      explain: "Trois cent vingt-cinq mille, c'est 325 milliers. Six cent quatre, c'est 604. On écrit 325 604, avec un zéro à la place des dizaines.",
    },
    {
      id: 'cm1-maths-grands-nombres-tf-1',
      kind: 'truefalse',
      statement: '40 008 se lit « quarante mille huit ».',
      answer: true,
      explain: "Oui : 40 milliers et 8 unités. Les zéros gardent la place des centaines et des dizaines.",
    },
    {
      id: 'cm1-maths-grands-nombres-tap-1',
      kind: 'tapword',
      prompt: 'Touche le chiffre des dizaines de mille dans 582 316',
      words: ['5', '8', '2', '3', '1', '6'],
      answer: [1],
      explain: "Dans la classe des mille, 582, le 2 compte les unités de mille, le 8 les dizaines de mille et le 5 les centaines de mille.",
    },
    {
      id: 'cm1-maths-grands-nombres-blanks-1',
      kind: 'blanks',
      prompt: 'Décompose le nombre',
      text: '407 350 = {{400 000}} + {{7 000}} + {{300}} + 50',
      distractors: ['40 000', '3 000'],
      explain: "4 centaines de mille font 400 000, 7 unités de mille font 7 000, 3 centaines font 300, et il reste 50.",
    },
    {
      id: 'cm1-maths-grands-nombres-sort-1',
      kind: 'sort',
      prompt: 'Range chaque nombre dans la bonne boîte',
      boxes: ['Moins de 100 000', 'Plus de 100 000'],
      items: [
        { word: '98 500', box: 0 },
        { word: '120 000', box: 1 },
        { word: '1 000 000', box: 1 },
        { word: '99 999', box: 0 },
        { word: '100 001', box: 1 },
        { word: '56 000', box: 0 },
      ],
      explain: "100 000 s'écrit avec six chiffres. Un nombre à cinq chiffres est forcément plus petit, un nombre à six ou sept chiffres est plus grand.",
    },
    {
      id: 'cm1-maths-grands-nombres-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a mal écrit le nombre, corrige-le',
      words: ['Six', 'cent', 'mille', 'vingt', '=', '600 200'],
      wrongIndex: 5,
      correct: '600 020',
      distractors: ['600 200', '60 020'],
      explain: "Six cent mille, c'est 600 000. Vingt, c'est 20. Il n'y a ni centaine ni unité : on écrit 600 020.",
    },
    {
      id: 'cm1-maths-grands-nombres-match-1',
      kind: 'match',
      prompt: 'Relie chaque nombre à son nom avant la fin du chrono',
      seconds: 50,
      pairs: [
        { a: '250 000', b: 'deux cent cinquante mille' },
        { a: '1 000 000', b: 'un million' },
        { a: '30 500', b: 'trente mille cinq cents' },
        { a: '805 000', b: 'huit cent cinq mille' },
        { a: '12 006', b: 'douze mille six' },
      ],
      explain: "Lis d'abord la classe des mille avec le mot « mille », puis la classe des unités comme un nombre à trois chiffres.",
    },
    {
      id: 'cm1-maths-grands-nombres-choice-2',
      kind: 'choice',
      prompt: 'Combien de centaines de mille dans 648 210 ?',
      options: ['4', '8', '6'],
      answer: 2,
      explain: "Le chiffre tout à gauche d'un nombre à six chiffres compte les centaines de mille : 6, c'est 600 000.",
    },
    {
      id: 'cm1-maths-grands-nombres-pairs-1',
      kind: 'pairs',
      prompt: 'Relie chaque nombre à son nombre de milliers',
      pairs: [
        { a: '45 000', b: '45 milliers' },
        { a: '450 000', b: '450 milliers' },
        { a: '4 500', b: '4 milliers' },
        { a: '1 000 000', b: '1 000 milliers' },
      ],
      explain: "Le nombre de milliers, c'est toute la classe des mille : les chiffres qui sont à gauche des trois derniers.",
    },
    {
      id: 'cm1-maths-grands-nombres-tf-2',
      kind: 'truefalse',
      statement: '999 999 + 1 = 1 000 000.',
      answer: true,
      explain: "Oui : juste après 999 999 vient un million, qui s'écrit avec un 1 et six zéros.",
    },
  ],
};

const COMPARER: Lesson = {
  id: 'cm1-maths-comparer',
  title: 'Comparer, encadrer, arrondir',
  subject: 'maths',
  source: 'numeration',
  level: 'CM1',
  notion: 'Comparer, ranger, encadrer et arrondir les grands nombres ; les placer sur une droite graduée',
  theme: 'nombres',
  attendu: 'Comparer, ranger, encadrer et arrondir les grands nombres ; les placer sur une droite graduée.',
  attenduId: 'cm1-nb-comparer',
  summary:
    "Pour comparer deux grands nombres, on compte d'abord leurs chiffres, puis on compare de gauche à droite. Arrondir, c'est choisir le nombre rond le plus proche : 72 480 arrondi au millier donne 72 000, parce que 480 est plus petit que 500.",
  minutes: 7,
  exercises: [
    {
      id: 'cm1-maths-comparer-choice-1',
      kind: 'choice',
      prompt: 'Quel est le plus grand de ces nombres ?',
      options: ['98 500', '102 000', '99 999'],
      answer: 1,
      explain: "102 000 a six chiffres, les deux autres n'en ont que cinq. C'est donc le plus grand.",
    },
    {
      id: 'cm1-maths-comparer-tf-1',
      kind: 'truefalse',
      statement: '245 100 est plus petit que 245 010.',
      answer: false,
      explain: "Les trois premiers chiffres sont pareils. Aux centaines, 1 est plus grand que 0 : 245 100 est plus grand.",
    },
    {
      id: 'cm1-maths-comparer-line-1',
      kind: 'numberline',
      prompt: 'Place le nombre 600 000',
      min: 0,
      max: 1000000,
      step: 100000,
      answer: 600000,
      explain: "Chaque graduation vaut 100 000. 600 000, c'est 6 graduations après 0.",
    },
    {
      id: 'cm1-maths-comparer-sort-1',
      kind: 'sort',
      prompt: 'Range chaque nombre dans la boîte du nombre rond le plus proche',
      boxes: ['Plus proche de 300 000', 'Plus proche de 400 000'],
      items: [
        { word: '320 000', box: 0 },
        { word: '390 000', box: 1 },
        { word: '345 000', box: 0 },
        { word: '360 000', box: 1 },
        { word: '310 500', box: 0 },
        { word: '399 000', box: 1 },
      ],
      explain: "Le milieu entre 300 000 et 400 000, c'est 350 000. En dessous, on est plus près de 300 000 ; au-dessus, plus près de 400 000.",
    },
    {
      id: 'cm1-maths-comparer-blanks-1',
      kind: 'blanks',
      prompt: 'Range du plus petit au plus grand',
      text: 'Du plus petit au plus grand : {{45 600}}, puis {{54 600}}, puis {{56 400}}.',
      distractors: ['65 400'],
      explain: "Ils ont tous cinq chiffres. On compare les dizaines de mille : 4, puis 5 et 5. Pour les deux qui commencent par 5, on regarde ensuite les milliers : 4 puis 6.",
    },
    {
      id: 'cm1-maths-comparer-fix-1',
      kind: 'fix',
      prompt: "Gribouille s'est trompé en arrondissant, corrige-le",
      words: ['72 480', 'arrondi', 'au', 'millier', '=', '73 000'],
      wrongIndex: 5,
      correct: '72 000',
      distractors: ['73 000', '72 500'],
      explain: "72 480 est entre 72 000 et 73 000. Comme 480 est plus petit que 500, il est plus près de 72 000.",
    },
    {
      id: 'cm1-maths-comparer-choice-2',
      kind: 'choice',
      prompt: 'Entre quelles centaines de mille se trouve 356 000 ?',
      options: ['300 000 et 400 000', '350 000 et 360 000', '200 000 et 300 000'],
      answer: 0,
      explain: "Les centaines de mille, ce sont les nombres ronds comme 300 000 et 400 000. 356 000 commence par 3, il est entre les deux.",
    },
    {
      id: 'cm1-maths-comparer-line-2',
      kind: 'numberline',
      prompt: 'Place le nombre 25 000',
      min: 20000,
      max: 30000,
      step: 1000,
      answer: 25000,
      explain: "Ici la droite va de 20 000 à 30 000 et chaque graduation vaut 1 000. 25 000 est juste au milieu.",
    },
    {
      id: 'cm1-maths-comparer-pairs-1',
      kind: 'pairs',
      prompt: 'Relie chaque nombre à son arrondi à la centaine',
      pairs: [
        { a: '4 572', b: '4 600' },
        { a: '8 149', b: '8 100' },
        { a: '12 350', b: '12 400' },
        { a: '90 980', b: '91 000' },
      ],
      explain: "On regarde les deux derniers chiffres : 50 ou plus, on monte à la centaine suivante ; moins de 50, on reste à la centaine d'avant.",
    },
    {
      id: 'cm1-maths-comparer-tf-2',
      kind: 'truefalse',
      statement: 'Le nombre qui vient juste avant 300 000 est 299 999.',
      answer: true,
      explain: "Oui : 299 999 + 1 = 300 000. Tous les 9 passent à 0 et le 2 devient 3.",
    },
  ],
};

const FRACTIONS: Lesson = {
  id: 'cm1-maths-fractions',
  title: 'Les fractions simples',
  subject: 'maths',
  source: 'numeration',
  level: 'CM1',
  notion: 'Lire, écrire et comparer des fractions simples : numérateur, dénominateur, demi, tiers, quart, dixième',
  theme: 'nombres',
  attendu: 'Lire, écrire et comparer des fractions simples (demi, tiers, quart, dixième) ; les placer sur une droite graduée.',
  attenduId: 'cm1-nb-fractions',
  summary:
    "Dans la fraction trois quarts, le 4 en bas est le dénominateur : on partage en 4 parts égales. Le 3 en haut est le numérateur : on prend 3 parts. Quand le numérateur est plus petit que le dénominateur, la fraction est plus petite que 1 ; quand il est plus grand, elle dépasse 1.",
  minutes: 7,
  exercises: [
    {
      id: 'cm1-maths-fractions-choice-1',
      kind: 'choice',
      prompt: 'Dans la fraction trois quarts, quel est le numérateur ?',
      options: ['4', '3', '7'],
      answer: 1,
      explain: "Le numérateur est le nombre du haut, celui qui dit combien de parts on prend : 3. Le 4 en bas est le dénominateur.",
    },
    {
      id: 'cm1-maths-fractions-tf-1',
      kind: 'truefalse',
      statement: "Un demi, c'est la même chose que deux quarts.",
      answer: true,
      explain: "Oui : si on coupe une moitié en deux, on obtient deux quarts. Deux quarts et un demi, c'est la même part.",
    },
    {
      id: 'cm1-maths-fractions-line-1',
      kind: 'numberline',
      prompt: 'Place la fraction trois quarts',
      min: 0,
      max: 1,
      step: 0.25,
      answer: 0.75,
      explain: "Entre 0 et 1, il y a 4 parts égales : chaque graduation vaut un quart. Trois quarts, c'est 3 graduations après 0.",
    },
    {
      id: 'cm1-maths-fractions-sort-1',
      kind: 'sort',
      prompt: 'Range chaque fraction dans la bonne boîte',
      boxes: ['Plus petite que 1', 'Plus grande que 1'],
      items: [
        { word: 'trois quarts', box: 0 },
        { word: 'cinq quarts', box: 1 },
        { word: 'deux tiers', box: 0 },
        { word: 'sept dixièmes', box: 0 },
        { word: 'trois demis', box: 1 },
        { word: 'quatre tiers', box: 1 },
      ],
      explain: "Compare le numérateur au dénominateur. Si on prend moins de parts qu'il n'en faut pour faire 1 entier, la fraction est plus petite que 1.",
    },
    {
      id: 'cm1-maths-fractions-blanks-1',
      kind: 'blanks',
      prompt: 'Complète avec la bonne fraction',
      text: 'Dans {{un quart}}, on partage en 4 parts égales et on en prend une. Dans {{trois dixièmes}}, on partage en 10 parts égales et on en prend trois.',
      distractors: ['un tiers', 'trois quarts'],
      explain: "Le dénominateur dit en combien de parts on partage, le numérateur combien on en prend.",
    },
    {
      id: 'cm1-maths-fractions-fix-1',
      kind: 'fix',
      prompt: "Gribouille s'est trompé, corrige-le",
      words: ['Trois', 'tiers', '=', '2'],
      wrongIndex: 3,
      correct: '1',
      distractors: ['2', '3'],
      explain: "Trois tiers, c'est les 3 parts sur 3 : tout l'entier. Trois tiers, c'est 1.",
    },
    {
      id: 'cm1-maths-fractions-line-2',
      kind: 'numberline',
      prompt: 'Place la fraction trois demis',
      min: 0,
      max: 2,
      step: 0.5,
      answer: 1.5,
      explain: "Chaque graduation vaut un demi. Trois demis, c'est 3 graduations après 0 : un entier et un demi.",
    },
    {
      id: 'cm1-maths-fractions-pairs-1',
      kind: 'pairs',
      prompt: 'Relie chaque fraction à son écriture en chiffres',
      pairs: [
        { a: 'un demi', b: '1/2' },
        { a: 'un quart', b: '1/4' },
        { a: 'un dixième', b: '1/10' },
        { a: 'deux tiers', b: '2/3' },
      ],
      explain: "Demi, c'est partagé en 2 ; quart en 4 ; dixième en 10 ; tiers en 3. Le nombre de parts prises se met en haut.",
    },
    {
      id: 'cm1-maths-fractions-choice-2',
      kind: 'choice',
      prompt: 'Quelle fraction est plus grande que 1 ?',
      options: ['quatre cinquièmes', 'cinq quarts', 'trois quarts'],
      answer: 1,
      explain: "Cinq quarts, c'est 5 parts alors qu'il en faut 4 pour un entier : c'est un entier et un quart, plus que 1.",
    },
    {
      id: 'cm1-maths-fractions-tf-2',
      kind: 'truefalse',
      statement: 'Le quart de 20 est 5.',
      answer: true,
      explain: "Oui : 20 partagé en 4 parts égales, c'est 5 par part, car 4 × 5 = 20.",
    },
  ],
};

const DECIMAUX: Lesson = {
  id: 'cm1-maths-decimaux',
  title: 'Les nombres décimaux',
  subject: 'maths',
  source: 'numeration',
  level: 'CM1',
  notion: "Comprendre les nombres décimaux : dixièmes, centièmes, écriture à virgule et fraction décimale",
  theme: 'nombres',
  attendu: 'Comprendre les nombres décimaux : dixièmes, centièmes, écriture à virgule et fraction décimale.',
  attenduId: 'cm1-nb-decimaux',
  summary:
    "Un dixième, c'est 1 partagé en 10 : on l'écrit 0,1. Un centième, c'est 1 partagé en 100 : 0,01. Trois dixièmes, c'est 3/10 ou 0,3. À gauche de la virgule, la partie entière ; à droite, les dixièmes puis les centièmes.",
  minutes: 7,
  exercises: [
    {
      id: 'cm1-maths-decimaux-choice-1',
      kind: 'choice',
      prompt: "Comment s'écrit trois dixièmes avec une virgule ?",
      options: ['3,10', '0,3', '3,0'],
      answer: 1,
      explain: "Trois dixièmes, c'est moins que 1 : la partie entière est 0 et il y a 3 au rang des dixièmes. On écrit 0,3.",
    },
    {
      id: 'cm1-maths-decimaux-tf-1',
      kind: 'truefalse',
      statement: "0,5, c'est cinq dixièmes, la moitié de 1.",
      answer: true,
      explain: "Oui : 5 dixièmes sur 10, c'est la moitié. 0,5 et un demi, c'est le même nombre.",
    },
    {
      id: 'cm1-maths-decimaux-line-1',
      kind: 'numberline',
      prompt: 'Place le nombre 0,7',
      min: 0,
      max: 1,
      step: 0.1,
      answer: 0.7,
      explain: "Entre 0 et 1, chaque graduation vaut un dixième. 0,7, c'est 7 graduations après 0.",
    },
    {
      id: 'cm1-maths-decimaux-blanks-1',
      kind: 'blanks',
      prompt: 'Décompose le nombre',
      text: '2,35 = 2 + {{3}} dixièmes + {{5}} centièmes',
      distractors: ['4', '35'],
      explain: "Juste après la virgule, c'est le chiffre des dixièmes : 3. Le suivant, c'est celui des centièmes : 5.",
    },
    {
      id: 'cm1-maths-decimaux-sort-1',
      kind: 'sort',
      prompt: 'Range chaque nombre dans la bonne boîte',
      boxes: ['Plus petit que 1', 'Plus grand que 1'],
      items: [
        { word: '0,9', box: 0 },
        { word: '1,2', box: 1 },
        { word: '0,45', box: 0 },
        { word: '1,05', box: 1 },
        { word: '0,99', box: 0 },
        { word: '10,1', box: 1 },
      ],
      explain: "Regarde la partie entière, avant la virgule : si c'est 0, le nombre est plus petit que 1.",
    },
    {
      id: 'cm1-maths-decimaux-fix-1',
      kind: 'fix',
      prompt: "Gribouille s'est trompé, corrige-le",
      words: ['Sept', 'centièmes', '=', '0,7'],
      wrongIndex: 3,
      correct: '0,07',
      distractors: ['0,7', '7,00'],
      explain: "Sept centièmes, c'est 7 au rang des centièmes, le deuxième chiffre après la virgule : 0,07. 0,7, ce serait sept dixièmes.",
    },
    {
      id: 'cm1-maths-decimaux-pairs-1',
      kind: 'pairs',
      prompt: 'Relie chaque nombre à la façon de le lire',
      pairs: [
        { a: '0,5', b: 'cinq dixièmes' },
        { a: '0,25', b: 'vingt-cinq centièmes' },
        { a: '1,5', b: 'un et cinq dixièmes' },
        { a: '0,05', b: 'cinq centièmes' },
      ],
      explain: "Un seul chiffre après la virgule, ce sont des dixièmes ; deux chiffres, ce sont des centièmes.",
    },
    {
      id: 'cm1-maths-decimaux-choice-2',
      kind: 'choice',
      prompt: 'Quel nombre est le plus grand ?',
      options: ['2,5', '2,45', '2,09'],
      answer: 0,
      explain: "La partie entière est 2 pour les trois. On compare les dixièmes : 5, 4 et 0. Le plus grand est 2,5, même s'il a moins de chiffres.",
    },
    {
      id: 'cm1-maths-decimaux-line-2',
      kind: 'numberline',
      prompt: 'Place le nombre 1,4',
      min: 1,
      max: 2,
      step: 0.1,
      answer: 1.4,
      explain: "La droite va de 1 à 2 par dixièmes. 1,4, c'est 4 graduations après 1.",
    },
    {
      id: 'cm1-maths-decimaux-tf-2',
      kind: 'truefalse',
      statement: "0,3 et 0,30, c'est le même nombre.",
      answer: true,
      explain: "Oui : 30 centièmes, c'est 3 dixièmes. Un zéro ajouté tout à droite après la virgule ne change pas le nombre.",
    },
  ],
};

const CALCUL_MENTAL: Lesson = {
  id: 'cm1-maths-calcul-mental',
  title: 'Calcul mental',
  subject: 'maths',
  source: 'calcul',
  level: 'CM1',
  notion: 'Multiplier et diviser par 10, 100, 1 000 ; doubles, moitiés ; compléments à 100 et à 1 000',
  theme: 'calcul',
  attendu: "Calculer mentalement : tables jusqu'à 9, multiplier et diviser par 10, 100, 1 000, doubles, moitiés, compléments à 100 et 1 000.",
  attenduId: 'cm1-calc-mental',
  summary:
    "Multiplier par 10, 100 ou 1 000, c'est ajouter un, deux ou trois zéros à droite : 36 × 100 = 3 600. Diviser par 10, c'est enlever un zéro : 4 500 : 10 = 450. Le complément à 100 de 37 est 63, car 37 + 63 = 100.",
  minutes: 6,
  exercises: [
    {
      id: 'cm1-maths-calcul-mental-choice-1',
      kind: 'choice',
      prompt: 'Combien font 36 × 100 ?',
      options: ['360', '3 600', '36 000'],
      answer: 1,
      explain: "Multiplier par 100, c'est ajouter deux zéros à droite : 36 devient 3 600.",
    },
    {
      id: 'cm1-maths-calcul-mental-tf-1',
      kind: 'truefalse',
      statement: '4 500 : 10 = 45.',
      answer: false,
      explain: "Diviser par 10, c'est enlever un seul zéro : 4 500 : 10 = 450. Pour avoir 45, il faudrait diviser par 100.",
    },
    {
      id: 'cm1-maths-calcul-mental-blanks-1',
      kind: 'blanks',
      prompt: 'Trouve les compléments',
      text: 'Complément à 100 : 37 + {{63}} = 100. Complément à 1 000 : 250 + {{750}} = 1 000.',
      distractors: ['73', '850'],
      explain: "37 + 63 = 100 : de 37 à 40 il y a 3, puis de 40 à 100 il y a 60. 250 + 750 = 1 000 : un quart plus trois quarts.",
    },
    {
      id: 'cm1-maths-calcul-mental-pairs-1',
      kind: 'pairs',
      prompt: 'Relie chaque calcul à son résultat',
      pairs: [
        { a: 'Double de 45', b: '90' },
        { a: 'Moitié de 86', b: '43' },
        { a: 'Double de 125', b: '250' },
        { a: 'Moitié de 150', b: '75' },
      ],
      explain: "Le double, c'est deux fois le nombre. La moitié, c'est le nombre partagé en deux parts égales.",
    },
    {
      id: 'cm1-maths-calcul-mental-fix-1',
      kind: 'fix',
      prompt: "Gribouille s'est trompé, corrige-le",
      words: ['28', '×', '1 000', '=', '2 800'],
      wrongIndex: 4,
      correct: '28 000',
      distractors: ['2 800', '280'],
      explain: "Multiplier par 1 000, c'est ajouter trois zéros : 28 000. Avec deux zéros, c'est seulement × 100.",
    },
    {
      id: 'cm1-maths-calcul-mental-sort-1',
      kind: 'sort',
      prompt: 'Range chaque calcul dans la boîte de son résultat',
      boxes: ['Résultat 420', 'Résultat 4 200'],
      items: [
        { word: '42 × 10', box: 0 },
        { word: '42 × 100', box: 1 },
        { word: '4 200 : 10', box: 0 },
        { word: '420 × 10', box: 1 },
        { word: '210 × 2', box: 0 },
        { word: '2 100 × 2', box: 1 },
      ],
      explain: "Compte les zéros : × 10 en ajoute un, × 100 en ajoute deux, : 10 en enlève un. Le double de 210 est 420, celui de 2 100 est 4 200.",
    },
    {
      id: 'cm1-maths-calcul-mental-choice-2',
      kind: 'choice',
      prompt: 'Combien font 7 × 8 ?',
      options: ['54', '56', '63'],
      answer: 1,
      explain: "7 × 8 = 56. Une astuce : 5, 6, 7, 8 se suivent : 56 = 7 × 8.",
    },
    {
      id: 'cm1-maths-calcul-mental-tap-1',
      kind: 'tapword',
      prompt: 'Touche le calcul qui est faux',
      words: ['9 × 6 = 54', '8 × 7 = 54', '6 × 7 = 42'],
      answer: [1],
      explain: "8 × 7 = 56, pas 54. Les deux autres sont justes : 9 × 6 = 54 et 6 × 7 = 42.",
    },
    {
      id: 'cm1-maths-calcul-mental-speed-1',
      kind: 'speed',
      prompt: 'Calcul éclair : dizaines, centaines, doubles et moitiés',
      seconds: 60,
      target: 7,
      items: [
        { q: '25 × 10', a: 250 },
        { q: '7 × 100', a: 700 },
        { q: '100 − 40', a: 60 },
        { q: '3 × 1 000', a: 3000 },
        { q: '800 : 10', a: 80 },
        { q: '6 × 9', a: 54 },
        { q: 'Double de 35', a: 70 },
        { q: 'Moitié de 48', a: 24 },
        { q: '1 000 − 300', a: 700 },
        { q: '45 × 10', a: 450 },
      ],
      explain: "Pas grave : pour × 10, × 100, × 1 000, on ajoute des zéros ; pour les compléments, on cherche ce qui manque pour arriver au nombre rond.",
    },
    {
      id: 'cm1-maths-calcul-mental-tf-2',
      kind: 'truefalse',
      statement: 'La moitié de 1 000 est 500.',
      answer: true,
      explain: "Oui : 500 + 500 = 1 000, donc 500 est la moitié de 1 000.",
    },
  ],
};

const OPERATIONS: Lesson = {
  id: 'cm1-maths-operations',
  title: 'Addition et soustraction posées',
  subject: 'maths',
  source: 'calcul',
  level: 'CM1',
  notion: 'Poser une addition et une soustraction de grands nombres et de nombres décimaux',
  theme: 'calcul',
  attendu: 'Poser une addition et une soustraction de grands nombres et de nombres décimaux.',
  attenduId: 'cm1-calc-operations',
  summary:
    "Pour poser une addition ou une soustraction, on aligne les chiffres par rang : unités sous unités, dizaines sous dizaines. Avec des nombres décimaux, on aligne les virgules : 3,50 + 1,25 = 4,75. On peut ajouter un zéro à droite de la virgule pour avoir autant de chiffres partout.",
  minutes: 7,
  exercises: [
    {
      id: 'cm1-maths-operations-choice-1',
      kind: 'choice',
      prompt: 'Combien font 45 672 + 23 519 ?',
      options: ['69 191', '68 191', '69 181'],
      answer: 0,
      explain: "2 + 9 = 11, je pose 1 et je retiens 1. 7 + 1 + 1 = 9. 6 + 5 = 11, je pose 1 et je retiens 1. 5 + 3 + 1 = 9. 4 + 2 = 6. Résultat : 69 191.",
    },
    {
      id: 'cm1-maths-operations-tf-1',
      kind: 'truefalse',
      statement: '12 500 − 4 750 = 7 750.',
      answer: true,
      explain: "Oui : 4 750 + 7 750 = 12 500. On peut toujours vérifier une soustraction avec une addition.",
    },
    {
      id: 'cm1-maths-operations-blanks-1',
      kind: 'blanks',
      prompt: 'Complète la méthode',
      text: 'Pour poser 3,5 + 1,25, on aligne les {{virgules}} : 3,50 + 1,25 = {{4,75}}.',
      distractors: ['chiffres de gauche', '4,30'],
      explain: "On aligne les virgules, puis on ajoute rang par rang : 50 centièmes + 25 centièmes = 75 centièmes, et 3 + 1 = 4. Résultat : 4,75.",
    },
    {
      id: 'cm1-maths-operations-fix-1',
      kind: 'fix',
      prompt: "Gribouille s'est trompé, corrige-le",
      words: ['8,4', '−', '2,15', '=', '6,35'],
      wrongIndex: 4,
      correct: '6,25',
      distractors: ['6,35', '6,15'],
      explain: "On écrit 8,40 − 2,15. Aux centièmes : 0 − 5, impossible, on emprunte : 10 − 5 = 5. Aux dixièmes : 3 − 1 = 2. Aux unités : 8 − 2 = 6. Résultat : 6,25.",
    },
    {
      id: 'cm1-maths-operations-pairs-1',
      kind: 'pairs',
      prompt: 'Relie chaque calcul à son résultat',
      pairs: [
        { a: '2,5 + 2,5', b: '5' },
        { a: '10 − 0,5', b: '9,5' },
        { a: '1,25 + 0,75', b: '2' },
        { a: '3,6 − 1,1', b: '2,5' },
      ],
      explain: "Deux fois deux et demi font cinq. 10 moins un demi, c'est 9 et demi. 25 centièmes et 75 centièmes font un entier.",
    },
    {
      id: 'cm1-maths-operations-sort-1',
      kind: 'sort',
      prompt: 'Quelle opération faut-il poser ? Range chaque situation',
      boxes: ['Addition', 'Soustraction'],
      items: [
        { word: 'Léa a 1 250 billes et en gagne 300', box: 0 },
        { word: 'Il reste combien sur 120 € après avoir dépensé 45 € ?', box: 1 },
        { word: '12 km puis 8,5 km : la distance totale', box: 0 },
        { word: 'La différence entre 7 800 et 6 950', box: 1 },
        { word: 'De combien a baissé la température, de 12,5 à 9 degrés ?', box: 1 },
      ],
      explain: "On additionne pour trouver un total ou ce qu'on a en plus. On soustrait pour trouver ce qui reste, ce qui a baissé ou un écart.",
    },
    {
      id: 'cm1-maths-operations-choice-2',
      kind: 'choice',
      prompt: 'Combien font 100 000 − 1 ?',
      options: ['99 000', '90 999', '99 999'],
      answer: 2,
      explain: "Juste avant 100 000 vient 99 999 : tous les chiffres deviennent des 9 et il y a un chiffre de moins.",
    },
    {
      id: 'cm1-maths-operations-tap-1',
      kind: 'tapword',
      prompt: "Touche l'opération qui est juste",
      words: ['254 + 378 = 632', '254 + 378 = 622', '254 + 378 = 532'],
      answer: [0],
      explain: "4 + 8 = 12, je pose 2 et je retiens 1. 5 + 7 + 1 = 13, je pose 3 et je retiens 1. 2 + 3 + 1 = 6. Résultat : 632.",
    },
    {
      id: 'cm1-maths-operations-tf-2',
      kind: 'truefalse',
      statement: '4,5 + 0,5 = 4,10.',
      answer: false,
      explain: "5 dixièmes + 5 dixièmes = 10 dixièmes, c'est 1 entier. 4,5 + 0,5 = 5. Et 4,10, c'est pareil que 4,1, plus petit que 4,5.",
    },
    {
      id: 'cm1-maths-operations-choice-3',
      kind: 'choice',
      prompt: 'Un pot de confiture coûte 2,80 € et un pain coûte 1,35 €. Combien coûtent les deux ensemble ?',
      options: ['3,15 €', '4,15 €', '4,05 €'],
      answer: 1,
      explain: "2,80 + 1,35 : 80 centimes + 35 centimes = 1,15 €. Avec 2 + 1 = 3 €, cela fait 4,15 €.",
    },
  ],
};

const MULTIPLICATION: Lesson = {
  id: 'cm1-maths-multiplication',
  title: 'La multiplication à deux chiffres',
  subject: 'maths',
  source: 'calcul',
  level: 'CM1',
  notion: 'Poser une multiplication à deux chiffres au multiplicateur',
  theme: 'calcul',
  attendu: 'Poser une multiplication à deux chiffres au multiplicateur.',
  attenduId: 'cm1-calc-multiplication',
  summary:
    "Pour calculer 34 × 12, on fait deux lignes : 34 × 2 = 68, puis 34 × 10 = 340. Sur la deuxième ligne, on écrit un 0 à droite parce qu'on multiplie par une dizaine. On additionne les deux lignes : 68 + 340 = 408.",
  minutes: 8,
  exercises: [
    {
      id: 'cm1-maths-multiplication-choice-1',
      kind: 'choice',
      prompt: 'Combien font 34 × 12 ?',
      options: ['348', '408', '418'],
      answer: 1,
      explain: "34 × 2 = 68 et 34 × 10 = 340. Ensemble : 68 + 340 = 408.",
    },
    {
      id: 'cm1-maths-multiplication-order-1',
      kind: 'order',
      prompt: "Remets dans l'ordre les étapes de la multiplication 34 × 12",
      lines: [
        'Je multiplie 34 par 2 unités : 68',
        'Je mets un 0 à droite sur la deuxième ligne',
        'Je multiplie 34 par 1 dizaine : 340',
        "J'additionne les deux lignes : 68 + 340 = 408",
      ],
      explain: "D'abord les unités du multiplicateur, puis les dizaines avec le zéro de décalage, et on finit par l'addition.",
    },
    {
      id: 'cm1-maths-multiplication-blanks-1',
      kind: 'blanks',
      prompt: 'Complète la multiplication 45 × 23',
      text: '45 × 3 = {{135}}, puis 45 × 20 = {{900}}. Total : 135 + 900 = {{1 035}}.',
      distractors: ['125', '1 025'],
      explain: "45 × 3 = 135, car 40 × 3 = 120 et 5 × 3 = 15. 45 × 20, c'est 45 × 2 = 90 avec un zéro : 900. Et 135 + 900 = 1 035.",
    },
    {
      id: 'cm1-maths-multiplication-tf-1',
      kind: 'truefalse',
      statement: '25 × 40 = 1 000.',
      answer: true,
      explain: "Oui : 25 × 4 = 100, et comme 40 c'est 4 dizaines, on ajoute un zéro : 1 000.",
    },
    {
      id: 'cm1-maths-multiplication-fix-1',
      kind: 'fix',
      prompt: "Gribouille s'est trompé, corrige-le",
      words: ['52', '×', '11', '=', '552'],
      wrongIndex: 4,
      correct: '572',
      distractors: ['552', '562'],
      explain: "52 × 1 = 52 et 52 × 10 = 520. Ensemble : 52 + 520 = 572.",
    },
    {
      id: 'cm1-maths-multiplication-pairs-1',
      kind: 'pairs',
      prompt: 'Relie chaque multiplication à son résultat',
      pairs: [
        { a: '12 × 12', b: '144' },
        { a: '15 × 20', b: '300' },
        { a: '21 × 30', b: '630' },
        { a: '13 × 11', b: '143' },
      ],
      explain: "12 × 12 = 144. 15 × 2 = 30 donc 15 × 20 = 300. 21 × 3 = 63 donc 21 × 30 = 630. 13 × 11 = 13 + 130 = 143.",
    },
    {
      id: 'cm1-maths-multiplication-choice-2',
      kind: 'choice',
      prompt: 'Dans 67 × 24, que vaut la deuxième ligne, 67 × 20 ?',
      options: ['134', '268', '1 340'],
      answer: 2,
      explain: "67 × 2 = 134. Comme on multiplie par 2 dizaines, on ajoute un zéro : 1 340.",
    },
    {
      id: 'cm1-maths-multiplication-tap-1',
      kind: 'tapword',
      prompt: 'Touche le résultat de 18 × 15',
      words: ['180', '270', '290'],
      answer: [1],
      explain: "18 × 5 = 90 et 18 × 10 = 180. Ensemble : 90 + 180 = 270.",
    },
    {
      id: 'cm1-maths-multiplication-tf-2',
      kind: 'truefalse',
      statement: 'Pour multiplier par 36, on multiplie par 6, puis par 30, et on additionne les deux lignes.',
      answer: true,
      explain: "Oui : 36, c'est 6 unités et 3 dizaines. Une ligne pour chacune, puis on additionne.",
    },
    {
      id: 'cm1-maths-multiplication-choice-3',
      kind: 'choice',
      prompt: 'Une boîte contient 24 crayons. Combien de crayons dans 15 boîtes ?',
      options: ['340', '390', '360'],
      answer: 2,
      explain: "24 × 15 : 24 × 5 = 120 et 24 × 10 = 240. Ensemble : 120 + 240 = 360 crayons.",
    },
  ],
};

const DIVISION: Lesson = {
  id: 'cm1-maths-division',
  title: 'La division euclidienne',
  subject: 'maths',
  source: 'calcul',
  level: 'CM1',
  notion: 'Poser une division euclidienne à un chiffre au diviseur : quotient et reste',
  theme: 'calcul',
  attendu: 'Poser une division euclidienne à un chiffre au diviseur : quotient et reste.',
  attenduId: 'cm1-calc-division',
  summary:
    "Diviser 47 par 5, c'est chercher combien de fois 5 dans 47 : 9 fois, et il reste 2. On écrit 47 = 5 × 9 + 2. Le 9 est le quotient, le 2 est le reste. Le reste est toujours plus petit que le diviseur.",
  minutes: 8,
  exercises: [
    {
      id: 'cm1-maths-division-choice-1',
      kind: 'choice',
      prompt: '47 = 5 × 9 + 2. Quel est le reste de la division de 47 par 5 ?',
      options: ['9', '2', '5'],
      answer: 1,
      explain: "5 × 9 = 45, et il manque 2 pour arriver à 47 : le reste est 2. Le 9 est le quotient, le 5 est le diviseur.",
    },
    {
      id: 'cm1-maths-division-tf-1',
      kind: 'truefalse',
      statement: 'Dans une division, le reste est toujours plus petit que le diviseur.',
      answer: true,
      explain: "Oui : si le reste était aussi grand que le diviseur, on pourrait encore partager une fois de plus.",
    },
    {
      id: 'cm1-maths-division-blanks-1',
      kind: 'blanks',
      prompt: 'Complète la division de 38 par 6',
      text: '38 = 6 × {{6}} + {{2}}',
      distractors: ['5', '3'],
      explain: "6 × 6 = 36, et 6 × 7 = 42, trop grand. Le quotient est 6 et il reste 38 − 36 = 2.",
    },
    {
      id: 'cm1-maths-division-fix-1',
      kind: 'fix',
      prompt: "Gribouille s'est trompé, corrige-le",
      words: ['52', ':', '7', '=', '7', 'reste', '2'],
      wrongIndex: 6,
      correct: '3',
      distractors: ['2', '4'],
      explain: "7 × 7 = 49. De 49 à 52, il y a 3 : le reste est 3, pas 2.",
    },
    {
      id: 'cm1-maths-division-pairs-1',
      kind: 'pairs',
      prompt: 'Relie chaque division à son quotient',
      pairs: [
        { a: '45 : 9', b: '5' },
        { a: '56 : 8', b: '7' },
        { a: '72 : 6', b: '12' },
        { a: '81 : 9', b: '9' },
      ],
      explain: "Cherche dans les tables : 9 × 5 = 45, 8 × 7 = 56, 6 × 12 = 72, 9 × 9 = 81. Ici, le reste est 0.",
    },
    {
      id: 'cm1-maths-division-sort-1',
      kind: 'sort',
      prompt: 'Range chaque division dans la bonne boîte',
      boxes: ['Reste 0', 'Reste différent de 0'],
      items: [
        { word: '24 : 4', box: 0 },
        { word: '25 : 4', box: 1 },
        { word: '63 : 7', box: 0 },
        { word: '50 : 7', box: 1 },
        { word: '90 : 9', box: 0 },
        { word: '100 : 9', box: 1 },
      ],
      explain: "Le reste est 0 quand le nombre est dans la table du diviseur : 24 = 4 × 6, 63 = 7 × 9, 90 = 9 × 10.",
    },
    {
      id: 'cm1-maths-division-choice-2',
      kind: 'choice',
      prompt: 'On partage 75 billes entre 4 enfants, le plus possible. Combien chacun, et combien en reste-t-il ?',
      options: ['17 billes, il en reste 7', '18 billes, il en reste 3', '19 billes, il en reste 1'],
      answer: 1,
      explain: "4 × 18 = 72, et 4 × 19 = 76, trop grand. Chacun a 18 billes et il en reste 75 − 72 = 3.",
    },
    {
      id: 'cm1-maths-division-order-1',
      kind: 'order',
      prompt: "Remets dans l'ordre les étapes de la division posée 96 : 4",
      lines: [
        'Je prends les 9 dizaines : 9 : 4, ça fait 2, il reste 1',
        "J'abaisse le 6 : il me reste 16",
        '16 : 4, ça fait 4, il reste 0',
        'Le quotient est 24 et le reste est 0',
      ],
      explain: "On commence par le chiffre de gauche, on abaisse le chiffre suivant, et on lit le quotient à la fin.",
    },
    {
      id: 'cm1-maths-division-tf-2',
      kind: 'truefalse',
      statement: 'Dans 100 : 8, le quotient est 12 et le reste est 4.',
      answer: true,
      explain: "Oui : 8 × 12 = 96, et 100 − 96 = 4. Le reste 4 est bien plus petit que 8.",
    },
    {
      id: 'cm1-maths-division-tap-1',
      kind: 'tapword',
      prompt: "Touche l'égalité qui est juste",
      words: ['61 = 8 × 7 + 5', '61 = 8 × 7 + 4', '61 = 8 × 6 + 5'],
      answer: [0],
      explain: "8 × 7 = 56, et 56 + 5 = 61. Les autres donnent 60 et 53.",
    },
  ],
};

const PROBLEMES: Lesson = {
  id: 'cm1-maths-problemes',
  title: 'Problèmes et proportionnalité',
  subject: 'maths',
  source: 'calcul',
  level: 'CM1',
  notion: 'Résoudre des problèmes à plusieurs étapes et des problèmes de proportionnalité simple',
  theme: 'calcul',
  attendu: 'Résoudre des problèmes à plusieurs étapes et des problèmes de proportionnalité simple (recette, prix, vitesse).',
  attenduId: 'cm1-calc-problemes',
  summary:
    "Un problème à plusieurs étapes se résout une étape à la fois, avec une phrase réponse à la fin. En proportionnalité, quand on double une quantité, on double aussi l'autre : si 4 personnes mangent 200 g de pâtes, 8 personnes en mangent 400 g.",
  minutes: 8,
  exercises: [
    {
      id: 'cm1-maths-problemes-choice-1',
      kind: 'choice',
      prompt: 'Une recette pour 4 personnes demande 200 g de farine. Combien de farine pour 8 personnes ?',
      options: ['300 g', '400 g', '800 g'],
      answer: 1,
      explain: "8 personnes, c'est deux fois 4 personnes. Il faut donc deux fois plus de farine : 2 × 200 = 400 g.",
    },
    {
      id: 'cm1-maths-problemes-tf-1',
      kind: 'truefalse',
      statement: 'Si 3 cahiers coûtent 6 €, alors 6 cahiers coûtent 12 €.',
      answer: true,
      explain: "Oui : deux fois plus de cahiers, deux fois plus cher. 6 × 2 = 12 €.",
    },
    {
      id: 'cm1-maths-problemes-order-1',
      kind: 'order',
      prompt: "Marie achète 3 livres à 8 € et 2 cahiers à 2 €. Remets les étapes dans l'ordre pour trouver ce qu'elle dépense",
      lines: [
        'Prix des livres : 3 × 8 = 24 €',
        'Prix des cahiers : 2 × 2 = 4 €',
        'Total : 24 + 4 = 28 €',
        'Réponse : Marie dépense 28 €',
      ],
      explain: "On calcule chaque prix séparément, on additionne, et on termine par la phrase réponse.",
    },
    {
      id: 'cm1-maths-problemes-blanks-1',
      kind: 'blanks',
      prompt: 'Complète le tableau de proportionnalité',
      text: '2 kg de pommes coûtent 5 €. Alors 4 kg coûtent {{10}} € et 6 kg coûtent {{15}} €.',
      distractors: ['20', '12'],
      explain: "4 kg, c'est le double de 2 kg : 2 × 5 = 10 €. 6 kg, c'est le triple : 3 × 5 = 15 €.",
    },
    {
      id: 'cm1-maths-problemes-choice-2',
      kind: 'choice',
      prompt: 'Un car roule à la même vitesse et parcourt 60 km en 1 heure. Quelle distance parcourt-il en 3 heures ?',
      options: ['120 km', '180 km', '63 km'],
      answer: 1,
      explain: "En 3 heures, il parcourt 3 fois plus qu'en 1 heure : 3 × 60 = 180 km.",
    },
    {
      id: 'cm1-maths-problemes-fix-1',
      kind: 'fix',
      prompt: "Gribouille s'est trompé, corrige-le",
      words: ['Pour', '6', 'personnes,', '300 g', 'de', 'riz.', 'Pour', '2', 'personnes,', '150 g'],
      wrongIndex: 9,
      correct: '100 g',
      distractors: ['150 g', '200 g'],
      explain: "2 personnes, c'est 3 fois moins que 6 personnes. Il faut donc 3 fois moins de riz : 300 : 3 = 100 g.",
    },
    {
      id: 'cm1-maths-problemes-pairs-1',
      kind: 'pairs',
      prompt: 'Relie les prix qui vont ensemble',
      pairs: [
        { a: '1 stylo : 2 €', b: '5 stylos : 10 €' },
        { a: '2 pains : 3 €', b: '4 pains : 6 €' },
        { a: '3 billets : 15 €', b: '1 billet : 5 €' },
        { a: '10 œufs : 4 €', b: '5 œufs : 2 €' },
      ],
      explain: "Quand on multiplie ou divise le nombre d'objets, le prix est multiplié ou divisé par le même nombre.",
    },
    {
      id: 'cm1-maths-problemes-choice-3',
      kind: 'choice',
      prompt: 'Paul a 50 €. Il achète 2 jeux à 12 € et un livre à 9 €. Combien lui reste-t-il ?',
      options: ['29 €', '17 €', '26 €'],
      answer: 1,
      explain: "Les jeux : 2 × 12 = 24 €. Avec le livre : 24 + 9 = 33 €. Il reste 50 − 33 = 17 €.",
    },
    {
      id: 'cm1-maths-problemes-tf-2',
      kind: 'truefalse',
      statement: 'Si 5 cahiers coûtent 10 €, alors 1 cahier coûte 5 €.',
      answer: false,
      explain: "Pour 1 cahier, on divise par 5 : 10 : 5 = 2 €. Un cahier coûte 2 €.",
    },
    {
      id: 'cm1-maths-problemes-sort-1',
      kind: 'sort',
      prompt: 'Est-ce une situation de proportionnalité ? Range chaque phrase',
      boxes: ['Proportionnel', 'Pas proportionnel'],
      items: [
        { word: '2 kg : 4 €, 4 kg : 8 €', box: 0 },
        { word: '1 livre : 5 €, 3 livres : 15 €', box: 0 },
        { word: '1 enfant : 6 ans, 2 enfants : 12 ans', box: 1 },
        { word: '3 stylos : 6 €, 6 stylos : 9 €', box: 1 },
      ],
      explain: "C'est proportionnel si, quand on double, tout double. L'âge ne s'additionne pas, et 6 stylos devraient coûter 12 €, pas 9.",
    },
  ],
};

const LONGUEURS: Lesson = {
  id: 'cm1-maths-longueurs',
  title: 'Longueurs et périmètre',
  subject: 'maths',
  source: 'lecon',
  level: 'CM1',
  notion: "Convertir des longueurs du millimètre au kilomètre et calculer le périmètre d'un carré et d'un rectangle",
  theme: 'grandeurs',
  attendu: "Convertir des longueurs du millimètre au kilomètre et calculer le périmètre d'un carré et d'un rectangle.",
  attenduId: 'cm1-gm-longueurs',
  summary:
    "1 km = 1 000 m, 1 m = 10 dm = 100 cm = 1 000 mm. Le périmètre, c'est la longueur du tour d'une figure. Pour un carré, c'est 4 fois le côté. Pour un rectangle, c'est longueur plus largeur, le tout multiplié par 2.",
  minutes: 7,
  exercises: [
    {
      id: 'cm1-maths-longueurs-choice-1',
      kind: 'choice',
      prompt: 'Combien de mètres dans 3 km ?',
      options: ['300 m', '3 000 m', '30 000 m'],
      answer: 1,
      explain: "Kilo veut dire mille : 1 km = 1 000 m, donc 3 km = 3 000 m.",
    },
    {
      id: 'cm1-maths-longueurs-tf-1',
      kind: 'truefalse',
      statement: '1 m = 10 dm = 100 cm = 1 000 mm.',
      answer: true,
      explain: "Oui : à chaque unité plus petite, on multiplie par 10. Déci, c'est dix ; centi, c'est cent ; milli, c'est mille.",
    },
    {
      id: 'cm1-maths-longueurs-blanks-1',
      kind: 'blanks',
      prompt: 'Convertis',
      text: '2 m 50 cm = {{250}} cm, et 4 500 m = {{4}} km 500 m.',
      distractors: ['25', '45'],
      explain: "2 m, c'est 200 cm, plus 50 cm : 250 cm. 4 500 m, c'est 4 000 m et 500 m, donc 4 km 500 m.",
    },
    {
      id: 'cm1-maths-longueurs-pairs-1',
      kind: 'pairs',
      prompt: 'Relie les longueurs égales',
      pairs: [
        { a: '1 km', b: '1 000 m' },
        { a: '1 dm', b: '10 cm' },
        { a: '1 cm', b: '10 mm' },
        { a: '1 m', b: '100 cm' },
      ],
      explain: "Du kilomètre au millimètre, chaque unité vaut 10 fois la suivante, sauf du km au m où il y a trois sauts : 1 000.",
    },
    {
      id: 'cm1-maths-longueurs-choice-2',
      kind: 'choice',
      prompt: "Quel est le périmètre d'un rectangle de 7 cm de long et 4 cm de large ?",
      options: ['11 cm', '22 cm', '28 cm'],
      answer: 1,
      explain: "Le tour, c'est 7 + 4 + 7 + 4. Donc (7 + 4) × 2 = 22 cm. 28, ce serait 7 × 4, ce n'est pas le périmètre.",
    },
    {
      id: 'cm1-maths-longueurs-fix-1',
      kind: 'fix',
      prompt: "Gribouille s'est trompé, corrige-le",
      words: ['Carré', 'de', '6 cm', 'de', 'côté', ':', 'périmètre', '12 cm'],
      wrongIndex: 7,
      correct: '24 cm',
      distractors: ['12 cm', '36 cm'],
      explain: "Un carré a 4 côtés égaux. Le périmètre, c'est 4 × 6 = 24 cm.",
    },
    {
      id: 'cm1-maths-longueurs-sort-1',
      kind: 'sort',
      prompt: 'Range chaque longueur dans la bonne boîte',
      boxes: ['Plus court que 1 m', 'Plus long que 1 m'],
      items: [
        { word: '85 cm', box: 0 },
        { word: '12 dm', box: 1 },
        { word: '999 mm', box: 0 },
        { word: '1 km', box: 1 },
        { word: '150 cm', box: 1 },
        { word: '9 dm', box: 0 },
      ],
      explain: "Convertis tout en mètres : 1 m, c'est 10 dm, 100 cm ou 1 000 mm. 12 dm, c'est 1 m 20 cm ; 999 mm, c'est juste en dessous de 1 m.",
    },
    {
      id: 'cm1-maths-longueurs-tf-2',
      kind: 'truefalse',
      statement: 'Un rectangle de 10 m sur 5 m a un périmètre de 30 m.',
      answer: true,
      explain: "Oui : 10 + 5 = 15, et 15 × 2 = 30 m.",
    },
    {
      id: 'cm1-maths-longueurs-choice-3',
      kind: 'choice',
      prompt: "Un terrain carré a un périmètre de 100 m. Combien mesure un côté ?",
      options: ['20 m', '50 m', '25 m'],
      answer: 2,
      explain: "Les 4 côtés sont égaux. On partage 100 m en 4 : 100 : 4 = 25 m.",
    },
    {
      id: 'cm1-maths-longueurs-line-1',
      kind: 'numberline',
      prompt: 'Place 750 m sur la droite graduée en mètres',
      min: 0,
      max: 1000,
      step: 250,
      answer: 750,
      explain: "La droite va de 0 à 1 000 m, et chaque graduation vaut 250 m. 750 m, c'est 3 graduations après 0.",
    },
  ],
};

const MASSES_CONTENANCES: Lesson = {
  id: 'cm1-maths-masses',
  title: 'Masses et contenances',
  subject: 'maths',
  source: 'lecon',
  level: 'CM1',
  notion: 'Convertir des masses (g, kg, tonne) et des contenances (mL, cL, dL, L)',
  theme: 'grandeurs',
  attendu: 'Convertir des masses (g, kg, tonne) et des contenances (mL, cL, dL, L).',
  attenduId: 'cm1-gm-masses',
  summary:
    "Pour les masses : 1 tonne = 1 000 kg et 1 kg = 1 000 g. Pour les contenances : 1 L = 10 dL = 100 cL = 1 000 mL. Une bouteille de 1,5 L contient 150 cL.",
  minutes: 6,
  exercises: [
    {
      id: 'cm1-maths-masses-choice-1',
      kind: 'choice',
      prompt: 'Combien de grammes dans 2 kg ?',
      options: ['200 g', '2 000 g', '20 000 g'],
      answer: 1,
      explain: "1 kg = 1 000 g, donc 2 kg = 2 000 g.",
    },
    {
      id: 'cm1-maths-masses-tf-1',
      kind: 'truefalse',
      statement: '1 tonne = 1 000 kg.',
      answer: true,
      explain: "Oui : la tonne sert pour les très grosses masses, comme un camion ou un éléphant. 1 t = 1 000 kg.",
    },
    {
      id: 'cm1-maths-masses-blanks-1',
      kind: 'blanks',
      prompt: 'Complète les contenances',
      text: '1 L = {{10}} dL = {{100}} cL = {{1 000}} mL',
      distractors: ['20', '500'],
      explain: "Comme pour les longueurs : déci, c'est dix fois plus petit ; centi, cent fois ; milli, mille fois.",
    },
    {
      id: 'cm1-maths-masses-pairs-1',
      kind: 'pairs',
      prompt: 'Relie les mesures égales',
      pairs: [
        { a: '3 kg 500 g', b: '3 500 g' },
        { a: '2 L', b: '200 cL' },
        { a: '1 500 kg', b: '1 t 500 kg' },
        { a: '25 cL', b: '250 mL' },
      ],
      explain: "3 kg = 3 000 g, plus 500 g. 1 L = 100 cL. 1 000 kg = 1 t. 1 cL = 10 mL.",
    },
    {
      id: 'cm1-maths-masses-sort-1',
      kind: 'sort',
      prompt: 'Masse ou contenance ? Range chaque unité',
      boxes: ['Masse', 'Contenance'],
      items: [
        { word: 'kilogramme', box: 0 },
        { word: 'litre', box: 1 },
        { word: 'tonne', box: 0 },
        { word: 'centilitre', box: 1 },
        { word: 'gramme', box: 0 },
        { word: 'millilitre', box: 1 },
      ],
      explain: "La masse se pèse, en grammes, kilogrammes ou tonnes. La contenance se mesure en litres et ses divisions.",
    },
    {
      id: 'cm1-maths-masses-fix-1',
      kind: 'fix',
      prompt: "Gribouille s'est trompé, corrige-le",
      words: ['Une', 'bouteille', 'de', '1,5 L', 'contient', '15 cL'],
      wrongIndex: 5,
      correct: '150 cL',
      distractors: ['15 cL', '1 500 cL'],
      explain: "1 L = 100 cL. Un litre et demi, c'est 100 cL + 50 cL = 150 cL.",
    },
    {
      id: 'cm1-maths-masses-choice-2',
      kind: 'choice',
      prompt: 'Un camion pèse 3 t 200 kg. Combien de kilogrammes cela fait-il ?',
      options: ['320 kg', '3 200 kg', '32 000 kg'],
      answer: 1,
      explain: "3 t = 3 000 kg. Avec les 200 kg : 3 200 kg.",
    },
    {
      id: 'cm1-maths-masses-tf-2',
      kind: 'truefalse',
      statement: "50 cL, c'est la moitié d'un litre.",
      answer: true,
      explain: "Oui : 1 L = 100 cL, et la moitié de 100, c'est 50.",
    },
    {
      id: 'cm1-maths-masses-choice-3',
      kind: 'choice',
      prompt: 'Un sac contient 4 paquets de 250 g de sucre. Quelle est la masse de sucre en tout ?',
      options: ['500 g', '1 kg', '2 kg'],
      answer: 1,
      explain: "4 × 250 g = 1 000 g, et 1 000 g, c'est 1 kg.",
    },
    {
      id: 'cm1-maths-masses-card-1',
      kind: 'flashcard',
      prompt: 'Lis la question, réfléchis, puis retourne la carte',
      front: 'Combien de millilitres dans 1 cL ?',
      back: '10 mL. Un litre fait 100 cL et aussi 1 000 mL : chaque centilitre vaut donc 10 millilitres.',
      explain: "Pense à une petite cuillère : environ 5 mL, c'est un demi-centilitre.",
    },
  ],
};

const DUREES: Lesson = {
  id: 'cm1-maths-durees',
  title: 'Les durées',
  subject: 'maths',
  source: 'lecon',
  level: 'CM1',
  notion: 'Convertir et calculer des durées ; lire un horaire ; siècle et année',
  theme: 'grandeurs',
  attendu: 'Convertir et calculer des durées (secondes, minutes, heures, jours) ; lire un horaire.',
  attenduId: 'cm1-gm-durees',
  summary:
    "1 h = 60 min et 1 min = 60 s. Pour convertir 1 h 45 min en minutes : 60 + 45 = 105 min. Pour calculer une durée entre deux horaires, on avance par étapes jusqu'à l'heure ronde, puis jusqu'à l'arrivée. Un siècle, c'est 100 ans.",
  minutes: 7,
  exercises: [
    {
      id: 'cm1-maths-durees-choice-1',
      kind: 'choice',
      prompt: 'Combien de minutes dans 1 h 45 min ?',
      options: ['145 min', '105 min', '95 min'],
      answer: 1,
      explain: "1 h = 60 min. 60 + 45 = 105 min. Attention, on ne colle pas les nombres : 145 serait faux.",
    },
    {
      id: 'cm1-maths-durees-tf-1',
      kind: 'truefalse',
      statement: '2 min = 120 s.',
      answer: true,
      explain: "Oui : 1 min = 60 s, donc 2 min = 2 × 60 = 120 s.",
    },
    {
      id: 'cm1-maths-durees-blanks-1',
      kind: 'blanks',
      prompt: 'Complète',
      text: '1 jour = {{24}} h, 1 h = {{60}} min, 1 siècle = {{100}} ans.',
      distractors: ['12', '1 000'],
      explain: "Une journée complète fait 24 heures, une heure 60 minutes, et un siècle 100 années.",
    },
    {
      id: 'cm1-maths-durees-choice-2',
      kind: 'choice',
      prompt: 'Le train part à 9 h 40 et arrive à 11 h 10. Combien de temps dure le trajet ?',
      options: ['2 h 30 min', '1 h 30 min', '1 h 10 min'],
      answer: 1,
      explain: "De 9 h 40 à 10 h : 20 min. De 10 h à 11 h : 1 h. De 11 h à 11 h 10 : 10 min. En tout : 1 h 30 min.",
    },
    {
      id: 'cm1-maths-durees-fix-1',
      kind: 'fix',
      prompt: "Gribouille s'est trompé, corrige-le",
      words: ['150 min', '=', '2 h', '50 min'],
      wrongIndex: 3,
      correct: '30 min',
      distractors: ['50 min', '15 min'],
      explain: "2 h = 120 min. Il reste 150 − 120 = 30 min. Donc 150 min = 2 h 30 min.",
    },
    {
      id: 'cm1-maths-durees-pairs-1',
      kind: 'pairs',
      prompt: 'Relie les durées égales',
      pairs: [
        { a: '90 min', b: '1 h 30 min' },
        { a: '1 h 15 min', b: '75 min' },
        { a: '3 h', b: '180 min' },
        { a: '1 min 30 s', b: '90 s' },
      ],
      explain: "Pour passer des heures aux minutes, on multiplie par 60. Des minutes aux secondes aussi.",
    },
    {
      id: 'cm1-maths-durees-sort-1',
      kind: 'sort',
      prompt: 'Range chaque durée dans la bonne boîte',
      boxes: ["Plus court qu'une heure", "Plus long qu'une heure"],
      items: [
        { word: '45 min', box: 0 },
        { word: '70 min', box: 1 },
        { word: '1 000 s', box: 0 },
        { word: '1 h 05 min', box: 1 },
        { word: '59 min', box: 0 },
        { word: '100 min', box: 1 },
      ],
      explain: "Une heure, c'est 60 min ou 3 600 s. 1 000 s, c'est un peu plus de 16 min, bien moins qu'une heure.",
    },
    {
      id: 'cm1-maths-durees-tf-2',
      kind: 'truefalse',
      statement: 'Un match commence à 14 h 50 et dure 40 minutes. Il se termine à 15 h 30.',
      answer: true,
      explain: "Oui : de 14 h 50 à 15 h, il y a 10 min. Il reste 30 min à ajouter : 15 h 30.",
    },
    {
      id: 'cm1-maths-durees-choice-3',
      kind: 'choice',
      prompt: "Combien d'années dans 3 siècles ?",
      options: ['30', '300', '3 000'],
      answer: 1,
      explain: "Un siècle, c'est 100 ans. 3 × 100 = 300 ans.",
    },
    {
      id: 'cm1-maths-durees-order-1',
      kind: 'order',
      prompt: 'Range ces durées de la plus courte à la plus longue',
      lines: ['1 minute', '1 heure', '1 jour', '1 semaine', '1 siècle'],
      explain: "Une minute tient dans une heure, une heure dans un jour, un jour dans une semaine, et un siècle fait 100 ans.",
    },
  ],
};

const AIRES: Lesson = {
  id: 'cm1-maths-aires',
  title: 'Les aires',
  subject: 'maths',
  source: 'lecon',
  level: 'CM1',
  notion: 'Comparer et mesurer des aires en comptant des carreaux ; distinguer aire et périmètre',
  theme: 'grandeurs',
  attendu: 'Comparer et mesurer des aires en comptant des carreaux ; distinguer aire et périmètre.',
  attenduId: 'cm1-gm-aires',
  summary:
    "L'aire, c'est la mesure de la surface à l'intérieur d'une figure : on la trouve en comptant les carreaux. Le périmètre, c'est la longueur du tour. Un rectangle de 5 carreaux sur 3 a une aire de 15 carreaux. Avec des carreaux de 1 cm de côté, on compte en cm².",
  minutes: 7,
  exercises: [
    {
      id: 'cm1-maths-aires-choice-1',
      kind: 'choice',
      prompt: 'Un rectangle mesure 5 carreaux de long et 3 carreaux de large. Quelle est son aire ?',
      options: ['8 carreaux', '15 carreaux', '16 carreaux'],
      answer: 1,
      explain: "Il y a 3 rangées de 5 carreaux : 3 × 5 = 15 carreaux. 16 serait le périmètre.",
    },
    {
      id: 'cm1-maths-aires-tf-1',
      kind: 'truefalse',
      statement: "L'aire, c'est la mesure de la surface, à l'intérieur de la figure.",
      answer: true,
      explain: "Oui : l'aire, c'est ce qu'on peut couvrir, comme la moquette d'une pièce. Le tour, c'est le périmètre.",
    },
    {
      id: 'cm1-maths-aires-count-1',
      kind: 'count',
      prompt: 'Compte les carreaux qui couvrent cette figure',
      emoji: '🟦',
      answer: 12,
      options: [10, 12, 14],
      explain: "Chaque carreau compte pour 1. En les comptant un par un, ou par rangées, on trouve 12 carreaux.",
    },
    {
      id: 'cm1-maths-aires-blanks-1',
      kind: 'blanks',
      prompt: 'Complète pour un carré de 3 cm de côté',
      text: "Un carré de 3 cm de côté a une aire de {{9}} cm² et un périmètre de {{12}} cm.",
      distractors: ['6', '3'],
      explain: "L'aire : 3 rangées de 3 carreaux de 1 cm², soit 9 cm². Le périmètre : 4 × 3 = 12 cm.",
    },
    {
      id: 'cm1-maths-aires-sort-1',
      kind: 'sort',
      prompt: 'Aire ou périmètre ? Range chaque phrase',
      boxes: ['Aire', 'Périmètre'],
      items: [
        { word: 'la longueur du tour', box: 1 },
        { word: "le nombre de carreaux à l'intérieur", box: 0 },
        { word: 'se mesure en cm²', box: 0 },
        { word: 'se mesure en cm', box: 1 },
        { word: "la clôture autour d'un champ", box: 1 },
        { word: 'la moquette qui couvre le sol', box: 0 },
      ],
      explain: "Ce qui fait le tour, c'est le périmètre, en cm ou en m. Ce qui recouvre, c'est l'aire, en cm² ou en carreaux.",
    },
    {
      id: 'cm1-maths-aires-fix-1',
      kind: 'fix',
      prompt: "Gribouille s'est trompé, corrige-le",
      words: ['Rectangle', 'de', '6', 'carreaux', 'sur', '2', ':', 'aire', '=', '16 carreaux'],
      wrongIndex: 9,
      correct: '12 carreaux',
      distractors: ['16 carreaux', '8 carreaux'],
      explain: "2 rangées de 6 carreaux, c'est 12 carreaux. 16, c'est le périmètre : (6 + 2) × 2.",
    },
    {
      id: 'cm1-maths-aires-choice-2',
      kind: 'choice',
      prompt: 'Deux figures ont le même périmètre. Ont-elles forcément la même aire ?',
      options: ['Oui, toujours', 'Non, pas forcément', 'Seulement si ce sont des carrés'],
      answer: 1,
      explain: "Non : un rectangle de 7 sur 1 et un carré de 4 ont tous les deux un périmètre de 16, mais des aires de 7 et de 16.",
    },
    {
      id: 'cm1-maths-aires-tf-2',
      kind: 'truefalse',
      statement: 'Un rectangle de 8 cm sur 2 cm et un carré de 4 cm de côté ont la même aire.',
      answer: true,
      explain: "Oui : 8 × 2 = 16 cm² et 4 × 4 = 16 cm². Même aire, mais pas le même périmètre : 20 cm et 16 cm.",
    },
    {
      id: 'cm1-maths-aires-pairs-1',
      kind: 'pairs',
      prompt: 'Relie chaque figure à son aire',
      pairs: [
        { a: 'Carré de 5 cm de côté', b: '25 cm²' },
        { a: 'Rectangle de 6 cm sur 2 cm', b: '12 cm²' },
        { a: 'Carré de 2 cm de côté', b: '4 cm²' },
        { a: 'Rectangle de 10 cm sur 3 cm', b: '30 cm²' },
      ],
      explain: "Pour un carré ou un rectangle, l'aire, c'est le nombre de rangées fois le nombre de carreaux par rangée.",
    },
    {
      id: 'cm1-maths-aires-choice-3',
      kind: 'choice',
      prompt: 'Une figure est faite de 7 carreaux entiers et de 2 demi-carreaux. Quelle est son aire ?',
      options: ['9 carreaux', '8 carreaux', '7 carreaux'],
      answer: 1,
      explain: "Deux demi-carreaux font un carreau entier. 7 + 1 = 8 carreaux.",
    },
  ],
};

const ANGLES: Lesson = {
  id: 'cm1-maths-angles',
  title: 'Les angles',
  subject: 'maths',
  source: 'lecon',
  level: 'CM1',
  notion: "Comparer des angles ; reconnaître un angle droit, aigu ou obtus avec l'équerre",
  theme: 'grandeurs',
  attendu: "Comparer des angles ; reconnaître un angle droit, aigu ou obtus avec l'équerre.",
  attenduId: 'cm1-gm-angles',
  summary:
    "Un angle, c'est l'ouverture entre deux côtés qui partent du même point. L'angle droit est celui de l'équerre, comme le coin d'une feuille. Un angle plus fermé que l'angle droit est aigu. Un angle plus ouvert est obtus.",
  minutes: 6,
  exercises: [
    {
      id: 'cm1-maths-angles-choice-1',
      kind: 'choice',
      prompt: "Comment s'appelle l'angle qui est exactement celui de l'équerre ?",
      options: ['Angle aigu', 'Angle droit', 'Angle obtus'],
      answer: 1,
      explain: "L'équerre sert à vérifier les angles droits, comme les coins d'une feuille ou d'un carré.",
    },
    {
      id: 'cm1-maths-angles-tf-1',
      kind: 'truefalse',
      statement: "Un angle aigu est plus petit qu'un angle droit.",
      answer: true,
      explain: "Oui : aigu veut dire pointu. L'angle est plus fermé que celui de l'équerre.",
    },
    {
      id: 'cm1-maths-angles-sort-1',
      kind: 'sort',
      prompt: 'Range chaque angle dans la bonne boîte',
      boxes: ['Aigu', 'Droit', 'Obtus'],
      items: [
        { word: "le coin d'une feuille", box: 1 },
        { word: "la pointe d'une flèche", box: 0 },
        { word: 'les aiguilles à 3 h', box: 1 },
        { word: 'les aiguilles à 1 h', box: 0 },
        { word: 'les aiguilles à 4 h', box: 2 },
        { word: "un angle plus ouvert que l'équerre", box: 2 },
      ],
      explain: "À 3 h, les aiguilles forment un angle droit. Avant 3 h, l'angle est plus fermé, aigu ; après, il est plus ouvert, obtus.",
    },
    {
      id: 'cm1-maths-angles-blanks-1',
      kind: 'blanks',
      prompt: 'Complète la règle',
      text: "Pour vérifier un angle droit, j'utilise l'{{équerre}}. Un angle plus ouvert qu'un angle droit est {{obtus}}.",
      distractors: ['règle', 'aigu'],
      explain: "L'équerre a un angle droit tout prêt. Plus ouvert que l'angle droit, c'est obtus ; plus fermé, c'est aigu.",
    },
    {
      id: 'cm1-maths-angles-fix-1',
      kind: 'fix',
      prompt: "Gribouille s'est trompé, corrige-le",
      words: ['Un', 'angle', 'obtus', 'est', 'plus', 'petit', "qu'un", 'angle', 'droit'],
      wrongIndex: 5,
      correct: 'grand',
      distractors: ['petit', 'fin'],
      explain: "Obtus veut dire large, ouvert : un angle obtus est plus grand qu'un angle droit.",
    },
    {
      id: 'cm1-maths-angles-pairs-1',
      kind: 'pairs',
      prompt: 'Relie chaque angle à sa description',
      pairs: [
        { a: 'Angle droit', b: "comme le coin d'un carré" },
        { a: 'Angle aigu', b: "plus fermé que l'équerre" },
        { a: 'Angle obtus', b: "plus ouvert que l'équerre" },
      ],
      explain: "On compare toujours à l'angle droit de l'équerre : égal, plus fermé ou plus ouvert.",
    },
    {
      id: 'cm1-maths-angles-tf-2',
      kind: 'truefalse',
      statement: 'Un carré a quatre angles droits.',
      answer: true,
      explain: "Oui : chaque coin d'un carré est un angle droit. C'est aussi vrai pour le rectangle.",
    },
    {
      id: 'cm1-maths-angles-choice-2',
      kind: 'choice',
      prompt: "Combien d'angles droits a un triangle rectangle ?",
      options: ['Un', 'Deux', 'Trois'],
      answer: 0,
      explain: "Un triangle rectangle a exactement un angle droit. Les deux autres angles sont aigus.",
    },
    {
      id: 'cm1-maths-angles-tap-1',
      kind: 'tapword',
      prompt: 'Touche les figures qui ont toujours des angles droits',
      words: ['rectangle', 'triangle équilatéral', 'carré', 'cercle'],
      answer: [0, 2],
      explain: "Le rectangle et le carré ont quatre angles droits. Le triangle équilatéral a trois angles aigus, et le cercle n'a pas d'angle.",
    },
    {
      id: 'cm1-maths-angles-choice-3',
      kind: 'choice',
      prompt: "Les aiguilles d'une horloge à 3 h forment quel angle ?",
      options: ['Aigu', 'Obtus', 'Droit'],
      answer: 2,
      explain: "À 3 h, la petite aiguille est sur le 3 et la grande sur le 12 : un quart de tour, c'est un angle droit.",
    },
  ],
};

const FIGURES: Lesson = {
  id: 'cm1-maths-figures',
  title: 'Droites et figures',
  subject: 'maths',
  source: 'lecon',
  level: 'CM1',
  notion: 'Reconnaître droites perpendiculaires et parallèles ; décrire triangles, quadrilatères particuliers et cercle',
  theme: 'geometrie',
  attendu: 'Reconnaître droites perpendiculaires et parallèles ; décrire et tracer polygones, triangles et quadrilatères particuliers, cercle.',
  attenduId: 'cm1-geo-figures',
  summary:
    "Deux droites perpendiculaires se coupent en formant un angle droit. Deux droites parallèles ne se croisent jamais. Le triangle isocèle a deux côtés égaux, l'équilatéral trois, le triangle rectangle a un angle droit. Le losange a quatre côtés égaux. Dans un cercle, le diamètre est le double du rayon.",
  minutes: 8,
  exercises: [
    {
      id: 'cm1-maths-figures-choice-1',
      kind: 'choice',
      prompt: 'Deux droites qui se coupent en formant un angle droit sont…',
      options: ['parallèles', 'perpendiculaires', 'sécantes sans angle droit'],
      answer: 1,
      explain: "Perpendiculaires, c'est le mot pour deux droites qui se croisent en angle droit, comme le coin de l'équerre.",
    },
    {
      id: 'cm1-maths-figures-tf-1',
      kind: 'truefalse',
      statement: 'Deux droites parallèles ne se croisent jamais.',
      answer: true,
      explain: "Oui : elles gardent toujours le même écart, comme les deux rails d'une voie de train.",
    },
    {
      id: 'cm1-maths-figures-sort-1',
      kind: 'sort',
      prompt: 'Range chaque indice dans la boîte du bon triangle',
      boxes: ['Triangle isocèle', 'Triangle équilatéral', 'Triangle rectangle'],
      items: [
        { word: 'deux côtés de même longueur', box: 0 },
        { word: 'trois côtés de même longueur', box: 1 },
        { word: 'un angle droit', box: 2 },
        { word: 'trois angles égaux', box: 1 },
        { word: "je le vérifie avec l'équerre", box: 2 },
        { word: 'deux angles égaux', box: 0 },
      ],
      explain: "Isocèle : deux côtés et deux angles égaux. Équilatéral : tout est égal. Rectangle : un angle droit, à vérifier avec l'équerre.",
    },
    {
      id: 'cm1-maths-figures-blanks-1',
      kind: 'blanks',
      prompt: 'Complète avec le nom de la figure',
      text: 'Le {{losange}} a quatre côtés de même longueur. Le {{rectangle}} a quatre angles droits et ses côtés opposés sont de même longueur.',
      distractors: ['triangle', 'cercle'],
      explain: "Le losange, c'est quatre côtés égaux. Le rectangle, c'est quatre angles droits. Le carré a les deux à la fois.",
    },
    {
      id: 'cm1-maths-figures-order-1',
      kind: 'order',
      prompt: "Remets dans l'ordre le programme de construction d'un carré ABCD de 4 cm de côté",
      lines: [
        'Trace un segment AB de 4 cm',
        'Trace la perpendiculaire à AB qui passe par A, et celle qui passe par B',
        'Sur ces perpendiculaires, place D à 4 cm de A et C à 4 cm de B',
        'Relie C et D : ABCD est un carré',
      ],
      explain: "On commence par un côté, on trace les perpendiculaires aux deux bouts, on reporte la longueur, et on ferme la figure.",
    },
    {
      id: 'cm1-maths-figures-fix-1',
      kind: 'fix',
      prompt: "Gribouille s'est trompé, corrige-le",
      words: ['Le', 'diamètre', 'est', 'deux', 'fois', 'plus', 'court', 'que', 'le', 'rayon'],
      wrongIndex: 6,
      correct: 'long',
      distractors: ['court', 'large'],
      explain: "Le rayon va du centre au bord. Le diamètre traverse tout le cercle en passant par le centre : c'est deux rayons, donc deux fois plus long.",
    },
    {
      id: 'cm1-maths-figures-pairs-1',
      kind: 'pairs',
      prompt: 'Relie chaque mot à sa définition',
      pairs: [
        { a: 'Rayon', b: "du centre à un point du cercle" },
        { a: 'Diamètre', b: 'traverse le cercle en passant par le centre' },
        { a: 'Carré', b: '4 côtés égaux et 4 angles droits' },
        { a: 'Losange', b: "4 côtés égaux, pas forcément d'angle droit" },
      ],
      explain: "Le compas trace un cercle : l'écart du compas, c'est le rayon. Le carré est un losange qui a en plus des angles droits.",
    },
    {
      id: 'cm1-maths-figures-tf-2',
      kind: 'truefalse',
      statement: "Si le rayon d'un cercle mesure 3 cm, son diamètre mesure 6 cm.",
      answer: true,
      explain: "Oui : le diamètre, c'est deux fois le rayon. 2 × 3 = 6 cm.",
    },
    {
      id: 'cm1-maths-figures-choice-2',
      kind: 'choice',
      prompt: "Un polygone à 5 côtés s'appelle…",
      options: ['un hexagone', 'un pentagone', 'un quadrilatère'],
      answer: 1,
      explain: "Penta veut dire cinq : le pentagone a 5 côtés. L'hexagone en a 6, le quadrilatère 4.",
    },
    {
      id: 'cm1-maths-figures-tap-1',
      kind: 'tapword',
      prompt: 'Touche les quadrilatères',
      words: ['carré', 'triangle', 'losange', 'cercle', 'rectangle'],
      answer: [0, 2, 4],
      explain: "Un quadrilatère a quatre côtés : carré, losange, rectangle. Le triangle en a trois, et le cercle n'a pas de côté.",
    },
  ],
};

const SYMETRIE: Lesson = {
  id: 'cm1-maths-symetrie',
  title: 'La symétrie axiale',
  subject: 'maths',
  source: 'lecon',
  level: 'CM1',
  notion: "Compléter une figure par symétrie axiale sur quadrillage ; trouver les axes de symétrie d'une figure",
  theme: 'geometrie',
  attendu: "Compléter une figure par symétrie axiale sur quadrillage ; trouver les axes de symétrie d'une figure.",
  attenduId: 'cm1-geo-symetrie',
  summary:
    "Une figure a un axe de symétrie quand on peut la plier le long de cet axe et que les deux moitiés se superposent exactement. Sur un quadrillage, chaque point et son symétrique sont à la même distance de l'axe, de chaque côté. Un carré a 4 axes, un rectangle en a 2.",
  minutes: 6,
  exercises: [
    {
      id: 'cm1-maths-symetrie-choice-1',
      kind: 'choice',
      prompt: 'Une figure a un axe de symétrie si…',
      options: ['elle a quatre côtés', 'on peut la plier en deux parties qui se superposent exactement', 'on peut la faire tourner'],
      answer: 1,
      explain: "L'axe de symétrie, c'est la ligne de pliage : les deux moitiés se recouvrent parfaitement, comme les ailes d'un papillon.",
    },
    {
      id: 'cm1-maths-symetrie-tf-1',
      kind: 'truefalse',
      statement: 'Un carré a 4 axes de symétrie.',
      answer: true,
      explain: "Oui : deux axes qui passent par le milieu des côtés, et deux axes qui suivent les diagonales.",
    },
    {
      id: 'cm1-maths-symetrie-sort-1',
      kind: 'sort',
      prompt: 'Cette lettre majuscule a-t-elle un axe de symétrie ? Range-la',
      boxes: ['A un axe de symétrie', "N'en a pas"],
      items: [
        { word: 'A', box: 0 },
        { word: 'F', box: 1 },
        { word: 'H', box: 0 },
        { word: 'G', box: 1 },
        { word: 'M', box: 0 },
        { word: 'P', box: 1 },
      ],
      explain: "A et M se plient en deux verticalement, H se plie dans les deux sens. F, G et P n'ont aucune ligne de pliage.",
    },
    {
      id: 'cm1-maths-symetrie-blanks-1',
      kind: 'blanks',
      prompt: 'Complète la règle',
      text: "Dans une symétrie, un point et son symétrique sont à la {{même}} distance de l'axe. Le symétrique d'un point placé sur l'axe est {{lui-même}}.",
      distractors: ['double', 'le centre'],
      explain: "L'axe est comme un miroir : chaque point se retrouve en face, à la même distance. Un point sur le miroir ne bouge pas.",
    },
    {
      id: 'cm1-maths-symetrie-fix-1',
      kind: 'fix',
      prompt: "Gribouille s'est trompé, corrige-le",
      words: ['Un', 'rectangle', 'a', '4', 'axes', 'de', 'symétrie'],
      wrongIndex: 3,
      correct: '2',
      distractors: ['4', '1'],
      explain: "Le rectangle a 2 axes, qui passent par le milieu des côtés. Ses diagonales ne sont pas des axes : en pliant, les coins ne se superposent pas.",
    },
    {
      id: 'cm1-maths-symetrie-choice-2',
      kind: 'choice',
      prompt: "Sur un quadrillage, l'axe est vertical. Un point est à 3 carreaux à gauche de l'axe. Où est son symétrique ?",
      options: ["sur l'axe", "à 3 carreaux à droite de l'axe", "à 6 carreaux à gauche de l'axe"],
      answer: 1,
      explain: "Le symétrique est de l'autre côté de l'axe, à la même distance : 3 carreaux à droite, sur la même ligne.",
    },
    {
      id: 'cm1-maths-symetrie-pairs-1',
      kind: 'pairs',
      prompt: "Relie chaque figure à son nombre d'axes de symétrie",
      pairs: [
        { a: 'Carré', b: '4 axes' },
        { a: 'Rectangle', b: '2 axes' },
        { a: 'Triangle équilatéral', b: '3 axes' },
        { a: 'Triangle isocèle', b: '1 axe' },
      ],
      explain: "Plus une figure est régulière, plus elle a d'axes. Le triangle isocèle n'en a qu'un, qui passe par sa pointe.",
    },
    {
      id: 'cm1-maths-symetrie-tf-2',
      kind: 'truefalse',
      statement: "Le symétrique d'un segment de 5 carreaux mesure aussi 5 carreaux.",
      answer: true,
      explain: "Oui : la symétrie garde les longueurs. La figure symétrique a exactement la même taille.",
    },
    {
      id: 'cm1-maths-symetrie-tap-1',
      kind: 'tapword',
      prompt: 'Touche les chiffres qui ont un axe de symétrie',
      words: ['0', '7', '8', '2'],
      answer: [0, 2],
      explain: "Le 0 et le 8 se plient en deux, dans les deux sens. Le 7 et le 2 n'ont pas de ligne de pliage.",
    },
    {
      id: 'cm1-maths-symetrie-choice-3',
      kind: 'choice',
      prompt: "L'axe est horizontal. Un point est à 2 carreaux au-dessus de l'axe. Où est son symétrique ?",
      options: ['2 carreaux au-dessus', '2 carreaux en dessous', '4 carreaux en dessous'],
      answer: 1,
      explain: "On traverse l'axe et on compte la même distance de l'autre côté : 2 carreaux en dessous.",
    },
  ],
};

const SOLIDES: Lesson = {
  id: 'cm1-maths-solides',
  title: 'Solides et patrons',
  subject: 'maths',
  source: 'lecon',
  level: 'CM1',
  notion: "Décrire cube, pavé, prisme, pyramide, cylindre, cône et boule ; reconnaître le patron d'un cube",
  theme: 'geometrie',
  attendu: "Décrire cube, pavé, prisme, pyramide, cylindre, cône et boule ; reconnaître le patron d'un cube.",
  attenduId: 'cm1-geo-solides',
  summary:
    "Un solide a des faces, des arêtes et des sommets. Le cube a 6 faces carrées, 12 arêtes et 8 sommets. Le prisme a deux bases identiques, la pyramide une seule base et une pointe. Le cylindre, le cône et la boule peuvent rouler. Le patron d'un cube, c'est le cube déplié : 6 carrés qu'on peut replier pour le fermer.",
  minutes: 6,
  exercises: [
    {
      id: 'cm1-maths-solides-choice-1',
      kind: 'choice',
      prompt: 'Quel solide a 6 faces carrées toutes pareilles ?',
      options: ['le pavé', 'le cube', 'la pyramide'],
      answer: 1,
      explain: "Le cube, comme un dé : 6 faces carrées identiques. Le pavé a aussi 6 faces, mais ce sont des rectangles.",
    },
    {
      id: 'cm1-maths-solides-tf-1',
      kind: 'truefalse',
      statement: "Un cône a une seule face plate, qui est un disque.",
      answer: true,
      explain: "Oui : le cône est posé sur un disque, et le reste est arrondi jusqu'à la pointe, comme un chapeau de fête.",
    },
    {
      id: 'cm1-maths-solides-sort-1',
      kind: 'sort',
      prompt: 'Range chaque solide dans la bonne boîte',
      boxes: ['Ne roule pas : que des faces planes', 'Peut rouler'],
      items: [
        { word: 'cube', box: 0 },
        { word: 'boule', box: 1 },
        { word: 'prisme', box: 0 },
        { word: 'cylindre', box: 1 },
        { word: 'pyramide', box: 0 },
        { word: 'cône', box: 1 },
      ],
      explain: "Les solides avec seulement des faces planes, les polyèdres, ne roulent pas. Ceux qui ont une partie arrondie peuvent rouler.",
    },
    {
      id: 'cm1-maths-solides-blanks-1',
      kind: 'blanks',
      prompt: 'Complète la description du cube',
      text: 'Un cube a {{6}} faces, {{12}} arêtes et {{8}} sommets.',
      distractors: ['4', '10'],
      explain: "6 faces comme un dé, 8 sommets qui sont les coins, et 12 arêtes qui sont les bords entre deux faces.",
    },
    {
      id: 'cm1-maths-solides-pairs-1',
      kind: 'pairs',
      prompt: 'Relie chaque objet au solide qui lui ressemble',
      pairs: [
        { a: 'Boîte de conserve', b: 'cylindre' },
        { a: 'Ballon', b: 'boule' },
        { a: 'Dé à jouer', b: 'cube' },
        { a: 'Chapeau pointu de fête', b: 'cône' },
      ],
      explain: "Autour de nous, beaucoup d'objets ont la forme d'un solide : regarde leurs faces et s'ils roulent.",
    },
    {
      id: 'cm1-maths-solides-fix-1',
      kind: 'fix',
      prompt: "Gribouille s'est trompé, corrige-le",
      words: ['Le', 'patron', "d'un", 'cube', 'a', '4', 'faces', 'carrées'],
      wrongIndex: 5,
      correct: '6',
      distractors: ['4', '8'],
      explain: "Le patron est le cube à plat : il doit avoir autant de faces que le cube, c'est-à-dire 6 carrés.",
    },
    {
      id: 'cm1-maths-solides-choice-2',
      kind: 'choice',
      prompt: 'Un prisme dont les bases sont des triangles a combien de faces en tout ?',
      options: ['3', '5', '6'],
      answer: 1,
      explain: "Les 2 bases triangulaires, plus 3 faces rectangles qui les relient : 2 + 3 = 5 faces.",
    },
    {
      id: 'cm1-maths-solides-tf-2',
      kind: 'truefalse',
      statement: 'Une pyramide à base carrée a 5 sommets.',
      answer: true,
      explain: "Oui : les 4 coins de la base carrée, plus la pointe en haut, cela fait 5 sommets.",
    },
    {
      id: 'cm1-maths-solides-choice-3',
      kind: 'choice',
      prompt: "Lequel de ces assemblages est un patron de cube ?",
      options: ['6 carrés alignés sur une seule ligne', '6 carrés qui se replient pour fermer le cube', '4 carrés et 2 triangles'],
      answer: 1,
      explain: "Il faut 6 carrés, et placés de façon à ce qu'en pliant, chaque face trouve sa place. Six carrés en ligne ne se referment pas.",
    },
    {
      id: 'cm1-maths-solides-card-1',
      kind: 'flashcard',
      prompt: 'Lis la question, réfléchis, puis retourne la carte',
      front: 'Quelle est la différence entre un prisme et une pyramide ?',
      back: 'Le prisme a deux bases identiques et des faces rectangles entre elles. La pyramide a une seule base, et des faces triangles qui se rejoignent en un sommet.',
      explain: "Pense à une tente de camping pour le prisme, et aux pyramides d'Égypte pour la pyramide.",
    },
  ],
};

const REPERAGE: Lesson = {
  id: 'cm1-maths-reperage',
  title: 'Se repérer sur un plan',
  subject: 'maths',
  source: 'lecon',
  level: 'CM1',
  notion: 'Se repérer et se déplacer sur un quadrillage, un plan ou une carte avec des coordonnées',
  theme: 'geometrie',
  attendu: 'Se repérer et se déplacer sur un plan, une carte ou un quadrillage avec des coordonnées.',
  attenduId: 'cm1-geo-reperage',
  summary:
    "Sur un quadrillage, une case se nomme avec sa colonne puis sa ligne : (C,4), c'est la colonne C et la ligne 4. Pour se déplacer, on compte les cases vers la droite, la gauche, le haut ou le bas. Sur un plan à l'échelle, 1 cm peut représenter 100 m dans la réalité.",
  minutes: 6,
  exercises: [
    {
      id: 'cm1-maths-reperage-choice-1',
      kind: 'choice',
      prompt: 'Sur un quadrillage, où est la case (C,4) ?',
      options: ['dans la colonne 4, à la ligne C', 'dans la colonne C, à la ligne 4', "n'importe où dans la colonne C"],
      answer: 1,
      explain: "On lit d'abord la lettre, qui donne la colonne, puis le chiffre, qui donne la ligne. La case est au croisement des deux.",
    },
    {
      id: 'cm1-maths-reperage-tf-1',
      kind: 'truefalse',
      statement: 'Pour nommer une case, on donne la colonne avec une lettre, puis la ligne avec un chiffre.',
      answer: true,
      explain: "Oui : c'est comme à la bataille navale. La lettre pour la colonne, le chiffre pour la ligne.",
    },
    {
      id: 'cm1-maths-reperage-blanks-1',
      kind: 'blanks',
      prompt: 'Complète le déplacement',
      text: "Je pars de (B,2). J'avance de 3 colonnes vers la droite : j'arrive en ({{E}},2). Puis je monte de 2 lignes : j'arrive en (E,{{4}}).",
      distractors: ['D', '5'],
      explain: "Après B, en avançant de 3 colonnes : C, D, E. Puis la ligne 2 plus 2 lignes, c'est la ligne 4.",
    },
    {
      id: 'cm1-maths-reperage-choice-2',
      kind: 'choice',
      prompt: 'Sur un plan, 1 cm représente 100 m. Deux maisons sont à 5 cm sur le plan. Quelle est la distance réelle ?',
      options: ['50 m', '500 m', '5 km'],
      answer: 1,
      explain: "Chaque centimètre vaut 100 m. 5 cm, c'est 5 × 100 = 500 m.",
    },
    {
      id: 'cm1-maths-reperage-fix-1',
      kind: 'fix',
      prompt: "Gribouille s'est trompé, corrige-le",
      words: ['Depuis', '(A,1),', '2', 'cases', 'à', 'droite', 'et', '1', 'vers', 'le', 'haut', ':', '(C,3)'],
      wrongIndex: 12,
      correct: '(C,2)',
      distractors: ['(C,3)', '(B,2)'],
      explain: "2 cases à droite depuis A : B puis C. 1 case vers le haut depuis la ligne 1 : ligne 2. On arrive en (C,2).",
    },
    {
      id: 'cm1-maths-reperage-pairs-1',
      kind: 'pairs',
      prompt: 'Relie chaque suite de flèches au déplacement',
      pairs: [
        { a: '→ → ↑', b: '2 à droite, 1 en haut' },
        { a: '← ↓ ↓', b: '1 à gauche, 2 en bas' },
        { a: '↑ ↑ ↑', b: '3 en haut' },
        { a: '→ ↓', b: '1 à droite, 1 en bas' },
      ],
      explain: "Chaque flèche, c'est une case. On compte les flèches de chaque sorte.",
    },
    {
      id: 'cm1-maths-reperage-sort-1',
      kind: 'sort',
      prompt: 'Range chaque case dans sa colonne',
      boxes: ['Colonne A', 'Colonne B'],
      items: [
        { word: '(A,3)', box: 0 },
        { word: '(B,1)', box: 1 },
        { word: '(A,5)', box: 0 },
        { word: '(B,4)', box: 1 },
        { word: '(B,2)', box: 1 },
        { word: '(A,1)', box: 0 },
      ],
      explain: "La lettre, écrite en premier, dit la colonne. Le chiffre ne compte pas ici : il dit seulement la ligne.",
    },
    {
      id: 'cm1-maths-reperage-tf-2',
      kind: 'truefalse',
      statement: "Sur un plan à l'échelle, les distances sont réduites, mais les formes sont gardées.",
      answer: true,
      explain: "Oui : un plan, c'est la réalité en plus petit, toutes les longueurs sont réduites de la même façon.",
    },
    {
      id: 'cm1-maths-reperage-order-1',
      kind: 'order',
      prompt: "Remets dans l'ordre les étapes du trajet jusqu'au trésor",
      lines: [
        'Pars de la case (A,1)',
        'Avance de 2 cases vers la droite : tu es en (C,1)',
        'Monte de 3 cases : tu es en (C,4)',
        'Le trésor est là, en (C,4) : tu as gagné',
      ],
      explain: "On part du départ, on bouge d'abord en colonne puis en ligne, et on vérifie les coordonnées à chaque étape.",
    },
    {
      id: 'cm1-maths-reperage-choice-3',
      kind: 'choice',
      prompt: 'Sur une carte, 1 cm représente 2 km. Une route mesure 7 cm sur la carte. Quelle est sa longueur réelle ?',
      options: ['9 km', '14 km', '72 km'],
      answer: 1,
      explain: "Chaque centimètre vaut 2 km. 7 cm, c'est 7 × 2 = 14 km.",
    },
  ],
};

export const LESSONS: Lesson[] = [
  GRANDS_NOMBRES,
  COMPARER,
  FRACTIONS,
  DECIMAUX,
  CALCUL_MENTAL,
  OPERATIONS,
  MULTIPLICATION,
  DIVISION,
  PROBLEMES,
  LONGUEURS,
  MASSES_CONTENANCES,
  DUREES,
  AIRES,
  ANGLES,
  FIGURES,
  SYMETRIE,
  SOLIDES,
  REPERAGE,
];
