import type { Lesson } from './types';

/**
 * Banque CE2, mathématiques : seize leçons qui couvrent les attendus de fin
 * de cycle 2 (nombres jusqu'à 10 000, fractions simples, quatre opérations,
 * grandeurs et mesures, espace et géométrie). Tout est neutre : l'univers
 * habille à l'affichage.
 */

const NOMBRES_10000: Lesson = {
  id: 'ce2-maths-nombres-10000',
  title: "Les nombres jusqu'à 10 000",
  subject: 'maths',
  source: 'numeration',
  level: 'CE2',
  notion: 'Lire, écrire et décomposer les nombres jusqu\'à 10 000 avec les unités de mille',
  theme: 'nombres',
  attendu: 'Lire, écrire, nommer et décomposer les nombres jusqu\'à 10 000.',
  attenduId: 'ce2-nb-lire',
  summary:
    'Un nombre à quatre chiffres commence par les unités de mille. Dans 3 250, il y a 3 milliers, 2 centaines, 5 dizaines et 0 unité. On le lit « trois mille deux cent cinquante ». Après 9 999 vient 10 000, dix mille.',
  minutes: 7,
  exercises: [
    {
      id: 'ce2-maths-nombres-10000-choice-1',
      kind: 'choice',
      prompt: 'Comment s\'écrit « trois mille deux cent cinquante » en chiffres ?',
      options: ['3025', '3250', '30250'],
      answer: 1,
      explain: 'Trois mille, c\'est 3 000. Deux cent cinquante, c\'est 250. Ensemble : 3 250, avec quatre chiffres.',
    },
    {
      id: 'ce2-maths-nombres-10000-tf-1',
      kind: 'truefalse',
      statement: '« Quatre mille huit » s\'écrit 4 008.',
      answer: true,
      explain: 'Quatre mille, c\'est 4 000, et huit unités de plus : 4 008. Les zéros gardent la place des centaines et des dizaines.',
    },
    {
      id: 'ce2-maths-nombres-10000-match-1',
      kind: 'match',
      prompt: 'Relie chaque nombre à son nom avant la fin du chrono',
      seconds: 45,
      pairs: [
        { a: '2 300', b: 'deux mille trois cents' },
        { a: '5 067', b: 'cinq mille soixante-sept' },
        { a: '1 500', b: 'mille cinq cents' },
        { a: '8 010', b: 'huit mille dix' },
        { a: '900', b: 'neuf cents' },
      ],
      explain: 'Lis d\'abord le chiffre de gauche avec « mille », puis le reste comme un nombre à trois chiffres.',
    },
    {
      id: 'ce2-maths-nombres-10000-blanks-1',
      kind: 'blanks',
      prompt: 'Décompose le nombre',
      text: '6 482 = {{6000}} + {{400}} + {{80}} + 2',
      distractors: ['600', '40'],
      explain: '6 unités de mille font 6 000, 4 centaines font 400, 8 dizaines font 80, et il reste 2 unités.',
    },
    {
      id: 'ce2-maths-nombres-10000-sort-1',
      kind: 'sort',
      prompt: 'Range chaque nombre dans la bonne boîte',
      boxes: ['Moins de 5 000', 'Plus de 5 000'],
      items: [
        { word: '3 200', box: 0 },
        { word: '7 500', box: 1 },
        { word: '4 999', box: 0 },
        { word: '5 001', box: 1 },
        { word: '9 000', box: 1 },
        { word: '1 800', box: 0 },
      ],
      explain: 'Regarde d\'abord le chiffre des unités de mille : 4 ou moins, c\'est moins de 5 000.',
    },
    {
      id: 'ce2-maths-nombres-10000-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a mal écrit le nombre, corrige-le',
      words: ['Deux', 'mille', 'quarante', '=', '2400'],
      wrongIndex: 4,
      correct: '2040',
      distractors: ['2400', '20040'],
      explain: 'Deux mille quarante, c\'est 2 000 + 40 = 2 040. Il n\'y a pas de centaine, on écrit un 0 à sa place.',
    },
    {
      id: 'ce2-maths-nombres-10000-choice-2',
      kind: 'choice',
      prompt: 'Combien d\'unités de mille dans 7 325 ?',
      options: ['3', '7', '5'],
      answer: 1,
      explain: 'Le chiffre tout à gauche compte les unités de mille : 7 milliers, c\'est 7 000.',
    },
    {
      id: 'ce2-maths-nombres-10000-tap-1',
      kind: 'tapword',
      prompt: 'Touche le chiffre des centaines dans 4 712',
      words: ['4', '7', '1', '2'],
      answer: [1],
      explain: 'De droite à gauche : 2 unités, 1 dizaine, 7 centaines, 4 unités de mille. Le chiffre des centaines est 7.',
    },
    {
      id: 'ce2-maths-nombres-10000-tf-2',
      kind: 'truefalse',
      statement: '9 999 + 1 = 10 000.',
      answer: true,
      explain: 'Oui : juste après 9 999 vient 10 000, dix mille. C\'est dix unités de mille.',
    },
    {
      id: 'ce2-maths-nombres-10000-speed-1',
      kind: 'speed',
      prompt: 'Calcul éclair : des milliers',
      seconds: 60,
      target: 6,
      items: [
        { q: '2 000 + 1 000', a: 3000 },
        { q: '4 500 + 1 000', a: 5500 },
        { q: '3 000 + 2 000', a: 5000 },
        { q: '1 000 + 1 000', a: 2000 },
        { q: '7 000 + 1 000', a: 8000 },
        { q: '500 + 1 000', a: 1500 },
        { q: '6 000 + 3 000', a: 9000 },
        { q: '2 500 + 1 000', a: 3500 },
      ],
      explain: 'Pas grave : ajouter 1 000, c\'est ajouter une unité de mille, seul le chiffre de gauche change.',
    },
  ],
};

const COMPARER: Lesson = {
  id: 'ce2-maths-comparer',
  title: 'Comparer et ranger les nombres',
  subject: 'maths',
  source: 'numeration',
  level: 'CE2',
  notion: 'Comparer, ranger, encadrer et placer les nombres jusqu\'à 10 000 sur une droite graduée',
  theme: 'nombres',
  attendu: 'Comparer, ranger, encadrer et placer les nombres jusqu\'à 10 000 sur une droite graduée.',
  attenduId: 'ce2-nb-comparer',
  summary:
    'Pour comparer deux nombres, on regarde d\'abord combien ils ont de chiffres, puis le chiffre de gauche. 3 001 est plus grand que 2 999 parce que 3 milliers, c\'est plus que 2 milliers. Sur une droite graduée, les nombres grandissent vers la droite.',
  minutes: 7,
  exercises: [
    {
      id: 'ce2-maths-comparer-choice-1',
      kind: 'choice',
      prompt: 'Quel est le plus grand de ces nombres ?',
      options: ['2 999', '3 001', '2 990'],
      answer: 1,
      explain: '3 001 a 3 unités de mille, les deux autres n\'en ont que 2. C\'est donc le plus grand.',
    },
    {
      id: 'ce2-maths-comparer-tf-1',
      kind: 'truefalse',
      statement: '4 567 est plus petit que 4 576.',
      answer: true,
      explain: 'Les milliers et les centaines sont pareils. Aux dizaines, 6 est plus petit que 7 : 4 567 est plus petit.',
    },
    {
      id: 'ce2-maths-comparer-line-1',
      kind: 'numberline',
      prompt: 'Place le nombre 700',
      min: 0,
      max: 1000,
      step: 100,
      answer: 700,
      explain: 'Chaque graduation vaut 100. 700, c\'est 7 graduations après 0.',
    },
    {
      id: 'ce2-maths-comparer-sort-1',
      kind: 'sort',
      prompt: 'Range chaque nombre dans la bonne boîte',
      boxes: ['Entre 1 000 et 2 000', 'Entre 2 000 et 3 000'],
      items: [
        { word: '1 450', box: 0 },
        { word: '2 100', box: 1 },
        { word: '1 999', box: 0 },
        { word: '2 850', box: 1 },
        { word: '1 020', box: 0 },
        { word: '2 005', box: 1 },
      ],
      explain: 'Le chiffre des unités de mille dit la boîte : 1, c\'est entre 1 000 et 2 000 ; 2, c\'est entre 2 000 et 3 000.',
    },
    {
      id: 'ce2-maths-comparer-fix-1',
      kind: 'fix',
      prompt: 'Gribouille s\'est trompé, corrige-le',
      words: ['3 400', 'est', 'plus', 'petit', 'que', '3 040'],
      wrongIndex: 3,
      correct: 'grand',
      distractors: ['petit', 'léger'],
      explain: 'Aux centaines, 4 est plus grand que 0. Donc 3 400 est plus grand que 3 040.',
    },
    {
      id: 'ce2-maths-comparer-line-2',
      kind: 'numberline',
      prompt: 'Place le nombre 6 000',
      min: 0,
      max: 10000,
      step: 1000,
      answer: 6000,
      explain: 'Ici chaque graduation vaut 1 000. 6 000, c\'est 6 graduations après 0.',
    },
    {
      id: 'ce2-maths-comparer-choice-2',
      kind: 'choice',
      prompt: 'Entre quels milliers se trouve 4 500 ?',
      options: ['3 000 et 4 000', '4 000 et 5 000', '5 000 et 6 000'],
      answer: 1,
      explain: '4 500 commence par 4 : il est après 4 000 et avant 5 000.',
    },
    {
      id: 'ce2-maths-comparer-blanks-1',
      kind: 'blanks',
      prompt: 'Range du plus petit au plus grand',
      text: 'Du plus petit au plus grand : {{1230}}, puis {{2130}}, puis {{3120}}.',
      distractors: ['3210'],
      explain: 'On compare d\'abord les unités de mille : 1, puis 2, puis 3. 3 210 n\'est pas dans la liste.',
    },
    {
      id: 'ce2-maths-comparer-pairs-1',
      kind: 'pairs',
      prompt: 'Relie chaque nombre à celui qui vient juste après',
      pairs: [
        { a: '2 999', b: '3 000' },
        { a: '4 509', b: '4 510' },
        { a: '7 099', b: '7 100' },
        { a: '9 999', b: '10 000' },
      ],
      explain: 'Le nombre qui vient juste après, c\'est le nombre plus 1. Quand il y a des 9, ils passent à 0 et le chiffre d\'avant grandit.',
    },
    {
      id: 'ce2-maths-comparer-tf-2',
      kind: 'truefalse',
      statement: '5 005 est plus grand que 5 050.',
      answer: false,
      explain: 'Les milliers et les centaines sont pareils. Aux dizaines, 0 est plus petit que 5 : 5 005 est plus petit que 5 050.',
    },
  ],
};

const FRACTIONS: Lesson = {
  id: 'ce2-maths-fractions',
  title: 'Moitié, tiers et quart',
  subject: 'maths',
  source: 'numeration',
  level: 'CE2',
  notion: 'Comprendre les fractions simples : moitié, tiers, quart, trois quarts',
  theme: 'nombres',
  attendu: 'Comprendre les fractions simples : la moitié, le tiers, le quart, trois quarts.',
  attenduId: 'ce2-nb-fractions',
  summary:
    'Partager en 2 parts égales, c\'est prendre la moitié. En 3 parts égales, c\'est le tiers. En 4 parts égales, c\'est le quart. Trois quarts, c\'est trois parts sur quatre. La moitié de 12, c\'est 6 ; le quart de 12, c\'est 3.',
  minutes: 7,
  exercises: [
    {
      id: 'ce2-maths-fractions-choice-1',
      kind: 'choice',
      prompt: 'Quelle est la moitié de 12 ?',
      options: ['4', '6', '24'],
      answer: 1,
      explain: 'La moitié, c\'est partager en 2 parts égales : 6 + 6 = 12. La moitié de 12 est 6.',
    },
    {
      id: 'ce2-maths-fractions-tf-1',
      kind: 'truefalse',
      statement: 'Le quart de 20, c\'est 5.',
      answer: true,
      explain: 'Oui : 20 partagé en 4 parts égales, c\'est 5 par part. 5 × 4 = 20.',
    },
    {
      id: 'ce2-maths-fractions-count-1',
      kind: 'count',
      prompt: 'Compte les parts de cette pizza coupée en parts égales',
      emoji: '🍕',
      answer: 4,
      options: [3, 4, 5],
      explain: 'Il y a 4 parts égales : chaque part est un quart de la pizza.',
    },
    {
      id: 'ce2-maths-fractions-blanks-1',
      kind: 'blanks',
      prompt: 'Complète avec le bon mot',
      text: 'Un gâteau coupé en 3 parts égales : chaque part est un {{tiers}}. Coupé en 4 parts égales : chaque part est un {{quart}}.',
      distractors: ['moitié', 'demi'],
      explain: 'Trois parts, c\'est un tiers chacune. Quatre parts, c\'est un quart chacune. La moitié, c\'est pour deux parts.',
    },
    {
      id: 'ce2-maths-fractions-sort-1',
      kind: 'sort',
      prompt: 'Range chaque calcul dans la boîte de son résultat',
      boxes: ['Vaut 4', 'Vaut 6'],
      items: [
        { word: 'la moitié de 8', box: 0 },
        { word: 'le tiers de 18', box: 1 },
        { word: 'le quart de 16', box: 0 },
        { word: 'la moitié de 12', box: 1 },
        { word: 'le quart de 24', box: 1 },
        { word: 'le tiers de 12', box: 0 },
      ],
      explain: 'Pour trouver la moitié, on partage en 2 ; le tiers, en 3 ; le quart, en 4. Vérifie en multipliant : 4 × 4 = 16, donc le quart de 16 est 4.',
    },
    {
      id: 'ce2-maths-fractions-fix-1',
      kind: 'fix',
      prompt: 'Gribouille s\'est trompé, corrige-le',
      words: ['Le', 'quart', 'de', '20,', 'c\'est', '10'],
      wrongIndex: 5,
      correct: '5',
      distractors: ['10', '4'],
      explain: '10, c\'est la moitié de 20. Le quart, c\'est la moitié de la moitié : 5.',
    },
    {
      id: 'ce2-maths-fractions-pairs-1',
      kind: 'pairs',
      prompt: 'Relie chaque fraction à son résultat',
      pairs: [
        { a: 'la moitié de 30', b: '15' },
        { a: 'le tiers de 30', b: '10' },
        { a: 'le quart de 32', b: '8' },
        { a: 'les trois quarts de 16', b: '12' },
      ],
      explain: 'Pour les trois quarts, on cherche d\'abord un quart (16 partagé en 4 = 4), puis on en prend trois : 4 × 3 = 12.',
    },
    {
      id: 'ce2-maths-fractions-choice-2',
      kind: 'choice',
      prompt: 'Combien font les trois quarts de 20 ?',
      options: ['5', '10', '15'],
      answer: 2,
      explain: 'Un quart de 20, c\'est 5. Trois quarts, c\'est 3 fois 5 : 15.',
    },
    {
      id: 'ce2-maths-fractions-tf-2',
      kind: 'truefalse',
      statement: 'Un demi, c\'est la même chose qu\'une moitié.',
      answer: true,
      explain: 'Oui : un demi-gâteau, c\'est la moitié du gâteau. Ce sont deux mots pour la même part.',
    },
    {
      id: 'ce2-maths-fractions-card-1',
      kind: 'flashcard',
      prompt: 'Lis la question, réfléchis, puis retourne la carte',
      front: 'Combien font deux moitiés ?',
      back: 'Un entier, c\'est-à-dire tout le gâteau. Deux moitiés, trois tiers ou quatre quarts font toujours un entier.',
      explain: 'Quand on remet toutes les parts ensemble, on retrouve le tout.',
    },
  ],
};

const ADDITION: Lesson = {
  id: 'ce2-maths-addition',
  title: 'L\'addition posée avec retenue',
  subject: 'maths',
  source: 'calcul',
  level: 'CE2',
  notion: 'Poser et calculer des additions en colonnes avec retenue, nombres à 3 et 4 chiffres',
  theme: 'calcul',
  attendu: 'Additionner et soustraire des nombres jusqu\'à 10 000, en ligne et en colonnes, avec retenue.',
  attenduId: 'ce2-calc-add',
  summary:
    'Pour poser une addition, on aligne les unités sous les unités, les dizaines sous les dizaines. On commence par la colonne de droite. Si le résultat dépasse 9, on écrit le chiffre des unités et on retient 1 dans la colonne suivante.',
  minutes: 7,
  exercises: [
    {
      id: 'ce2-maths-addition-choice-1',
      kind: 'choice',
      prompt: 'Combien font 347 + 285 ?',
      options: ['622', '632', '522'],
      answer: 1,
      explain: '7 + 5 = 12, j\'écris 2 et je retiens 1. 4 + 8 + 1 = 13, j\'écris 3 et je retiens 1. 3 + 2 + 1 = 6. Résultat : 632.',
    },
    {
      id: 'ce2-maths-addition-tf-1',
      kind: 'truefalse',
      statement: '1 250 + 750 = 2 000.',
      answer: true,
      explain: 'Oui : 250 + 750 = 1 000, et 1 000 + 1 000 = 2 000.',
    },
    {
      id: 'ce2-maths-addition-blanks-1',
      kind: 'blanks',
      prompt: 'Complète la première étape du calcul',
      text: 'Pose 468 + 257 : aux unités, 8 + 7 = 15, j\'écris {{5}} et je retiens {{1}}.',
      distractors: ['15', '0'],
      explain: '15, c\'est 1 dizaine et 5 unités. Les 5 unités restent dans la colonne, la dizaine part dans la colonne d\'à côté.',
    },
    {
      id: 'ce2-maths-addition-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a oublié quelque chose, corrige le résultat',
      words: ['529', '+', '384', '=', '813'],
      wrongIndex: 4,
      correct: '913',
      distractors: ['813', '903'],
      explain: '9 + 4 = 13, je retiens 1. 2 + 8 + 1 = 11, je retiens encore 1. 5 + 3 + 1 = 9. Gribouille a oublié la deuxième retenue.',
    },
    {
      id: 'ce2-maths-addition-pairs-1',
      kind: 'pairs',
      prompt: 'Relie chaque addition à son résultat',
      pairs: [
        { a: '600 + 400', b: '1 000' },
        { a: '250 + 250', b: '500' },
        { a: '1 500 + 500', b: '2 000' },
        { a: '700 + 800', b: '1 500' },
      ],
      explain: 'Avec des centaines rondes, on additionne les centaines comme des petits nombres : 7 + 8 = 15, donc 700 + 800 = 1 500.',
    },
    {
      id: 'ce2-maths-addition-choice-2',
      kind: 'choice',
      prompt: 'Combien font 1 846 + 2 379 ?',
      options: ['4 225', '4 125', '4 215'],
      answer: 0,
      explain: '6 + 9 = 15, je retiens 1. 4 + 7 + 1 = 12, je retiens 1. 8 + 3 + 1 = 12, je retiens 1. 1 + 2 + 1 = 4. Résultat : 4 225.',
    },
    {
      id: 'ce2-maths-addition-sort-1',
      kind: 'sort',
      prompt: 'Y a-t-il une retenue ? Range chaque addition',
      boxes: ['Avec retenue', 'Sans retenue'],
      items: [
        { word: '34 + 25', box: 1 },
        { word: '48 + 36', box: 0 },
        { word: '125 + 243', box: 1 },
        { word: '267 + 158', box: 0 },
        { word: '1 200 + 3 400', box: 1 },
        { word: '2 575 + 1 650', box: 0 },
      ],
      explain: 'Il y a une retenue dès qu\'une colonne dépasse 9. Dans 48 + 36, 8 + 6 = 14 : retenue.',
    },
    {
      id: 'ce2-maths-addition-tf-2',
      kind: 'truefalse',
      statement: 'Dans 356 + 278, on commence par ajouter les centaines.',
      answer: false,
      explain: 'On commence toujours par la colonne de droite, les unités, pour pouvoir passer les retenues.',
    },
    {
      id: 'ce2-maths-addition-speed-1',
      kind: 'speed',
      prompt: 'Calcul éclair : additions',
      seconds: 60,
      target: 6,
      items: [
        { q: '45 + 15', a: 60 },
        { q: '120 + 80', a: 200 },
        { q: '350 + 150', a: 500 },
        { q: '67 + 23', a: 90 },
        { q: '400 + 350', a: 750 },
        { q: '99 + 1', a: 100 },
        { q: '250 + 75', a: 325 },
        { q: '1 000 + 999', a: 1999 },
      ],
      explain: 'Pas grave : pour aller vite, cherche d\'abord à faire un nombre rond, comme 45 + 15 = 60.',
    },
  ],
};

const SOUSTRACTION: Lesson = {
  id: 'ce2-maths-soustraction',
  title: 'La soustraction posée avec retenue',
  subject: 'maths',
  source: 'calcul',
  level: 'CE2',
  notion: 'Poser et calculer des soustractions en colonnes avec retenue',
  theme: 'calcul',
  attendu: 'Additionner et soustraire des nombres jusqu\'à 10 000, en ligne et en colonnes, avec retenue.',
  attenduId: 'ce2-calc-add',
  summary:
    'Pour poser une soustraction, on met le grand nombre en haut et on commence par les unités. Quand le chiffre du haut est trop petit, on emprunte une dizaine : on ajoute 10 en haut et on ajoute 1 en bas dans la colonne suivante. Pour vérifier, on fait l\'addition à l\'envers.',
  minutes: 7,
  exercises: [
    {
      id: 'ce2-maths-soustraction-choice-1',
      kind: 'choice',
      prompt: 'Combien font 452 − 237 ?',
      options: ['215', '225', '285'],
      answer: 0,
      explain: '2 − 7, impossible : j\'emprunte, 12 − 7 = 5. Puis 5 − 3 − 1 = 1. Puis 4 − 2 = 2. Résultat : 215.',
    },
    {
      id: 'ce2-maths-soustraction-tf-1',
      kind: 'truefalse',
      statement: '1 000 − 350 = 650.',
      answer: true,
      explain: 'Oui : 350 + 650 = 1 000. Quand on enlève 350 à 1 000, il reste 650.',
    },
    {
      id: 'ce2-maths-soustraction-blanks-1',
      kind: 'blanks',
      prompt: 'Complète l\'étape de l\'emprunt',
      text: 'Pose 523 − 178 : 3 − 8, c\'est impossible, alors j\'emprunte {{une}} dizaine et je calcule {{13}} − 8 = 5.',
      distractors: ['deux', '23'],
      explain: 'Une dizaine empruntée, c\'est 10 de plus en haut : 3 devient 13. Et il ne faut pas oublier d\'ajouter 1 en bas, dans la colonne des dizaines.',
    },
    {
      id: 'ce2-maths-soustraction-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a oublié la retenue, corrige le résultat',
      words: ['806', '−', '349', '=', '467'],
      wrongIndex: 4,
      correct: '457',
      distractors: ['467', '557'],
      explain: '6 − 9, j\'emprunte : 16 − 9 = 7. Puis 0 − 4 − 1, j\'emprunte encore : 10 − 5 = 5. Puis 8 − 3 − 1 = 4. Résultat : 457.',
    },
    {
      id: 'ce2-maths-soustraction-pairs-1',
      kind: 'pairs',
      prompt: 'Relie chaque soustraction à son résultat',
      pairs: [
        { a: '1 000 − 1', b: '999' },
        { a: '500 − 250', b: '250' },
        { a: '2 000 − 500', b: '1 500' },
        { a: '700 − 150', b: '550' },
      ],
      explain: 'Avec des nombres ronds, pense à ce qu\'il faut ajouter : 150 + 550 = 700, donc 700 − 150 = 550.',
    },
    {
      id: 'ce2-maths-soustraction-choice-2',
      kind: 'choice',
      prompt: 'Pour vérifier que 452 − 237 = 215, quel calcul fais-tu ?',
      options: ['452 + 237', '215 + 237', '237 − 215'],
      answer: 1,
      explain: 'On ajoute le résultat au nombre enlevé : 215 + 237 doit redonner 452. Si c\'est bon, la soustraction est juste.',
    },
    {
      id: 'ce2-maths-soustraction-sort-1',
      kind: 'sort',
      prompt: 'Le résultat est-il plus petit ou plus grand que 100 ?',
      boxes: ['Plus petit que 100', 'Plus grand que 100'],
      items: [
        { word: '150 − 70', box: 0 },
        { word: '300 − 120', box: 1 },
        { word: '95 − 40', box: 0 },
        { word: '500 − 250', box: 1 },
        { word: '230 − 150', box: 0 },
        { word: '1 000 − 600', box: 1 },
      ],
      explain: 'Pas besoin de tout calculer : 150 − 70, c\'est 80, moins que 100. 300 − 120, c\'est 180, plus que 100.',
    },
    {
      id: 'ce2-maths-soustraction-tap-1',
      kind: 'tapword',
      prompt: 'Touche le mot qui désigne le résultat d\'une soustraction',
      words: ['somme', 'différence', 'produit', 'reste'],
      answer: [1],
      explain: 'Le résultat d\'une soustraction s\'appelle la différence. La somme, c\'est pour l\'addition ; le produit, pour la multiplication.',
    },
    {
      id: 'ce2-maths-soustraction-tf-2',
      kind: 'truefalse',
      statement: 'Dans une soustraction, on peut changer l\'ordre des deux nombres sans changer le résultat.',
      answer: false,
      explain: 'Non : 10 − 3 = 7, mais 3 − 10, ce n\'est pas possible avec nos nombres. Dans une soustraction, le grand nombre reste en haut.',
    },
    {
      id: 'ce2-maths-soustraction-speed-1',
      kind: 'speed',
      prompt: 'Calcul éclair : soustractions',
      seconds: 60,
      target: 6,
      items: [
        { q: '60 − 15', a: 45 },
        { q: '200 − 80', a: 120 },
        { q: '500 − 150', a: 350 },
        { q: '90 − 23', a: 67 },
        { q: '750 − 350', a: 400 },
        { q: '100 − 1', a: 99 },
        { q: '325 − 75', a: 250 },
        { q: '2 000 − 1 000', a: 1000 },
      ],
      explain: 'Pas grave : pour aller vite, enlève d\'abord les dizaines rondes, puis le reste.',
    },
  ],
};

const TABLES_6_9: Lesson = {
  id: 'ce2-maths-tables-6-9',
  title: 'Les tables de 6, 7, 8 et 9',
  subject: 'maths',
  source: 'calcul',
  level: 'CE2',
  notion: 'Connaître les tables de 6, 7, 8 et 9, multiplier par 10 et par 100',
  theme: 'calcul',
  attendu: 'Connaître les tables de multiplication de 2 à 9 et multiplier par 10 et 100.',
  attenduId: 'ce2-calc-tables',
  summary:
    'Les tables de 6, 7, 8 et 9 se retiennent à force de les dire et de les réviser. Astuce : 6 × 9, c\'est la même chose que 9 × 6. Pour multiplier par 10, on ajoute un zéro à droite ; par 100, on en ajoute deux.',
  minutes: 7,
  exercises: [
    {
      id: 'ce2-maths-tables-6-9-tf-1',
      kind: 'truefalse',
      statement: '7 × 8 = 56.',
      answer: true,
      explain: 'Oui : 7 × 8 = 56. On le retient avec « 5, 6, 7, 8 » : 56 = 7 × 8.',
    },
    {
      id: 'ce2-maths-tables-6-9-choice-1',
      kind: 'choice',
      prompt: 'Combien font 9 × 9 ?',
      options: ['72', '81', '99'],
      answer: 1,
      explain: '9 × 9 = 81. Astuce : 9 × 10 = 90, et on enlève un 9 : 90 − 9 = 81.',
    },
    {
      id: 'ce2-maths-tables-6-9-match-1',
      kind: 'match',
      prompt: 'Relie chaque multiplication à son résultat avant la fin du chrono',
      seconds: 45,
      pairs: [
        { a: '6 × 7', b: '42' },
        { a: '8 × 8', b: '64' },
        { a: '9 × 6', b: '54' },
        { a: '7 × 7', b: '49' },
        { a: '8 × 9', b: '72' },
      ],
      explain: 'Pas grave, les tables de 6 à 9 demandent un peu de temps. Redis-les à voix haute, elles rentreront.',
    },
    {
      id: 'ce2-maths-tables-6-9-blanks-1',
      kind: 'blanks',
      prompt: 'Complète la règle',
      text: 'Pour multiplier par 10, on ajoute un {{zéro}} à droite : 36 × 10 = {{360}}.',
      distractors: ['un', '306'],
      explain: 'Multiplier par 10, c\'est transformer les unités en dizaines : 36 devient 360.',
    },
    {
      id: 'ce2-maths-tables-6-9-fix-1',
      kind: 'fix',
      prompt: 'Gribouille s\'est trompé de table, corrige-le',
      words: ['7', '×', '6', '=', '48'],
      wrongIndex: 4,
      correct: '42',
      distractors: ['48', '36'],
      explain: '48, c\'est 8 × 6. Et 7 × 6, c\'est 42 : un 6 de moins que 48.',
    },
    {
      id: 'ce2-maths-tables-6-9-pairs-1',
      kind: 'pairs',
      prompt: 'Relie chaque calcul à son résultat',
      pairs: [
        { a: '45 × 100', b: '4 500' },
        { a: '8 × 10', b: '80' },
        { a: '27 × 100', b: '2 700' },
        { a: '9 × 100', b: '900' },
      ],
      explain: 'Multiplier par 100, c\'est ajouter deux zéros à droite : 45 devient 4 500.',
    },
    {
      id: 'ce2-maths-tables-6-9-sort-1',
      kind: 'sort',
      prompt: 'Dans quelle table se trouve chaque nombre ?',
      boxes: ['Dans la table de 6', 'Dans la table de 9'],
      items: [
        { word: '24', box: 0 },
        { word: '63', box: 1 },
        { word: '30', box: 0 },
        { word: '45', box: 1 },
        { word: '48', box: 0 },
        { word: '81', box: 1 },
      ],
      explain: 'Astuce pour la table de 9 : les deux chiffres du résultat font toujours 9 ensemble, comme 6 + 3 dans 63.',
    },
    {
      id: 'ce2-maths-tables-6-9-choice-2',
      kind: 'choice',
      prompt: 'Quel calcul donne 72 ?',
      options: ['7 × 9', '8 × 8', '8 × 9'],
      answer: 2,
      explain: '8 × 9 = 72. 7 × 9 fait 63 et 8 × 8 fait 64.',
    },
    {
      id: 'ce2-maths-tables-6-9-tf-2',
      kind: 'truefalse',
      statement: '6 × 9, c\'est la même chose que 9 × 6.',
      answer: true,
      explain: 'Oui : dans une multiplication, on peut changer l\'ordre. 6 × 9 = 54 et 9 × 6 = 54.',
    },
    {
      id: 'ce2-maths-tables-6-9-speed-1',
      kind: 'speed',
      prompt: 'Calcul éclair : les tables de 6 à 9',
      seconds: 60,
      target: 8,
      items: [
        { q: '6 × 4', a: 24 },
        { q: '7 × 5', a: 35 },
        { q: '8 × 3', a: 24 },
        { q: '9 × 2', a: 18 },
        { q: '6 × 8', a: 48 },
        { q: '7 × 9', a: 63 },
        { q: '8 × 7', a: 56 },
        { q: '9 × 5', a: 45 },
        { q: '6 × 6', a: 36 },
        { q: '7 × 10', a: 70 },
      ],
      explain: 'Pas grave : les tables, ça se joue et se rejoue. Elles reviendront dans une prochaine mission.',
    },
  ],
};

const MULTIPLICATION_POSEE: Lesson = {
  id: 'ce2-maths-multiplication-posee',
  title: 'La multiplication posée',
  subject: 'maths',
  source: 'calcul',
  level: 'CE2',
  notion: 'Poser une multiplication à un chiffre, calculer le double, le triple et la moitié',
  theme: 'calcul',
  attendu: 'Poser une multiplication à un chiffre, calculer le double, le triple, la moitié.',
  attenduId: 'ce2-calc-multiplication',
  summary:
    'Pour poser 34 × 6, on multiplie d\'abord les unités : 6 × 4 = 24, j\'écris 4 et je retiens 2. Puis les dizaines : 6 × 3 = 18, plus la retenue 2, ça fait 20. Résultat : 204. Le double, c\'est fois 2 ; le triple, fois 3 ; la moitié, partagé en 2.',
  minutes: 7,
  exercises: [
    {
      id: 'ce2-maths-multiplication-posee-tf-1',
      kind: 'truefalse',
      statement: 'Le double de 45, c\'est 90.',
      answer: true,
      explain: 'Oui : le double, c\'est 2 fois. 45 + 45 = 90.',
    },
    {
      id: 'ce2-maths-multiplication-posee-choice-1',
      kind: 'choice',
      prompt: 'Quel est le triple de 12 ?',
      options: ['24', '36', '15'],
      answer: 1,
      explain: 'Le triple, c\'est 3 fois : 12 × 3 = 36. 24, c\'est seulement le double.',
    },
    {
      id: 'ce2-maths-multiplication-posee-blanks-1',
      kind: 'blanks',
      prompt: 'Complète les étapes de la multiplication posée',
      text: 'Pose 34 × 6 : 6 × 4 = {{24}}, j\'écris 4 et je retiens {{2}}. Puis 6 × 3 = 18, plus la retenue : {{20}}.',
      distractors: ['14', '3'],
      explain: 'On commence par les unités. La retenue de 24, c\'est 2 dizaines, qu\'on ajoute au résultat des dizaines : 18 + 2 = 20.',
    },
    {
      id: 'ce2-maths-multiplication-posee-choice-2',
      kind: 'choice',
      prompt: 'Combien font 34 × 6 ?',
      options: ['184', '204', '194'],
      answer: 1,
      explain: '6 × 4 = 24, j\'écris 4, je retiens 2. 6 × 3 = 18, plus 2 = 20. Résultat : 204.',
    },
    {
      id: 'ce2-maths-multiplication-posee-pairs-1',
      kind: 'pairs',
      prompt: 'Relie chaque calcul à son résultat',
      pairs: [
        { a: 'le double de 25', b: '50' },
        { a: 'le triple de 10', b: '30' },
        { a: 'la moitié de 80', b: '40' },
        { a: 'le double de 150', b: '300' },
      ],
      explain: 'Double : fois 2. Triple : fois 3. Moitié : partagé en 2. La moitié de 80, c\'est 40 parce que 40 + 40 = 80.',
    },
    {
      id: 'ce2-maths-multiplication-posee-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a confondu double et triple, corrige-le',
      words: ['Le', 'triple', 'de', '8,', 'c\'est', '16'],
      wrongIndex: 5,
      correct: '24',
      distractors: ['16', '32'],
      explain: '16, c\'est le double de 8. Le triple, c\'est 8 × 3 = 24.',
    },
    {
      id: 'ce2-maths-multiplication-posee-sort-1',
      kind: 'sort',
      prompt: 'Range chaque calcul dans la boîte de son résultat',
      boxes: ['Le résultat est 60', 'Le résultat est 120'],
      items: [
        { word: 'le double de 30', box: 0 },
        { word: 'le double de 60', box: 1 },
        { word: 'le triple de 20', box: 0 },
        { word: 'le triple de 40', box: 1 },
        { word: 'la moitié de 120', box: 0 },
        { word: 'la moitié de 240', box: 1 },
      ],
      explain: 'Calcule chacun : 30 × 2 = 60, 60 × 2 = 120, 20 × 3 = 60, 40 × 3 = 120. La moitié de 120 est 60.',
    },
    {
      id: 'ce2-maths-multiplication-posee-tap-1',
      kind: 'tapword',
      prompt: 'Touche le mot qui désigne le résultat d\'une multiplication',
      words: ['somme', 'différence', 'produit', 'quotient'],
      answer: [2],
      explain: 'Le résultat d\'une multiplication s\'appelle le produit. 34 × 6 = 204 : 204 est le produit.',
    },
    {
      id: 'ce2-maths-multiplication-posee-choice-3',
      kind: 'choice',
      prompt: 'Combien font 128 × 4 ?',
      options: ['412', '512', '482'],
      answer: 1,
      explain: '4 × 8 = 32, j\'écris 2, je retiens 3. 4 × 2 = 8, plus 3 = 11, j\'écris 1, je retiens 1. 4 × 1 = 4, plus 1 = 5. Résultat : 512.',
    },
    {
      id: 'ce2-maths-multiplication-posee-tf-2',
      kind: 'truefalse',
      statement: '52 × 3 = 156.',
      answer: true,
      explain: 'Oui : 3 × 2 = 6, puis 3 × 5 = 15. Résultat : 156.',
    },
  ],
};

const PARTAGE: Lesson = {
  id: 'ce2-maths-partage',
  title: 'Partager et grouper : la division',
  subject: 'maths',
  source: 'calcul',
  level: 'CE2',
  notion: 'Partager et grouper, approcher la division avec et sans reste',
  theme: 'calcul',
  attendu: 'Partager et grouper : approcher la division, avec ou sans reste.',
  attenduId: 'ce2-calc-division',
  summary:
    'Diviser, c\'est partager en parts égales. 24 divisé par 4, c\'est 6, parce que 4 × 6 = 24. Parfois le partage ne tombe pas juste : 25 divisé par 4, c\'est 6 et il reste 1. Le reste est toujours plus petit que le nombre de parts.',
  minutes: 7,
  exercises: [
    {
      id: 'ce2-maths-partage-count-1',
      kind: 'count',
      prompt: 'Léa range 12 billes dans 3 boîtes, le même nombre dans chaque. Compte les billes d\'une boîte',
      emoji: '🔵',
      answer: 4,
      options: [3, 4, 6],
      explain: '12 billes partagées en 3 boîtes égales, c\'est 4 billes par boîte : 4 + 4 + 4 = 12.',
    },
    {
      id: 'ce2-maths-partage-choice-1',
      kind: 'choice',
      prompt: 'Combien font 24 divisé par 4 ?',
      options: ['4', '6', '8'],
      answer: 1,
      explain: 'On cherche combien de fois 4 dans 24 : 4 × 6 = 24. Donc 24 divisé par 4, c\'est 6.',
    },
    {
      id: 'ce2-maths-partage-tf-1',
      kind: 'truefalse',
      statement: '20 divisé par 5, c\'est 4.',
      answer: true,
      explain: 'Oui : 5 × 4 = 20. Si on partage 20 en 5 parts égales, chaque part a 4.',
    },
    {
      id: 'ce2-maths-partage-blanks-1',
      kind: 'blanks',
      prompt: 'Complète la division avec reste',
      text: '25 divisé par 4 : 4 × {{6}} = 24, il reste {{1}}.',
      distractors: ['5', '2'],
      explain: 'On cherche la table de 4 juste en dessous de 25 : 4 × 6 = 24. De 24 à 25, il reste 1.',
    },
    {
      id: 'ce2-maths-partage-pairs-1',
      kind: 'pairs',
      prompt: 'Relie chaque division à son résultat',
      pairs: [
        { a: '18 divisé par 3', b: '6' },
        { a: '35 divisé par 5', b: '7' },
        { a: '40 divisé par 8', b: '5' },
        { a: '27 divisé par 9', b: '3' },
      ],
      explain: 'Pense à la table : 3 × 6 = 18, 5 × 7 = 35, 8 × 5 = 40, 9 × 3 = 27.',
    },
    {
      id: 'ce2-maths-partage-fix-1',
      kind: 'fix',
      prompt: 'Gribouille s\'est trompé, corrige-le',
      words: ['30', 'divisé', 'par', '6,', 'c\'est', '6'],
      wrongIndex: 5,
      correct: '5',
      distractors: ['6', '4'],
      explain: '6 × 5 = 30, donc 30 divisé par 6, c\'est 5. 6 × 6 ferait 36, c\'est trop.',
    },
    {
      id: 'ce2-maths-partage-sort-1',
      kind: 'sort',
      prompt: 'Le partage tombe-t-il juste ? Range chaque situation',
      boxes: ['Partage sans reste', 'Il reste quelque chose'],
      items: [
        { word: '16 bonbons pour 4 enfants', box: 0 },
        { word: '17 bonbons pour 4 enfants', box: 1 },
        { word: '21 images pour 3 enfants', box: 0 },
        { word: '22 images pour 5 enfants', box: 1 },
        { word: '30 billes pour 6 enfants', box: 0 },
        { word: '31 billes pour 6 enfants', box: 1 },
      ],
      explain: 'Le partage tombe juste quand le nombre est dans la table : 16 est dans la table de 4, 17 n\'y est pas.',
    },
    {
      id: 'ce2-maths-partage-choice-2',
      kind: 'choice',
      prompt: 'Avec 32 crayons, combien de paquets de 5 crayons peut-on faire ?',
      options: ['7 paquets, il reste 2', '6 paquets, il reste 2', '6 paquets, il reste 1'],
      answer: 1,
      explain: '5 × 6 = 30, et il reste 2 crayons, pas assez pour un paquet de plus. 6 paquets, reste 2.',
    },
    {
      id: 'ce2-maths-partage-tf-2',
      kind: 'truefalse',
      statement: 'Quand on partage 13 cartes entre 2 enfants, il n\'en reste aucune.',
      answer: false,
      explain: '13 est impair : 2 × 6 = 12, chaque enfant a 6 cartes et il en reste 1.',
    },
    {
      id: 'ce2-maths-partage-card-1',
      kind: 'flashcard',
      prompt: 'Lis la question, réfléchis, puis retourne la carte',
      front: 'Que veut dire « diviser » ?',
      back: 'Partager en parts égales, ou chercher combien de fois un nombre tient dans un autre. 24 divisé par 4 : 4 tient 6 fois dans 24.',
      explain: 'Diviser, c\'est le contraire de multiplier : on part du résultat et on cherche un des deux nombres.',
    },
  ],
};

const PROBLEMES: Lesson = {
  id: 'ce2-maths-problemes',
  title: 'Problèmes à deux étapes',
  subject: 'maths',
  source: 'calcul',
  level: 'CE2',
  notion: 'Résoudre des problèmes à deux étapes avec les quatre opérations',
  theme: 'calcul',
  attendu: 'Résoudre des problèmes à deux étapes avec les quatre opérations.',
  attenduId: 'ce2-calc-problemes',
  summary:
    'Dans un problème à deux étapes, il faut faire deux calculs l\'un après l\'autre. On lit bien l\'énoncé, on cherche ce qu\'on doit trouver d\'abord, puis on utilise ce résultat pour le deuxième calcul. On termine par une phrase réponse.',
  minutes: 8,
  exercises: [
    {
      id: 'ce2-maths-problemes-choice-1',
      kind: 'choice',
      prompt: 'Paul a 3 paquets de 8 gâteaux. Il en mange 5. Combien lui en reste-t-il ?',
      options: ['19', '24', '21'],
      answer: 0,
      explain: 'Première étape : 3 × 8 = 24 gâteaux. Deuxième étape : 24 − 5 = 19. Il lui reste 19 gâteaux.',
    },
    {
      id: 'ce2-maths-problemes-blanks-1',
      kind: 'blanks',
      prompt: 'Complète les deux étapes',
      text: 'Léa achète 4 cahiers à 2 € et un stylo à 3 €. Les cahiers coûtent {{8}} €, et avec le stylo elle paie {{11}} € en tout.',
      distractors: ['6', '9'],
      explain: 'D\'abord les cahiers : 4 × 2 = 8 €. Ensuite on ajoute le stylo : 8 + 3 = 11 €.',
    },
    {
      id: 'ce2-maths-problemes-tf-1',
      kind: 'truefalse',
      statement: 'Un car transporte 45 enfants. 18 descendent et 12 montent. Il y a maintenant 39 enfants.',
      answer: true,
      explain: 'Oui : 45 − 18 = 27, puis 27 + 12 = 39 enfants.',
    },
    {
      id: 'ce2-maths-problemes-order-1',
      kind: 'order',
      prompt: 'Tom a 50 €. Il achète 3 livres à 12 €. Remets les étapes dans l\'ordre pour trouver ce qu\'il lui reste',
      lines: [
        'Je calcule le prix des 3 livres : 3 × 12 = 36 €',
        'J\'enlève ce prix aux 50 € : 50 − 36 = 14 €',
        'Je réponds : il reste 14 € à Tom',
      ],
      explain: 'On trouve d\'abord combien coûtent les livres, puis on enlève, et on finit par la phrase réponse.',
    },
    {
      id: 'ce2-maths-problemes-choice-2',
      kind: 'choice',
      prompt: 'On partage 36 bonbons entre 4 enfants. Quelle opération donne le nombre de bonbons de chacun ?',
      options: ['36 + 4', '36 × 4', '36 divisé par 4'],
      answer: 2,
      explain: 'Partager en parts égales, c\'est diviser : 36 divisé par 4 = 9 bonbons chacun.',
    },
    {
      id: 'ce2-maths-problemes-fix-1',
      kind: 'fix',
      prompt: 'Gribouille s\'est trompé dans la réponse, corrige-le',
      words: ['Inès', 'a', '125', 'billes,', 'elle', 'en', 'gagne', '40', 'puis', 'en', 'perd', '15.', 'Elle', 'en', 'a', '140.'],
      wrongIndex: 15,
      correct: '150.',
      distractors: ['180.', '160.'],
      explain: '125 + 40 = 165, puis 165 − 15 = 150. Inès a 150 billes.',
    },
    {
      id: 'ce2-maths-problemes-sort-1',
      kind: 'sort',
      prompt: 'Dans chaque situation, est-ce qu\'on ajoute ou qu\'on enlève ?',
      boxes: ['On ajoute', 'On enlève'],
      items: [
        { word: 'Il gagne 10 billes', box: 0 },
        { word: 'Elle perd 3 cartes', box: 1 },
        { word: 'Il reçoit 5 € de plus', box: 0 },
        { word: 'Elle dépense 12 €', box: 1 },
        { word: '8 enfants montent dans le car', box: 0 },
        { word: '4 enfants descendent', box: 1 },
      ],
      explain: 'Gagner, recevoir, monter : ça fait plus, on ajoute. Perdre, dépenser, descendre : ça fait moins, on enlève.',
    },
    {
      id: 'ce2-maths-problemes-choice-3',
      kind: 'choice',
      prompt: 'Une boîte contient 6 œufs. Mamie achète 4 boîtes et utilise 9 œufs. Combien en reste-t-il ?',
      options: ['15', '24', '13'],
      answer: 0,
      explain: 'Première étape : 4 × 6 = 24 œufs. Deuxième étape : 24 − 9 = 15 œufs.',
    },
    {
      id: 'ce2-maths-problemes-tf-2',
      kind: 'truefalse',
      statement: 'Pour résoudre un problème à deux étapes, on fait un seul calcul.',
      answer: false,
      explain: 'Deux étapes, c\'est deux calculs : le résultat du premier sert pour le deuxième.',
    },
    {
      id: 'ce2-maths-problemes-pairs-1',
      kind: 'pairs',
      prompt: 'Relie chaque question à l\'opération qu\'elle demande',
      pairs: [
        { a: 'Combien en tout ?', b: 'addition' },
        { a: 'Combien de plus ?', b: 'soustraction' },
        { a: '3 paquets de 8, combien ?', b: 'multiplication' },
        { a: 'Combien pour chacun ?', b: 'division' },
      ],
      explain: '« En tout », on ajoute. « De plus », on cherche la différence. « Paquets de », on multiplie. « Pour chacun », on partage.',
    },
  ],
};

const LONGUEURS: Lesson = {
  id: 'ce2-maths-longueurs',
  title: 'Les longueurs : mm, cm, m, km',
  subject: 'maths',
  source: 'lecon',
  level: 'CE2',
  notion: 'Mesurer et convertir des longueurs : millimètre, centimètre, mètre, kilomètre',
  theme: 'grandeurs',
  attendu: 'Mesurer et convertir des longueurs : millimètre, centimètre, mètre, kilomètre.',
  attenduId: 'ce2-gm-longueurs',
  summary:
    'Le millimètre est tout petit, le centimètre tient dans la trousse, le mètre mesure la classe, le kilomètre mesure la route. 1 cm = 10 mm, 1 m = 100 cm, 1 km = 1 000 m.',
  minutes: 7,
  exercises: [
    {
      id: 'ce2-maths-longueurs-choice-1',
      kind: 'choice',
      prompt: 'Combien de centimètres dans 1 mètre ?',
      options: ['10 cm', '100 cm', '1 000 cm'],
      answer: 1,
      explain: '1 m = 100 cm. C\'est la longueur de la grande règle de la classe, avec ses 100 petits traits.',
    },
    {
      id: 'ce2-maths-longueurs-tf-1',
      kind: 'truefalse',
      statement: '1 km, c\'est 1 000 m.',
      answer: true,
      explain: 'Oui : « kilo » veut dire mille. 1 kilomètre = 1 000 mètres.',
    },
    {
      id: 'ce2-maths-longueurs-sort-1',
      kind: 'sort',
      prompt: 'Avec quelle unité mesure-t-on chaque chose ?',
      boxes: ['En cm', 'En m', 'En km'],
      items: [
        { word: 'un crayon', box: 0 },
        { word: 'une salle de classe', box: 1 },
        { word: 'la distance entre deux villes', box: 2 },
        { word: 'une gomme', box: 0 },
        { word: 'un terrain de foot', box: 1 },
        { word: 'un voyage en voiture', box: 2 },
      ],
      explain: 'Les petits objets en cm, les pièces et les terrains en m, les grandes distances en km.',
    },
    {
      id: 'ce2-maths-longueurs-blanks-1',
      kind: 'blanks',
      prompt: 'Complète les conversions',
      text: '3 m = {{300}} cm et 5 cm = {{50}} mm.',
      distractors: ['30', '500'],
      explain: '1 m = 100 cm, donc 3 m = 300 cm. 1 cm = 10 mm, donc 5 cm = 50 mm.',
    },
    {
      id: 'ce2-maths-longueurs-pairs-1',
      kind: 'pairs',
      prompt: 'Relie chaque longueur à la même longueur dans une autre unité',
      pairs: [
        { a: '2 km', b: '2 000 m' },
        { a: '4 m', b: '400 cm' },
        { a: '7 cm', b: '70 mm' },
        { a: '1 m 50 cm', b: '150 cm' },
      ],
      explain: 'Pour passer à une unité plus petite, le nombre grandit : 1 m 50 cm, c\'est 100 cm + 50 cm = 150 cm.',
    },
    {
      id: 'ce2-maths-longueurs-fix-1',
      kind: 'fix',
      prompt: 'Gribouille s\'est trompé de conversion, corrige-le',
      words: ['1', 'km', '=', '100', 'm'],
      wrongIndex: 3,
      correct: '1 000',
      distractors: ['100', '10 000'],
      explain: '100, c\'est le nombre de centimètres dans un mètre. Dans un kilomètre, il y a 1 000 mètres.',
    },
    {
      id: 'ce2-maths-longueurs-choice-2',
      kind: 'choice',
      prompt: 'Quelle longueur est la plus grande ?',
      options: ['250 cm', '3 m', '2 900 mm'],
      answer: 1,
      explain: 'Mets tout en cm : 3 m = 300 cm, 2 900 mm = 290 cm, et 250 cm. Le plus grand est 3 m.',
    },
    {
      id: 'ce2-maths-longueurs-line-1',
      kind: 'numberline',
      prompt: 'Place 500 m sur la droite qui va de 0 à 1 000 m',
      min: 0,
      max: 1000,
      step: 100,
      answer: 500,
      explain: '500 m, c\'est la moitié d\'un kilomètre : juste au milieu de la droite.',
    },
    {
      id: 'ce2-maths-longueurs-tf-2',
      kind: 'truefalse',
      statement: 'Un millimètre est plus grand qu\'un centimètre.',
      answer: false,
      explain: 'Non : il faut 10 millimètres pour faire 1 centimètre. Le millimètre est plus petit.',
    },
    {
      id: 'ce2-maths-longueurs-tap-1',
      kind: 'tapword',
      prompt: 'Touche l\'unité la plus petite',
      words: ['mètre', 'kilomètre', 'millimètre', 'centimètre'],
      answer: [2],
      explain: 'Du plus petit au plus grand : millimètre, centimètre, mètre, kilomètre.',
    },
  ],
};

const MASSES_CONTENANCES: Lesson = {
  id: 'ce2-maths-masses-contenances',
  title: 'Masses et contenances',
  subject: 'maths',
  source: 'lecon',
  level: 'CE2',
  notion: 'Mesurer des masses et des contenances : gramme, kilogramme, centilitre, litre',
  theme: 'grandeurs',
  attendu: 'Mesurer des masses et des contenances : gramme, kilogramme, centilitre, litre.',
  attenduId: 'ce2-gm-masses',
  summary:
    'La masse se mesure en grammes et en kilogrammes : 1 kg = 1 000 g. La contenance d\'une bouteille se mesure en centilitres et en litres : 1 l = 100 cl. Une bouteille d\'eau fait 1 l et demi, un paquet de sucre fait 1 kg.',
  minutes: 7,
  exercises: [
    {
      id: 'ce2-maths-masses-contenances-choice-1',
      kind: 'choice',
      prompt: 'Combien de grammes dans 1 kilogramme ?',
      options: ['100 g', '1 000 g', '10 g'],
      answer: 1,
      explain: '1 kg = 1 000 g. « Kilo » veut dire mille, comme dans kilomètre.',
    },
    {
      id: 'ce2-maths-masses-contenances-tf-1',
      kind: 'truefalse',
      statement: '1 l, c\'est 100 cl.',
      answer: true,
      explain: 'Oui : « centi » veut dire centième. Il faut 100 centilitres pour faire 1 litre.',
    },
    {
      id: 'ce2-maths-masses-contenances-sort-1',
      kind: 'sort',
      prompt: 'Masse ou contenance ? Range chaque chose',
      boxes: ['Masse (g, kg)', 'Contenance (cl, l)'],
      items: [
        { word: 'un sac de farine', box: 0 },
        { word: 'une bouteille d\'eau', box: 1 },
        { word: 'un sac de pommes', box: 0 },
        { word: 'un verre de jus', box: 1 },
        { word: 'un chat', box: 0 },
        { word: 'une baignoire', box: 1 },
      ],
      explain: 'Ce qu\'on pèse sur une balance, c\'est une masse. Ce qu\'on remplit de liquide, c\'est une contenance.',
    },
    {
      id: 'ce2-maths-masses-contenances-blanks-1',
      kind: 'blanks',
      prompt: 'Complète les conversions',
      text: '2 kg = {{2000}} g et 3 l = {{300}} cl.',
      distractors: ['200', '3000'],
      explain: '1 kg = 1 000 g, donc 2 kg = 2 000 g. 1 l = 100 cl, donc 3 l = 300 cl.',
    },
    {
      id: 'ce2-maths-masses-contenances-pairs-1',
      kind: 'pairs',
      prompt: 'Relie chaque mesure à la même mesure écrite autrement',
      pairs: [
        { a: '500 g + 500 g', b: '1 kg' },
        { a: '50 cl + 50 cl', b: '1 l' },
        { a: '1 kg 200 g', b: '1 200 g' },
        { a: '2 l', b: '200 cl' },
      ],
      explain: 'Deux moitiés font un entier : 500 g + 500 g = 1 000 g = 1 kg, et 50 cl + 50 cl = 100 cl = 1 l.',
    },
    {
      id: 'ce2-maths-masses-contenances-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a confondu avec les grammes, corrige-le',
      words: ['Une', 'bouteille', 'de', '1', 'litre', 'contient', '1 000', 'cl'],
      wrongIndex: 6,
      correct: '100',
      distractors: ['1 000', '10'],
      explain: '1 000, c\'est pour les grammes dans un kilo. Pour les centilitres dans un litre, c\'est 100.',
    },
    {
      id: 'ce2-maths-masses-contenances-choice-2',
      kind: 'choice',
      prompt: 'Quelle masse est la plus lourde ?',
      options: ['1 kg', '1 500 g', '900 g'],
      answer: 1,
      explain: 'Mets tout en grammes : 1 kg = 1 000 g. 1 500 g, c\'est plus lourd que 1 000 g et que 900 g.',
    },
    {
      id: 'ce2-maths-masses-contenances-count-1',
      kind: 'count',
      prompt: 'Compte les verres de 25 cl qu\'il faut pour remplir une bouteille de 1 litre',
      emoji: '🥛',
      answer: 4,
      options: [3, 4, 5],
      explain: '25 cl + 25 cl + 25 cl + 25 cl = 100 cl = 1 l. Il faut 4 verres.',
    },
    {
      id: 'ce2-maths-masses-contenances-tf-2',
      kind: 'truefalse',
      statement: 'Un éléphant pèse à peu près 5 kg.',
      answer: false,
      explain: '5 kg, c\'est la masse d\'un chat. Un éléphant pèse des milliers de kilogrammes.',
    },
    {
      id: 'ce2-maths-masses-contenances-card-1',
      kind: 'flashcard',
      prompt: 'Lis la question, réfléchis, puis retourne la carte',
      front: 'Combien de grammes dans un demi-kilo ?',
      back: '500 g, car 1 kg = 1 000 g et la moitié de 1 000 est 500.',
      explain: 'Un demi-kilo de fraises, c\'est 500 g sur la balance.',
    },
  ],
};

const HEURE_DUREES: Lesson = {
  id: 'ce2-maths-heure-durees',
  title: 'L\'heure, les durées, le calendrier',
  subject: 'maths',
  source: 'lecon',
  level: 'CE2',
  notion: 'Lire l\'heure à la minute près, calculer des durées, utiliser le calendrier',
  theme: 'grandeurs',
  attendu: 'Lire l\'heure à la minute près, calculer des durées, utiliser le calendrier.',
  attenduId: 'ce2-gm-heure',
  summary:
    'La petite aiguille montre les heures, la grande montre les minutes : chaque chiffre du cadran vaut 5 minutes. 1 h = 60 min et 1 min = 60 s. Une année a 12 mois et une semaine a 7 jours.',
  minutes: 7,
  exercises: [
    {
      id: 'ce2-maths-heure-durees-tf-1',
      kind: 'truefalse',
      statement: '1 heure = 60 minutes.',
      answer: true,
      explain: 'Oui : la grande aiguille fait un tour complet en 60 minutes, c\'est une heure.',
    },
    {
      id: 'ce2-maths-heure-durees-choice-1',
      kind: 'choice',
      prompt: 'La petite aiguille est entre le 3 et le 4, la grande aiguille est sur le 7. Quelle heure est-il ?',
      options: ['4 h 35', '3 h 07', '3 h 35'],
      answer: 2,
      explain: 'La petite aiguille a dépassé le 3 : il est 3 h et quelque chose. La grande sur le 7, c\'est 7 × 5 = 35 minutes. Il est 3 h 35.',
    },
    {
      id: 'ce2-maths-heure-durees-blanks-1',
      kind: 'blanks',
      prompt: 'Complète avec les mots de l\'heure',
      text: 'Quand la grande aiguille est sur le 9, il est « moins le {{quart}} ». Sur le 6, il est « et {{demie}} ».',
      distractors: ['demi', 'dix'],
      explain: 'Sur le 6, la moitié du tour est faite : « et demie ». Sur le 9, il manque un quart de tour : « moins le quart ».',
    },
    {
      id: 'ce2-maths-heure-durees-pairs-1',
      kind: 'pairs',
      prompt: 'Relie chaque durée à la même durée écrite autrement',
      pairs: [
        { a: '1 h', b: '60 min' },
        { a: '1 min', b: '60 s' },
        { a: 'une demi-heure', b: '30 min' },
        { a: 'un quart d\'heure', b: '15 min' },
      ],
      explain: 'Une demi-heure, c\'est la moitié de 60 min : 30 min. Un quart d\'heure, c\'est le quart de 60 : 15 min.',
    },
    {
      id: 'ce2-maths-heure-durees-choice-2',
      kind: 'choice',
      prompt: 'Le film commence à 14 h 10 et dure 1 h 30. À quelle heure finit-il ?',
      options: ['15 h 40', '15 h 30', '16 h 10'],
      answer: 0,
      explain: '14 h 10 plus 1 h, c\'est 15 h 10. Plus 30 min, c\'est 15 h 40.',
    },
    {
      id: 'ce2-maths-heure-durees-fix-1',
      kind: 'fix',
      prompt: 'Gribouille s\'est trompé sur le calendrier, corrige-le',
      words: ['Il', 'y', 'a', '7', 'jours', 'dans', 'une', 'semaine', 'et', '10', 'mois', 'dans', 'une', 'année.'],
      wrongIndex: 9,
      correct: '12',
      distractors: ['10', '11'],
      explain: 'Une année a 12 mois, de janvier à décembre. Compte-les sur tes doigts !',
    },
    {
      id: 'ce2-maths-heure-durees-sort-1',
      kind: 'sort',
      prompt: 'Est-ce que ça dure moins ou plus d\'une heure ?',
      boxes: ['Moins d\'une heure', 'Plus d\'une heure'],
      items: [
        { word: 'se brosser les dents', box: 0 },
        { word: 'une nuit de sommeil', box: 1 },
        { word: 'une récréation', box: 0 },
        { word: 'une journée d\'école', box: 1 },
        { word: 'chanter une chanson', box: 0 },
        { word: 'un voyage en train entre deux grandes villes', box: 1 },
      ],
      explain: 'Se brosser les dents prend 3 minutes, une récréation 15 minutes. Une nuit, c\'est 10 heures.',
    },
    {
      id: 'ce2-maths-heure-durees-order-1',
      kind: 'order',
      prompt: 'Remets les mois dans l\'ordre du calendrier',
      lines: ['septembre', 'octobre', 'novembre', 'décembre'],
      explain: 'Après la rentrée en septembre viennent octobre, novembre, puis décembre, le dernier mois de l\'année.',
    },
    {
      id: 'ce2-maths-heure-durees-tf-2',
      kind: 'truefalse',
      statement: 'Entre 8 h 15 et 8 h 45, il s\'écoule 30 minutes.',
      answer: true,
      explain: 'Oui : de 15 à 45, la grande aiguille avance de 30 minutes, une demi-heure.',
    },
    {
      id: 'ce2-maths-heure-durees-choice-3',
      kind: 'choice',
      prompt: 'Quel mois a seulement 28 jours, ou 29 les années bissextiles ?',
      options: ['janvier', 'février', 'mars'],
      answer: 1,
      explain: 'Février est le mois le plus court. Janvier et mars ont 31 jours.',
    },
  ],
};

const MONNAIE: Lesson = {
  id: 'ce2-maths-monnaie',
  title: 'Euros et centimes',
  subject: 'maths',
  source: 'lecon',
  level: 'CE2',
  notion: 'Calculer avec la monnaie, euros et centimes, rendre la monnaie',
  theme: 'grandeurs',
  attendu: 'Calculer avec la monnaie, euros et centimes, et rendre la monnaie.',
  attenduId: 'ce2-gm-monnaie',
  summary:
    '1 € = 100 c. Les pièces vont de 1 c à 2 €, les billets commencent à 5 €. Pour rendre la monnaie, on calcule ce qui manque entre le prix et ce qu\'on a donné : un objet à 3 € payé avec 5 €, on rend 2 €.',
  minutes: 7,
  exercises: [
    {
      id: 'ce2-maths-monnaie-choice-1',
      kind: 'choice',
      prompt: 'Combien de centimes dans 1 euro ?',
      options: ['10 c', '100 c', '1 000 c'],
      answer: 1,
      explain: '1 € = 100 c. « Centime » vient de « cent ».',
    },
    {
      id: 'ce2-maths-monnaie-tf-1',
      kind: 'truefalse',
      statement: 'Deux pièces de 50 c font 1 €.',
      answer: true,
      explain: 'Oui : 50 c + 50 c = 100 c = 1 €.',
    },
    {
      id: 'ce2-maths-monnaie-count-1',
      kind: 'count',
      prompt: 'Compte les pièces de 1 €',
      emoji: '🪙',
      answer: 7,
      options: [6, 7, 8],
      explain: '7 pièces de 1 €, c\'est 7 € en tout.',
    },
    {
      id: 'ce2-maths-monnaie-blanks-1',
      kind: 'blanks',
      prompt: 'Complète la monnaie rendue',
      text: 'Un cahier coûte 2 € 50 c. Je paie avec 5 €. On me rend {{2}} € et {{50}} c.',
      distractors: ['3', '20'],
      explain: 'De 2 € 50 c à 3 €, il manque 50 c. De 3 € à 5 €, il manque 2 €. On rend 2 € 50 c.',
    },
    {
      id: 'ce2-maths-monnaie-pairs-1',
      kind: 'pairs',
      prompt: 'Relie chaque somme à la même somme écrite autrement',
      pairs: [
        { a: '1 € 50 c', b: '150 c' },
        { a: '3 €', b: '300 c' },
        { a: '75 c + 25 c', b: '1 €' },
        { a: '2 € + 2 € + 1 €', b: '5 €' },
      ],
      explain: '1 € vaut 100 c, donc 1 € 50 c vaut 150 c. Et 75 c + 25 c = 100 c = 1 €.',
    },
    {
      id: 'ce2-maths-monnaie-fix-1',
      kind: 'fix',
      prompt: 'Gribouille s\'est trompé sur le prix de deux pains, corrige-le',
      words: ['Un', 'pain', 'coûte', '1 €', '20 c.', 'Deux', 'pains', 'coûtent', '2 €', '20 c.'],
      wrongIndex: 9,
      correct: '40 c.',
      distractors: ['20 c.', '60 c.'],
      explain: 'Deux pains, c\'est deux fois 1 € 20 c : 2 € et 40 c. Les centimes aussi doublent.',
    },
    {
      id: 'ce2-maths-monnaie-choice-2',
      kind: 'choice',
      prompt: 'Léo achète un livre à 8 € et un stylo à 2 € 50 c. Il paie avec un billet de 20 €. Combien lui rend-on ?',
      options: ['10 € 50 c', '9 € 50 c', '11 € 50 c'],
      answer: 1,
      explain: 'Il dépense 8 € + 2 € 50 c = 10 € 50 c. De 10 € 50 c à 20 €, il manque 9 € 50 c.',
    },
    {
      id: 'ce2-maths-monnaie-sort-1',
      kind: 'sort',
      prompt: 'Chaque somme vaut-elle moins ou plus de 1 € ?',
      boxes: ['Moins de 1 €', 'Plus de 1 €'],
      items: [
        { word: '80 c', box: 0 },
        { word: '1 € 20 c', box: 1 },
        { word: '2 pièces de 20 c', box: 0 },
        { word: '3 pièces de 50 c', box: 1 },
        { word: '99 c', box: 0 },
        { word: '110 c', box: 1 },
      ],
      explain: '1 € = 100 c. 3 pièces de 50 c font 150 c, plus que 100 c. 2 pièces de 20 c font 40 c, moins que 100 c.',
    },
    {
      id: 'ce2-maths-monnaie-tf-2',
      kind: 'truefalse',
      statement: 'Avec 3 pièces de 20 c, j\'ai 60 c.',
      answer: true,
      explain: 'Oui : 20 c × 3 = 60 c.',
    },
    {
      id: 'ce2-maths-monnaie-tap-1',
      kind: 'tapword',
      prompt: 'Touche les deux pièces qui existent vraiment',
      words: ['1 €', '3 €', '50 c', '25 c'],
      answer: [0, 2],
      explain: 'Les pièces sont 1 c, 2 c, 5 c, 10 c, 20 c, 50 c, 1 € et 2 €. Il n\'y a pas de pièce de 3 € ni de 25 c.',
    },
  ],
};

const FIGURES_SYMETRIE: Lesson = {
  id: 'ce2-maths-figures-symetrie',
  title: 'Les figures planes',
  subject: 'maths',
  source: 'lecon',
  level: 'CE2',
  notion: 'Décrire carré, rectangle, triangle rectangle et cercle, reconnaître un angle droit et un axe de symétrie',
  theme: 'geometrie',
  attendu: 'Décrire et tracer carré, rectangle, triangle rectangle et cercle ; reconnaître un angle droit.',
  attenduId: 'ce2-geo-figures',
  summary:
    'Le carré a 4 côtés égaux et 4 angles droits. Le rectangle a 4 angles droits, avec 2 longueurs et 2 largeurs. Le triangle rectangle a 3 côtés et un angle droit. Le cercle a un centre et un rayon, on le trace au compas. L\'équerre sert à vérifier un angle droit.',
  minutes: 8,
  exercises: [
    {
      id: 'ce2-maths-figures-symetrie-tf-1',
      kind: 'truefalse',
      statement: 'Un rectangle a 4 angles droits.',
      answer: true,
      explain: 'Oui : les 4 coins d\'un rectangle sont des angles droits, comme ceux d\'une feuille de papier.',
    },
    {
      id: 'ce2-maths-figures-symetrie-choice-1',
      kind: 'choice',
      prompt: 'Qu\'est-ce qu\'un carré ?',
      options: ['Une figure à 3 côtés', 'Une figure à 4 côtés égaux et 4 angles droits', 'Une figure ronde'],
      answer: 1,
      explain: 'Le carré a 4 côtés de la même longueur et 4 angles droits. C\'est un rectangle tout spécial.',
    },
    {
      id: 'ce2-maths-figures-symetrie-sort-1',
      kind: 'sort',
      prompt: 'Quelle forme a chaque objet ?',
      boxes: ['Carré', 'Rectangle', 'Triangle rectangle'],
      items: [
        { word: 'une page de cahier', box: 1 },
        { word: 'un carreau de carrelage', box: 0 },
        { word: 'une équerre', box: 2 },
        { word: 'une porte', box: 1 },
        { word: 'une face de dé', box: 0 },
        { word: 'une part de sandwich coupé en diagonale', box: 2 },
      ],
      explain: 'La page et la porte sont plus hautes que larges : des rectangles. Le carreau et la face du dé ont 4 côtés égaux : des carrés.',
    },
    {
      id: 'ce2-maths-figures-symetrie-blanks-1',
      kind: 'blanks',
      prompt: 'Complète la description du cercle',
      text: 'Le centre du cercle est au milieu. La distance du centre au bord s\'appelle le {{rayon}}. Pour tracer un cercle, j\'utilise un {{compas}}.',
      distractors: ['côté', 'règle'],
      explain: 'La pointe du compas se plante au centre, l\'écartement du compas est le rayon.',
    },
    {
      id: 'ce2-maths-figures-symetrie-tap-1',
      kind: 'tapword',
      prompt: 'Touche l\'outil qui sert à vérifier un angle droit',
      words: ['règle', 'équerre', 'compas', 'gomme'],
      answer: [1],
      explain: 'L\'équerre a un coin en angle droit : on le pose dans le coin de la figure pour vérifier.',
    },
    {
      id: 'ce2-maths-figures-symetrie-fix-1',
      kind: 'fix',
      prompt: 'Gribouille s\'est trompé, corrige-le',
      words: ['Un', 'triangle', 'a', '4', 'côtés', 'et', '3', 'sommets.'],
      wrongIndex: 3,
      correct: '3',
      distractors: ['4', '5'],
      explain: '« Tri » veut dire trois : un triangle a 3 côtés et 3 sommets.',
    },
    {
      id: 'ce2-maths-figures-symetrie-pairs-1',
      kind: 'pairs',
      prompt: 'Relie chaque figure à sa description',
      pairs: [
        { a: 'carré', b: '4 côtés égaux' },
        { a: 'rectangle', b: '2 longueurs et 2 largeurs' },
        { a: 'cercle', b: 'un centre et un rayon' },
        { a: 'triangle rectangle', b: '3 côtés et un angle droit' },
      ],
      explain: 'Chaque figure a sa carte d\'identité : le nombre de côtés, les angles droits, ou le centre pour le cercle.',
    },
    {
      id: 'ce2-maths-figures-symetrie-tf-2',
      kind: 'truefalse',
      statement: 'Un cercle a des sommets.',
      answer: false,
      explain: 'Non : un cercle est tout rond, il n\'a ni côté ni sommet. Il a un centre et un rayon.',
    },
    {
      id: 'ce2-maths-figures-symetrie-choice-2',
      kind: 'choice',
      prompt: 'Une figure a un axe de symétrie si…',
      options: ['elle a 4 côtés', 'en la pliant sur l\'axe, les deux moitiés se superposent', 'elle est très grande'],
      answer: 1,
      explain: 'L\'axe de symétrie est la ligne de pliage : les deux moitiés sont exactement pareilles, comme dans un miroir.',
    },
    {
      id: 'ce2-maths-figures-symetrie-tf-3',
      kind: 'truefalse',
      statement: 'Un carré a 4 axes de symétrie.',
      answer: true,
      explain: 'Oui : on peut le plier en deux par le milieu de deux façons, et aussi en diagonale de deux façons.',
    },
  ],
};

const SYMETRIE: Lesson = {
  id: 'ce2-maths-symetrie',
  title: 'L\'axe de symétrie',
  subject: 'maths',
  source: 'lecon',
  level: 'CE2',
  notion: 'Reconnaître une figure symétrique et son axe de symétrie',
  theme: 'geometrie',
  attendu: 'Reconnaître et compléter une figure symétrique, tracer un axe de symétrie.',
  attenduId: 'ce2-geo-symetrie',
  summary:
    'Une figure est symétrique quand on peut la plier en deux et que les deux moitiés se superposent parfaitement. La ligne de pliage s\'appelle l\'axe de symétrie. Le papillon, le cœur et la lettre A en ont un ; la lettre F n\'en a pas.',
  minutes: 5,
  exercises: [
    {
      id: 'ce2-maths-symetrie-tf-1',
      kind: 'truefalse',
      statement: 'Un axe de symétrie partage une figure en deux parties qui se superposent quand on plie.',
      answer: true,
      explain: 'Oui : c\'est la ligne de pliage. Les deux moitiés sont comme un objet et son reflet dans un miroir.',
    },
    {
      id: 'ce2-maths-symetrie-choice-1',
      kind: 'choice',
      prompt: 'Quelle lettre majuscule a un axe de symétrie debout, au milieu ?',
      options: ['F', 'A', 'L'],
      answer: 1,
      explain: 'Si on plie un A en deux par le milieu, les deux côtés se superposent. Pour F et L, non.',
    },
    {
      id: 'ce2-maths-symetrie-sort-1',
      kind: 'sort',
      prompt: 'Range chaque dessin ou lettre dans la bonne boîte',
      boxes: ['A un axe de symétrie', 'N\'a pas d\'axe de symétrie'],
      items: [
        { word: 'un cœur', box: 0 },
        { word: 'la lettre F', box: 1 },
        { word: 'un papillon', box: 0 },
        { word: 'la lettre A', box: 0 },
        { word: 'la lettre L', box: 1 },
        { word: 'la lettre R', box: 1 },
      ],
      explain: 'Imagine que tu plies la figure : si les deux moitiés sont pareilles, elle a un axe de symétrie.',
    },
    {
      id: 'ce2-maths-symetrie-blanks-1',
      kind: 'blanks',
      prompt: 'Complète la règle',
      text: 'Quand je plie une feuille sur l\'{{axe}}, les deux moitiés se superposent : la figure est {{symétrique}}.',
      distractors: ['côté', 'ronde'],
      explain: 'Axe et symétrique sont les deux mots de la leçon : l\'axe est la ligne, symétrique est la figure.',
    },
    {
      id: 'ce2-maths-symetrie-fix-1',
      kind: 'fix',
      prompt: 'Gribouille s\'est trompé, corrige-le',
      words: ['Un', 'rectangle', 'a', '4', 'axes', 'de', 'symétrie.'],
      wrongIndex: 3,
      correct: '2',
      distractors: ['4', '1'],
      explain: 'Le rectangle se plie en deux par le milieu de la longueur et par le milieu de la largeur : 2 axes. En diagonale, ça ne marche pas, c\'est seulement pour le carré.',
    },
    {
      id: 'ce2-maths-symetrie-tap-1',
      kind: 'tapword',
      prompt: 'Touche le mot qui désigne la ligne de pliage d\'une figure symétrique',
      words: ['sommet', 'axe', 'rayon', 'arête'],
      answer: [1],
      explain: 'La ligne de pliage s\'appelle l\'axe de symétrie. Le rayon, c\'est pour le cercle ; l\'arête, pour les solides.',
    },
    {
      id: 'ce2-maths-symetrie-tf-2',
      kind: 'truefalse',
      statement: 'Dans une symétrie, un point et son reflet sont à la même distance de l\'axe.',
      answer: true,
      explain: 'Oui : comme dans un miroir, ce qui est à 2 carreaux à gauche de l\'axe se retrouve à 2 carreaux à droite.',
    },
  ],
};

const SOLIDES: Lesson = {
  id: 'ce2-maths-solides',
  title: 'Les solides et le plan',
  subject: 'maths',
  source: 'lecon',
  level: 'CE2',
  notion: 'Décrire cube, pavé, pyramide, cylindre avec leurs faces, arêtes et sommets ; se repérer sur un plan',
  theme: 'geometrie',
  attendu: 'Décrire cube, pavé, pyramide, cylindre : faces, arêtes, sommets ; se repérer sur un plan.',
  attenduId: 'ce2-geo-solides',
  summary:
    'Un solide a des faces (les surfaces plates), des arêtes (les traits entre deux faces) et des sommets (les coins). Le cube a 6 faces carrées, 12 arêtes et 8 sommets. Le pavé a 6 faces rectangulaires. La pyramide a une pointe, le cylindre peut rouler. Sur un plan, on voit les choses vues du dessus.',
  minutes: 7,
  exercises: [
    {
      id: 'ce2-maths-solides-choice-1',
      kind: 'choice',
      prompt: 'Combien de faces a un cube ?',
      options: ['4', '6', '8'],
      answer: 1,
      explain: 'Un cube a 6 faces : regarde un dé, il a 6 côtés avec des points de 1 à 6.',
    },
    {
      id: 'ce2-maths-solides-tf-1',
      kind: 'truefalse',
      statement: 'Un cube a 8 sommets.',
      answer: true,
      explain: 'Oui : 4 coins en haut et 4 coins en bas, ça fait 8 sommets.',
    },
    {
      id: 'ce2-maths-solides-blanks-1',
      kind: 'blanks',
      prompt: 'Complète la carte d\'identité du cube',
      text: 'Un cube a {{6}} faces carrées, {{12}} arêtes et {{8}} sommets.',
      distractors: ['4', '10'],
      explain: '6 faces, 12 arêtes (4 en haut, 4 en bas, 4 debout) et 8 sommets. Compte-les sur un dé ou une boîte.',
    },
    {
      id: 'ce2-maths-solides-sort-1',
      kind: 'sort',
      prompt: 'Quel solide ressemble à chaque objet ?',
      boxes: ['Cube', 'Pavé', 'Pyramide', 'Cylindre'],
      items: [
        { word: 'un dé', box: 0 },
        { word: 'une boîte à chaussures', box: 1 },
        { word: 'une boîte de conserve', box: 3 },
        { word: 'une brique', box: 1 },
        { word: 'un morceau de sucre', box: 0 },
        { word: 'un toit pointu à 4 pentes', box: 2 },
      ],
      explain: 'Le dé et le sucre ont des faces carrées : des cubes. La boîte et la brique ont des faces rectangulaires : des pavés. La conserve roule : un cylindre.',
    },
    {
      id: 'ce2-maths-solides-pairs-1',
      kind: 'pairs',
      prompt: 'Relie chaque mot à ce qu\'il veut dire',
      pairs: [
        { a: 'face', b: 'une surface plate du solide' },
        { a: 'arête', b: 'le trait entre deux faces' },
        { a: 'sommet', b: 'le coin, là où les arêtes se rejoignent' },
        { a: 'cylindre', b: 'deux faces rondes et une face qui roule' },
      ],
      explain: 'Pose la main sur une boîte : la partie plate est une face, le bord est une arête, le coin est un sommet.',
    },
    {
      id: 'ce2-maths-solides-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a mal décrit la pyramide, corrige-le',
      words: ['Une', 'pyramide', 'a', 'une', 'base', 'et', 'des', 'faces', 'rondes', 'qui', 'se', 'rejoignent', 'en', 'un', 'sommet.'],
      wrongIndex: 8,
      correct: 'triangulaires',
      distractors: ['rondes', 'carrées'],
      explain: 'Les faces d\'une pyramide sont des triangles : elles partent de la base et montent jusqu\'à la pointe.',
    },
    {
      id: 'ce2-maths-solides-tap-1',
      kind: 'tapword',
      prompt: 'Touche le solide qui peut rouler',
      words: ['cube', 'pavé', 'cylindre', 'pyramide'],
      answer: [2],
      explain: 'Le cylindre a une face courbe : posé sur le côté, il roule. Les autres ont seulement des faces plates.',
    },
    {
      id: 'ce2-maths-solides-choice-2',
      kind: 'choice',
      prompt: 'Sur le plan, le trésor est dans la colonne B et sur la ligne 3. Comment écrit-on cette case ?',
      options: ['3B', 'B3', 'C3'],
      answer: 1,
      explain: 'On écrit d\'abord la lettre de la colonne, puis le numéro de la ligne : B3, comme à la bataille navale.',
    },
    {
      id: 'ce2-maths-solides-tf-2',
      kind: 'truefalse',
      statement: 'Sur un plan, on voit les objets comme si on les regardait du dessus.',
      answer: true,
      explain: 'Oui : un plan, c\'est le dessin de la pièce vue d\'en haut, comme un oiseau qui vole au-dessus.',
    },
    {
      id: 'ce2-maths-solides-card-1',
      kind: 'flashcard',
      prompt: 'Lis la question, réfléchis, puis retourne la carte',
      front: 'Combien de faces a un pavé ?',
      back: '6 faces, comme le cube, mais ce sont des rectangles. Il a aussi 12 arêtes et 8 sommets.',
      explain: 'Le pavé est un cube étiré : même nombre de faces, d\'arêtes et de sommets.',
    },
  ],
};

export const LESSONS: Lesson[] = [
  NOMBRES_10000,
  COMPARER,
  FRACTIONS,
  ADDITION,
  SOUSTRACTION,
  TABLES_6_9,
  MULTIPLICATION_POSEE,
  PARTAGE,
  PROBLEMES,
  LONGUEURS,
  MASSES_CONTENANCES,
  HEURE_DUREES,
  MONNAIE,
  FIGURES_SYMETRIE,
  SYMETRIE,
  SOLIDES,
];
