import type { Lesson } from './types';

/**
 * Banque de départ, CE1. Trois leçons qui couvrent les trois types de photo
 * les plus fréquents : une leçon de maths, une poésie, une liste de mots.
 * Quand le pipeline photo existera, les leçons viendront de là ; cette banque
 * restera pour le parcours sans photo.
 */

const NOMBRES_100: Lesson = {
  id: 'maths-nombres-100',
  title: "Les nombres jusqu'à 100",
  subject: 'maths',
  source: 'numeration',
  level: 'CE1',
  notion: 'Comparer, ranger et repérer les nombres jusqu\'à 100',
  attendu: 'Comprendre et utiliser des nombres entiers pour dénombrer, ordonner, repérer, comparer.',
  attenduId: 'ce1-nb-comparer',
  summary:
    'Dans un nombre à deux chiffres, le chiffre de gauche compte les dizaines et celui de droite les unités. Pour comparer deux nombres, on regarde d\'abord les dizaines.',
  minutes: 6,
  exercises: [
    {
      id: 'n100-qty-1',
      kind: 'quantity',
      prompt: 'Fabrique le nombre 34 avec des barres de dix et des cubes',
      target: 34,
      tens: true,
      explain: '34, c\'est 3 dizaines et 4 unités : trois barres et quatre cubes.',
    },
    {
      id: 'n100-qty-2',
      kind: 'quantity',
      prompt: 'Fabrique le nombre 70',
      target: 70,
      tens: true,
      explain: '70, c\'est 7 dizaines et 0 unité : sept barres, aucun cube.',
    },
    {
      id: 'n100-cmp-1',
      kind: 'choice',
      prompt: 'Quel est le plus grand ?',
      options: ['47', '74'],
      answer: 1,
      explain: '74 a 7 dizaines, 47 n\'en a que 4. Plus de dizaines, plus grand.',
    },
    {
      id: 'n100-line-1',
      kind: 'numberline',
      prompt: 'Place le nombre 50',
      min: 0,
      max: 100,
      step: 10,
      answer: 50,
      explain: '50, c\'est 5 dizaines : juste au milieu entre 0 et 100.',
    },
    {
      id: 'n100-cmp-2',
      kind: 'choice',
      prompt: 'Combien de dizaines dans 83 ?',
      options: ['3', '8', '83'],
      answer: 1,
      explain: 'Dans 83, le 8 est à gauche : ce sont les dizaines. Le 3 compte les unités.',
    },
    {
      id: 'n100-line-2',
      kind: 'numberline',
      prompt: 'Place le nombre 80',
      min: 0,
      max: 100,
      step: 10,
      answer: 80,
      explain: '80, c\'est 8 dizaines : deux graduations avant 100.',
    },
    {
      id: 'n100-cmp-3',
      kind: 'choice',
      prompt: 'Range du plus petit au plus grand',
      options: ['36, 63, 39', '36, 39, 63', '63, 39, 36'],
      answer: 1,
      explain: '36 et 39 ont 3 dizaines, 63 en a 6. Entre 36 et 39, on compare les unités : 6 puis 9.',
    },
    {
      id: 'n100-speed',
      kind: 'speed',
      prompt: 'Calcul éclair : additions',
      seconds: 45,
      target: 6,
      items: [
        { q: '20 + 30', a: 50 },
        { q: '45 + 5', a: 50 },
        { q: '60 + 7', a: 67 },
        { q: '38 + 2', a: 40 },
        { q: '10 + 15', a: 25 },
        { q: '50 + 25', a: 75 },
        { q: '33 + 6', a: 39 },
        { q: '70 + 20', a: 90 },
        { q: '9 + 9', a: 18 },
        { q: '41 + 10', a: 51 },
        { q: '25 + 25', a: 50 },
        { q: '80 + 8', a: 88 },
      ],
    },
  ],
};

const CIGALE: Lesson = {
  id: 'poesie-cigale',
  title: 'La Cigale et la Fourmi',
  subject: 'francais',
  source: 'poesie',
  level: 'CE1',
  notion: 'Mémoriser et réciter un poème',
  attendu: 'Dire pour être entendu et compris : mémoriser des textes.',
  attenduId: 'ce1-oral-memoriser',
  summary:
    'Une fable de Jean de La Fontaine. La cigale a chanté tout l\'été, et quand l\'hiver arrive, elle n\'a plus rien à manger. Les huit premiers vers, à savoir par cœur.',
  minutes: 7,
  exercises: [
    {
      id: 'cig-order-1',
      kind: 'order',
      prompt: 'Remets les quatre premiers vers dans l\'ordre',
      lines: [
        'La Cigale, ayant chanté',
        'Tout l\'été,',
        'Se trouva fort dépourvue',
        'Quand la bise fut venue :',
      ],
      explain: 'La cigale chante tout l\'été, puis se retrouve sans rien quand le vent froid arrive.',
    },
    {
      id: 'cig-blanks-1',
      kind: 'blanks',
      prompt: 'Complète les vers',
      text: 'Pas un seul petit {{morceau}}\nDe mouche ou de {{vermisseau}}.\nElle alla crier {{famine}}\nChez la Fourmi sa voisine,',
      distractors: ['fromage', 'cuisine'],
      explain: 'Morceau rime avec vermisseau, famine rime avec voisine.',
    },
    {
      id: 'cig-rime',
      kind: 'choice',
      prompt: 'Quel mot rime avec « venue » ?',
      options: ['dépourvue', 'chanté', 'voisine'],
      answer: 0,
      explain: 'Venue et dépourvue finissent toutes les deux par le son « ue ».',
    },
    {
      id: 'cig-order-2',
      kind: 'order',
      prompt: 'Remets les vers 5 à 8 dans l\'ordre',
      lines: [
        'Pas un seul petit morceau',
        'De mouche ou de vermisseau.',
        'Elle alla crier famine',
        'Chez la Fourmi sa voisine,',
      ],
      explain: 'D\'abord ce qui manque (le morceau de mouche), puis ce qu\'elle fait (crier famine chez la fourmi).',
    },
    {
      id: 'cig-blanks-2',
      kind: 'blanks',
      prompt: 'Le poème qui s\'efface : complète',
      text: 'La {{Cigale}}, ayant {{chanté}}\nTout l\'{{été}},\nSe trouva fort {{dépourvue}}\nQuand la {{bise}} fut venue :',
      distractors: ['Fourmi', 'hiver', 'pluie'],
      explain: 'Relis le poème en entier une fois à voix haute, puis recommence.',
    },
  ],
};

const MOTS_SEMAINE: Lesson = {
  id: 'mots-semaine-3',
  title: 'Mots de la semaine',
  subject: 'francais',
  source: 'mots',
  level: 'CE1',
  notion: 'Orthographier les mots invariables et les mots fréquents',
  attendu: 'Mémoriser l\'orthographe des mots fréquents et des mots invariables.',
  attenduId: 'ce1-ortho-mots',
  summary:
    'Sept mots à savoir écrire pour la dictée de vendredi : toujours, beaucoup, maison, jardin, chemin, oiseau, souvent.',
  minutes: 6,
  exercises: [
    { id: 'mot-scr-1', kind: 'scramble', word: 'maison', explain: 'mai-son : on entend « mai » puis « son ».' },
    {
      id: 'mot-flash-1',
      kind: 'flash',
      word: 'toujours',
      distractors: ['toujour', 'toujoures'],
      explain: 'Toujours finit toujours par un s, même s\'il ne s\'entend pas.',
    },
    { id: 'mot-scr-2', kind: 'scramble', word: 'oiseau', explain: 'oi-seau : le son « o » de la fin s\'écrit « eau ».' },
    {
      id: 'mot-choice-1',
      kind: 'choice',
      prompt: 'Quelle est la bonne écriture ?',
      speak: 'beaucoup',
      options: ['bocou', 'beaucoup', 'beaucou'],
      answer: 1,
      explain: 'Beau-coup : « beau » comme dans un beau jardin, et un p muet à la fin.',
    },
    {
      id: 'mot-flash-2',
      kind: 'flash',
      word: 'chemin',
      distractors: ['chemain', 'chemen'],
      explain: 'Le son « in » de chemin s\'écrit i-n.',
    },
    { id: 'mot-scr-3', kind: 'scramble', word: 'jardin', explain: 'jar-din : le son « in » s\'écrit i-n, comme dans chemin.' },
    {
      id: 'mot-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a fait une faute, corrige-le',
      words: ['Je', 'vais', 'souvant', 'au', 'jardin.'],
      wrongIndex: 2,
      correct: 'souvent',
      distractors: ['souven', 'souvant'],
      explain: 'Souvent finit par « ent », comme dans « lentement ».',
    },
    {
      id: 'mot-dict-1',
      kind: 'dictation',
      word: 'toujours',
      sentence: 'Je range toujours mes affaires.',
      explain: 'Toujours : t-o-u-j-o-u-r-s, avec un s à la fin.',
    },
    {
      id: 'mot-flash-3',
      kind: 'flash',
      word: 'souvent',
      distractors: ['souvant', 'souven'],
      explain: 'Souvent finit par « ent », avec un t muet.',
    },
  ],
};

const VERBE_SUJET: Lesson = {
  id: 'grammaire-verbe-sujet',
  title: 'Le verbe et le sujet',
  subject: 'francais',
  source: 'grammaire',
  level: 'CE1',
  notion: 'Reconnaître le verbe et son sujet dans une phrase',
  attendu: 'Identifier le verbe conjugué et son sujet dans des phrases simples.',
  attenduId: 'ce1-gram-verbe-sujet',
  summary:
    'Le verbe, c\'est le mot qui dit ce qu\'on fait : il change quand on change le temps (hier, demain). Le sujet, c\'est qui fait l\'action : on le trouve en demandant « qui est-ce qui ? ».',
  minutes: 6,
  exercises: [
    {
      id: 'vs-tap-1',
      kind: 'tapword',
      prompt: 'Touche le verbe',
      words: ['Le', 'chat', 'dort', 'sur', 'le', 'canapé.'],
      answer: [2],
      explain: 'Hier, le chat dormait. Demain, il dormira. Le mot qui change, c\'est le verbe : dort.',
    },
    {
      id: 'vs-tap-2',
      kind: 'tapword',
      prompt: 'Touche le sujet',
      words: ['Les', 'enfants', 'jouent', 'dans', 'la', 'cour.'],
      answer: [0, 1],
      explain: 'Qui est-ce qui joue ? Les enfants. C\'est le sujet.',
    },
    {
      id: 'vs-tf-1',
      kind: 'truefalse',
      statement: 'Dans « Papa prépare le repas », le verbe est « repas ».',
      answer: false,
      explain: 'Le verbe, c\'est prépare : hier papa préparait. « Repas » ne change pas, c\'est un nom.',
    },
    {
      id: 'vs-sort-1',
      kind: 'sort',
      prompt: 'Range chaque mot dans la bonne boîte',
      boxes: ['Verbes', 'Noms'],
      items: [
        { word: 'mange', box: 0 },
        { word: 'table', box: 1 },
        { word: 'court', box: 0 },
        { word: 'école', box: 1 },
        { word: 'chante', box: 0 },
        { word: 'vélo', box: 1 },
      ],
      explain: 'Un verbe se conjugue (je mange, tu manges). Un nom se met après « un » ou « une » : une table.',
    },
    {
      id: 'vs-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a mal accordé le verbe, corrige-le',
      words: ['Les', 'enfants', 'chante', 'dans', 'la', 'cour.'],
      wrongIndex: 2,
      correct: 'chantent',
      distractors: ['chantes', 'chante'],
      explain: 'Les enfants, c\'est « ils » : ils chantent, avec « ent ».',
    },
    {
      id: 'vs-sentence-1',
      kind: 'sentence',
      prompt: 'Remets la phrase dans l\'ordre',
      words: ['Ma', 'sœur', 'lit', 'un', 'livre.'],
      explain: 'Le sujet d\'abord (ma sœur), puis le verbe (lit), puis le reste.',
    },
    {
      id: 'vs-card-1',
      kind: 'flashcard',
      prompt: 'Comment trouve-t-on le sujet ?',
      front: 'Quelle question pose-t-on pour trouver le sujet du verbe ?',
      back: '« Qui est-ce qui ? » devant le verbe.',
      explain: 'Qui est-ce qui dort ? Le chat. Le chat est le sujet.',
    },
    {
      id: 'vs-tf-2',
      kind: 'truefalse',
      statement: 'Pour trouver le sujet, on demande « qui est-ce qui ? ».',
      answer: true,
      explain: 'Oui : qui est-ce qui lit ? Ma sœur. Le sujet, c\'est ma sœur.',
    },
  ],
};

const TABLES_2_5: Lesson = {
  id: 'calcul-tables-2-5',
  title: 'Les tables de 2 et de 5',
  subject: 'maths',
  source: 'calcul',
  level: 'CE1',
  notion: 'Mémoriser les tables de multiplication de 2 et de 5',
  attendu: 'Connaître les tables de multiplication de 2 et de 5.',
  attenduId: 'ce1-calc-tables',
  summary:
    'Multiplier par 2, c\'est doubler : 2 × 4, c\'est 4 + 4. Multiplier par 5, c\'est compter de 5 en 5 : les résultats finissent toujours par 0 ou par 5.',
  minutes: 6,
  exercises: [
    {
      id: 't25-match',
      kind: 'match',
      prompt: 'Relie chaque calcul à son résultat avant la fin du chrono',
      seconds: 40,
      pairs: [
        { a: '2 × 8', b: '16' },
        { a: '5 × 6', b: '30' },
        { a: '2 × 4', b: '8' },
        { a: '5 × 3', b: '15' },
        { a: '2 × 6', b: '12' },
      ],
      explain: 'Bats ton record la prochaine fois : les tables rentrent en les répétant.',
    },
    {
      id: 't25-card-1',
      kind: 'flashcard',
      prompt: 'Dis le résultat, puis vérifie',
      front: '5 × 7',
      back: '35',
      explain: '5 × 7 = 35. Les résultats de la table de 5 finissent par 0 ou 5.',
    },
    {
      id: 't25-count-1',
      kind: 'count',
      prompt: 'Combien y a-t-il d\'objets ? Touche-les pour compter.',
      emoji: '🍎',
      answer: 10,
      options: [8, 10, 12],
      explain: '2 rangées de 5, ou 5 paquets de 2 : ça fait 10.',
    },
    {
      id: 't25-pairs-1',
      kind: 'pairs',
      prompt: 'Retrouve chaque calcul et son résultat',
      pairs: [
        { a: '2 × 3', b: '6' },
        { a: '5 × 2', b: '10' },
        { a: '2 × 7', b: '14' },
        { a: '5 × 4', b: '20' },
        { a: '5 × 5', b: '25' },
        { a: '2 × 9', b: '18' },
      ],
      explain: 'Les résultats de la table de 5 finissent par 0 ou 5, ceux de la table de 2 sont toujours pairs.',
    },
    {
      id: 't25-tf-1',
      kind: 'truefalse',
      statement: '5 × 6 = 30',
      answer: true,
      explain: '5, 10, 15, 20, 25, 30 : six sauts de 5, ça fait 30.',
    },
    {
      id: 't25-tf-2',
      kind: 'truefalse',
      statement: '2 × 8 = 14',
      answer: false,
      explain: '2 × 8, c\'est 8 + 8 = 16.',
    },
    {
      id: 't25-fix-1',
      kind: 'fix',
      prompt: 'Gribouille s\'est trompé dans son calcul, corrige-le',
      words: ['5', '×', '4', '=', '25'],
      wrongIndex: 4,
      correct: '20',
      distractors: ['24', '25'],
      explain: '5 × 4, c\'est 5 + 5 + 5 + 5 = 20. 25, c\'est 5 × 5.',
    },
    {
      id: 't25-speed-1',
      kind: 'speed',
      prompt: 'Calcul éclair : tables de 2 et de 5',
      seconds: 45,
      target: 6,
      items: [
        { q: '2 × 4', a: 8 },
        { q: '5 × 3', a: 15 },
        { q: '2 × 6', a: 12 },
        { q: '5 × 7', a: 35 },
        { q: '2 × 10', a: 20 },
        { q: '5 × 9', a: 45 },
        { q: '2 × 5', a: 10 },
        { q: '5 × 8', a: 40 },
      ],
      explain: 'Pas grave : on y revient demain, les tables rentrent en les répétant un peu chaque jour.',
    },
  ],
};

export const LESSONS: Lesson[] = [NOMBRES_100, CIGALE, MOTS_SEMAINE, VERBE_SUJET, TABLES_2_5];

export function findLesson(id: string | undefined): Lesson | undefined {
  return LESSONS.find((l) => l.id === id);
}
