import type { Lesson } from './types';

/**
 * Banque de français, CE2. Dix-sept leçons qui couvrent les attendus de fin
 * de CE2 : lecture, poésie, orthographe, grammaire, conjugaison, vocabulaire.
 * Tous les textes sont originaux, sauf la fable de La Fontaine (domaine public).
 */

const LIRE_EXPRESSION: Lesson = {
  id: 'ce2-francais-lire-expression',
  title: 'Lire avec expression',
  subject: 'francais',
  source: 'lecture',
  level: 'CE2',
  notion: 'Lire à voix haute avec expression, en respectant la ponctuation et les liaisons',
  theme: 'lecture',
  attendu: 'Lire à voix haute avec fluidité et expression, en respectant la ponctuation et les liaisons.',
  attenduId: 'ce2-lect-fluide',
  summary:
    "Quand tu lis à voix haute, ta voix suit la ponctuation : elle monte pour une question, elle s'anime pour une exclamation. Et quand un mot finit par une lettre muette et que le suivant commence par une voyelle, on fait la liaison : « les arbres » se dit « les-z-arbres ». Voici le texte : Ce soir, Inès et son cousin Malo campent dans le jardin. Ils ont monté la tente tout seuls, sans aide ! Quand la nuit tombe, les arbres font des ombres étranges. « Tu as entendu ce bruit ? » chuchote Malo. Inès allume la lampe et éclaire un hérisson qui trottine. Les deux enfants rient, puis ils s'endorment sous les étoiles.",
  minutes: 6,
  exercises: [
    {
      id: 'ce2-francais-lire-expression-tap-1',
      kind: 'tapword',
      prompt: 'Touche les deux mots après lesquels on fait une liaison',
      words: ['Quand', 'la', 'nuit', 'tombe,', 'les', 'arbres', 'font', 'des', 'ombres', 'étranges.'],
      answer: [4, 7],
      explain: "« Les arbres » et « des ombres » : le s muet se fait entendre comme un « z » devant la voyelle.",
    },
    {
      id: 'ce2-francais-lire-expression-tap-2',
      kind: 'tapword',
      prompt: 'Touche le mot sur lequel la voix monte',
      words: ['Tu', 'as', 'entendu', 'ce', 'bruit ?', 'chuchote', 'Malo.'],
      answer: [4],
      explain: "Le point d'interrogation est après « bruit » : c'est là que la voix monte, comme pour une question.",
    },
    {
      id: 'ce2-francais-lire-expression-tf-1',
      kind: 'truefalse',
      statement: "Quand une phrase finit par un point d'exclamation, on la lit avec plus d'énergie.",
      answer: true,
      explain: "C'est ça : le point d'exclamation montre la surprise ou la joie, la voix s'anime.",
    },
    {
      id: 'ce2-francais-lire-expression-choice-1',
      kind: 'choice',
      prompt: 'Comment lit-on « Ils ont monté la tente tout seuls, sans aide ! »',
      options: ['Avec une voix fière et joyeuse', 'Avec une voix triste', 'Avec une voix qui monte comme une question'],
      answer: 0,
      explain: "Le point d'exclamation dit la fierté des enfants : on lit la phrase avec entrain.",
    },
    {
      id: 'ce2-francais-lire-expression-order-1',
      kind: 'order',
      prompt: "Remets les phrases du texte dans l'ordre",
      lines: [
        'Ce soir, Inès et son cousin Malo campent dans le jardin.',
        'Ils ont monté la tente tout seuls, sans aide !',
        'Quand la nuit tombe, les arbres font des ombres étranges.',
        '« Tu as entendu ce bruit ? » chuchote Malo.',
      ],
      explain: "D'abord ils campent, puis ils montent la tente, la nuit tombe, et enfin Malo entend un bruit.",
    },
    {
      id: 'ce2-francais-lire-expression-tap-3',
      kind: 'tapword',
      prompt: 'Touche les deux mots après lesquels on fait une liaison',
      words: ['Les', 'deux', 'enfants', 'rient,', 'puis', 'ils', "s'endorment", 'sous', 'les', 'étoiles.'],
      answer: [1, 8],
      explain: '« Deux enfants » se dit « deux-z-enfants » et « les étoiles » se dit « les-z-étoiles ».',
    },
    {
      id: 'ce2-francais-lire-expression-sentence-1',
      kind: 'sentence',
      prompt: "Remets les mots de la phrase dans l'ordre",
      words: ['Inès', 'allume', 'la', 'lampe', 'et', 'éclaire', 'un', 'hérisson', 'qui', 'trottine.'],
      explain: "Inès allume d'abord la lampe, et ensuite elle éclaire le hérisson. Le point est sur le dernier mot.",
    },
    {
      id: 'ce2-francais-lire-expression-tf-2',
      kind: 'truefalse',
      statement: 'Dans « Tu as entendu », on fait la liaison entre « as » et « entendu ».',
      answer: true,
      explain: 'Oui : « as » finit par un s muet et « entendu » commence par une voyelle, on dit « as-z-entendu ».',
    },
    {
      id: 'ce2-francais-lire-expression-choice-2',
      kind: 'choice',
      prompt: 'Lire avec expression, ça veut dire...',
      options: ['Lire le plus vite possible', 'Changer sa voix selon la ponctuation et le sens', "Lire tout d'une traite sans respirer"],
      answer: 1,
      explain: "Lire avec expression, c'est faire vivre le texte : la voix change avec les points, les virgules et les émotions.",
    },
  ],
};

const COMPRENDRE_RECIT: Lesson = {
  id: 'ce2-francais-comprendre-recit',
  title: 'Comprendre un récit',
  subject: 'francais',
  source: 'lecture',
  level: 'CE2',
  notion: "Comprendre une histoire : les personnages, les lieux, l'ordre des événements et ce qu'on devine",
  theme: 'lecture',
  attendu: "Comprendre un texte : personnages, lieux, chronologie, ce qui n'est pas écrit mais qu'on devine.",
  attenduId: 'ce2-lect-comprendre',
  summary:
    "Lis bien l'histoire, puis réponds aux questions. Certaines réponses ne sont pas écrites : il faut les deviner avec les indices. Lundi matin, Jules arrive à l'école avec un sac très lourd. Il n'a dit à personne ce qu'il y a dedans. À la récréation, il s'assoit sur le banc et surveille son sac du coin de l'œil. Sa copine Léa s'approche et entend un petit bruit : « Miaou ! » Jules devient tout rouge. Il explique qu'il a trouvé un chaton abandonné devant chez lui et qu'il n'a pas voulu le laisser seul. Léa va chercher la maîtresse. Celle-ci regarde dans le sac, sourit et appelle les parents de Jules. Le soir, le chaton dort dans un panier, au chaud, dans la chambre de Jules.",
  minutes: 7,
  exercises: [
    {
      id: 'ce2-francais-comprendre-recit-choice-1',
      kind: 'choice',
      prompt: "Qu'y a-t-il dans le sac de Jules ?",
      options: ['Un lapin', 'Un chaton', 'Un gros livre'],
      answer: 1,
      explain: "Relis : Léa entend « Miaou ! », et Jules explique qu'il a trouvé un chaton.",
    },
    {
      id: 'ce2-francais-comprendre-recit-tf-1',
      kind: 'truefalse',
      statement: "Jules a dit à tout le monde ce qu'il y a dans son sac.",
      answer: false,
      explain: "Pas grave. Le texte dit « Il n'a dit à personne ce qu'il y a dedans » : c'est un secret.",
    },
    {
      id: 'ce2-francais-comprendre-recit-tap-1',
      kind: 'tapword',
      prompt: "Touche le mot qui dit quel jour se passe l'histoire",
      words: ['Lundi', 'matin,', 'Jules', 'arrive', 'à', "l'école", 'avec', 'un', 'sac', 'très', 'lourd.'],
      answer: [0],
      explain: "C'est « lundi » qui donne le jour. « Matin » donne le moment de la journée.",
    },
    {
      id: 'ce2-francais-comprendre-recit-choice-2',
      kind: 'choice',
      prompt: "Pourquoi Jules devient-il tout rouge ? Ce n'est pas écrit, il faut deviner.",
      options: ['Parce qu\'il a trop chaud', 'Parce qu\'il est en colère contre Léa', 'Parce qu\'il est gêné : son secret est découvert'],
      answer: 2,
      explain: "Léa vient d'entendre le miaou : Jules est gêné parce que son secret est découvert. On devine ça grâce aux indices.",
    },
    {
      id: 'ce2-francais-comprendre-recit-tf-2',
      kind: 'truefalse',
      statement: "C'est Léa qui va chercher la maîtresse.",
      answer: true,
      explain: 'Oui, le texte dit « Léa va chercher la maîtresse ».',
    },
    {
      id: 'ce2-francais-comprendre-recit-sort-1',
      kind: 'sort',
      prompt: "Range : personnage de l'histoire, ou pas dans l'histoire",
      boxes: ["Dans l'histoire", "Pas dans l'histoire"],
      items: [
        { word: 'Jules', box: 0 },
        { word: 'le directeur', box: 1 },
        { word: 'Léa', box: 0 },
        { word: 'la maîtresse', box: 0 },
        { word: 'le grand-père', box: 1 },
        { word: 'le chaton', box: 0 },
      ],
      explain: "Jules, Léa, la maîtresse et le chaton sont dans l'histoire. Il n'y a ni directeur ni grand-père.",
    },
    {
      id: 'ce2-francais-comprendre-recit-order-1',
      kind: 'order',
      prompt: "Remets les événements dans l'ordre de l'histoire",
      lines: [
        "Jules arrive à l'école avec un sac lourd.",
        'Léa entend un miaou dans le sac.',
        'La maîtresse regarde dans le sac et appelle les parents.',
        'Le chaton dort dans la chambre de Jules.',
      ],
      explain: "D'abord le sac mystérieux, puis le miaou, puis la maîtresse, et à la fin le chaton bien au chaud.",
    },
    {
      id: 'ce2-francais-comprendre-recit-choice-3',
      kind: 'choice',
      prompt: 'Pourquoi la maîtresse sourit-elle en regardant dans le sac ?',
      options: ['Elle trouve le chaton mignon et elle n\'est pas fâchée', 'Elle veut punir Jules', 'Elle a gagné un cadeau'],
      answer: 0,
      explain: "Ce n'est pas écrit, mais on le devine : elle sourit parce que le chaton est mignon, et elle aide Jules en appelant ses parents.",
    },
    {
      id: 'ce2-francais-comprendre-recit-tf-3',
      kind: 'truefalse',
      statement: 'À la fin, les parents de Jules ont accepté de garder le chaton.',
      answer: true,
      explain: "Ce n'est pas écrit, mais le chaton dort dans la chambre de Jules le soir : les parents ont dit oui.",
    },
  ],
};

const CIGALE_FOURMI: Lesson = {
  id: 'ce2-francais-cigale-fourmi',
  title: 'La Cigale et la Fourmi',
  subject: 'francais',
  source: 'poesie',
  level: 'CE2',
  notion: 'Mémoriser et réciter une fable',
  theme: 'poesie',
  attendu: 'Mémoriser et dire un poème avec expression, en respectant les vers et les rimes.',
  attenduId: 'ce2-oral-memoriser',
  summary:
    "Une fable de Jean de La Fontaine. La cigale a chanté tout l'été sans rien mettre de côté. Quand l'hiver arrive, elle demande à manger à la fourmi, qui refuse. Apprends-la par morceaux de quatre vers.",
  minutes: 8,
  exercises: [
    {
      id: 'ce2-francais-cigale-fourmi-order-1',
      kind: 'order',
      prompt: "Remets les quatre premiers vers dans l'ordre",
      lines: ['La Cigale, ayant chanté', "Tout l'été,", 'Se trouva fort dépourvue', 'Quand la bise fut venue :'],
      explain: "D'abord la cigale chante tout l'été, puis elle se retrouve sans rien quand le vent froid arrive.",
    },
    {
      id: 'ce2-francais-cigale-fourmi-blanks-1',
      kind: 'blanks',
      prompt: 'Complète les vers',
      text: 'Se trouva fort {{dépourvue}}\nQuand la {{bise}} fut venue :',
      distractors: ['contente', 'pluie'],
      explain: "« Dépourvue » veut dire qu'elle n'a plus rien, et la « bise », c'est le vent froid de l'hiver.",
    },
    {
      id: 'ce2-francais-cigale-fourmi-choice-1',
      kind: 'choice',
      prompt: 'Quel mot rime avec « chanté » ?',
      options: ['dépourvue', 'été', 'morceau'],
      answer: 1,
      explain: 'Chanté et été finissent tous les deux par le son « é ».',
    },
    {
      id: 'ce2-francais-cigale-fourmi-order-2',
      kind: 'order',
      prompt: "Remets les vers 5 à 8 dans l'ordre",
      lines: ['Pas un seul petit morceau', 'De mouche ou de vermisseau.', 'Elle alla crier famine', 'Chez la Fourmi sa voisine,'],
      explain: "Elle n'a plus rien à manger, alors elle va se plaindre chez sa voisine la fourmi.",
    },
    {
      id: 'ce2-francais-cigale-fourmi-flashcard-1',
      kind: 'flashcard',
      prompt: 'Récite le vers suivant, puis retourne la carte pour vérifier',
      front: 'Elle alla crier famine',
      back: 'Chez la Fourmi sa voisine,',
      explain: '« Crier famine », ça veut dire se plaindre d\'avoir très faim.',
    },
    {
      id: 'ce2-francais-cigale-fourmi-order-3',
      kind: 'order',
      prompt: "Remets les vers 9 à 12 dans l'ordre",
      lines: ['La priant de lui prêter', 'Quelque grain pour subsister', "Jusqu'à la saison nouvelle.", '« Je vous paierai, lui dit-elle,'],
      explain: 'La cigale demande du grain pour tenir jusqu\'au printemps, et elle promet de payer.',
    },
    {
      id: 'ce2-francais-cigale-fourmi-choice-2',
      kind: 'choice',
      prompt: 'Quel mot rime avec « morceau » ?',
      options: ['vermisseau', 'famine', 'voisine'],
      answer: 0,
      explain: 'Morceau et vermisseau finissent tous les deux par le son « eau ».',
    },
    {
      id: 'ce2-francais-cigale-fourmi-tf-1',
      kind: 'truefalse',
      statement: 'La Fourmi prête du grain à la Cigale.',
      answer: false,
      explain: "Pas grave. Le texte dit « La Fourmi n'est pas prêteuse » : elle refuse.",
    },
    {
      id: 'ce2-francais-cigale-fourmi-order-4',
      kind: 'order',
      prompt: "Remets les vers 17 à 20 dans l'ordre",
      lines: ['« Que faisiez-vous au temps chaud ?', 'Dit-elle à cette emprunteuse.', '— Nuit et jour à tout venant', 'Je chantais, ne vous déplaise.'],
      explain: "La fourmi pose sa question, puis la cigale répond qu'elle chantait nuit et jour.",
    },
    {
      id: 'ce2-francais-cigale-fourmi-blanks-2',
      kind: 'blanks',
      prompt: 'Complète les deux derniers vers',
      text: "— Vous {{chantiez}} ? j'en suis fort aise.\nEh bien ! {{dansez}} maintenant. »",
      distractors: ['dormiez', 'mangez'],
      explain: 'La fourmi se moque : « Vous chantiez ? Eh bien, dansez maintenant ! »',
    },
  ],
};

const HOMOPHONES_A_ET: Lesson = {
  id: 'ce2-francais-homophones-a-et',
  title: 'a ou à, et ou est',
  subject: 'francais',
  source: 'lecon',
  level: 'CE2',
  notion: 'Distinguer les homophones a / à et et / est',
  theme: 'orthographe',
  attendu: 'Orthographier les mots fréquents et les mots invariables, et les homophones a/à, et/est, on/ont, son/sont.',
  attenduId: 'ce2-ortho-mots',
  summary:
    "« a » sans accent, c'est le verbe avoir : on peut le remplacer par « avait ». « à » avec accent ne change jamais : il va à la piscine. « est », c'est le verbe être : on peut dire « était ». « et » veut dire « et puis » : du pain et du fromage.",
  minutes: 6,
  exercises: [
    {
      id: 'ce2-francais-homophones-a-et-choice-1',
      kind: 'choice',
      prompt: 'Lina ... un vélo rouge.',
      options: ['à', 'a'],
      answer: 1,
      explain: 'On peut dire « Lina avait un vélo » : c\'est le verbe avoir, sans accent.',
    },
    {
      id: 'ce2-francais-homophones-a-et-choice-2',
      kind: 'choice',
      prompt: 'Il va ... la piscine.',
      options: ['a', 'à'],
      answer: 1,
      explain: 'On ne peut pas dire « il va avait la piscine » : c\'est « à » avec accent.',
    },
    {
      id: 'ce2-francais-homophones-a-et-tf-1',
      kind: 'truefalse',
      statement: 'Dans « Papa est parti », on peut remplacer « est » par « était ».',
      answer: true,
      explain: 'Oui : « Papa était parti ». C\'est le verbe être, on écrit e-s-t.',
    },
    {
      id: 'ce2-francais-homophones-a-et-blanks-1',
      kind: 'blanks',
      prompt: 'Complète avec est ou et',
      text: 'Le chat {{est}} sur le mur {{et}} il regarde les oiseaux.',
      distractors: ['a', 'à'],
      explain: '« Le chat était sur le mur » : verbe être. Puis « et puis il regarde » : e-t.',
    },
    {
      id: 'ce2-francais-homophones-a-et-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a fait une faute, corrige-le',
      words: ['Tom', 'à', 'mangé', 'une', 'pomme.'],
      wrongIndex: 1,
      correct: 'a',
      distractors: ['et', 'est'],
      explain: 'On peut dire « Tom avait mangé » : c\'est le verbe avoir, sans accent.',
    },
    {
      id: 'ce2-francais-homophones-a-et-sort-1',
      kind: 'sort',
      prompt: 'Peut-on remplacer par « avait » ?',
      boxes: ['Oui, on écrit a', 'Non, on écrit à'],
      items: [
        { word: 'Il ... faim', box: 0 },
        { word: '... la maison', box: 1 },
        { word: 'Elle ... dix ans', box: 0 },
        { word: '... bientôt', box: 1 },
        { word: 'Le chien ... soif', box: 0 },
        { word: '... midi', box: 1 },
      ],
      explain: '« Il avait faim », « elle avait dix ans », « le chien avait soif » : verbe avoir. Les autres prennent un accent.',
    },
    {
      id: 'ce2-francais-homophones-a-et-blanks-2',
      kind: 'blanks',
      prompt: 'Complète avec a, à, et ou est',
      text: "Noé {{a}} un frère {{et}} une sœur. Il va {{à}} l'école {{et}} son frère {{est}} au collège.",
      distractors: ['ai', 'es'],
      explain: '« Noé avait un frère et puis une sœur. Il va à l\'école, et puis son frère était au collège. »',
    },
    {
      id: 'ce2-francais-homophones-a-et-fix-2',
      kind: 'fix',
      prompt: 'Gribouille a fait une faute, corrige-le',
      words: ['La', 'maison', 'et', 'grande', 'et', 'belle.'],
      wrongIndex: 2,
      correct: 'est',
      distractors: ['a', 'à'],
      explain: '« La maison était grande » : c\'est le verbe être, on écrit e-s-t.',
    },
    {
      id: 'ce2-francais-homophones-a-et-choice-3',
      kind: 'choice',
      prompt: 'Quel mot peut remplacer « est » dans « Le ciel est bleu » ?',
      options: ['était', 'et puis', 'avait'],
      answer: 0,
      explain: '« Le ciel était bleu » : ça marche, donc c\'est bien le verbe être.',
    },
  ],
};

const HOMOPHONES_ON_SON: Lesson = {
  id: 'ce2-francais-homophones-on-son',
  title: 'on ou ont, son ou sont',
  subject: 'francais',
  source: 'lecon',
  level: 'CE2',
  notion: 'Distinguer les homophones on / ont et son / sont',
  theme: 'orthographe',
  attendu: 'Orthographier les mots fréquents et les mots invariables, et les homophones a/à, et/est, on/ont, son/sont.',
  attenduId: 'ce2-ortho-mots',
  summary:
    "« on », c'est quelqu'un : on peut le remplacer par « il ». « ont », c'est le verbe avoir : on peut dire « avaient ». « son » veut dire « le sien » : on peut dire « mon ». « sont », c'est le verbe être : on peut dire « étaient ».",
  minutes: 6,
  exercises: [
    {
      id: 'ce2-francais-homophones-on-son-choice-1',
      kind: 'choice',
      prompt: 'Les enfants ... faim.',
      options: ['on', 'ont'],
      answer: 1,
      explain: '« Les enfants avaient faim » : c\'est le verbe avoir, on écrit o-n-t.',
    },
    {
      id: 'ce2-francais-homophones-on-son-choice-2',
      kind: 'choice',
      prompt: '... part demain matin.',
      options: ['On', 'Ont'],
      answer: 0,
      explain: '« Il part demain matin » : ça marche, donc c\'est « on », quelqu\'un.',
    },
    {
      id: 'ce2-francais-homophones-on-son-tf-1',
      kind: 'truefalse',
      statement: 'Dans « ils sont partis », on peut dire « ils étaient partis ».',
      answer: true,
      explain: 'Oui : c\'est le verbe être, on écrit s-o-n-t.',
    },
    {
      id: 'ce2-francais-homophones-on-son-sort-1',
      kind: 'sort',
      prompt: 'Range : on ou ont ?',
      boxes: ['on = quelqu\'un', 'ont = avaient'],
      items: [
        { word: '... rit', box: 0 },
        { word: 'Ils ... peur', box: 1 },
        { word: '... dort', box: 0 },
        { word: 'Elles ... fini', box: 1 },
        { word: '... joue', box: 0 },
        { word: 'Les chats ... faim', box: 1 },
      ],
      explain: '« Il rit, il dort, il joue » : c\'est on. « Ils avaient peur, elles avaient fini, les chats avaient faim » : c\'est ont.',
    },
    {
      id: 'ce2-francais-homophones-on-son-blanks-1',
      kind: 'blanks',
      prompt: 'Complète avec son ou sont',
      text: 'Léa prend {{son}} manteau. Ses frères {{sont}} déjà dehors.',
      distractors: ['on', 'ont'],
      explain: '« Léa prend mon manteau » : son, le sien. « Ses frères étaient dehors » : sont, verbe être.',
    },
    {
      id: 'ce2-francais-homophones-on-son-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a fait une faute, corrige-le',
      words: ['Les', 'voisins', 'son', 'gentils.'],
      wrongIndex: 2,
      correct: 'sont',
      distractors: ['ont', 'on'],
      explain: '« Les voisins étaient gentils » : verbe être, il faut le t de sont.',
    },
    {
      id: 'ce2-francais-homophones-on-son-fix-2',
      kind: 'fix',
      prompt: 'Gribouille a fait une faute, corrige-le',
      words: ['On', 'va', 'au', 'parc', 'avec', 'sont', 'chien.'],
      wrongIndex: 5,
      correct: 'son',
      distractors: ['sons', 'ont'],
      explain: '« Avec mon chien » : ça marche, donc c\'est « son », sans t.',
    },
    {
      id: 'ce2-francais-homophones-on-son-blanks-2',
      kind: 'blanks',
      prompt: 'Complète avec on, ont, son ou sont',
      text: 'Les élèves {{sont}} en classe. Ils {{ont}} un cahier. {{On}} entend {{son}} crayon.',
      distractors: ['est', 'a'],
      explain: '« Les élèves étaient en classe. Ils avaient un cahier. Il entend mon crayon. »',
    },
    {
      id: 'ce2-francais-homophones-on-son-dict-1',
      kind: 'dictation',
      word: 'sont',
      sentence: 'Les oiseaux sont dans le nid.',
      explain: '« Les oiseaux étaient dans le nid » : verbe être, s-o-n-t.',
    },
    {
      id: 'ce2-francais-homophones-on-son-tf-2',
      kind: 'truefalse',
      statement: 'Dans « on chante », on peut remplacer « on » par « avaient ».',
      answer: false,
      explain: 'Pas grave. « Avaient chante », ça ne marche pas. Ici on peut dire « il chante » : c\'est on.',
    },
  ],
};

const MOTS_INVARIABLES: Lesson = {
  id: 'ce2-francais-mots-invariables',
  title: 'Les mots invariables',
  subject: 'francais',
  source: 'mots',
  level: 'CE2',
  notion: 'Mémoriser l\'orthographe des mots invariables fréquents',
  theme: 'orthographe',
  attendu: 'Orthographier les mots fréquents et les mots invariables, et les homophones a/à, et/est, on/ont, son/sont.',
  attenduId: 'ce2-ortho-mots',
  summary:
    "Les mots invariables s'écrivent toujours de la même façon, jamais de s ni de e en plus. Il faut les connaître par cœur. Les mots de la semaine : aujourd'hui, maintenant, longtemps, pendant, souvent, autour, après, avant, encore, enfin, parfois, presque, trop, ensuite.",
  minutes: 7,
  exercises: [
    {
      id: 'ce2-francais-mots-invariables-tf-1',
      kind: 'truefalse',
      statement: "Un mot invariable s'écrit toujours de la même façon.",
      answer: true,
      explain: 'C\'est ça : invariable veut dire « qui ne varie pas ». Il ne prend jamais de s.',
    },
    {
      id: 'ce2-francais-mots-invariables-flash-1',
      kind: 'flash',
      word: "aujourd'hui",
      distractors: ['aujourdui', "aujour'dhui"],
      explain: "Aujourd'hui : l'apostrophe est après le d, et il y a un h muet avant le ui.",
    },
    {
      id: 'ce2-francais-mots-invariables-scramble-1',
      kind: 'scramble',
      word: 'souvent',
      explain: 'Sou-vent : le son « ou » s\'écrit o-u, et le t final est muet.',
    },
    {
      id: 'ce2-francais-mots-invariables-dict-1',
      kind: 'dictation',
      word: 'maintenant',
      sentence: 'Maintenant, il est temps de partir.',
      explain: 'Main-te-nant : « main » comme la main, puis « te », puis « nant » avec a-n-t.',
    },
    {
      id: 'ce2-francais-mots-invariables-flash-2',
      kind: 'flash',
      word: 'longtemps',
      distractors: ['lontemps', 'longtemp'],
      explain: 'Long-temps : il y a un g muet après « lon », et un s muet à la fin.',
    },
    {
      id: 'ce2-francais-mots-invariables-blanks-1',
      kind: 'blanks',
      prompt: 'Complète la phrase',
      text: 'Il pleut {{souvent}} en automne, mais {{parfois}} le soleil revient.',
      distractors: ['trop', 'avant'],
      explain: 'Il pleut souvent, c\'est-à-dire beaucoup de fois, mais parfois, de temps en temps, le soleil revient.',
    },
    {
      id: 'ce2-francais-mots-invariables-scramble-2',
      kind: 'scramble',
      word: 'presque',
      explain: 'Pres-que : le son « k » s\'écrit q-u, et le e final est muet.',
    },
    {
      id: 'ce2-francais-mots-invariables-dict-2',
      kind: 'dictation',
      word: 'ensuite',
      sentence: 'Ensuite, nous irons à la piscine.',
      explain: 'En-sui-te : le son « en » s\'écrit e-n, puis « suite » comme la suite.',
    },
    {
      id: 'ce2-francais-mots-invariables-blanks-2',
      kind: 'blanks',
      prompt: 'Complète la phrase',
      text: '{{Avant}} de dormir, Léa lit {{encore}} une page, puis {{enfin}} elle éteint la lumière.',
      distractors: ['après', 'autour'],
      explain: 'Avant de dormir, elle lit encore une page, et enfin, à la toute fin, elle éteint.',
    },
    {
      id: 'ce2-francais-mots-invariables-dict-3',
      kind: 'dictation',
      word: 'trop',
      sentence: 'Ce sac est trop lourd pour moi.',
      explain: 'Trop : t-r-o-p, le p final est muet.',
    },
  ],
};

const PLURIELS_X: Lesson = {
  id: 'ce2-francais-pluriels-x',
  title: 'Les pluriels en -x',
  subject: 'francais',
  source: 'lecon',
  level: 'CE2',
  notion: 'Former les pluriels en -x et accorder l\'adjectif dans le groupe nominal',
  theme: 'orthographe',
  attendu: 'Accorder dans le groupe nominal (genre et nombre, pluriels en -x) et le verbe avec son sujet.',
  attenduId: 'ce2-ortho-accords',
  summary:
    "Au pluriel, les noms en -eau et en -eu prennent un x : des bateaux, des jeux. Les noms en -al deviennent -aux : un cheval, des chevaux. Sept noms en -ou prennent un x : bijou, caillou, chou, genou, hibou, joujou, pou. L'adjectif s'accorde avec le nom : des petits bateaux, des robes bleues.",
  minutes: 7,
  exercises: [
    {
      id: 'ce2-francais-pluriels-x-choice-1',
      kind: 'choice',
      prompt: 'Quel est le pluriel de « bateau » ?',
      options: ['bateaus', 'bateaux', 'bateaut'],
      answer: 1,
      explain: 'Les noms en -eau prennent un x au pluriel : des bateaux.',
    },
    {
      id: 'ce2-francais-pluriels-x-choice-2',
      kind: 'choice',
      prompt: 'Quel est le pluriel de « cheval » ?',
      options: ['chevaux', 'chevals', 'chevales'],
      answer: 0,
      explain: 'Les noms en -al deviennent -aux : un cheval, des chevaux.',
    },
    {
      id: 'ce2-francais-pluriels-x-sort-1',
      kind: 'sort',
      prompt: 'Range : pluriel en -s ou pluriel en -x ?',
      boxes: ['Pluriel en -s', 'Pluriel en -x'],
      items: [
        { word: 'un jeu', box: 1 },
        { word: 'un trou', box: 0 },
        { word: 'un bijou', box: 1 },
        { word: 'un chat', box: 0 },
        { word: 'un gâteau', box: 1 },
        { word: 'un clou', box: 0 },
        { word: 'un caillou', box: 1 },
        { word: 'une table', box: 0 },
      ],
      explain: 'Jeux, bijoux, gâteaux, cailloux prennent un x. Trous, chats, clous, tables prennent un s.',
    },
    {
      id: 'ce2-francais-pluriels-x-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a fait une faute, corrige-le',
      words: ['Les', 'chevaus', 'galopent', 'dans', 'le', 'pré.'],
      wrongIndex: 1,
      correct: 'chevaux',
      distractors: ['chevals', 'chevalx'],
      explain: 'Cheval finit par -al : au pluriel, ça devient chevaux avec a-u-x.',
    },
    {
      id: 'ce2-francais-pluriels-x-blanks-1',
      kind: 'blanks',
      prompt: 'Complète avec les mots au pluriel',
      text: 'Lina range ses {{bijoux}} et ses {{jeux}} dans deux {{boîtes}}.',
      distractors: ['bijous', 'jeus'],
      explain: 'Bijou fait partie des sept mots en -ou qui prennent un x. Jeu prend un x. Boîte prend un s.',
    },
    {
      id: 'ce2-francais-pluriels-x-pairs-1',
      kind: 'pairs',
      prompt: 'Associe chaque mot à son pluriel',
      pairs: [
        { a: 'cheval', b: 'chevaux' },
        { a: 'bateau', b: 'bateaux' },
        { a: 'jeu', b: 'jeux' },
        { a: 'bijou', b: 'bijoux' },
        { a: 'journal', b: 'journaux' },
      ],
      explain: 'Cheval et journal deviennent -aux ; bateau, jeu et bijou prennent un x.',
    },
    {
      id: 'ce2-francais-pluriels-x-fix-2',
      kind: 'fix',
      prompt: 'Gribouille a oublié un accord, corrige-le',
      words: ['Les', 'petit', 'oiseaux', 'chantent.'],
      wrongIndex: 1,
      correct: 'petits',
      distractors: ['petites', 'petite'],
      explain: '« Oiseaux » est au masculin pluriel, alors l\'adjectif prend un s : petits.',
    },
    {
      id: 'ce2-francais-pluriels-x-tf-1',
      kind: 'truefalse',
      statement: '« des gros cailloux » est bien écrit.',
      answer: true,
      explain: 'Oui : caillou prend un x au pluriel, et « gros » ne change pas car il finit déjà par un s.',
    },
    {
      id: 'ce2-francais-pluriels-x-dict-1',
      kind: 'dictation',
      word: 'chevaux',
      sentence: 'Les chevaux courent dans le pré.',
      explain: 'Che-vaux : c-h au début, et a-u-x à la fin pour le pluriel.',
    },
    {
      id: 'ce2-francais-pluriels-x-fix-3',
      kind: 'fix',
      prompt: 'Gribouille a oublié un accord, corrige-le',
      words: ['Elles', 'portent', 'des', 'robes', 'bleu.'],
      wrongIndex: 4,
      correct: 'bleues',
      distractors: ['bleus', 'bleue'],
      explain: '« Robes » est au féminin pluriel : l\'adjectif prend un e et un s, bleues.',
    },
  ],
};

const ACCORD_VERBE: Lesson = {
  id: 'ce2-francais-accord-verbe',
  title: 'Accorder le verbe avec le sujet',
  subject: 'francais',
  source: 'lecon',
  level: 'CE2',
  notion: 'Accorder le verbe avec son sujet, même éloigné ou inversé, avec nous et vous',
  theme: 'orthographe',
  attendu: 'Accorder dans le groupe nominal (genre et nombre, pluriels en -x) et le verbe avec son sujet.',
  attenduId: 'ce2-ortho-accords',
  summary:
    "Le verbe s'accorde toujours avec son sujet, même si le sujet est loin ou placé après le verbe. Pour trouver le sujet, demande « qui est-ce qui ? » devant le verbe. Avec nous, le verbe finit par -ons ; avec vous, il finit par -ez.",
  minutes: 7,
  exercises: [
    {
      id: 'ce2-francais-accord-verbe-tap-1',
      kind: 'tapword',
      prompt: 'Touche le nom qui commande le verbe « jouent »',
      words: ['Les', 'enfants', 'de', 'la', 'classe', 'jouent', 'dans', 'la', 'cour.'],
      answer: [1],
      explain: 'Qui est-ce qui joue ? Les enfants. Pas « la classe », même si ce mot est juste avant le verbe.',
    },
    {
      id: 'ce2-francais-accord-verbe-choice-1',
      kind: 'choice',
      prompt: 'Le chien des voisins ... toute la nuit.',
      options: ['aboient', 'aboie'],
      answer: 1,
      explain: 'Qui est-ce qui aboie ? Le chien, un seul. Attention à « voisins » qui est juste avant.',
    },
    {
      id: 'ce2-francais-accord-verbe-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a fait une faute, corrige-le',
      words: ['Les', 'amis', 'de', 'Tom', 'arrive', 'ce', 'soir.'],
      wrongIndex: 4,
      correct: 'arrivent',
      distractors: ['arrivez', 'arrives'],
      explain: 'Qui est-ce qui arrive ? Les amis, plusieurs : le verbe prend -ent.',
    },
    {
      id: 'ce2-francais-accord-verbe-choice-2',
      kind: 'choice',
      prompt: 'Dans le ciel ... des oiseaux.',
      options: ['vole', 'volent'],
      answer: 1,
      explain: 'Qui est-ce qui vole ? Des oiseaux. Le sujet est après le verbe, mais il commande quand même.',
    },
    {
      id: 'ce2-francais-accord-verbe-tap-2',
      kind: 'tapword',
      prompt: 'Touche le nom qui est le sujet du verbe « poussent »',
      words: ['Dans', 'le', 'jardin', 'poussent', 'des', 'tomates.'],
      answer: [5],
      explain: 'Qui est-ce qui pousse ? Les tomates, même si elles sont après le verbe.',
    },
    {
      id: 'ce2-francais-accord-verbe-blanks-1',
      kind: 'blanks',
      prompt: 'Complète les verbes',
      text: 'Nous {{chantons}} et vous {{dansez}}.',
      distractors: ['chantez', 'dansons'],
      explain: 'Avec nous, le verbe finit par -ons ; avec vous, par -ez.',
    },
    {
      id: 'ce2-francais-accord-verbe-fix-2',
      kind: 'fix',
      prompt: 'Gribouille a fait une faute, corrige-le',
      words: ['Vous', 'mangeons', 'à', 'la', 'cantine.'],
      wrongIndex: 1,
      correct: 'mangez',
      distractors: ['mangent', 'mange'],
      explain: 'Avec vous, le verbe finit par -ez : vous mangez.',
    },
    {
      id: 'ce2-francais-accord-verbe-sort-1',
      kind: 'sort',
      prompt: 'Range chaque verbe avec son sujet',
      boxes: ['nous', 'vous', 'ils'],
      items: [
        { word: 'finissons', box: 0 },
        { word: 'finissez', box: 1 },
        { word: 'finissent', box: 2 },
        { word: 'partons', box: 0 },
        { word: 'partez', box: 1 },
        { word: 'partent', box: 2 },
      ],
      explain: '-ons va avec nous, -ez avec vous, -ent avec ils.',
    },
    {
      id: 'ce2-francais-accord-verbe-tf-1',
      kind: 'truefalse',
      statement: 'Dans « Les fleurs du jardin sentent bon », le sujet est « les fleurs ».',
      answer: true,
      explain: 'Oui : qui est-ce qui sent bon ? Les fleurs. « Du jardin » dit seulement où elles sont.',
    },
    {
      id: 'ce2-francais-accord-verbe-dict-1',
      kind: 'dictation',
      word: 'chantons',
      sentence: 'Nous chantons tous ensemble.',
      explain: 'Chan-tons : avec nous, le verbe finit par o-n-s.',
    },
  ],
};

const LETTRES_MUETTES: Lesson = {
  id: 'ce2-francais-lettres-muettes',
  title: 'Lettres muettes, m devant b et p, c et g',
  subject: 'francais',
  source: 'lecon',
  level: 'CE2',
  notion: 'Écrire la lettre finale muette, le m devant m, b, p, et les valeurs des lettres c et g',
  theme: 'orthographe',
  attendu: 'Écrire les lettres muettes, le m devant m, b, p, et les valeurs des lettres c, g, s.',
  attenduId: 'ce2-ortho-lettres',
  summary:
    "Pour trouver la lettre muette à la fin d'un mot, cherche le féminin : grand, grande. Devant m, b et p, on écrit m au lieu de n : chambre, tomber, pompier. Le c se lit « s » devant e, i, y ; devant a, o, u il faut une cédille pour le son « s » : garçon. Le g se lit « j » devant e et i ; on ajoute un u pour garder le son « g » (guitare) et un e pour le son « j » devant a et o (pigeon).",
  minutes: 7,
  exercises: [
    {
      id: 'ce2-francais-lettres-muettes-choice-1',
      kind: 'choice',
      prompt: 'Quelle lettre muette finit le mot « gran... » ?',
      options: ['t', 'd', 's'],
      answer: 1,
      explain: 'Pense au féminin : grande. On entend le d, donc grand finit par un d.',
    },
    {
      id: 'ce2-francais-lettres-muettes-pairs-1',
      kind: 'pairs',
      prompt: 'Associe chaque mot à son féminin',
      pairs: [
        { a: 'grand', b: 'grande' },
        { a: 'petit', b: 'petite' },
        { a: 'gros', b: 'grosse' },
        { a: 'blanc', b: 'blanche' },
        { a: 'long', b: 'longue' },
      ],
      explain: 'Le féminin fait entendre la lettre muette : grande, petite, grosse, blanche, longue.',
    },
    {
      id: 'ce2-francais-lettres-muettes-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a fait une faute, corrige-le',
      words: ['La', 'chanbre', 'de', 'Léa', 'est', 'rangée.'],
      wrongIndex: 1,
      correct: 'chambre',
      distractors: ['chambe', 'chanmbre'],
      explain: 'Devant un b, on écrit m et pas n : chambre.',
    },
    {
      id: 'ce2-francais-lettres-muettes-tf-1',
      kind: 'truefalse',
      statement: 'Devant un b, on écrit m et pas n, comme dans « tomber ».',
      answer: true,
      explain: 'C\'est la règle du m devant m, b, p : tomber, chambre, pompier.',
    },
    {
      id: 'ce2-francais-lettres-muettes-dict-1',
      kind: 'dictation',
      word: 'pompier',
      sentence: 'Le pompier éteint le feu.',
      explain: 'Pom-pier : devant le p, le son « on » s\'écrit o-m.',
    },
    {
      id: 'ce2-francais-lettres-muettes-sort-1',
      kind: 'sort',
      prompt: 'Comment se lit le c ?',
      boxes: ['c se lit « k »', 'c se lit « s »'],
      items: [
        { word: 'cadeau', box: 0 },
        { word: 'cerise', box: 1 },
        { word: 'citron', box: 1 },
        { word: 'cochon', box: 0 },
        { word: 'cube', box: 0 },
        { word: 'cygne', box: 1 },
      ],
      explain: 'Devant a, o, u, le c se lit « k ». Devant e, i, y, il se lit « s ».',
    },
    {
      id: 'ce2-francais-lettres-muettes-fix-2',
      kind: 'fix',
      prompt: 'Gribouille a fait une faute, corrige-le',
      words: ['Le', 'garcon', 'joue', 'au', 'ballon.'],
      wrongIndex: 1,
      correct: 'garçon',
      distractors: ['garson', 'garsson'],
      explain: 'Devant un o, il faut une cédille pour que le c se lise « s » : garçon.',
    },
    {
      id: 'ce2-francais-lettres-muettes-blanks-1',
      kind: 'blanks',
      prompt: 'Complète avec les mots bien écrits',
      text: 'Lina joue de la {{guitare}} et nourrit un {{pigeon}}.',
      distractors: ['gitare', 'pigon'],
      explain: 'Guitare : le u garde le son « g » devant le i. Pigeon : le e donne le son « j » devant le o.',
    },
    {
      id: 'ce2-francais-lettres-muettes-scramble-1',
      kind: 'scramble',
      word: 'chambre',
      explain: 'Cham-bre : c-h au début, puis m devant le b.',
    },
    {
      id: 'ce2-francais-lettres-muettes-choice-2',
      kind: 'choice',
      prompt: 'Dans quel mot le g se lit « j » ?',
      options: ['gare', 'girafe', 'gomme'],
      answer: 1,
      explain: 'Devant un i, le g se lit « j » : girafe. Devant a et o, il se lit « g » : gare, gomme.',
    },
  ],
};

const TYPES_PHRASES: Lesson = {
  id: 'ce2-francais-types-phrases',
  title: 'Les types et formes de phrases',
  subject: 'francais',
  source: 'grammaire',
  level: 'CE2',
  notion: 'Reconnaître les phrases déclarative, interrogative, exclamative, impérative et la forme négative',
  theme: 'grammaire',
  attendu: 'Reconnaître les types et formes de phrases, la ponctuation, et le groupe nominal.',
  attenduId: 'ce2-gram-phrase',
  summary:
    "Une phrase déclarative raconte et finit par un point. Une phrase interrogative pose une question et finit par un point d'interrogation. Une phrase exclamative montre une émotion forte, avec un point d'exclamation. Une phrase impérative donne un ordre ou un conseil. Une phrase est à la forme négative quand elle contient ne... pas, ne... plus ou ne... jamais.",
  minutes: 7,
  exercises: [
    {
      id: 'ce2-francais-types-phrases-sort-1',
      kind: 'sort',
      prompt: 'Range chaque phrase selon son type',
      boxes: ['Déclarative', 'Interrogative', 'Exclamative', 'Impérative'],
      items: [
        { word: 'Le chat dort sur le canapé.', box: 0 },
        { word: 'Où est ma trousse ?', box: 1 },
        { word: 'Quel beau dessin !', box: 2 },
        { word: 'Ferme la porte.', box: 3 },
        { word: 'Tu viens à la fête ?', box: 1 },
        { word: 'Il pleut depuis ce matin.', box: 0 },
        { word: 'Range ta chambre.', box: 3 },
        { word: 'Comme il fait froid !', box: 2 },
      ],
      explain: 'Un point pour raconter, un point d\'interrogation pour demander, un point d\'exclamation pour s\'exclamer, un ordre pour l\'impérative.',
    },
    {
      id: 'ce2-francais-types-phrases-choice-1',
      kind: 'choice',
      prompt: 'Quel signe termine une phrase interrogative ?',
      options: ['Le point', "Le point d'interrogation", "Le point d'exclamation"],
      answer: 1,
      explain: 'Une phrase interrogative pose une question : elle finit par un point d\'interrogation.',
    },
    {
      id: 'ce2-francais-types-phrases-sentence-1',
      kind: 'sentence',
      prompt: "Remets les mots de la question dans l'ordre",
      words: ['Est-ce', 'que', 'tu', 'as', 'fini', 'tes', 'devoirs ?'],
      explain: 'Une question commence souvent par « Est-ce que » et finit par le point d\'interrogation.',
    },
    {
      id: 'ce2-francais-types-phrases-tf-1',
      kind: 'truefalse',
      statement: '« Ne cours pas dans le couloir. » est une phrase à la forme négative.',
      answer: true,
      explain: 'Oui : elle contient « ne... pas ». C\'est aussi une phrase impérative, un ordre.',
    },
    {
      id: 'ce2-francais-types-phrases-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a fait une faute, corrige-le',
      words: ['Tom', 'ne', 'aime', 'pas', 'les', 'épinards.'],
      wrongIndex: 1,
      correct: "n'",
      distractors: ['ne pas', 'non'],
      explain: "Devant une voyelle, « ne » devient « n' » avec une apostrophe : Tom n'aime pas.",
    },
    {
      id: 'ce2-francais-types-phrases-sort-2',
      kind: 'sort',
      prompt: 'Range : forme affirmative ou forme négative ?',
      boxes: ['Forme affirmative', 'Forme négative'],
      items: [
        { word: 'Je mange une pomme.', box: 0 },
        { word: 'Je ne mange plus de pain.', box: 1 },
        { word: "Il n'est jamais en retard.", box: 1 },
        { word: 'Elle chante bien.', box: 0 },
        { word: "Nous n'avons pas fini.", box: 1 },
        { word: 'Vous jouez dehors.', box: 0 },
      ],
      explain: 'La forme négative contient ne... plus, ne... jamais ou ne... pas.',
    },
    {
      id: 'ce2-francais-types-phrases-sentence-2',
      kind: 'sentence',
      prompt: "Remets les mots de la phrase négative dans l'ordre",
      words: ['Léa', 'ne', 'veut', 'plus', 'jouer', 'dehors.'],
      explain: '« Ne » se place avant le verbe, et « plus » juste après : Léa ne veut plus jouer.',
    },
    {
      id: 'ce2-francais-types-phrases-choice-2',
      kind: 'choice',
      prompt: 'Transforme « Il pleut. » en phrase interrogative.',
      options: ['Il pleut !', "Est-ce qu'il pleut ?", 'Il ne pleut pas.'],
      answer: 1,
      explain: 'Pour poser la question, on ajoute « Est-ce que » et un point d\'interrogation.',
    },
    {
      id: 'ce2-francais-types-phrases-tap-1',
      kind: 'tapword',
      prompt: 'Touche les deux mots de la négation',
      words: ['Nous', 'ne', 'sortons', 'jamais', 'sans', 'manteau.'],
      answer: [1, 3],
      explain: 'La négation est en deux morceaux autour du verbe : « ne » et « jamais ».',
    },
    {
      id: 'ce2-francais-types-phrases-tf-2',
      kind: 'truefalse',
      statement: '« Comme ce gâteau est bon ! » est une phrase impérative.',
      answer: false,
      explain: 'Pas grave. Cette phrase ne donne pas d\'ordre, elle exprime une émotion : elle est exclamative.',
    },
  ],
};

const SUJET_VERBE_COMPLEMENT: Lesson = {
  id: 'ce2-francais-sujet-verbe-complement',
  title: 'Sujet, verbe, complément',
  subject: 'francais',
  source: 'grammaire',
  level: 'CE2',
  notion: 'Identifier le sujet, le verbe et le complément dans une phrase',
  theme: 'grammaire',
  attendu: "Identifier le sujet, le verbe et les compléments ; reconnaître le nom, le déterminant, l'adjectif, le pronom.",
  attenduId: 'ce2-gram-fonctions',
  summary:
    "Dans une phrase, le verbe dit ce qu'on fait. Le sujet, c'est qui fait l'action : on le trouve en demandant « qui est-ce qui ? ». Le complément complète le verbe : il dit quoi, où ou quand. Dans « Il mange une pomme », « une pomme » est le complément.",
  minutes: 7,
  exercises: [
    {
      id: 'ce2-francais-sujet-verbe-complement-tap-1',
      kind: 'tapword',
      prompt: 'Touche le verbe',
      words: ['Le', 'chat', 'attrape', 'une', 'souris.'],
      answer: [2],
      explain: 'Le verbe dit ce que fait le chat : il attrape.',
    },
    {
      id: 'ce2-francais-sujet-verbe-complement-tap-2',
      kind: 'tapword',
      prompt: 'Touche les mots du sujet',
      words: ['Ma', 'sœur', 'lit', 'un', 'livre.'],
      answer: [0, 1],
      explain: 'Qui est-ce qui lit ? Ma sœur. Le sujet, c\'est « ma sœur ».',
    },
    {
      id: 'ce2-francais-sujet-verbe-complement-tap-3',
      kind: 'tapword',
      prompt: 'Touche les mots du complément',
      words: ['Il', 'mange', 'une', 'pomme.'],
      answer: [2, 3],
      explain: 'Il mange quoi ? Une pomme. Le complément complète le verbe.',
    },
    {
      id: 'ce2-francais-sujet-verbe-complement-choice-1',
      kind: 'choice',
      prompt: 'Dans « Les enfants construisent une cabane », quel est le complément ?',
      options: ['Les enfants', 'construisent', 'une cabane'],
      answer: 2,
      explain: 'Ils construisent quoi ? Une cabane. « Les enfants » est le sujet, « construisent » le verbe.',
    },
    {
      id: 'ce2-francais-sujet-verbe-complement-sort-1',
      kind: 'sort',
      prompt: 'Range chaque morceau de phrase dans la bonne boîte',
      boxes: ['Sujet', 'Verbe', 'Complément'],
      items: [
        { word: 'Papa', box: 0 },
        { word: 'prépare', box: 1 },
        { word: 'le dîner', box: 2 },
        { word: 'Les oiseaux', box: 0 },
        { word: 'picorent', box: 1 },
        { word: 'des graines', box: 2 },
      ],
      explain: 'Papa prépare le dîner ; les oiseaux picorent des graines. Sujet, verbe, complément.',
    },
    {
      id: 'ce2-francais-sujet-verbe-complement-tf-1',
      kind: 'truefalse',
      statement: 'Dans « Lina dessine un cheval », le sujet est « un cheval ».',
      answer: false,
      explain: 'Pas grave. Qui est-ce qui dessine ? Lina. « Un cheval », c\'est le complément.',
    },
    {
      id: 'ce2-francais-sujet-verbe-complement-tap-4',
      kind: 'tapword',
      prompt: 'Touche les mots du complément qui dit où',
      words: ['Les', 'enfants', 'jouent', 'dans', 'le', 'jardin.'],
      answer: [3, 4, 5],
      explain: 'Ils jouent où ? Dans le jardin. Ce complément donne le lieu.',
    },
    {
      id: 'ce2-francais-sujet-verbe-complement-sentence-1',
      kind: 'sentence',
      prompt: "Remets les mots dans l'ordre : sujet, verbe, complément",
      words: ['Mon', 'frère', 'range', 'ses', 'jouets.'],
      explain: 'Mon frère, c\'est le sujet ; range, le verbe ; ses jouets, le complément.',
    },
    {
      id: 'ce2-francais-sujet-verbe-complement-choice-2',
      kind: 'choice',
      prompt: 'Comment trouve-t-on le sujet du verbe ?',
      options: ['On demande « qui est-ce qui ? » devant le verbe', 'On prend le dernier mot de la phrase', 'On cherche le mot le plus long'],
      answer: 0,
      explain: 'La question « qui est-ce qui ? » donne toujours le sujet.',
    },
    {
      id: 'ce2-francais-sujet-verbe-complement-pairs-1',
      kind: 'pairs',
      prompt: 'Associe chaque question à ce qu\'elle permet de trouver',
      pairs: [
        { a: 'Qui est-ce qui ?', b: 'le sujet' },
        { a: 'Que fait-on ?', b: 'le verbe' },
        { a: 'Quoi ? Où ? Quand ?', b: 'le complément' },
      ],
      explain: '« Qui est-ce qui ? » donne le sujet, « que fait-on ? » le verbe, « quoi, où, quand » le complément.',
    },
  ],
};

const GROUPE_NOMINAL: Lesson = {
  id: 'ce2-francais-groupe-nominal',
  title: 'Le groupe nominal',
  subject: 'francais',
  source: 'grammaire',
  level: 'CE2',
  notion: 'Reconnaître le nom, le déterminant, l\'adjectif et le pronom',
  theme: 'grammaire',
  attendu: "Identifier le sujet, le verbe et les compléments ; reconnaître le nom, le déterminant, l'adjectif, le pronom.",
  attenduId: 'ce2-gram-fonctions',
  summary:
    "Le groupe nominal, c'est un nom avec son déterminant, et parfois un adjectif : « le petit chat ». Le déterminant est devant le nom : le, la, les, un, une, des, mon, ta... L'adjectif dit comment est le nom. Le pronom remplace le groupe nominal : « Le petit chat dort » devient « Il dort ».",
  minutes: 7,
  exercises: [
    {
      id: 'ce2-francais-groupe-nominal-tap-1',
      kind: 'tapword',
      prompt: 'Touche le nom',
      words: ['une', 'grande', 'maison'],
      answer: [2],
      explain: 'Le nom, c\'est la chose dont on parle : maison. « Une » est le déterminant, « grande » l\'adjectif.',
    },
    {
      id: 'ce2-francais-groupe-nominal-tap-2',
      kind: 'tapword',
      prompt: 'Touche le déterminant',
      words: ['les', 'jolies', 'fleurs'],
      answer: [0],
      explain: 'Le déterminant est le petit mot devant le nom : les.',
    },
    {
      id: 'ce2-francais-groupe-nominal-tap-3',
      kind: 'tapword',
      prompt: "Touche l'adjectif",
      words: ['Mon', 'vieux', 'vélo', 'est', 'cassé.'],
      answer: [1],
      explain: '« Vieux » dit comment est le vélo : c\'est l\'adjectif.',
    },
    {
      id: 'ce2-francais-groupe-nominal-sort-1',
      kind: 'sort',
      prompt: 'Range chaque mot dans la bonne boîte',
      boxes: ['Nom', 'Déterminant', 'Adjectif', 'Pronom'],
      items: [
        { word: 'table', box: 0 },
        { word: 'des', box: 1 },
        { word: 'rouge', box: 2 },
        { word: 'elle', box: 3 },
        { word: 'chien', box: 0 },
        { word: 'ma', box: 1 },
        { word: 'gentil', box: 2 },
        { word: 'nous', box: 3 },
      ],
      explain: 'Table et chien sont des noms ; des et ma vont devant un nom ; rouge et gentil disent comment ; elle et nous remplacent.',
    },
    {
      id: 'ce2-francais-groupe-nominal-pairs-1',
      kind: 'pairs',
      prompt: 'Associe chaque groupe nominal au pronom qui le remplace',
      pairs: [
        { a: 'le garçon', b: 'il' },
        { a: 'la fille', b: 'elle' },
        { a: 'les enfants', b: 'ils' },
        { a: 'les filles', b: 'elles' },
      ],
      explain: 'Il pour un garçon, elle pour une fille, ils pour plusieurs, elles pour plusieurs filles.',
    },
    {
      id: 'ce2-francais-groupe-nominal-choice-1',
      kind: 'choice',
      prompt: 'Quel pronom remplace « Ma grand-mère » dans « Ma grand-mère tricote » ?',
      options: ['Il', 'Elle', 'Elles'],
      answer: 1,
      explain: 'Ma grand-mère est une seule personne, au féminin : elle tricote.',
    },
    {
      id: 'ce2-francais-groupe-nominal-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a fait une faute, corrige-le',
      words: ['Le', 'petite', 'chat', 'dort.'],
      wrongIndex: 1,
      correct: 'petit',
      distractors: ['petits', 'petites'],
      explain: '« Chat » est au masculin singulier : l\'adjectif s\'écrit petit, sans e.',
    },
    {
      id: 'ce2-francais-groupe-nominal-tf-1',
      kind: 'truefalse',
      statement: 'Dans « un gros ballon », « gros » est un adjectif.',
      answer: true,
      explain: 'Oui : « gros » dit comment est le ballon, c\'est un adjectif.',
    },
    {
      id: 'ce2-francais-groupe-nominal-tap-4',
      kind: 'tapword',
      prompt: 'Touche les trois mots du groupe nominal sujet',
      words: ['Les', 'grands', 'arbres', 'perdent', 'leurs', 'feuilles.'],
      answer: [0, 1, 2],
      explain: '« Les grands arbres » : déterminant, adjectif, nom. C\'est le groupe nominal qui fait l\'action.',
    },
    {
      id: 'ce2-francais-groupe-nominal-choice-2',
      kind: 'choice',
      prompt: 'Lequel est un groupe nominal ?',
      options: ['il court', 'une belle histoire', 'très vite'],
      answer: 1,
      explain: '« Une belle histoire » a un déterminant, un adjectif et un nom : c\'est un groupe nominal.',
    },
  ],
};

const PRESENT_IR: Lesson = {
  id: 'ce2-francais-present-ir',
  title: 'Le présent : finir, pouvoir, vouloir, prendre...',
  subject: 'francais',
  source: 'lecon',
  level: 'CE2',
  notion: 'Conjuguer au présent les verbes en -ir comme finir, et pouvoir, vouloir, prendre, faire, dire, venir',
  theme: 'conjugaison',
  attendu: 'Conjuguer au présent les verbes en -er, -ir (finir), être, avoir, aller, faire, dire, venir, pouvoir, vouloir, prendre.',
  attenduId: 'ce2-conj-present',
  summary:
    "Les verbes comme finir se conjuguent au présent : je finis, tu finis, il finit, nous finissons, vous finissez, ils finissent. Pouvoir et vouloir prennent un x : je peux, tu veux. Prendre : je prends, nous prenons, ils prennent. Faire : nous faisons, vous faites, ils font. Dire : vous dites. Venir : je viens, nous venons, ils viennent.",
  minutes: 7,
  exercises: [
    {
      id: 'ce2-francais-present-ir-choice-1',
      kind: 'choice',
      prompt: 'Nous ... nos devoirs.',
      options: ['finissons', 'finisons', 'finissent'],
      answer: 0,
      explain: 'Avec nous, finir devient finissons : deux s et -ons.',
    },
    {
      id: 'ce2-francais-present-ir-match-1',
      kind: 'match',
      prompt: 'Relie chaque pronom à sa forme du verbe choisir',
      pairs: [
        { a: 'je', b: 'choisis' },
        { a: 'il', b: 'choisit' },
        { a: 'nous', b: 'choisissons' },
        { a: 'vous', b: 'choisissez' },
        { a: 'ils', b: 'choisissent' },
      ],
      seconds: 40,
      explain: 'Choisir se conjugue comme finir : -is, -it, -issons, -issez, -issent.',
    },
    {
      id: 'ce2-francais-present-ir-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a fait une faute, corrige-le',
      words: ['Tu', 'peut', 'venir', 'avec', 'moi.'],
      wrongIndex: 1,
      correct: 'peux',
      distractors: ['peus', 'peuts'],
      explain: 'Avec tu, pouvoir finit par un x : tu peux.',
    },
    {
      id: 'ce2-francais-present-ir-blanks-1',
      kind: 'blanks',
      prompt: 'Complète les verbes',
      text: 'Je {{veux}} un gâteau et tu {{prends}} une pomme.',
      distractors: ['veut', 'prend'],
      explain: 'Je veux avec un x, tu prends avec un s.',
    },
    {
      id: 'ce2-francais-present-ir-choice-2',
      kind: 'choice',
      prompt: 'Vous ... la vérité.',
      options: ['disez', 'dites', 'dis'],
      answer: 1,
      explain: 'Dire est spécial avec vous : vous dites.',
    },
    {
      id: 'ce2-francais-present-ir-sort-1',
      kind: 'sort',
      prompt: 'Range : verbe faire ou verbe venir ?',
      boxes: ['Verbe faire', 'Verbe venir'],
      items: [
        { word: 'nous faisons', box: 0 },
        { word: 'ils viennent', box: 1 },
        { word: 'vous faites', box: 0 },
        { word: 'je viens', box: 1 },
        { word: 'ils font', box: 0 },
        { word: 'nous venons', box: 1 },
      ],
      explain: 'Faire : faisons, faites, font. Venir : viens, venons, viennent.',
    },
    {
      id: 'ce2-francais-present-ir-tf-1',
      kind: 'truefalse',
      statement: '« Ils prennent le bus » est bien conjugué.',
      answer: true,
      explain: 'Oui : avec ils, prendre devient prennent, avec deux n.',
    },
    {
      id: 'ce2-francais-present-ir-blanks-2',
      kind: 'blanks',
      prompt: 'Complète les verbes',
      text: 'Les élèves {{finissent}} leur dessin et {{font}} une pause.',
      distractors: ['finit', 'fait'],
      explain: 'Les élèves, c\'est ils : ils finissent, ils font.',
    },
    {
      id: 'ce2-francais-present-ir-fix-2',
      kind: 'fix',
      prompt: 'Gribouille a fait une faute, corrige-le',
      words: ['Vous', 'faisez', 'un', 'gâteau.'],
      wrongIndex: 1,
      correct: 'faites',
      distractors: ['faisons', 'font'],
      explain: 'Faire est spécial avec vous : vous faites, et pas « faisez ».',
    },
    {
      id: 'ce2-francais-present-ir-dict-1',
      kind: 'dictation',
      word: 'viennent',
      sentence: 'Mes cousins viennent dimanche.',
      explain: 'Vien-nent : deux n au milieu, et -ent à la fin pour ils.',
    },
  ],
};

const PASSE_COMPOSE: Lesson = {
  id: 'ce2-francais-passe-compose',
  title: 'Le passé composé',
  subject: 'francais',
  source: 'lecon',
  level: 'CE2',
  notion: 'Conjuguer au passé composé avec avoir et être, participes passés en -é, -i, -u',
  theme: 'conjugaison',
  attendu: "Conjuguer à l'imparfait, au futur et au passé composé les verbes fréquents.",
  attenduId: 'ce2-conj-passe',
  summary:
    "Le passé composé raconte ce qui est déjà passé. Il se forme avec avoir ou être au présent, puis le participe passé : j'ai mangé, il est parti. Le participe passé finit par -é pour les verbes en -er (chanté), -i pour les verbes comme finir (fini), -u pour beaucoup d'autres (vu, lu, venu). Avec être, le participe s'accorde : elle est partie.",
  minutes: 7,
  exercises: [
    {
      id: 'ce2-francais-passe-compose-choice-1',
      kind: 'choice',
      prompt: "Hier, j'... mangé une glace.",
      options: ['ai', 'est', 'a'],
      answer: 0,
      explain: 'Avec je, on utilise avoir au présent : j\'ai mangé.',
    },
    {
      id: 'ce2-francais-passe-compose-sort-1',
      kind: 'sort',
      prompt: 'Range chaque participe passé selon sa fin',
      boxes: ['Fin en -é', 'Fin en -i', 'Fin en -u'],
      items: [
        { word: 'chanté', box: 0 },
        { word: 'fini', box: 1 },
        { word: 'vu', box: 2 },
        { word: 'joué', box: 0 },
        { word: 'choisi', box: 1 },
        { word: 'lu', box: 2 },
        { word: 'venu', box: 2 },
        { word: 'parlé', box: 0 },
      ],
      explain: 'Les verbes en -er donnent -é, ceux comme finir donnent -i, et vu, lu, venu finissent par -u.',
    },
    {
      id: 'ce2-francais-passe-compose-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a fait une faute, corrige-le',
      words: ['Nous', 'avons', 'manger', 'des', 'crêpes.'],
      wrongIndex: 2,
      correct: 'mangé',
      distractors: ['mangez', 'mangés'],
      explain: 'Après avoir, on écrit le participe passé : mangé avec un é. Astuce : on peut dire « nous avons pris ».',
    },
    {
      id: 'ce2-francais-passe-compose-blanks-1',
      kind: 'blanks',
      prompt: 'Complète avec est ou a',
      text: 'Lina {{est}} partie tôt et elle {{a}} pris son sac.',
      distractors: ['ai', 'sont'],
      explain: 'Partir se conjugue avec être : elle est partie. Prendre avec avoir : elle a pris.',
    },
    {
      id: 'ce2-francais-passe-compose-tf-1',
      kind: 'truefalse',
      statement: '« Il a fini ses devoirs » est au passé composé.',
      answer: true,
      explain: 'Oui : avoir au présent, puis le participe passé « fini ». C\'est déjà passé.',
    },
    {
      id: 'ce2-francais-passe-compose-match-1',
      kind: 'match',
      prompt: 'Relie chaque verbe à son participe passé',
      pairs: [
        { a: 'manger', b: 'mangé' },
        { a: 'finir', b: 'fini' },
        { a: 'voir', b: 'vu' },
        { a: 'prendre', b: 'pris' },
        { a: 'faire', b: 'fait' },
      ],
      seconds: 40,
      explain: 'Mangé, fini, vu, et deux participes spéciaux : pris et fait.',
    },
    {
      id: 'ce2-francais-passe-compose-choice-2',
      kind: 'choice',
      prompt: "Les enfants ... arrivés à l'heure.",
      options: ['ont', 'sont', 'est'],
      answer: 1,
      explain: 'Arriver se conjugue avec être : ils sont arrivés, avec un s au participe.',
    },
    {
      id: 'ce2-francais-passe-compose-sentence-1',
      kind: 'sentence',
      prompt: "Remets les mots de la phrase dans l'ordre",
      words: ['Ce', 'matin,', 'nous', 'avons', 'lu', 'une', 'histoire.'],
      explain: 'Au passé composé, avoir vient avant le participe : nous avons lu.',
    },
    {
      id: 'ce2-francais-passe-compose-fix-2',
      kind: 'fix',
      prompt: 'Gribouille a oublié un accord, corrige-le',
      words: ['Elle', 'est', 'parti', 'à', 'la', 'gare.'],
      wrongIndex: 2,
      correct: 'partie',
      distractors: ['partis', 'parties'],
      explain: 'Avec être, le participe s\'accorde avec le sujet : elle est partie, avec un e.',
    },
    {
      id: 'ce2-francais-passe-compose-dict-1',
      kind: 'dictation',
      word: 'fini',
      sentence: 'Tom a fini son dessin.',
      explain: 'Fini : le participe passé de finir finit par un i, sans s.',
    },
  ],
};

const IMPARFAIT_FUTUR: Lesson = {
  id: 'ce2-francais-imparfait-futur',
  title: "L'imparfait et le futur",
  subject: 'francais',
  source: 'lecon',
  level: 'CE2',
  notion: "Conjuguer à l'imparfait et au futur les verbes en -er, -ir, être, avoir, aller, faire",
  theme: 'conjugaison',
  attendu: "Conjuguer à l'imparfait, au futur et au passé composé les verbes fréquents.",
  attenduId: 'ce2-conj-passe',
  summary:
    "L'imparfait raconte ce qui se passait avant, longtemps ou souvent : je chantais, nous finissions, il était, ils avaient, vous alliez, tu faisais. Ses terminaisons sont -ais, -ais, -ait, -ions, -iez, -aient. Le futur dit ce qui va arriver : je chanterai, tu finiras, il sera, nous aurons, vous irez, ils feront. Ses terminaisons sont -ai, -as, -a, -ons, -ez, -ont.",
  minutes: 7,
  exercises: [
    {
      id: 'ce2-francais-imparfait-futur-sort-1',
      kind: 'sort',
      prompt: 'Range : imparfait ou futur ?',
      boxes: ['Imparfait', 'Futur'],
      items: [
        { word: 'je jouais', box: 0 },
        { word: 'je jouerai', box: 1 },
        { word: 'il était', box: 0 },
        { word: 'il sera', box: 1 },
        { word: 'nous ferons', box: 1 },
        { word: 'vous aviez', box: 0 },
        { word: 'ils iront', box: 1 },
        { word: 'tu finissais', box: 0 },
      ],
      explain: 'L\'imparfait finit par -ais, -ait, -iez... Le futur par -ai, -a, -ons, -ont.',
    },
    {
      id: 'ce2-francais-imparfait-futur-choice-1',
      kind: 'choice',
      prompt: "Quand j'étais petit, je ... au parc tous les jours.",
      options: ['jouerai', 'jouais', 'joue'],
      answer: 1,
      explain: '« Quand j\'étais petit », c\'est avant : imparfait, je jouais.',
    },
    {
      id: 'ce2-francais-imparfait-futur-blanks-1',
      kind: 'blanks',
      prompt: 'Complète au futur',
      text: 'Demain, nous {{irons}} à la mer et il {{fera}} beau.',
      distractors: ['allions', 'faisait'],
      explain: '« Demain », c\'est le futur : nous irons, il fera.',
    },
    {
      id: 'ce2-francais-imparfait-futur-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a fait une faute, corrige-le',
      words: ['Avant,', 'les', 'enfants', 'avait', 'un', 'chien.'],
      wrongIndex: 3,
      correct: 'avaient',
      distractors: ['avais', 'auront'],
      explain: 'Les enfants, c\'est ils : à l\'imparfait, ils avaient, avec -aient.',
    },
    {
      id: 'ce2-francais-imparfait-futur-choice-2',
      kind: 'choice',
      prompt: "L'année prochaine, tu ... en CM1.",
      options: ['seras', 'étais', 'sera'],
      answer: 0,
      explain: '« L\'année prochaine », c\'est le futur : tu seras, avec un s pour tu.',
    },
    {
      id: 'ce2-francais-imparfait-futur-blanks-2',
      kind: 'blanks',
      prompt: "Complète à l'imparfait",
      text: 'Hier, il {{pleuvait}}, alors nous {{restions}} à la maison.',
      distractors: ['pleuvra', 'resterons'],
      explain: '« Hier », c\'est avant : il pleuvait, nous restions.',
    },
    {
      id: 'ce2-francais-imparfait-futur-tf-1',
      kind: 'truefalse',
      statement: "« Nous finirons » est à l'imparfait.",
      answer: false,
      explain: 'Pas grave. « Finirons » finit par -rons : c\'est le futur. À l\'imparfait, ce serait « nous finissions ».',
    },
    {
      id: 'ce2-francais-imparfait-futur-pairs-1',
      kind: 'pairs',
      prompt: 'Associe chaque pronom au verbe aller au futur',
      pairs: [
        { a: 'je', b: 'irai' },
        { a: 'tu', b: 'iras' },
        { a: 'il', b: 'ira' },
        { a: 'nous', b: 'irons' },
        { a: 'vous', b: 'irez' },
      ],
      explain: 'Au futur, aller devient ir- : irai, iras, ira, irons, irez, iront.',
    },
    {
      id: 'ce2-francais-imparfait-futur-fix-2',
      kind: 'fix',
      prompt: 'Gribouille a fait une faute, corrige-le',
      words: ['Demain,', 'je', 'ferai', 'mes', 'devoirs', 'et', 'je', 'jouait', 'au', 'ballon.'],
      wrongIndex: 7,
      correct: 'jouerai',
      distractors: ['jouais', 'jouera'],
      explain: 'Toute la phrase est au futur, avec « demain » : je ferai, je jouerai.',
    },
    {
      id: 'ce2-francais-imparfait-futur-dict-1',
      kind: 'dictation',
      word: 'étaient',
      sentence: 'Les élèves étaient en classe.',
      explain: 'É-taient : avec ils, l\'imparfait finit par a-i-e-n-t.',
    },
  ],
};

const PREFIXES_SUFFIXES: Lesson = {
  id: 'ce2-francais-prefixes-suffixes',
  title: 'Préfixes, suffixes, sens propre et figuré',
  subject: 'francais',
  source: 'lecon',
  level: 'CE2',
  notion: 'Comprendre les préfixes et suffixes, distinguer le sens propre et le sens figuré',
  theme: 'vocabulaire',
  attendu: 'Utiliser synonymes, contraires, familles de mots, préfixes et suffixes, sens propre et sens figuré.',
  attenduId: 'ce2-voc-sens',
  summary:
    "Un préfixe se place devant un mot pour changer son sens : re- veut dire « encore » (refaire), dé- veut dire « le contraire » (défaire), in- veut dire « pas » (inconnu). Un suffixe se place après : -ette rend plus petit (maisonnette), -eur dit celui qui fait (chanteur), -age fabrique un nom (lavage). Au sens propre, les mots disent vraiment ce qu'ils disent ; au sens figuré, c'est une image : « avoir un cœur d'or », c'est être très gentil.",
  minutes: 8,
  exercises: [
    {
      id: 'ce2-francais-prefixes-suffixes-pairs-1',
      kind: 'pairs',
      prompt: 'Associe chaque préfixe à son sens',
      pairs: [
        { a: 're-', b: 'encore' },
        { a: 'dé-', b: 'le contraire' },
        { a: 'in-', b: 'pas' },
        { a: 'pré-', b: 'avant' },
      ],
      explain: 'Refaire : faire encore. Défaire : le contraire de faire. Inconnu : pas connu. Préhistoire : avant l\'histoire.',
    },
    {
      id: 'ce2-francais-prefixes-suffixes-sort-1',
      kind: 'sort',
      prompt: 'Range chaque mot selon son préfixe',
      boxes: ['Préfixe re-', 'Préfixe dé-', 'Préfixe in-'],
      items: [
        { word: 'refaire', box: 0 },
        { word: 'défaire', box: 1 },
        { word: 'inconnu', box: 2 },
        { word: 'relire', box: 0 },
        { word: 'décoller', box: 1 },
        { word: 'invisible', box: 2 },
      ],
      explain: 'Re- pour recommencer, dé- pour le contraire, in- pour dire « pas ».',
    },
    {
      id: 'ce2-francais-prefixes-suffixes-choice-1',
      kind: 'choice',
      prompt: 'Que veut dire « relire » ?',
      options: ['Lire encore une fois', 'Ne pas lire', 'Lire très vite'],
      answer: 0,
      explain: 'Le préfixe re- veut dire « encore » : relire, c\'est lire une nouvelle fois.',
    },
    {
      id: 'ce2-francais-prefixes-suffixes-match-1',
      kind: 'match',
      prompt: 'Relie chaque mot au mot fabriqué avec un suffixe',
      pairs: [
        { a: 'chanter', b: 'chanteur' },
        { a: 'maison', b: 'maisonnette' },
        { a: 'laver', b: 'lavage' },
        { a: 'fille', b: 'fillette' },
        { a: 'jardin', b: 'jardinage' },
      ],
      seconds: 40,
      explain: '-eur dit celui qui fait, -ette rend plus petit, -age fabrique un nom.',
    },
    {
      id: 'ce2-francais-prefixes-suffixes-order-1',
      kind: 'order',
      prompt: "Remets dans l'ordre les étapes pour fabriquer le mot « décollage »",
      lines: ['Le mot de départ : coller', 'On ajoute le préfixe dé- : décoller', 'On ajoute le suffixe -age : décollage'],
      explain: 'On part de coller, le préfixe dé- donne décoller, et le suffixe -age donne décollage.',
    },
    {
      id: 'ce2-francais-prefixes-suffixes-sort-2',
      kind: 'sort',
      prompt: 'Range : sens propre ou sens figuré ?',
      boxes: ['Sens propre', 'Sens figuré'],
      items: [
        { word: "Il a un cœur d'or.", box: 1 },
        { word: 'Il mange une tartine.', box: 0 },
        { word: 'Elle est tombée dans les pommes.', box: 1 },
        { word: 'Le chat dort.', box: 0 },
        { word: 'Tom a la tête dans les nuages.', box: 1 },
        { word: 'La neige tombe.', box: 0 },
      ],
      explain: 'Un cœur d\'or, tomber dans les pommes, la tête dans les nuages : ce sont des images, pas des choses vraies.',
    },
    {
      id: 'ce2-francais-prefixes-suffixes-choice-2',
      kind: 'choice',
      prompt: "« Avoir un cœur d'or », ça veut dire...",
      options: ['Avoir un cœur en métal', 'Être très gentil', 'Être très riche'],
      answer: 1,
      explain: 'C\'est le sens figuré : un cœur d\'or, c\'est un cœur précieux, celui de quelqu\'un de très gentil.',
    },
    {
      id: 'ce2-francais-prefixes-suffixes-tf-1',
      kind: 'truefalse',
      statement: 'Dans « inconnu », le préfixe in- veut dire « pas connu ».',
      answer: true,
      explain: 'Oui : in- veut dire « pas ». Inconnu, invisible, incapable.',
    },
    {
      id: 'ce2-francais-prefixes-suffixes-blanks-1',
      kind: 'blanks',
      prompt: 'Complète avec les mots en -eur',
      text: 'Le {{chanteur}} chante, le {{coiffeur}} coiffe et le {{vendeur}} vend.',
      distractors: ['chantage', 'coiffette'],
      explain: 'Le suffixe -eur dit celui qui fait l\'action : chanteur, coiffeur, vendeur.',
    },
    {
      id: 'ce2-francais-prefixes-suffixes-tap-1',
      kind: 'tapword',
      prompt: 'Touche le mot qui a un préfixe',
      words: ['Léa', 'a', 'refait', 'son', 'lit', 'ce', 'matin.'],
      answer: [2],
      explain: '« Refait », c\'est re- devant fait : elle a fait son lit encore une fois.',
    },
  ],
};

const DICTIONNAIRE: Lesson = {
  id: 'ce2-francais-dictionnaire',
  title: 'Chercher dans le dictionnaire',
  subject: 'francais',
  source: 'lecon',
  level: 'CE2',
  notion: "Ranger des mots dans l'ordre alphabétique à la deuxième et troisième lettre, lire la nature d'un mot",
  theme: 'vocabulaire',
  attendu: 'Chercher un mot dans le dictionnaire et comprendre un article : nature, définitions, exemples.',
  attenduId: 'ce2-voc-dictionnaire',
  summary:
    "Dans le dictionnaire, les mots sont rangés dans l'ordre alphabétique. Si deux mots commencent par la même lettre, on regarde la deuxième lettre, puis la troisième. Un article de dictionnaire donne la nature du mot (n. pour nom, v. pour verbe, adj. pour adjectif), sa définition et un exemple.",
  minutes: 5,
  exercises: [
    {
      id: 'ce2-francais-dictionnaire-order-1',
      kind: 'order',
      prompt: 'Range ces mots dans l\'ordre du dictionnaire',
      lines: ['bague', 'balle', 'banc', 'bateau'],
      explain: 'Ils commencent tous par b-a : on regarde la troisième lettre, g, l, n, t.',
    },
    {
      id: 'ce2-francais-dictionnaire-choice-1',
      kind: 'choice',
      prompt: 'Quel mot vient en premier dans le dictionnaire ?',
      options: ['chien', 'chat', 'chou'],
      answer: 1,
      explain: 'Ils commencent par c-h : on regarde la troisième lettre. A vient avant i et o : chat.',
    },
    {
      id: 'ce2-francais-dictionnaire-order-2',
      kind: 'order',
      prompt: 'Range ces mots dans l\'ordre du dictionnaire',
      lines: ['pomme', 'porte', 'poule', 'poussin'],
      explain: 'Troisième lettre : m, r, u, u. Pour poule et poussin, on regarde la quatrième : l avant s.',
    },
    {
      id: 'ce2-francais-dictionnaire-pairs-1',
      kind: 'pairs',
      prompt: 'Associe chaque abréviation à la nature du mot',
      pairs: [
        { a: 'n.', b: 'nom' },
        { a: 'v.', b: 'verbe' },
        { a: 'adj.', b: 'adjectif' },
        { a: 'adv.', b: 'adverbe' },
      ],
      explain: 'Le dictionnaire raccourcit la nature du mot : n. pour nom, v. pour verbe, adj. pour adjectif, adv. pour adverbe.',
    },
    {
      id: 'ce2-francais-dictionnaire-tf-1',
      kind: 'truefalse',
      statement: 'Pour ranger « table » et « tapis », on regarde la troisième lettre.',
      answer: true,
      explain: 'Oui : les deux commencent par t-a, alors on compare b et p. Table vient avant tapis.',
    },
    {
      id: 'ce2-francais-dictionnaire-choice-2',
      kind: 'choice',
      prompt: 'Dans l\'article « courir : v. Se déplacer vite en faisant de grands pas. », que veut dire v. ?',
      options: ['verbe', 'vite', 'vrai'],
      answer: 0,
      explain: 'L\'abréviation v. signale que courir est un verbe.',
    },
    {
      id: 'ce2-francais-dictionnaire-sort-1',
      kind: 'sort',
      prompt: 'Range : avant ou après « maison » dans le dictionnaire ?',
      boxes: ['Avant « maison »', 'Après « maison »'],
      items: [
        { word: 'mairie', box: 0 },
        { word: 'malade', box: 1 },
        { word: 'magie', box: 0 },
        { word: 'matin', box: 1 },
        { word: 'main', box: 0 },
        { word: 'mars', box: 1 },
      ],
      explain: 'Magie, main et mairie viennent avant maison ; malade, mars et matin viennent après, car l, r et t sont après i.',
    },
  ],
};

export const LESSONS: Lesson[] = [
  LIRE_EXPRESSION,
  COMPRENDRE_RECIT,
  CIGALE_FOURMI,
  HOMOPHONES_A_ET,
  HOMOPHONES_ON_SON,
  MOTS_INVARIABLES,
  PLURIELS_X,
  ACCORD_VERBE,
  LETTRES_MUETTES,
  TYPES_PHRASES,
  SUJET_VERBE_COMPLEMENT,
  GROUPE_NOMINAL,
  PRESENT_IR,
  PASSE_COMPOSE,
  IMPARFAIT_FUTUR,
  PREFIXES_SUFFIXES,
  DICTIONNAIRE,
];
