import type { Lesson } from './types';

/**
 * Banque de français, CP. Quatorze leçons qui couvrent les attendus de fin
 * de CP : sons et syllabes, mots outils, lecture de phrases, petite histoire,
 * comptine, phrase, nom et verbe, je / tu / il, vocabulaire, alphabet.
 * Tous les textes sont originaux, y compris la comptine.
 */

const SYLLABES: Lesson = {
  id: 'cp-francais-syllabes-a-i-o',
  title: 'Les syllabes la, li, lo',
  subject: 'francais',
  source: 'lecture',
  level: 'CP',
  notion: 'Lire et écrire des syllabes simples avec a, i, o',
  theme: 'lecture',
  attendu: 'Connaître les correspondances entre les lettres et les sons, lire des syllabes et des mots simples.',
  attenduId: 'cp-lect-sons',
  summary:
    'Une lettre qui chante, comme a, i ou o, et une lettre qui l\'accompagne, comme l, m ou r, font une syllabe : la, mi, ro. Deux syllabes font un mot : la-ma, mo-to.',
  minutes: 6,
  exercises: [
    {
      id: 'cp-francais-syllabes-a-i-o-choice-1',
      kind: 'choice',
      prompt: 'Quelle syllabe entends-tu ?',
      speak: 'la',
      options: ['li', 'la', 'lo'],
      answer: 1,
      explain: 'On entend le son a à la fin : l et a, ça fait la.',
    },
    {
      id: 'cp-francais-syllabes-a-i-o-choice-2',
      kind: 'choice',
      prompt: 'Quelle syllabe entends-tu ?',
      speak: 'mo',
      options: ['mo', 'ma', 'mi'],
      answer: 0,
      explain: 'On entend le son o à la fin : m et o, ça fait mo.',
    },
    {
      id: 'cp-francais-syllabes-a-i-o-tf-1',
      kind: 'truefalse',
      statement: 'Dans « moto », on entend le son o.',
      answer: true,
      explain: 'Mo-to : on entend le son o deux fois.',
    },
    {
      id: 'cp-francais-syllabes-a-i-o-sort-1',
      kind: 'sort',
      prompt: 'Quel son entends-tu dans le mot ?',
      boxes: ['a', 'i', 'o'],
      items: [
        { word: 'sac', box: 0 },
        { word: 'riz', box: 1 },
        { word: 'pot', box: 2 },
        { word: 'mal', box: 0 },
        { word: 'lit', box: 1 },
        { word: 'bol', box: 2 },
      ],
      explain: 'Pas grave. Dis le mot tout doucement et écoute la lettre qui chante : a, i ou o.',
    },
    {
      id: 'cp-francais-syllabes-a-i-o-flash-1',
      kind: 'flash',
      word: 'lama',
      distractors: ['lima', 'loma'],
      explain: 'La-ma : deux fois le son a.',
    },
    {
      id: 'cp-francais-syllabes-a-i-o-flash-2',
      kind: 'flash',
      word: 'moto',
      distractors: ['mato', 'mito'],
      explain: 'Mo-to : deux fois le son o.',
    },
    {
      id: 'cp-francais-syllabes-a-i-o-tap-1',
      kind: 'tapword',
      prompt: 'Touche le mot où tu entends le son i',
      words: ['Mila', 'a', 'une', 'moto.'],
      answer: [0],
      explain: 'Mi-la : on entend le son i dans la première syllabe.',
    },
    {
      id: 'cp-francais-syllabes-a-i-o-scramble-1',
      kind: 'scramble',
      word: 'lama',
      explain: 'La-ma : la, puis ma. Les lettres l, a, m, a.',
    },
    {
      id: 'cp-francais-syllabes-a-i-o-scramble-2',
      kind: 'scramble',
      word: 'moto',
      explain: 'Mo-to : mo, puis to. Les lettres m, o, t, o.',
    },
    {
      id: 'cp-francais-syllabes-a-i-o-scramble-3',
      kind: 'scramble',
      word: 'rami',
      explain: 'Ra-mi : ra, puis mi. Les lettres r, a, m, i.',
    },
  ],
};

const SONS_OU_ON: Lesson = {
  id: 'cp-francais-sons-ou-on',
  title: 'Les sons ou et on',
  subject: 'francais',
  source: 'mots',
  level: 'CP',
  notion: 'Entendre et écrire les sons ou et on',
  theme: 'orthographe',
  attendu: 'Écrire des syllabes et des mots simples en respectant les sons (a, i, o, u, é, ou, on, an, in).',
  attenduId: 'cp-ortho-sons',
  summary:
    'Le son ou s\'écrit avec deux lettres : o et u, comme dans loup. Le son on s\'écrit aussi avec deux lettres : o et n, comme dans ballon.',
  minutes: 6,
  exercises: [
    {
      id: 'cp-francais-sons-ou-on-tf-1',
      kind: 'truefalse',
      statement: 'Dans « loup », on entend le son ou.',
      answer: true,
      explain: 'Loup : l et ou. Le son ou s\'écrit o-u.',
    },
    {
      id: 'cp-francais-sons-ou-on-sort-1',
      kind: 'sort',
      prompt: 'Quel son entends-tu dans le mot ?',
      boxes: ['ou', 'on'],
      items: [
        { word: 'loup', box: 0 },
        { word: 'bonbon', box: 1 },
        { word: 'poule', box: 0 },
        { word: 'ballon', box: 1 },
        { word: 'roue', box: 0 },
        { word: 'pont', box: 1 },
      ],
      explain: 'Pas grave. Le son ou se dit la bouche en rond, le son on se dit avec le nez.',
    },
    {
      id: 'cp-francais-sons-ou-on-choice-1',
      kind: 'choice',
      prompt: 'Quel mot a le son on ?',
      options: ['loup', 'ballon', 'poule'],
      answer: 1,
      explain: 'Ba-llon : on entend le son on à la fin. Loup et poule ont le son ou.',
    },
    {
      id: 'cp-francais-sons-ou-on-flash-1',
      kind: 'flash',
      word: 'loup',
      distractors: ['lop', 'lup'],
      explain: 'Loup : le son ou s\'écrit o-u, et il y a un p muet à la fin.',
    },
    {
      id: 'cp-francais-sons-ou-on-flash-2',
      kind: 'flash',
      word: 'ballon',
      distractors: ['balon', 'ballan'],
      explain: 'Ballon : deux l, et le son on s\'écrit o-n.',
    },
    {
      id: 'cp-francais-sons-ou-on-tap-1',
      kind: 'tapword',
      prompt: 'Touche les mots où tu entends le son on',
      words: ['Le', 'ballon', 'roule', 'sous', 'le', 'pont.'],
      answer: [1, 5],
      explain: 'Ballon et pont ont le son on. Roule et sous ont le son ou.',
    },
    {
      id: 'cp-francais-sons-ou-on-dict-1',
      kind: 'dictation',
      word: 'poule',
      sentence: 'La poule pond un œuf.',
      explain: 'Poule : p, ou, l, e. Le son ou s\'écrit o-u.',
    },
    {
      id: 'cp-francais-sons-ou-on-dict-2',
      kind: 'dictation',
      word: 'bonbon',
      sentence: 'Je mange un bonbon.',
      explain: 'Bon-bon : deux fois b-o-n.',
    },
    {
      id: 'cp-francais-sons-ou-on-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a fait une faute, corrige-le',
      words: ['Le', 'balon', 'est', 'rond.'],
      wrongIndex: 1,
      correct: 'ballon',
      distractors: ['ballan', 'balan'],
      explain: 'Ballon s\'écrit avec deux l, et le son on s\'écrit o-n.',
    },
  ],
};

const SONS_AN_IN: Lesson = {
  id: 'cp-francais-sons-an-in',
  title: 'Les sons an et in',
  subject: 'francais',
  source: 'mots',
  level: 'CP',
  notion: 'Entendre et écrire les sons an / en et in',
  theme: 'orthographe',
  attendu: 'Écrire des syllabes et des mots simples en respectant les sons (a, i, o, u, é, ou, on, an, in).',
  attenduId: 'cp-ortho-sons',
  summary:
    'Le son an s\'écrit a-n comme dans maman, ou e-n comme dans dent. Le son in s\'écrit i-n, comme dans lapin et matin.',
  minutes: 6,
  exercises: [
    {
      id: 'cp-francais-sons-an-in-tf-1',
      kind: 'truefalse',
      statement: '« maman » et « dent » ont le même son à la fin.',
      answer: true,
      explain: 'Oui : a-n et e-n font le même son an.',
    },
    {
      id: 'cp-francais-sons-an-in-sort-1',
      kind: 'sort',
      prompt: 'Quel son entends-tu dans le mot ?',
      boxes: ['an', 'in'],
      items: [
        { word: 'maman', box: 0 },
        { word: 'lapin', box: 1 },
        { word: 'dent', box: 0 },
        { word: 'matin', box: 1 },
        { word: 'vent', box: 0 },
        { word: 'sapin', box: 1 },
      ],
      explain: 'Pas grave. Dis le mot et écoute la fin : an comme dans maman, ou in comme dans lapin.',
    },
    {
      id: 'cp-francais-sons-an-in-choice-1',
      kind: 'choice',
      prompt: 'Comment s\'écrit le son an dans « dent » ?',
      options: ['a-n', 'e-n', 'i-n'],
      answer: 1,
      explain: 'Dent s\'écrit d-e-n-t : ici le son an s\'écrit e-n.',
    },
    {
      id: 'cp-francais-sons-an-in-flash-1',
      kind: 'flash',
      word: 'lapin',
      distractors: ['lapan', 'lapun'],
      explain: 'La-pin : le son in s\'écrit i-n.',
    },
    {
      id: 'cp-francais-sons-an-in-flash-2',
      kind: 'flash',
      word: 'maman',
      distractors: ['mamen', 'mamin'],
      explain: 'Ma-man : le son an s\'écrit a-n.',
    },
    {
      id: 'cp-francais-sons-an-in-blanks-1',
      kind: 'blanks',
      prompt: 'Complète avec le bon mot',
      text: 'Le {{lapin}} dort dans le {{jardin}}.',
      distractors: ['maman', 'matin'],
      explain: 'Le lapin dort dans le jardin : deux mots qui finissent par le son in.',
    },
    {
      id: 'cp-francais-sons-an-in-dict-1',
      kind: 'dictation',
      word: 'matin',
      sentence: 'Le matin, je me lève.',
      explain: 'Ma-tin : m-a-t-i-n. Le son in s\'écrit i-n.',
    },
    {
      id: 'cp-francais-sons-an-in-dict-2',
      kind: 'dictation',
      word: 'dent',
      sentence: 'J\'ai perdu une dent.',
      explain: 'Dent : d-e-n-t. Le son an s\'écrit e-n, et le t ne s\'entend pas.',
    },
    {
      id: 'cp-francais-sons-an-in-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a fait une faute, corrige-le',
      words: ['Le', 'lapan', 'mange', 'une', 'carotte.'],
      wrongIndex: 1,
      correct: 'lapin',
      distractors: ['lapen', 'lapon'],
      explain: 'Lapin finit par le son in, qui s\'écrit i-n.',
    },
  ],
};

const SON_E_ACCENT: Lesson = {
  id: 'cp-francais-son-e-accent',
  title: 'Les sons é et è',
  subject: 'francais',
  source: 'lecture',
  level: 'CP',
  notion: 'Lire é, è, ê et le e muet',
  theme: 'lecture',
  attendu: 'Connaître les correspondances entre les lettres et les sons, lire des syllabes et des mots simples.',
  attenduId: 'cp-lect-sons',
  summary:
    'Le é avec l\'accent qui monte se lit comme dans bébé. Le è et le ê se lisent comme dans père et fête. Le e tout seul à la fin d\'un mot, comme dans petite, ne s\'entend pas.',
  minutes: 6,
  exercises: [
    {
      id: 'cp-francais-son-e-accent-choice-1',
      kind: 'choice',
      prompt: 'Quel mot a le son é ?',
      options: ['père', 'bébé', 'fête'],
      answer: 1,
      explain: 'Bé-bé : deux fois le son é, avec l\'accent qui monte.',
    },
    {
      id: 'cp-francais-son-e-accent-sort-1',
      kind: 'sort',
      prompt: 'Quel son entends-tu dans le mot ?',
      boxes: ['é', 'è ou ê'],
      items: [
        { word: 'bébé', box: 0 },
        { word: 'père', box: 1 },
        { word: 'vélo', box: 0 },
        { word: 'fête', box: 1 },
        { word: 'été', box: 0 },
        { word: 'tête', box: 1 },
      ],
      explain: 'Pas grave. Regarde l\'accent : s\'il monte, c\'est é ; s\'il descend ou fait un chapeau, c\'est è.',
    },
    {
      id: 'cp-francais-son-e-accent-tf-1',
      kind: 'truefalse',
      statement: 'Dans « petite », on entend le e de la fin.',
      answer: false,
      explain: 'Pas grave. Le e de la fin est muet : on dit « petit » et on ne l\'entend pas.',
    },
    {
      id: 'cp-francais-son-e-accent-flash-1',
      kind: 'flash',
      word: 'bébé',
      distractors: ['bèbè', 'bebe'],
      explain: 'Bébé : deux é avec l\'accent qui monte.',
    },
    {
      id: 'cp-francais-son-e-accent-flash-2',
      kind: 'flash',
      word: 'fête',
      distractors: ['féte', 'fete'],
      explain: 'Fête : le e porte un petit chapeau, l\'accent circonflexe.',
    },
    {
      id: 'cp-francais-son-e-accent-tap-1',
      kind: 'tapword',
      prompt: 'Touche les mots où tu entends le son é',
      words: ['Le', 'bébé', 'a', 'un', 'vélo.'],
      answer: [1, 4],
      explain: 'Bébé et vélo ont le son é.',
    },
    {
      id: 'cp-francais-son-e-accent-choice-2',
      kind: 'choice',
      prompt: 'Quel mot finit par un e muet, qu\'on n\'entend pas ?',
      options: ['bébé', 'petite', 'été'],
      answer: 1,
      explain: 'Petite finit par un e sans accent : il ne s\'entend pas.',
    },
    {
      id: 'cp-francais-son-e-accent-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a fait une faute, corrige-le',
      words: ['Mon', 'pére', 'a', 'un', 'vélo.'],
      wrongIndex: 1,
      correct: 'père',
      distractors: ['pêre', 'pere'],
      explain: 'Père s\'écrit avec un è, l\'accent qui descend.',
    },
    {
      id: 'cp-francais-son-e-accent-dict-1',
      kind: 'dictation',
      word: 'vélo',
      sentence: 'Je roule à vélo.',
      explain: 'Vé-lo : v-é-l-o, avec un é qui monte.',
    },
  ],
};

const LETTRES_SONS: Lesson = {
  id: 'cp-francais-lettres-sons',
  title: 'Les lettres c, g et s',
  subject: 'francais',
  source: 'lecture',
  level: 'CP',
  notion: 'Lire les lettres qui font deux sons : c, g, s',
  theme: 'lecture',
  attendu: 'Connaître les correspondances entre les lettres et les sons, lire des syllabes et des mots simples.',
  attenduId: 'cp-lect-sons',
  summary:
    'La lettre c se lit comme dans canard ou comme dans cerise. La lettre g se lit comme dans gâteau ou comme dans girafe. La lettre s se lit comme dans sac, ou comme un z entre deux lettres qui chantent, comme dans rose.',
  minutes: 7,
  exercises: [
    {
      id: 'cp-francais-lettres-sons-choice-1',
      kind: 'choice',
      prompt: 'Dans « cerise », comment se lit le c ?',
      options: ['comme dans canard', 'comme un s'],
      answer: 1,
      explain: 'Devant un e ou un i, le c se lit comme un s : ce-rise.',
    },
    {
      id: 'cp-francais-lettres-sons-sort-1',
      kind: 'sort',
      prompt: 'Comment se lit le c ?',
      boxes: ['c comme canard', 'c comme cerise'],
      items: [
        { word: 'canard', box: 0 },
        { word: 'cerise', box: 1 },
        { word: 'cube', box: 0 },
        { word: 'citron', box: 1 },
        { word: 'cou', box: 0 },
        { word: 'ciel', box: 1 },
      ],
      explain: 'Pas grave. Devant e ou i, le c fait le son s. Devant a, o ou u, il fait le son k.',
    },
    {
      id: 'cp-francais-lettres-sons-tf-1',
      kind: 'truefalse',
      statement: 'Dans « girafe », le g fait le même son que dans « gâteau ».',
      answer: false,
      explain: 'Pas grave. Devant un i, le g se lit comme un j : gi-rafe.',
    },
    {
      id: 'cp-francais-lettres-sons-sort-2',
      kind: 'sort',
      prompt: 'Comment se lit le g ?',
      boxes: ['g comme gâteau', 'g comme girafe'],
      items: [
        { word: 'gâteau', box: 0 },
        { word: 'girafe', box: 1 },
        { word: 'gomme', box: 0 },
        { word: 'gilet', box: 1 },
        { word: 'gare', box: 0 },
        { word: 'bougie', box: 1 },
      ],
      explain: 'Pas grave. Devant e ou i, le g fait le son j. Devant a, o ou u, il fait le son g.',
    },
    {
      id: 'cp-francais-lettres-sons-flash-1',
      kind: 'flash',
      word: 'girafe',
      distractors: ['jirafe', 'guirafe'],
      explain: 'Girafe commence par un g, qui se lit comme un j devant le i.',
    },
    {
      id: 'cp-francais-lettres-sons-tf-2',
      kind: 'truefalse',
      statement: 'Dans « rose », le s se lit comme un z.',
      answer: true,
      explain: 'Oui : entre deux lettres qui chantent, o et e, le s fait le son z.',
    },
    {
      id: 'cp-francais-lettres-sons-sort-3',
      kind: 'sort',
      prompt: 'Comment se lit le s ?',
      boxes: ['s comme sac', 's comme rose'],
      items: [
        { word: 'sac', box: 0 },
        { word: 'rose', box: 1 },
        { word: 'salade', box: 0 },
        { word: 'valise', box: 1 },
        { word: 'soupe', box: 0 },
        { word: 'cousin', box: 1 },
      ],
      explain: 'Pas grave. Entre deux lettres qui chantent, le s fait le son z. Au début du mot, il fait le son s.',
    },
    {
      id: 'cp-francais-lettres-sons-tap-1',
      kind: 'tapword',
      prompt: 'Touche le mot où le s se lit comme un z',
      words: ['La', 'rose', 'est', 'sur', 'la', 'table.'],
      answer: [1],
      explain: 'Rose : le s est entre o et e, il fait le son z. Dans sur, il fait le son s.',
    },
    {
      id: 'cp-francais-lettres-sons-choice-2',
      kind: 'choice',
      prompt: 'Quel mot a le son j ?',
      options: ['gare', 'gomme', 'gilet'],
      answer: 2,
      explain: 'Gi-let : devant le i, le g se lit comme un j.',
    },
  ],
};

const MOTS_OUTILS: Lesson = {
  id: 'cp-francais-mots-outils',
  title: 'Les mots outils',
  subject: 'francais',
  source: 'mots',
  level: 'CP',
  notion: 'Lire et écrire les petits mots outils : le, la, les, un, une, des, et, est, il, elle, dans, sur',
  theme: 'orthographe',
  attendu: 'Orthographier les mots outils et les mots de la classe appris par cœur.',
  attenduId: 'cp-ortho-mots',
  summary:
    'Les mots outils sont de petits mots qu\'on voit tout le temps : le, la, les, un, une, des, et, est, il, elle, dans, sur. On les apprend par cœur pour les lire d\'un coup.',
  minutes: 6,
  exercises: [
    {
      id: 'cp-francais-mots-outils-flash-1',
      kind: 'flash',
      word: 'les',
      distractors: ['lé', 'lès'],
      explain: 'Les : l-e-s. Le s de la fin ne s\'entend pas.',
    },
    {
      id: 'cp-francais-mots-outils-flash-2',
      kind: 'flash',
      word: 'elle',
      distractors: ['èle', 'ele'],
      explain: 'Elle : e-l-l-e, avec deux l.',
    },
    {
      id: 'cp-francais-mots-outils-choice-1',
      kind: 'choice',
      prompt: 'Quel mot est bien écrit ?',
      options: ['dan', 'dans', 'dant'],
      answer: 1,
      explain: 'Dans s\'écrit d-a-n-s. Le s de la fin ne s\'entend pas.',
    },
    {
      id: 'cp-francais-mots-outils-flash-3',
      kind: 'flash',
      word: 'une',
      distractors: ['unne', 'hune'],
      explain: 'Une : u-n-e, un seul n.',
    },
    {
      id: 'cp-francais-mots-outils-scramble-1',
      kind: 'scramble',
      word: 'dans',
      explain: 'Dans : d, a, n, s.',
    },
    {
      id: 'cp-francais-mots-outils-scramble-2',
      kind: 'scramble',
      word: 'elle',
      explain: 'Elle : e, l, l, e.',
    },
    {
      id: 'cp-francais-mots-outils-dict-1',
      kind: 'dictation',
      word: 'sur',
      sentence: 'Le chat est sur le lit.',
      explain: 'Sur : s-u-r.',
    },
    {
      id: 'cp-francais-mots-outils-dict-2',
      kind: 'dictation',
      word: 'une',
      sentence: 'J\'ai une pomme.',
      explain: 'Une : u-n-e.',
    },
    {
      id: 'cp-francais-mots-outils-blanks-1',
      kind: 'blanks',
      prompt: 'Complète avec le bon mot',
      text: 'Lila est {{dans}} le jardin et {{elle}} joue.',
      distractors: ['sur', 'il'],
      explain: 'Lila est dans le jardin. Lila est une fille, alors on dit elle.',
    },
    {
      id: 'cp-francais-mots-outils-blanks-2',
      kind: 'blanks',
      prompt: 'Complète : et ou est ?',
      text: 'Le chat {{est}} sur le lit {{et}} il dort.',
      distractors: ['es', 'ai'],
      explain: 'Le chat est sur le lit : est, c\'est le verbe être. Et, c\'est pour ajouter quelque chose.',
    },
  ],
};

const LIRE_PHRASES: Lesson = {
  id: 'cp-francais-lire-phrases',
  title: 'Lire des phrases',
  subject: 'francais',
  source: 'lecture',
  level: 'CP',
  notion: 'Lire et comprendre des phrases courtes',
  theme: 'lecture',
  attendu: 'Lire des mots fréquents et des phrases courtes, comprendre ce qu\'on lit.',
  attenduId: 'cp-lect-mots',
  summary:
    'Quand tu lis une phrase, tu cherches qui fait quoi, et où. Le chat dort sur le lit : c\'est le chat, il dort, et il est sur le lit.',
  minutes: 6,
  exercises: [
    {
      id: 'cp-francais-lire-phrases-tf-1',
      kind: 'truefalse',
      statement: '« Le chat dort sur le lit. » Le chat est sur le lit.',
      answer: true,
      explain: 'Oui : la phrase dit que le chat dort sur le lit.',
    },
    {
      id: 'cp-francais-lire-phrases-tf-2',
      kind: 'truefalse',
      statement: '« Lila a un vélo rouge. » Le vélo de Lila est vert.',
      answer: false,
      explain: 'Pas grave. La phrase dit que le vélo est rouge.',
    },
    {
      id: 'cp-francais-lire-phrases-choice-1',
      kind: 'choice',
      prompt: 'Qui dort sur le lit ?',
      speak: 'Le chat dort sur le lit. Qui dort sur le lit ?',
      options: ['le chien', 'le chat', 'Lila'],
      answer: 1,
      explain: 'Le premier mot après « le », c\'est chat : c\'est le chat qui dort.',
    },
    {
      id: 'cp-francais-lire-phrases-tap-1',
      kind: 'tapword',
      prompt: 'Touche le mot qui dit ce que fait le chat',
      words: ['Le', 'chat', 'dort', 'sur', 'le', 'lit.'],
      answer: [2],
      explain: 'Le chat dort : dort, c\'est ce qu\'il fait.',
    },
    {
      id: 'cp-francais-lire-phrases-choice-2',
      kind: 'choice',
      prompt: 'Quelle phrase va avec : un papa qui lit ?',
      options: ['Papa lit un livre.', 'Papa fait du vélo.', 'Papa dort.'],
      answer: 0,
      explain: 'Papa lit un livre : le mot lit nous dit qu\'il lit.',
    },
    {
      id: 'cp-francais-lire-phrases-tap-2',
      kind: 'tapword',
      prompt: 'Touche le mot qui dit où court le chien',
      words: ['Le', 'chien', 'court', 'dans', 'le', 'jardin.'],
      answer: [5],
      explain: 'Dans le jardin : jardin, c\'est l\'endroit où court le chien.',
    },
    {
      id: 'cp-francais-lire-phrases-sentence-1',
      kind: 'sentence',
      prompt: 'Remets les mots dans l\'ordre',
      words: ['Papa', 'lit', 'un', 'livre.'],
      explain: 'Papa lit un livre. On commence par la majuscule et on finit par le point.',
    },
    {
      id: 'cp-francais-lire-phrases-choice-3',
      kind: 'choice',
      prompt: 'Quelle phrase va avec : un chien dehors ?',
      options: ['Le chien dort sur le lit.', 'Le chien court dans le jardin.'],
      answer: 1,
      explain: 'Le jardin est dehors : le chien court dans le jardin.',
    },
    {
      id: 'cp-francais-lire-phrases-sentence-2',
      kind: 'sentence',
      prompt: 'Remets les mots dans l\'ordre',
      words: ['Lila', 'a', 'un', 'vélo', 'rouge.'],
      explain: 'Lila a un vélo rouge. Le mot rouge vient après vélo, et il porte le point.',
    },
    {
      id: 'cp-francais-lire-phrases-tf-3',
      kind: 'truefalse',
      statement: '« Papa lit un livre. » Papa regarde la télé.',
      answer: false,
      explain: 'Pas grave. La phrase dit que Papa lit un livre, pas qu\'il regarde la télé.',
    },
  ],
};

const PETITE_HISTOIRE: Lesson = {
  id: 'cp-francais-petite-histoire',
  title: 'Le chat de Tom',
  subject: 'francais',
  source: 'lecture',
  level: 'CP',
  notion: 'Lire une petite histoire et la comprendre',
  theme: 'lecture',
  attendu: 'Lire des mots fréquents et des phrases courtes, comprendre ce qu\'on lit.',
  attenduId: 'cp-lect-mots',
  summary:
    'Voici l\'histoire : Tom a un petit chat. Le chat dort dans le jardin. Tom lui donne du lait. Le chat boit tout le lait. Puis il saute sur le lit de Tom.',
  minutes: 7,
  exercises: [
    {
      id: 'cp-francais-petite-histoire-choice-1',
      kind: 'choice',
      prompt: 'Qui a un chat ?',
      options: ['Lila', 'Tom', 'Papa'],
      answer: 1,
      explain: 'La première phrase dit : Tom a un petit chat.',
    },
    {
      id: 'cp-francais-petite-histoire-choice-2',
      kind: 'choice',
      prompt: 'Où dort le chat ?',
      options: ['dans le jardin', 'sur le lit', 'dans la cuisine'],
      answer: 0,
      explain: 'Le chat dort dans le jardin. Il saute sur le lit seulement à la fin.',
    },
    {
      id: 'cp-francais-petite-histoire-tf-1',
      kind: 'truefalse',
      statement: 'Tom donne du pain au chat.',
      answer: false,
      explain: 'Pas grave. Tom lui donne du lait, pas du pain.',
    },
    {
      id: 'cp-francais-petite-histoire-tf-2',
      kind: 'truefalse',
      statement: 'Le chat boit tout le lait.',
      answer: true,
      explain: 'Oui : le chat boit tout le lait.',
    },
    {
      id: 'cp-francais-petite-histoire-tap-1',
      kind: 'tapword',
      prompt: 'Touche le mot qui dit ce que boit le chat',
      words: ['Le', 'chat', 'boit', 'tout', 'le', 'lait.'],
      answer: [5],
      explain: 'Le chat boit du lait : le mot lait est à la fin de la phrase.',
    },
    {
      id: 'cp-francais-petite-histoire-blanks-1',
      kind: 'blanks',
      prompt: 'Complète l\'histoire',
      text: 'Tom a un petit {{chat}}. Le chat dort dans le {{jardin}}.',
      distractors: ['chien', 'lit'],
      explain: 'Tom a un petit chat, et le chat dort dans le jardin.',
    },
    {
      id: 'cp-francais-petite-histoire-choice-3',
      kind: 'choice',
      prompt: 'Que fait le chat à la fin ?',
      options: ['Il dort.', 'Il saute sur le lit.', 'Il mange.'],
      answer: 1,
      explain: 'La dernière phrase dit : puis il saute sur le lit de Tom.',
    },
    {
      id: 'cp-francais-petite-histoire-sentence-1',
      kind: 'sentence',
      prompt: 'Remets les mots dans l\'ordre',
      words: ['Tom', 'lui', 'donne', 'du', 'lait.'],
      explain: 'Tom lui donne du lait. On commence par Tom, avec la majuscule.',
    },
    {
      id: 'cp-francais-petite-histoire-order-1',
      kind: 'order',
      prompt: 'Remets l\'histoire dans l\'ordre',
      lines: [
        'Tom a un petit chat.',
        'Le chat dort dans le jardin.',
        'Tom lui donne du lait.',
        'Le chat boit tout le lait.',
      ],
      explain: 'D\'abord Tom a un chat, le chat dort, Tom donne du lait, et le chat le boit.',
    },
  ],
};

const COMPTINE: Lesson = {
  id: 'cp-francais-comptine',
  title: 'Petit lapin',
  subject: 'francais',
  source: 'poesie',
  level: 'CP',
  notion: 'Mémoriser et réciter une comptine',
  theme: 'poesie',
  attendu: 'Mémoriser et réciter une comptine ou un petit poème.',
  attenduId: 'cp-oral-memoriser',
  summary:
    'Une comptine de huit vers à apprendre par cœur. Petit lapin, petit lapin, Tu sautes dans le jardin. Tu croques une carotte, Puis tu cours vers la grotte. Le soir, tu rentres au lit, Tu fermes les yeux, petit. Fais de beaux rêves, lapin, On se revoit demain matin.',
  minutes: 7,
  exercises: [
    {
      id: 'cp-francais-comptine-flashcard-1',
      kind: 'flashcard',
      prompt: 'Récite le vers suivant',
      front: 'Petit lapin, petit lapin,',
      back: 'Tu sautes dans le jardin.',
      explain: 'Après « petit lapin », le lapin saute dans le jardin. Lapin rime avec jardin.',
    },
    {
      id: 'cp-francais-comptine-choice-1',
      kind: 'choice',
      prompt: 'Quel mot rime avec lapin ?',
      options: ['carotte', 'matin', 'lit'],
      answer: 1,
      explain: 'Lapin et matin finissent tous les deux par le son in.',
    },
    {
      id: 'cp-francais-comptine-order-1',
      kind: 'order',
      prompt: 'Remets les quatre premiers vers dans l\'ordre',
      lines: [
        'Petit lapin, petit lapin,',
        'Tu sautes dans le jardin.',
        'Tu croques une carotte,',
        'Puis tu cours vers la grotte.',
      ],
      explain: 'Le lapin saute dans le jardin, croque une carotte, puis court vers la grotte.',
    },
    {
      id: 'cp-francais-comptine-blanks-1',
      kind: 'blanks',
      prompt: 'Complète les vers',
      text: 'Petit lapin, petit {{lapin}},\nTu sautes dans le {{jardin}}.',
      distractors: ['matin', 'lit'],
      explain: 'Lapin rime avec jardin.',
    },
    {
      id: 'cp-francais-comptine-blanks-2',
      kind: 'blanks',
      prompt: 'Complète les vers',
      text: 'Tu croques une {{carotte}},\nPuis tu cours vers la {{grotte}}.',
      distractors: ['pomme', 'maison'],
      explain: 'Carotte rime avec grotte.',
    },
    {
      id: 'cp-francais-comptine-tf-1',
      kind: 'truefalse',
      statement: 'Dans la comptine, le lapin croque une pomme.',
      answer: false,
      explain: 'Pas grave. Le lapin croque une carotte.',
    },
    {
      id: 'cp-francais-comptine-order-2',
      kind: 'order',
      prompt: 'Remets les quatre derniers vers dans l\'ordre',
      lines: [
        'Le soir, tu rentres au lit,',
        'Tu fermes les yeux, petit.',
        'Fais de beaux rêves, lapin,',
        'On se revoit demain matin.',
      ],
      explain: 'Le soir, le lapin va au lit, ferme les yeux, rêve, et on le revoit demain matin.',
    },
    {
      id: 'cp-francais-comptine-choice-2',
      kind: 'choice',
      prompt: 'Quel mot rime avec lit ?',
      options: ['petit', 'jardin', 'grotte'],
      answer: 0,
      explain: 'Lit et petit finissent tous les deux par le son i.',
    },
    {
      id: 'cp-francais-comptine-blanks-3',
      kind: 'blanks',
      prompt: 'Complète les vers',
      text: 'Le soir, tu rentres au {{lit}},\nTu fermes les yeux, {{petit}}.',
      distractors: ['jardin', 'grotte'],
      explain: 'Lit rime avec petit.',
    },
  ],
};

const LA_PHRASE: Lesson = {
  id: 'cp-francais-la-phrase',
  title: 'La phrase',
  subject: 'francais',
  source: 'grammaire',
  level: 'CP',
  notion: 'Reconnaître une phrase : majuscule, point, ordre des mots',
  theme: 'grammaire',
  attendu: 'Reconnaître une phrase : majuscule, point, ordre des mots.',
  attenduId: 'cp-gram-phrase',
  summary:
    'Une phrase commence par une majuscule et finit par un point. Les mots sont dans le bon ordre et la phrase veut dire quelque chose.',
  minutes: 6,
  exercises: [
    {
      id: 'cp-francais-la-phrase-choice-1',
      kind: 'choice',
      prompt: 'Par quoi commence une phrase ?',
      options: ['un point', 'une majuscule', 'une virgule'],
      answer: 1,
      explain: 'Une phrase commence par une majuscule, la grande lettre.',
    },
    {
      id: 'cp-francais-la-phrase-tf-1',
      kind: 'truefalse',
      statement: 'Une phrase finit par un point.',
      answer: true,
      explain: 'Oui : le point dit que la phrase est finie.',
    },
    {
      id: 'cp-francais-la-phrase-tap-1',
      kind: 'tapword',
      prompt: 'Touche le mot qui a la majuscule',
      words: ['Le', 'chien', 'court', 'vite.'],
      answer: [0],
      explain: 'Le premier mot, Le, a la majuscule : c\'est le début de la phrase.',
    },
    {
      id: 'cp-francais-la-phrase-tap-2',
      kind: 'tapword',
      prompt: 'Touche le mot qui porte le point',
      words: ['Lila', 'mange', 'une', 'pomme.'],
      answer: [3],
      explain: 'Pomme est le dernier mot : il porte le point.',
    },
    {
      id: 'cp-francais-la-phrase-sentence-1',
      kind: 'sentence',
      prompt: 'Remets les mots dans l\'ordre',
      words: ['Le', 'chat', 'dort.'],
      explain: 'Le chat dort. On commence par le mot avec la majuscule et on finit par le point.',
    },
    {
      id: 'cp-francais-la-phrase-sort-1',
      kind: 'sort',
      prompt: 'Phrase ou pas phrase ?',
      boxes: ['C\'est une phrase', 'Ce n\'est pas une phrase'],
      items: [
        { word: 'Le chat dort.', box: 0 },
        { word: 'dort chat le', box: 1 },
        { word: 'Lila a un vélo.', box: 0 },
        { word: 'vélo un Lila', box: 1 },
        { word: 'Papa lit.', box: 0 },
        { word: 'lit papa', box: 1 },
      ],
      explain: 'Pas grave. Une phrase a une majuscule, un point, et elle veut dire quelque chose.',
    },
    {
      id: 'cp-francais-la-phrase-sentence-2',
      kind: 'sentence',
      prompt: 'Remets les mots dans l\'ordre',
      words: ['Lila', 'a', 'un', 'vélo.'],
      explain: 'Lila a un vélo. Lila a la majuscule, vélo porte le point.',
    },
    {
      id: 'cp-francais-la-phrase-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a oublié quelque chose, corrige-le',
      words: ['le', 'chat', 'dort.'],
      wrongIndex: 0,
      correct: 'Le',
      distractors: ['LE', 'la'],
      explain: 'Le premier mot de la phrase prend une majuscule : Le.',
    },
    {
      id: 'cp-francais-la-phrase-fix-2',
      kind: 'fix',
      prompt: 'Gribouille a oublié quelque chose, corrige-le',
      words: ['Papa', 'lit', 'un', 'livre'],
      wrongIndex: 3,
      correct: 'livre.',
      distractors: ['livre,', 'Livre.'],
      explain: 'Le dernier mot porte le point : livre, suivi d\'un point.',
    },
    {
      id: 'cp-francais-la-phrase-tf-2',
      kind: 'truefalse',
      statement: '« dort le chat » est une phrase.',
      answer: false,
      explain: 'Pas grave. Il manque la majuscule et le point, et les mots sont dans le désordre.',
    },
  ],
};

const UN_DES: Lesson = {
  id: 'cp-francais-un-des',
  title: 'Un ou des, le nom et le verbe',
  subject: 'francais',
  source: 'grammaire',
  level: 'CP',
  notion: 'Distinguer un et des, le et les, le nom et le verbe, fille et garçon',
  theme: 'grammaire',
  attendu: 'Distinguer le nom et le verbe, un et des, le et les, fille et garçon.',
  attenduId: 'cp-gram-nom',
  summary:
    'Un chat, c\'est un seul ; des chats, c\'est plusieurs. Dans « la fille chante », fille est le nom et chante est le verbe, ce qu\'elle fait.',
  minutes: 6,
  exercises: [
    {
      id: 'cp-francais-un-des-choice-1',
      kind: 'choice',
      prompt: 'Il y a trois chats. Que dit-on ?',
      options: ['un chat', 'des chats'],
      answer: 1,
      explain: 'Trois, c\'est plusieurs : on dit des chats, avec un s.',
    },
    {
      id: 'cp-francais-un-des-sort-1',
      kind: 'sort',
      prompt: 'Un seul ou plusieurs ?',
      boxes: ['un seul', 'plusieurs'],
      items: [
        { word: 'un chat', box: 0 },
        { word: 'des chats', box: 1 },
        { word: 'le vélo', box: 0 },
        { word: 'les vélos', box: 1 },
        { word: 'une pomme', box: 0 },
        { word: 'des pommes', box: 1 },
      ],
      explain: 'Pas grave. Un, une, le, la : un seul. Des, les : plusieurs.',
    },
    {
      id: 'cp-francais-un-des-choice-2',
      kind: 'choice',
      prompt: 'Complète : ... lapins',
      options: ['le', 'les'],
      answer: 1,
      explain: 'Lapins finit par un s : il y en a plusieurs, on dit les lapins.',
    },
    {
      id: 'cp-francais-un-des-blanks-1',
      kind: 'blanks',
      prompt: 'Complète avec un ou des',
      text: 'Lila a {{un}} chat et {{des}} poissons.',
      distractors: ['une'],
      explain: 'Un chat : un seul. Des poissons : plusieurs, avec un s.',
    },
    {
      id: 'cp-francais-un-des-tap-1',
      kind: 'tapword',
      prompt: 'Touche le nom',
      words: ['La', 'fille', 'chante.'],
      answer: [1],
      explain: 'Fille est le nom : c\'est de qui on parle.',
    },
    {
      id: 'cp-francais-un-des-tap-2',
      kind: 'tapword',
      prompt: 'Touche le verbe',
      words: ['La', 'fille', 'chante.'],
      answer: [2],
      explain: 'Chante est le verbe : c\'est ce que fait la fille.',
    },
    {
      id: 'cp-francais-un-des-tf-1',
      kind: 'truefalse',
      statement: '« chante » est un verbe.',
      answer: true,
      explain: 'Oui : chanter, c\'est une action, donc chante est un verbe.',
    },
    {
      id: 'cp-francais-un-des-tap-3',
      kind: 'tapword',
      prompt: 'Touche le nom',
      words: ['Le', 'chien', 'court.'],
      answer: [1],
      explain: 'Chien est le nom. Court est le verbe, ce qu\'il fait.',
    },
    {
      id: 'cp-francais-un-des-sort-2',
      kind: 'sort',
      prompt: 'Fille ou garçon ?',
      boxes: ['fille', 'garçon'],
      items: [
        { word: 'une fille', box: 0 },
        { word: 'un garçon', box: 1 },
        { word: 'la maman', box: 0 },
        { word: 'le papa', box: 1 },
        { word: 'la reine', box: 0 },
        { word: 'le roi', box: 1 },
      ],
      explain: 'Pas grave. Une, la : c\'est pour une fille. Un, le : c\'est pour un garçon.',
    },
    {
      id: 'cp-francais-un-des-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a fait une faute, corrige-le',
      words: ['Je', 'vois', 'des', 'chat', 'noirs.'],
      wrongIndex: 3,
      correct: 'chats',
      distractors: ['chate', 'chatt'],
      explain: 'Des, c\'est plusieurs : on ajoute un s à chat.',
    },
  ],
};

const JE_TU_IL: Lesson = {
  id: 'cp-francais-je-tu-il',
  title: 'Je, tu, il',
  subject: 'francais',
  source: 'grammaire',
  level: 'CP',
  notion: 'Le verbe change avec je, tu, il : être, avoir, chanter',
  theme: 'conjugaison',
  attendu: 'Comprendre que le verbe change avec je, tu, il ; utiliser être et avoir à l\'oral et à l\'écrit.',
  attenduId: 'cp-conj-present',
  summary:
    'Je suis, tu es, il est. J\'ai, tu as, il a. Je chante, tu chantes, il chante : avec tu, le verbe prend un s.',
  minutes: 6,
  exercises: [
    {
      id: 'cp-francais-je-tu-il-match-1',
      kind: 'match',
      prompt: 'Relie chaque mot au bon verbe',
      pairs: [
        { a: 'je', b: 'suis' },
        { a: 'tu', b: 'es' },
        { a: 'il', b: 'est' },
      ],
      seconds: 30,
      explain: 'Je suis, tu es, il est : c\'est le verbe être.',
    },
    {
      id: 'cp-francais-je-tu-il-blanks-1',
      kind: 'blanks',
      prompt: 'Complète avec le verbe être',
      text: 'Je {{suis}} grand. Tu {{es}} petit.',
      distractors: ['est'],
      explain: 'Je suis, tu es. Est, c\'est pour il.',
    },
    {
      id: 'cp-francais-je-tu-il-choice-1',
      kind: 'choice',
      prompt: 'Je ... une pomme.',
      options: ['ai', 'as', 'a'],
      answer: 0,
      explain: 'J\'ai une pomme : avec je, le verbe avoir s\'écrit ai.',
    },
    {
      id: 'cp-francais-je-tu-il-blanks-2',
      kind: 'blanks',
      prompt: 'Complète avec le verbe avoir',
      text: 'J\'{{ai}} un chat. Tu {{as}} un chien. Il {{a}} un lapin.',
      distractors: ['est'],
      explain: 'J\'ai, tu as, il a : c\'est le verbe avoir.',
    },
    {
      id: 'cp-francais-je-tu-il-sort-1',
      kind: 'sort',
      prompt: 'Je, tu ou il ?',
      boxes: ['je', 'tu', 'il'],
      items: [
        { word: 'suis', box: 0 },
        { word: 'es', box: 1 },
        { word: 'est', box: 2 },
        { word: 'ai', box: 0 },
        { word: 'as', box: 1 },
        { word: 'a', box: 2 },
      ],
      explain: 'Pas grave. Je suis, j\'ai. Tu es, tu as. Il est, il a.',
    },
    {
      id: 'cp-francais-je-tu-il-choice-2',
      kind: 'choice',
      prompt: 'Tu ... content.',
      options: ['est', 'es', 'suis'],
      answer: 1,
      explain: 'Tu es content : avec tu, le verbe être s\'écrit es.',
    },
    {
      id: 'cp-francais-je-tu-il-tf-1',
      kind: 'truefalse',
      statement: 'Avec tu, le verbe chanter prend un s : tu chantes.',
      answer: true,
      explain: 'Oui : tu chantes, avec un s à la fin.',
    },
    {
      id: 'cp-francais-je-tu-il-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a fait une faute, corrige-le',
      words: ['Il', 'chantes', 'très', 'bien.'],
      wrongIndex: 1,
      correct: 'chante',
      distractors: ['chant', 'chantent'],
      explain: 'Avec il, pas de s : il chante.',
    },
    {
      id: 'cp-francais-je-tu-il-fix-2',
      kind: 'fix',
      prompt: 'Gribouille a fait une faute, corrige-le',
      words: ['Tu', 'chante', 'très', 'fort.'],
      wrongIndex: 1,
      correct: 'chantes',
      distractors: ['chant', 'chantent'],
      explain: 'Avec tu, le verbe prend un s : tu chantes.',
    },
  ],
};

const CATEGORIES: Lesson = {
  id: 'cp-francais-categories',
  title: 'Ranger les mots',
  subject: 'francais',
  source: 'lecon',
  level: 'CP',
  notion: 'Ranger des mots par catégorie et trouver des contraires simples',
  theme: 'vocabulaire',
  attendu: 'Ranger des mots par catégorie, trouver des contraires simples, utiliser le vocabulaire de l\'école et de la maison.',
  attenduId: 'cp-voc-mots',
  summary:
    'On peut ranger les mots par famille : les animaux, les fruits, les vêtements. Un contraire, c\'est le mot qui dit l\'inverse : grand et petit, chaud et froid.',
  minutes: 6,
  exercises: [
    {
      id: 'cp-francais-categories-tf-1',
      kind: 'truefalse',
      statement: 'Un pull est un vêtement.',
      answer: true,
      explain: 'Oui : on met un pull sur soi, c\'est un vêtement.',
    },
    {
      id: 'cp-francais-categories-sort-1',
      kind: 'sort',
      prompt: 'Range chaque mot dans sa famille',
      boxes: ['animaux', 'fruits', 'vêtements'],
      items: [
        { word: 'chat', box: 0 },
        { word: 'pomme', box: 1 },
        { word: 'pull', box: 2 },
        { word: 'lapin', box: 0 },
        { word: 'poire', box: 1 },
        { word: 'robe', box: 2 },
        { word: 'vache', box: 0 },
        { word: 'banane', box: 1 },
        { word: 'bonnet', box: 2 },
      ],
      explain: 'Pas grave. Un animal est vivant, un fruit se mange, un vêtement se porte.',
    },
    {
      id: 'cp-francais-categories-choice-1',
      kind: 'choice',
      prompt: 'Quel mot n\'est pas un fruit ?',
      options: ['pomme', 'poire', 'pull'],
      answer: 2,
      explain: 'Le pull est un vêtement. La pomme et la poire sont des fruits.',
    },
    {
      id: 'cp-francais-categories-tf-2',
      kind: 'truefalse',
      statement: 'La vache est un fruit.',
      answer: false,
      explain: 'Pas grave. La vache est un animal.',
    },
    {
      id: 'cp-francais-categories-choice-2',
      kind: 'choice',
      prompt: 'Quel est le contraire de grand ?',
      options: ['petit', 'gros', 'long'],
      answer: 0,
      explain: 'Le contraire de grand, c\'est petit.',
    },
    {
      id: 'cp-francais-categories-pairs-1',
      kind: 'pairs',
      prompt: 'Retrouve les contraires',
      pairs: [
        { a: 'grand', b: 'petit' },
        { a: 'chaud', b: 'froid' },
        { a: 'jour', b: 'nuit' },
        { a: 'ouvert', b: 'fermé' },
      ],
      explain: 'Grand et petit, chaud et froid, jour et nuit, ouvert et fermé : chacun dit l\'inverse de l\'autre.',
    },
    {
      id: 'cp-francais-categories-sort-2',
      kind: 'sort',
      prompt: 'Chaud ou froid ?',
      boxes: ['chaud', 'froid'],
      items: [
        { word: 'soleil', box: 0 },
        { word: 'neige', box: 1 },
        { word: 'feu', box: 0 },
        { word: 'glace', box: 1 },
        { word: 'four', box: 0 },
        { word: 'hiver', box: 1 },
      ],
      explain: 'Pas grave. Le soleil, le feu et le four chauffent. La neige, la glace et l\'hiver sont froids.',
    },
    {
      id: 'cp-francais-categories-choice-3',
      kind: 'choice',
      prompt: 'Quel est le contraire de chaud ?',
      options: ['sec', 'froid', 'doux'],
      answer: 1,
      explain: 'Le contraire de chaud, c\'est froid.',
    },
    {
      id: 'cp-francais-categories-blanks-1',
      kind: 'blanks',
      prompt: 'Complète avec le contraire',
      text: 'Le contraire de grand, c\'est {{petit}}. Le contraire de jour, c\'est {{nuit}}.',
      distractors: ['froid', 'gros'],
      explain: 'Grand et petit, jour et nuit.',
    },
  ],
};

const ALPHABET: Lesson = {
  id: 'cp-francais-alphabet',
  title: 'L\'alphabet',
  subject: 'francais',
  source: 'lecon',
  level: 'CP',
  notion: 'Connaître l\'alphabet dans l\'ordre, en majuscules et en minuscules',
  theme: 'vocabulaire',
  attendu: 'Connaître l\'alphabet dans l\'ordre, en lettres majuscules et minuscules.',
  attenduId: 'cp-voc-alphabet',
  summary:
    'L\'alphabet a 26 lettres, de a à z, toujours dans le même ordre. Chaque lettre a une majuscule, la grande, et une minuscule, la petite : A et a, B et b.',
  minutes: 6,
  exercises: [
    {
      id: 'cp-francais-alphabet-order-1',
      kind: 'order',
      prompt: 'Remets les lettres dans l\'ordre de l\'alphabet',
      lines: ['a', 'b', 'c', 'd'],
      explain: 'L\'alphabet commence par a, b, c, d.',
    },
    {
      id: 'cp-francais-alphabet-tf-1',
      kind: 'truefalse',
      statement: 'La lettre z est la dernière de l\'alphabet.',
      answer: true,
      explain: 'Oui : l\'alphabet va de a jusqu\'à z.',
    },
    {
      id: 'cp-francais-alphabet-choice-1',
      kind: 'choice',
      prompt: 'Quelle lettre vient juste après d ?',
      options: ['c', 'e', 'f'],
      answer: 1,
      explain: 'a, b, c, d, e : après d, il y a e.',
    },
    {
      id: 'cp-francais-alphabet-blanks-1',
      kind: 'blanks',
      prompt: 'Complète l\'alphabet',
      text: 'a, b, {{c}}, d, {{e}}, f, g',
      distractors: ['h', 'j'],
      explain: 'a, b, c, d, e, f, g.',
    },
    {
      id: 'cp-francais-alphabet-pairs-1',
      kind: 'pairs',
      prompt: 'Retrouve la majuscule et la minuscule',
      pairs: [
        { a: 'A', b: 'a' },
        { a: 'B', b: 'b' },
        { a: 'E', b: 'e' },
        { a: 'G', b: 'g' },
        { a: 'R', b: 'r' },
      ],
      explain: 'Chaque grande lettre a sa petite lettre : A et a, B et b, E et e, G et g, R et r.',
    },
    {
      id: 'cp-francais-alphabet-order-2',
      kind: 'order',
      prompt: 'Remets les lettres dans l\'ordre de l\'alphabet',
      lines: ['l', 'm', 'n', 'o'],
      explain: 'l, m, n, o : c\'est le milieu de l\'alphabet.',
    },
    {
      id: 'cp-francais-alphabet-choice-2',
      kind: 'choice',
      prompt: 'Quelle lettre vient juste avant t ?',
      options: ['s', 'u', 'r'],
      answer: 0,
      explain: 'r, s, t : juste avant t, il y a s.',
    },
    {
      id: 'cp-francais-alphabet-tf-2',
      kind: 'truefalse',
      statement: 'La lettre m vient avant la lettre b.',
      answer: false,
      explain: 'Pas grave. Le b est au début de l\'alphabet, le m est au milieu.',
    },
    {
      id: 'cp-francais-alphabet-choice-3',
      kind: 'choice',
      prompt: 'Quelle est la majuscule de r ?',
      options: ['R', 'P', 'B'],
      answer: 0,
      explain: 'La grande lettre de r, c\'est R.',
    },
    {
      id: 'cp-francais-alphabet-order-3',
      kind: 'order',
      prompt: 'Remets les lettres dans l\'ordre de l\'alphabet',
      lines: ['w', 'x', 'y', 'z'],
      explain: 'w, x, y, z : ce sont les quatre dernières lettres.',
    },
  ],
};

export const LESSONS: Lesson[] = [
  SYLLABES,
  SONS_OU_ON,
  SONS_AN_IN,
  SON_E_ACCENT,
  LETTRES_SONS,
  MOTS_OUTILS,
  LIRE_PHRASES,
  PETITE_HISTOIRE,
  COMPTINE,
  LA_PHRASE,
  UN_DES,
  JE_TU_IL,
  CATEGORIES,
  ALPHABET,
];
