import type { Lesson } from './types';

/**
 * Banque CE1, mathématiques : quatorze leçons qui couvrent les attendus de
 * fin d'année (nombres, calcul, grandeurs et mesures, espace et géométrie).
 * Tout est neutre : l'univers habille à l'affichage.
 */

const NOMBRES_1000: Lesson = {
  id: 'maths-nombres-1000',
  title: "Les nombres jusqu'à 1 000",
  subject: 'maths',
  source: 'numeration',
  level: 'CE1',
  notion: 'Lire, écrire et nommer les nombres jusqu\'à 1 000',
  theme: 'nombres',
  attendu: 'Lire, écrire et nommer les nombres jusqu\'à 1 000.',
  attenduId: 'ce1-nb-lire',
  summary:
    'Un nombre à trois chiffres se lit en trois morceaux : les centaines, puis les dizaines, puis les unités. 234 se dit « deux cent trente-quatre ». Après 999 vient 1 000, mille.',
  minutes: 7,
  exercises: [
    {
      id: 'maths-nombres-1000-choice-1',
      kind: 'choice',
      prompt: 'Comment s\'écrit « deux cent trente-quatre » en chiffres ?',
      options: ['234', '2034', '324'],
      answer: 0,
      explain: 'Deux cents, c\'est 200. Trente-quatre, c\'est 34. Ensemble : 234, avec trois chiffres seulement.',
    },
    {
      id: 'maths-nombres-1000-tf-1',
      kind: 'truefalse',
      statement: '« Sept cent dix » s\'écrit 710.',
      answer: true,
      explain: 'Sept cents, c\'est 700, et dix de plus : 710.',
    },
    {
      id: 'maths-nombres-1000-match-1',
      kind: 'match',
      prompt: 'Relie chaque nombre à son nom avant la fin du chrono',
      seconds: 45,
      pairs: [
        { a: '156', b: 'cent cinquante-six' },
        { a: '400', b: 'quatre cents' },
        { a: '82', b: 'quatre-vingt-deux' },
        { a: '710', b: 'sept cent dix' },
        { a: '305', b: 'trois cent cinq' },
      ],
      explain: 'Lis le chiffre de gauche avec « cent », puis le reste comme un nombre à deux chiffres.',
    },
    {
      id: 'maths-nombres-1000-line-1',
      kind: 'numberline',
      prompt: 'Place le nombre 600',
      min: 0,
      max: 1000,
      step: 100,
      answer: 600,
      explain: '600, c\'est 6 centaines : six graduations après 0.',
    },
    {
      id: 'maths-nombres-1000-blanks-1',
      kind: 'blanks',
      prompt: 'Complète le nom du nombre 568',
      text: 'Le nombre 568 s\'écrit {{cinq}} cent {{soixante-huit}}.',
      distractors: ['six', 'cinquante-huit'],
      explain: '5 centaines, ça se dit « cinq cent ». Puis 68, « soixante-huit ».',
    },
    {
      id: 'maths-nombres-1000-sort-1',
      kind: 'sort',
      prompt: 'Range chaque nombre dans la bonne boîte',
      boxes: ['Moins de 500', 'Plus de 500'],
      items: [
        { word: '320', box: 0 },
        { word: '750', box: 1 },
        { word: '499', box: 0 },
        { word: '501', box: 1 },
        { word: '900', box: 1 },
        { word: '180', box: 0 },
      ],
      explain: 'Regarde d\'abord le chiffre des centaines : 4 centaines ou moins, c\'est moins de 500.',
    },
    {
      id: 'maths-nombres-1000-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a mal écrit le nombre, corrige-le',
      words: ['Trois', 'cent', 'quarante', '=', '304'],
      wrongIndex: 4,
      correct: '340',
      distractors: ['304', '3040'],
      explain: 'Trois cent quarante, c\'est 300 + 40 = 340. Le 0 des unités reste à droite.',
    },
    {
      id: 'maths-nombres-1000-choice-2',
      kind: 'choice',
      prompt: 'Quel nombre s\'écrit « quatre-vingt-dix-neuf » ?',
      options: ['909', '99', '990'],
      answer: 1,
      explain: 'Quatre-vingt-dix-neuf, c\'est 80 + 19 = 99. Juste avant 100, pas de centaine.',
    },
    {
      id: 'maths-nombres-1000-tf-2',
      kind: 'truefalse',
      statement: 'Le nombre 999 vient juste avant 1 000.',
      answer: true,
      explain: 'Oui : 999 + 1 = 1 000. Mille, c\'est dix centaines.',
    },
    {
      id: 'maths-nombres-1000-speed-1',
      kind: 'speed',
      prompt: 'Calcul éclair : des centaines',
      seconds: 45,
      target: 5,
      items: [
        { q: '200 + 100', a: 300 },
        { q: '450 + 100', a: 550 },
        { q: '300 + 200', a: 500 },
        { q: '100 + 100', a: 200 },
        { q: '700 + 100', a: 800 },
        { q: '50 + 100', a: 150 },
        { q: '600 + 300', a: 900 },
        { q: '250 + 100', a: 350 },
      ],
      explain: 'Pas grave : ajouter 100, c\'est ajouter une centaine, seul le chiffre de gauche change.',
    },
  ],
};

const CENTAINES: Lesson = {
  id: 'maths-centaines',
  title: 'Centaines, dizaines, unités',
  subject: 'maths',
  source: 'numeration',
  level: 'CE1',
  notion: 'Comprendre les centaines, les dizaines et les unités, décomposer un nombre',
  theme: 'nombres',
  attendu: 'Comprendre les dizaines, les centaines et les unités, et décomposer un nombre.',
  attenduId: 'ce1-nb-dizaines',
  summary:
    'Dans 347, le 3 compte les centaines, le 4 les dizaines et le 7 les unités. On peut l\'écrire 300 + 40 + 7. Dix unités font une dizaine, dix dizaines font une centaine.',
  minutes: 7,
  exercises: [
    {
      id: 'maths-centaines-qty-1',
      kind: 'quantity',
      prompt: 'Fabrique le nombre 47 avec des barres de dix et des cubes',
      target: 47,
      tens: true,
      explain: '47, c\'est 4 dizaines et 7 unités : quatre barres et sept cubes.',
    },
    {
      id: 'maths-centaines-qty-2',
      kind: 'quantity',
      prompt: 'Fabrique le nombre 83',
      target: 83,
      tens: true,
      explain: '83, c\'est 8 barres de dix et 3 cubes.',
    },
    {
      id: 'maths-centaines-choice-1',
      kind: 'choice',
      prompt: 'Combien de centaines dans 347 ?',
      options: ['4', '3', '7'],
      answer: 1,
      explain: 'Le chiffre tout à gauche compte les centaines : 3 centaines, c\'est 300.',
    },
    {
      id: 'maths-centaines-blanks-1',
      kind: 'blanks',
      prompt: 'Décompose le nombre',
      text: '347 = {{300}} + {{40}} + {{7}}',
      distractors: ['30', '400'],
      explain: '3 centaines font 300, 4 dizaines font 40, et il reste 7 unités.',
    },
    {
      id: 'maths-centaines-tf-1',
      kind: 'truefalse',
      statement: 'Dans 805, le chiffre des dizaines est 0.',
      answer: true,
      explain: 'Oui : 805, c\'est 8 centaines, 0 dizaine et 5 unités. Le 0 garde la place des dizaines.',
    },
    {
      id: 'maths-centaines-choice-2',
      kind: 'choice',
      prompt: 'Quel nombre vaut 500 + 20 + 6 ?',
      options: ['526', '5206', '562'],
      answer: 0,
      explain: '5 centaines, 2 dizaines, 6 unités : 526. On écrit un seul chiffre par place.',
    },
    {
      id: 'maths-centaines-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a mal décomposé, corrige-le',
      words: ['672', '=', '600', '+', '7', '+', '2'],
      wrongIndex: 4,
      correct: '70',
      distractors: ['7', '700'],
      explain: 'Le 7 de 672 est au milieu : ce sont 7 dizaines, donc 70.',
    },
    {
      id: 'maths-centaines-sort-1',
      kind: 'sort',
      prompt: 'Où est le 4 dans chaque nombre ?',
      boxes: ['Le 4 compte les unités', 'Le 4 compte les dizaines'],
      items: [
        { word: '254', box: 0 },
        { word: '149', box: 1 },
        { word: '34', box: 0 },
        { word: '840', box: 1 },
        { word: '704', box: 0 },
        { word: '641', box: 1 },
      ],
      explain: 'Le chiffre tout à droite compte les unités, celui juste à sa gauche compte les dizaines.',
    },
    {
      id: 'maths-centaines-blanks-2',
      kind: 'blanks',
      prompt: 'Complète',
      text: 'Le nombre 912 a {{9}} centaines, {{1}} dizaine et {{2}} unités.',
      distractors: ['12', '91'],
      explain: 'On lit de gauche à droite : 9 centaines, 1 dizaine, 2 unités.',
    },
    {
      id: 'maths-centaines-pairs-1',
      kind: 'pairs',
      prompt: 'Retrouve chaque décomposition et son nombre',
      pairs: [
        { a: '2 centaines et 5 unités', b: '205' },
        { a: '4 dizaines et 3 unités', b: '43' },
        { a: '6 centaines et 1 dizaine', b: '610' },
        { a: '3 centaines, 3 dizaines et 3 unités', b: '333' },
      ],
      explain: 'Quand une place est vide, on y met un 0 : 2 centaines et 5 unités, c\'est 205.',
    },
  ],
};

const PAIRS_DOUBLES: Lesson = {
  id: 'maths-pairs-doubles',
  title: 'Pairs, impairs, doubles et moitiés',
  subject: 'maths',
  source: 'numeration',
  level: 'CE1',
  notion: 'Reconnaître les nombres pairs et impairs, calculer les doubles et les moitiés',
  theme: 'nombres',
  attendu: 'Reconnaître les nombres pairs et impairs, les doubles et les moitiés.',
  attenduId: 'ce1-nb-pairs',
  summary:
    'Un nombre pair finit par 0, 2, 4, 6 ou 8 : on peut le partager en deux parts égales. Le double, c\'est deux fois le nombre ; la moitié, c\'est le partager en deux.',
  minutes: 6,
  exercises: [
    {
      id: 'maths-pairs-doubles-sort-1',
      kind: 'sort',
      prompt: 'Pair ou impair ? Range chaque nombre',
      boxes: ['Pair', 'Impair'],
      items: [
        { word: '8', box: 0 },
        { word: '13', box: 1 },
        { word: '20', box: 0 },
        { word: '7', box: 1 },
        { word: '16', box: 0 },
        { word: '31', box: 1 },
      ],
      explain: 'Regarde le dernier chiffre : 0, 2, 4, 6, 8, c\'est pair. 1, 3, 5, 7, 9, c\'est impair.',
    },
    {
      id: 'maths-pairs-doubles-choice-1',
      kind: 'choice',
      prompt: 'Quel est le double de 7 ?',
      options: ['12', '14', '16'],
      answer: 1,
      explain: 'Le double de 7, c\'est 7 + 7 = 14.',
    },
    {
      id: 'maths-pairs-doubles-count-1',
      kind: 'count',
      prompt: 'Compte les objets. Peux-tu les mettre deux par deux ?',
      emoji: '⭐',
      answer: 12,
      options: [10, 11, 12, 14],
      explain: 'Il y en a 12. C\'est pair : six paires, aucun objet tout seul.',
    },
    {
      id: 'maths-pairs-doubles-tf-1',
      kind: 'truefalse',
      statement: '15 est un nombre pair.',
      answer: false,
      explain: '15 finit par 5 : il est impair. Si on le partage en deux, il reste un tout seul.',
    },
    {
      id: 'maths-pairs-doubles-blanks-1',
      kind: 'blanks',
      prompt: 'Complète',
      text: 'La moitié de 18, c\'est {{9}}. Le double de 9, c\'est {{18}}.',
      distractors: ['8', '16'],
      explain: '9 + 9 = 18, donc la moitié de 18 est 9. Double et moitié, c\'est l\'aller et le retour.',
    },
    {
      id: 'maths-pairs-doubles-pairs-1',
      kind: 'pairs',
      prompt: 'Retrouve chaque question et sa réponse',
      pairs: [
        { a: 'Double de 6', b: '12' },
        { a: 'Double de 10', b: '20' },
        { a: 'Moitié de 8', b: '4' },
        { a: 'Moitié de 20', b: '10' },
        { a: 'Double de 25', b: '50' },
      ],
      explain: 'Pour le double, j\'ajoute le nombre à lui-même. Pour la moitié, je cherche le nombre qui, doublé, redonne le départ.',
    },
    {
      id: 'maths-pairs-doubles-fix-1',
      kind: 'fix',
      prompt: 'Gribouille s\'est trompé, corrige-le',
      words: ['Double', 'de', '8', '=', '18'],
      wrongIndex: 4,
      correct: '16',
      distractors: ['18', '14'],
      explain: '8 + 8 = 16. 18, ce serait le double de 9.',
    },
    {
      id: 'maths-pairs-doubles-choice-2',
      kind: 'choice',
      prompt: 'Quelle est la moitié de 30 ?',
      options: ['20', '10', '15'],
      answer: 2,
      explain: '15 + 15 = 30, donc la moitié de 30 est 15.',
    },
    {
      id: 'maths-pairs-doubles-tf-2',
      kind: 'truefalse',
      statement: 'Un nombre qui finit par 0 est toujours pair.',
      answer: true,
      explain: 'Oui : 10, 20, 30... on peut toujours les partager en deux parts égales.',
    },
    {
      id: 'maths-pairs-doubles-speed-1',
      kind: 'speed',
      prompt: 'Calcul éclair : doubles et moitiés',
      seconds: 45,
      target: 5,
      items: [
        { q: 'Double de 4', a: 8 },
        { q: 'Double de 9', a: 18 },
        { q: 'Moitié de 10', a: 5 },
        { q: 'Double de 15', a: 30 },
        { q: 'Moitié de 16', a: 8 },
        { q: 'Double de 50', a: 100 },
        { q: 'Moitié de 40', a: 20 },
        { q: 'Double de 12', a: 24 },
      ],
      explain: 'Pas grave : les doubles rentrent vite quand on les répète. On y revient demain.',
    },
  ],
};

const ADDITION_POSEE: Lesson = {
  id: 'maths-addition-posee',
  title: 'L\'addition posée',
  subject: 'maths',
  source: 'calcul',
  level: 'CE1',
  notion: 'Additionner en ligne et poser une addition avec retenue',
  theme: 'calcul',
  attendu: 'Additionner et soustraire mentalement et en posant l\'opération.',
  attenduId: 'ce1-calc-add',
  summary:
    'Pour poser une addition, j\'aligne les unités sous les unités et les dizaines sous les dizaines. Je commence par les unités. Si ça dépasse 9, j\'écris le chiffre des unités et je retiens 1 dizaine.',
  minutes: 7,
  exercises: [
    {
      id: 'maths-addition-posee-choice-1',
      kind: 'choice',
      prompt: 'Combien font 34 + 20 ?',
      options: ['54', '56', '44'],
      answer: 0,
      explain: 'J\'ajoute 2 dizaines à 34 : 44, 54. Les unités ne bougent pas.',
    },
    {
      id: 'maths-addition-posee-line-1',
      kind: 'numberline',
      prompt: 'Place le résultat de 40 + 30',
      min: 0,
      max: 100,
      step: 10,
      answer: 70,
      explain: '4 dizaines et 3 dizaines, ça fait 7 dizaines : 70.',
    },
    {
      id: 'maths-addition-posee-blanks-1',
      kind: 'blanks',
      prompt: 'Complète la règle',
      text: 'Pour poser 36 + 27, j\'aligne les {{unités}} sous les unités et les {{dizaines}} sous les dizaines.',
      distractors: ['centaines'],
      explain: 'Chaque chiffre a sa colonne : les unités à droite, les dizaines à gauche.',
    },
    {
      id: 'maths-addition-posee-tf-1',
      kind: 'truefalse',
      statement: 'Dans 36 + 27, 6 + 7 = 13 : j\'écris 3 et je retiens 1.',
      answer: true,
      explain: 'Oui : 13, c\'est 1 dizaine et 3 unités. J\'écris 3 et la dizaine part dans la colonne d\'à côté.',
    },
    {
      id: 'maths-addition-posee-choice-2',
      kind: 'choice',
      prompt: 'Combien font 36 + 27 ?',
      options: ['53', '63', '64'],
      answer: 1,
      explain: '6 + 7 = 13, j\'écris 3 et je retiens 1. Puis 3 + 2 + 1 = 6. Résultat : 63.',
    },
    {
      id: 'maths-addition-posee-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a oublié quelque chose, corrige-le',
      words: ['48', '+', '25', '=', '63'],
      wrongIndex: 4,
      correct: '73',
      distractors: ['63', '72'],
      explain: '8 + 5 = 13, on retient 1. Gribouille a oublié la retenue : 4 + 2 + 1 = 7, donc 73.',
    },
    {
      id: 'maths-addition-posee-match-1',
      kind: 'match',
      prompt: 'Relie chaque addition à son résultat avant la fin du chrono',
      seconds: 40,
      pairs: [
        { a: '25 + 25', b: '50' },
        { a: '18 + 7', b: '25' },
        { a: '40 + 35', b: '75' },
        { a: '56 + 9', b: '65' },
        { a: '33 + 33', b: '66' },
      ],
      explain: 'Pour aller vite, ajoute d\'abord les dizaines, puis les unités.',
    },
    {
      id: 'maths-addition-posee-blanks-2',
      kind: 'blanks',
      prompt: 'Pose 58 + 36 étape par étape',
      text: '8 + 6 = {{14}}, j\'écris 4 et je retiens {{1}}. Puis 5 + 3 + 1 = {{9}}. Résultat : {{94}}.',
      distractors: ['84', '2'],
      explain: 'Les unités d\'abord, la retenue va avec les dizaines, et on lit le résultat : 94.',
    },
    {
      id: 'maths-addition-posee-tf-2',
      kind: 'truefalse',
      statement: '45 + 38 = 83',
      answer: true,
      explain: '5 + 8 = 13, j\'écris 3 et je retiens 1. 4 + 3 + 1 = 8. Ça fait bien 83.',
    },
    {
      id: 'maths-addition-posee-speed-1',
      kind: 'speed',
      prompt: 'Calcul éclair : additions',
      seconds: 45,
      target: 5,
      items: [
        { q: '34 + 20', a: 54 },
        { q: '15 + 15', a: 30 },
        { q: '27 + 3', a: 30 },
        { q: '50 + 46', a: 96 },
        { q: '19 + 6', a: 25 },
        { q: '42 + 30', a: 72 },
        { q: '8 + 9', a: 17 },
        { q: '63 + 7', a: 70 },
      ],
      explain: 'Pas grave : on s\'entraîne un peu chaque jour et ça devient automatique.',
    },
  ],
};

const SOUSTRACTION: Lesson = {
  id: 'maths-soustraction',
  title: 'La soustraction',
  subject: 'maths',
  source: 'calcul',
  level: 'CE1',
  notion: 'Soustraire mentalement et poser une soustraction sans puis avec retenue',
  theme: 'calcul',
  attendu: 'Additionner et soustraire mentalement et en posant l\'opération.',
  attenduId: 'ce1-calc-add',
  summary:
    'Soustraire, c\'est enlever. Je commence par les unités. Si je n\'ai pas assez d\'unités, je casse une dizaine pour en avoir dix de plus, et je n\'oublie pas de l\'enlever dans la colonne des dizaines.',
  minutes: 7,
  exercises: [
    {
      id: 'maths-soustraction-choice-1',
      kind: 'choice',
      prompt: 'Combien font 58 moins 20 ?',
      options: ['38', '48', '36'],
      answer: 0,
      explain: 'J\'enlève 2 dizaines à 58 : 48, 38. Les unités ne changent pas.',
    },
    {
      id: 'maths-soustraction-line-1',
      kind: 'numberline',
      prompt: 'Place le résultat de 70 moins 30',
      min: 0,
      max: 100,
      step: 10,
      answer: 40,
      explain: '7 dizaines moins 3 dizaines, il en reste 4 : 40.',
    },
    {
      id: 'maths-soustraction-blanks-1',
      kind: 'blanks',
      prompt: 'Calcule 64 moins 21 en deux étapes',
      text: 'Je retire d\'abord les dizaines : 64 moins 20 = {{44}}. Puis je retire 1 : {{43}}.',
      distractors: ['42', '45'],
      explain: 'Enlever 21, c\'est enlever 20 puis encore 1.',
    },
    {
      id: 'maths-soustraction-tf-1',
      kind: 'truefalse',
      statement: '83 moins 5 = 78',
      answer: true,
      explain: 'De 83, je recule de 3 jusqu\'à 80, puis encore de 2 : 78.',
    },
    {
      id: 'maths-soustraction-fix-1',
      kind: 'fix',
      prompt: 'Gribouille s\'est trompé, corrige-le',
      words: ['75', '−', '32', '=', '47'],
      wrongIndex: 4,
      correct: '43',
      distractors: ['47', '53'],
      explain: '5 moins 2 = 3 et 7 moins 3 = 4 : ça fait 43. Gribouille a mélangé les chiffres.',
    },
    {
      id: 'maths-soustraction-choice-2',
      kind: 'choice',
      prompt: 'Combien font 52 moins 17 ?',
      options: ['45', '35', '34'],
      answer: 1,
      explain: '2 moins 7, impossible. Je casse une dizaine : 12 moins 7 = 5. Il reste 4 dizaines, 4 moins 1 = 3. Résultat : 35.',
    },
    {
      id: 'maths-soustraction-pairs-1',
      kind: 'pairs',
      prompt: 'Retrouve chaque soustraction et son résultat',
      pairs: [
        { a: '30 − 10', b: '20' },
        { a: '45 − 5', b: '40' },
        { a: '20 − 9', b: '11' },
        { a: '100 − 50', b: '50' },
        { a: '36 − 6', b: '30' },
      ],
      explain: 'Enlever des dizaines entières ou revenir au nombre rond, c\'est le plus rapide.',
    },
    {
      id: 'maths-soustraction-blanks-2',
      kind: 'blanks',
      prompt: 'Pose 81 moins 46 étape par étape',
      text: '1 moins 6, impossible. Je prends une dizaine : 11 moins 6 = {{5}}. Il reste 7 dizaines : 7 moins 4 = {{3}}. Résultat : {{35}}.',
      distractors: ['4', '45'],
      explain: 'Quand je casse une dizaine, le 8 devient 7. C\'est la retenue de la soustraction.',
    },
    {
      id: 'maths-soustraction-tf-2',
      kind: 'truefalse',
      statement: '60 moins 25 = 45',
      answer: false,
      explain: '60 moins 20 = 40, puis moins 5 = 35. Pas 45.',
    },
    {
      id: 'maths-soustraction-speed-1',
      kind: 'speed',
      prompt: 'Calcul éclair : soustractions',
      seconds: 45,
      target: 5,
      items: [
        { q: '50 − 20', a: 30 },
        { q: '18 − 9', a: 9 },
        { q: '47 − 7', a: 40 },
        { q: '90 − 40', a: 50 },
        { q: '25 − 5', a: 20 },
        { q: '33 − 10', a: 23 },
        { q: '14 − 6', a: 8 },
        { q: '76 − 30', a: 46 },
      ],
      explain: 'Pas grave : enlever des dizaines, puis des unités, et ça vient tout seul.',
    },
  ],
};

const TABLES_3_4: Lesson = {
  id: 'maths-tables-3-4',
  title: 'Les tables de 3 et de 4',
  subject: 'maths',
  source: 'calcul',
  level: 'CE1',
  notion: 'Mémoriser les tables de multiplication de 3 et de 4',
  theme: 'calcul',
  attendu: 'Connaître les tables de multiplication de 2, 3, 4 et 5.',
  attenduId: 'ce1-calc-tables',
  summary:
    'Multiplier par 3, c\'est compter de 3 en 3 : 3, 6, 9, 12... Multiplier par 4, c\'est doubler deux fois : 4 × 6, c\'est le double de 12, donc 24.',
  minutes: 6,
  exercises: [
    {
      id: 'maths-tables-3-4-count-1',
      kind: 'count',
      prompt: 'Compte les objets : il y a 3 rangées de 4',
      emoji: '🧱',
      answer: 12,
      options: [9, 12, 15],
      explain: '3 rangées de 4, c\'est 4 + 4 + 4 = 12. On écrit 3 × 4 = 12.',
    },
    {
      id: 'maths-tables-3-4-choice-1',
      kind: 'choice',
      prompt: 'Combien font 3 × 5 ?',
      options: ['12', '15', '18'],
      answer: 1,
      explain: '3, 6, 9, 12, 15 : cinq sauts de 3, ça fait 15.',
    },
    {
      id: 'maths-tables-3-4-pairs-1',
      kind: 'pairs',
      prompt: 'Retrouve chaque calcul et son résultat',
      pairs: [
        { a: '3 × 2', b: '6' },
        { a: '4 × 3', b: '12' },
        { a: '3 × 7', b: '21' },
        { a: '4 × 5', b: '20' },
        { a: '3 × 9', b: '27' },
        { a: '4 × 8', b: '32' },
      ],
      explain: 'Les résultats de la table de 4 sont toujours pairs. Ceux de la table de 3 alternent pair, impair.',
    },
    {
      id: 'maths-tables-3-4-tf-1',
      kind: 'truefalse',
      statement: '4 × 6 = 24',
      answer: true,
      explain: 'Le double de 6, c\'est 12. Le double de 12, c\'est 24.',
    },
    {
      id: 'maths-tables-3-4-tf-2',
      kind: 'truefalse',
      statement: '3 × 8 = 21',
      answer: false,
      explain: '3 × 8, c\'est 8 + 8 + 8 = 24. 21, c\'est 3 × 7.',
    },
    {
      id: 'maths-tables-3-4-fix-1',
      kind: 'fix',
      prompt: 'Gribouille s\'est trompé dans son calcul, corrige-le',
      words: ['4', '×', '7', '=', '24'],
      wrongIndex: 4,
      correct: '28',
      distractors: ['24', '27'],
      explain: '4 × 7 = 28 : le double de 7 est 14, le double de 14 est 28.',
    },
    {
      id: 'maths-tables-3-4-sort-1',
      kind: 'sort',
      prompt: 'Dans quelle table se trouve chaque nombre ?',
      boxes: ['Table de 3', 'Table de 4'],
      items: [
        { word: '9', box: 0 },
        { word: '16', box: 1 },
        { word: '21', box: 0 },
        { word: '28', box: 1 },
        { word: '15', box: 0 },
        { word: '32', box: 1 },
      ],
      explain: 'Compte de 3 en 3 : 3, 6, 9, 12, 15, 18, 21. Puis de 4 en 4 : 4, 8, 12, 16, 20, 24, 28, 32.',
    },
    {
      id: 'maths-tables-3-4-card-1',
      kind: 'flashcard',
      prompt: 'Dis le résultat, puis vérifie',
      front: '4 × 9',
      back: '36',
      explain: '4 × 9 = 36. Astuce : 4 × 10 = 40, et j\'enlève un 4.',
    },
    {
      id: 'maths-tables-3-4-blanks-1',
      kind: 'blanks',
      prompt: 'Complète',
      text: '3 × 6 = {{18}} et 4 × 6 = {{24}}',
      distractors: ['21', '20'],
      explain: '4 × 6, c\'est 3 × 6 plus un 6 de plus : 18 + 6 = 24.',
    },
    {
      id: 'maths-tables-3-4-speed-1',
      kind: 'speed',
      prompt: 'Calcul éclair : tables de 3 et de 4',
      seconds: 45,
      target: 6,
      items: [
        { q: '3 × 4', a: 12 },
        { q: '4 × 2', a: 8 },
        { q: '3 × 6', a: 18 },
        { q: '4 × 5', a: 20 },
        { q: '3 × 3', a: 9 },
        { q: '4 × 10', a: 40 },
        { q: '3 × 8', a: 24 },
        { q: '4 × 4', a: 16 },
        { q: '3 × 10', a: 30 },
      ],
      explain: 'Pas grave : les tables rentrent en les répétant un peu chaque jour.',
    },
  ],
};

const PROBLEMES: Lesson = {
  id: 'maths-problemes',
  title: 'Petits problèmes',
  subject: 'maths',
  source: 'calcul',
  level: 'CE1',
  notion: 'Résoudre des problèmes en une ou deux étapes',
  theme: 'calcul',
  attendu: 'Résoudre des problèmes en une ou deux étapes avec les quatre opérations.',
  attenduId: 'ce1-calc-problemes',
  summary:
    'Pour résoudre un problème, je lis l\'histoire, je cherche ce qu\'on me demande, puis je choisis l\'opération. « En tout » ou « en plus », c\'est une addition. « Il reste » ou « il en perd », c\'est une soustraction.',
  minutes: 8,
  exercises: [
    {
      id: 'maths-problemes-choice-1',
      kind: 'choice',
      prompt: 'Léa a 12 billes. Elle en gagne 5. Combien en a-t-elle maintenant ?',
      options: ['17', '7', '15'],
      answer: 0,
      explain: 'Elle en gagne, elle en a plus : 12 + 5 = 17.',
    },
    {
      id: 'maths-problemes-choice-2',
      kind: 'choice',
      prompt: 'Tom a 20 images. Il en donne 8 à sa sœur. Combien lui en reste-t-il ?',
      options: ['28', '12', '13'],
      answer: 1,
      explain: 'Il en donne, il en a moins : 20 moins 8 = 12.',
    },
    {
      id: 'maths-problemes-sort-1',
      kind: 'sort',
      prompt: 'Addition ou soustraction ? Range chaque indice',
      boxes: ['Addition', 'Soustraction'],
      items: [
        { word: 'Combien en tout ?', box: 0 },
        { word: 'Combien il en reste ?', box: 1 },
        { word: 'Elle en gagne 5', box: 0 },
        { word: 'Il en perd 3', box: 1 },
        { word: 'On en ajoute 10', box: 0 },
        { word: 'On en enlève 4', box: 1 },
      ],
      explain: 'Gagner, ajouter, en tout : on additionne. Perdre, enlever, il reste : on soustrait.',
    },
    {
      id: 'maths-problemes-count-1',
      kind: 'count',
      prompt: 'Il y a 3 paniers de 5 pommes. Compte toutes les pommes',
      emoji: '🍎',
      answer: 15,
      options: [12, 15, 18],
      explain: '3 paniers de 5, c\'est 5 + 5 + 5 = 15, ou 3 × 5 = 15.',
    },
    {
      id: 'maths-problemes-blanks-1',
      kind: 'blanks',
      prompt: 'Un problème en deux étapes : complète',
      text: 'Dans la classe, il y a 14 filles et 12 garçons, donc {{26}} élèves en tout. Aujourd\'hui, 6 sont absents : il y a {{20}} élèves présents.',
      distractors: ['24', '18'],
      explain: 'Première étape : 14 + 12 = 26. Deuxième étape : 26 moins 6 = 20.',
    },
    {
      id: 'maths-problemes-tf-1',
      kind: 'truefalse',
      statement: 'Un paquet de gâteaux coûte 3 euros. Pour 2 paquets, je paie 6 euros.',
      answer: true,
      explain: '2 paquets à 3 euros : 3 + 3 = 6 euros, ou 2 × 3.',
    },
    {
      id: 'maths-problemes-choice-3',
      kind: 'choice',
      prompt: 'Nina partage 12 bonbons entre 3 amis, chacun en a autant. Combien chacun en reçoit-il ?',
      options: ['3', '4', '6'],
      answer: 1,
      explain: '4 + 4 + 4 = 12 : chaque ami reçoit 4 bonbons. Un partage équitable, c\'est la même quantité pour tous.',
    },
    {
      id: 'maths-problemes-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a 18 cartes et en reçoit 7. Corrige son calcul',
      words: ['18', '+', '7', '=', '24'],
      wrongIndex: 4,
      correct: '25',
      distractors: ['24', '26'],
      explain: '18 + 7 : j\'ajoute 2 pour aller à 20, puis encore 5 : 25.',
    },
    {
      id: 'maths-problemes-tf-2',
      kind: 'truefalse',
      statement: 'Samir a 30 euros. Il achète un livre à 12 euros et un jeu à 10 euros. Il lui reste 8 euros.',
      answer: true,
      explain: 'Il dépense 12 + 10 = 22 euros. 30 moins 22 = 8 euros. Deux étapes, et c\'est juste.',
    },
    {
      id: 'maths-problemes-card-1',
      kind: 'flashcard',
      prompt: 'Les mots qui aident',
      front: 'Quels mots d\'un problème montrent qu\'il faut faire une addition ?',
      back: '« En tout », « en plus », « il gagne », « on ajoute ».',
      explain: 'Et pour la soustraction : « il reste », « il perd », « on enlève ».',
    },
  ],
};

const LONGUEURS: Lesson = {
  id: 'maths-longueurs',
  title: 'Centimètres et mètres',
  subject: 'maths',
  source: 'lecon',
  level: 'CE1',
  notion: 'Mesurer et comparer des longueurs en centimètres et en mètres',
  theme: 'grandeurs',
  attendu: 'Mesurer et comparer des longueurs en centimètres et en mètres.',
  attenduId: 'ce1-gm-longueurs',
  summary:
    'On mesure les petites longueurs en centimètres avec une règle, et les grandes en mètres. 1 mètre, c\'est 100 centimètres. Pour comparer, on met tout dans la même unité.',
  minutes: 6,
  exercises: [
    {
      id: 'maths-longueurs-choice-1',
      kind: 'choice',
      prompt: 'Avec quoi mesure-t-on la longueur d\'un crayon ?',
      options: ['Une balance', 'Une règle', 'Une horloge'],
      answer: 1,
      explain: 'La règle est graduée en centimètres : parfaite pour un crayon.',
    },
    {
      id: 'maths-longueurs-sort-1',
      kind: 'sort',
      prompt: 'En centimètres ou en mètres ? Range chaque longueur',
      boxes: ['Centimètres', 'Mètres'],
      items: [
        { word: 'une gomme', box: 0 },
        { word: 'un terrain de foot', box: 1 },
        { word: 'un doigt', box: 0 },
        { word: 'la hauteur d\'une maison', box: 1 },
        { word: 'une fourchette', box: 0 },
        { word: 'la longueur d\'un bus', box: 1 },
      ],
      explain: 'Ce qui tient dans la main se mesure en centimètres. Ce qui est plus grand que toi, en mètres.',
    },
    {
      id: 'maths-longueurs-tf-1',
      kind: 'truefalse',
      statement: '1 mètre = 100 centimètres.',
      answer: true,
      explain: 'Oui : dans un mètre, il y a cent centimètres. Cent, comme dans « centimètre ».',
    },
    {
      id: 'maths-longueurs-line-1',
      kind: 'numberline',
      prompt: 'Place 50 centimètres sur la règle qui va de 0 à 100',
      min: 0,
      max: 100,
      step: 10,
      answer: 50,
      explain: '50 centimètres, c\'est la moitié d\'un mètre : pile au milieu.',
    },
    {
      id: 'maths-longueurs-blanks-1',
      kind: 'blanks',
      prompt: 'Complète',
      text: '2 mètres, c\'est {{200}} centimètres. Un demi-mètre, c\'est {{50}} centimètres.',
      distractors: ['20', '100'],
      explain: '1 mètre = 100 centimètres, donc 2 mètres = 200 centimètres, et la moitié de 100, c\'est 50.',
    },
    {
      id: 'maths-longueurs-choice-2',
      kind: 'choice',
      prompt: 'Quelle longueur est la plus grande ?',
      options: ['80 centimètres', '1 mètre', '95 centimètres'],
      answer: 1,
      explain: '1 mètre, c\'est 100 centimètres : plus que 80 et plus que 95.',
    },
    {
      id: 'maths-longueurs-fix-1',
      kind: 'fix',
      prompt: 'Gribouille s\'est trompé, corrige-le',
      words: ['1', 'm', '=', '10', 'cm'],
      wrongIndex: 3,
      correct: '100',
      distractors: ['10', '1000'],
      explain: 'Un mètre, c\'est 100 centimètres, pas 10. Regarde une règle d\'un mètre : elle va jusqu\'à 100.',
    },
    {
      id: 'maths-longueurs-pairs-1',
      kind: 'pairs',
      prompt: 'Retrouve les longueurs égales',
      pairs: [
        { a: '1 m', b: '100 cm' },
        { a: '3 m', b: '300 cm' },
        { a: '1 m 50 cm', b: '150 cm' },
        { a: '2 m', b: '200 cm' },
      ],
      explain: 'Chaque mètre vaut 100 centimètres : 1 m 50 cm, c\'est 100 + 50 = 150 cm.',
    },
    {
      id: 'maths-longueurs-tf-2',
      kind: 'truefalse',
      statement: 'Un crayon mesure environ 15 mètres.',
      answer: false,
      explain: '15 mètres, c\'est plus long qu\'un bus ! Un crayon mesure environ 15 centimètres.',
    },
    {
      id: 'maths-longueurs-line-2',
      kind: 'numberline',
      prompt: 'Place 1 mètre 20 sur la règle qui va de 0 à 200 centimètres',
      min: 0,
      max: 200,
      step: 20,
      answer: 120,
      explain: '1 mètre 20, c\'est 100 + 20 = 120 centimètres : une graduation après 100.',
    },
  ],
};

const MASSES_LITRES: Lesson = {
  id: 'maths-masses-litres',
  title: 'Grammes, kilos et litres',
  subject: 'maths',
  source: 'lecon',
  level: 'CE1',
  notion: 'Comparer des masses et des contenances en grammes, kilogrammes et litres',
  theme: 'grandeurs',
  attendu: 'Comparer des masses et des contenances (gramme, kilogramme, litre).',
  attenduId: 'ce1-gm-masses',
  summary:
    'La masse, c\'est le poids : on la mesure avec une balance, en grammes pour les choses légères et en kilogrammes pour les lourdes. 1 kilogramme = 1 000 grammes. Le litre sert à mesurer les liquides.',
  minutes: 6,
  exercises: [
    {
      id: 'maths-masses-litres-choice-1',
      kind: 'choice',
      prompt: 'Avec quoi pèse-t-on un paquet de farine ?',
      options: ['Une règle', 'Un verre doseur', 'Une balance'],
      answer: 2,
      explain: 'Pour connaître une masse, on utilise une balance.',
    },
    {
      id: 'maths-masses-litres-sort-1',
      kind: 'sort',
      prompt: 'Léger ou lourd ? Range chaque objet',
      boxes: ['Se pèse en grammes', 'Se pèse en kilogrammes'],
      items: [
        { word: 'une lettre', box: 0 },
        { word: 'un vélo', box: 1 },
        { word: 'une cuillère', box: 0 },
        { word: 'un enfant', box: 1 },
        { word: 'un bonbon', box: 0 },
        { word: 'un sac de pommes de terre', box: 1 },
      ],
      explain: 'Ce qui est léger comme une plume se pèse en grammes. Ce qu\'on porte à deux mains, en kilogrammes.',
    },
    {
      id: 'maths-masses-litres-tf-1',
      kind: 'truefalse',
      statement: '1 kilogramme = 1 000 grammes.',
      answer: true,
      explain: 'Oui : « kilo » veut dire mille. Un kilogramme, c\'est mille grammes.',
    },
    {
      id: 'maths-masses-litres-choice-2',
      kind: 'choice',
      prompt: 'Qu\'est-ce qui est le plus lourd ?',
      options: ['500 grammes', '1 kilogramme', '900 grammes'],
      answer: 1,
      explain: '1 kilogramme, c\'est 1 000 grammes : plus que 500 et plus que 900.',
    },
    {
      id: 'maths-masses-litres-sort-2',
      kind: 'sort',
      prompt: 'Masse ou contenance ? Range chaque chose',
      boxes: ['Une masse, en grammes ou kilos', 'Une contenance, en litres'],
      items: [
        { word: 'l\'eau d\'une bouteille', box: 1 },
        { word: 'un sac de riz', box: 0 },
        { word: 'le jus dans un verre', box: 1 },
        { word: 'un chien', box: 0 },
        { word: 'l\'eau de la baignoire', box: 1 },
        { word: 'un cahier', box: 0 },
      ],
      explain: 'Les liquides se mesurent en litres. Les objets solides se pèsent.',
    },
    {
      id: 'maths-masses-litres-blanks-1',
      kind: 'blanks',
      prompt: 'Complète',
      text: 'Le litre sert à mesurer les {{liquides}}. Le kilogramme sert à mesurer la {{masse}}.',
      distractors: ['longueur', 'heure'],
      explain: 'Litre pour ce qui coule, kilogramme pour ce qui pèse.',
    },
    {
      id: 'maths-masses-litres-fix-1',
      kind: 'fix',
      prompt: 'Gribouille s\'est trompé, corrige-le',
      words: ['1', 'kg', '=', '100', 'g'],
      wrongIndex: 3,
      correct: '1 000',
      distractors: ['100', '10'],
      explain: 'Kilo veut dire mille : 1 kg = 1 000 g.',
    },
    {
      id: 'maths-masses-litres-tf-2',
      kind: 'truefalse',
      statement: 'Une bouteille de 2 litres contient plus d\'eau qu\'une bouteille de 1 litre.',
      answer: true,
      explain: 'Oui : 2 litres, c\'est deux fois 1 litre.',
    },
    {
      id: 'maths-masses-litres-pairs-1',
      kind: 'pairs',
      prompt: 'Retrouve les quantités égales',
      pairs: [
        { a: '2 kg', b: '2 000 g' },
        { a: '1 kg', b: '1 000 g' },
        { a: '500 g + 500 g', b: '1 kilo' },
        { a: '1 litre + 1 litre', b: '2 litres' },
      ],
      explain: 'Deux fois 500 grammes font 1 000 grammes, c\'est-à-dire 1 kilogramme.',
    },
    {
      id: 'maths-masses-litres-tf-3',
      kind: 'truefalse',
      statement: 'Un gramme est plus lourd qu\'un kilogramme.',
      answer: false,
      explain: 'C\'est le contraire : il faut 1 000 grammes pour faire un kilogramme.',
    },
  ],
};

const HEURE: Lesson = {
  id: 'maths-heure',
  title: 'Lire l\'heure',
  subject: 'maths',
  source: 'lecon',
  level: 'CE1',
  notion: 'Lire l\'heure et utiliser les durées en jours, heures et minutes',
  theme: 'grandeurs',
  attendu: 'Lire l\'heure et utiliser les durées (jours, heures, minutes).',
  attenduId: 'ce1-gm-heure',
  summary:
    'La petite aiguille montre les heures, la grande montre les minutes. Grande aiguille sur le 12 : heure pile. Sur le 3 : et quart. Sur le 6 : et demie. Une heure dure 60 minutes, une journée 24 heures.',
  minutes: 7,
  exercises: [
    {
      id: 'maths-heure-choice-1',
      kind: 'choice',
      prompt: 'La petite aiguille est sur le 3 et la grande sur le 12. Quelle heure est-il ?',
      options: ['3 heures', '12 heures', '3 heures et demie'],
      answer: 0,
      explain: 'La petite aiguille dit l\'heure : 3. La grande sur le 12, c\'est l\'heure pile.',
    },
    {
      id: 'maths-heure-tf-1',
      kind: 'truefalse',
      statement: 'Quand la grande aiguille est sur le 6, il est « et demie ».',
      answer: true,
      explain: 'Oui : le 6 est à mi-chemin du tour, la grande aiguille a fait la moitié d\'une heure.',
    },
    {
      id: 'maths-heure-choice-2',
      kind: 'choice',
      prompt: 'La petite aiguille est entre le 7 et le 8, la grande sur le 6. Quelle heure est-il ?',
      options: ['8 heures et demie', '7 heures et demie', '7 heures et quart'],
      answer: 1,
      explain: 'La petite aiguille a dépassé le 7 mais pas atteint le 8 : il est encore 7 heures. La grande sur le 6 : et demie.',
    },
    {
      id: 'maths-heure-blanks-1',
      kind: 'blanks',
      prompt: 'Complète les durées',
      text: 'Une heure dure {{60}} minutes. Une journée dure {{24}} heures. Une semaine dure {{7}} jours.',
      distractors: ['100', '12'],
      explain: '60 minutes dans une heure, 24 heures dans une journée, 7 jours dans une semaine.',
    },
    {
      id: 'maths-heure-sort-1',
      kind: 'sort',
      prompt: 'Chaque durée dans la bonne boîte',
      boxes: ['Moins d\'une heure', 'Plus d\'une heure'],
      items: [
        { word: 'Se brosser les dents', box: 0 },
        { word: 'Une nuit de sommeil', box: 1 },
        { word: 'La récréation', box: 0 },
        { word: 'Un long voyage en train', box: 1 },
        { word: 'Manger une pomme', box: 0 },
        { word: 'Une journée d\'école', box: 1 },
      ],
      explain: 'Se brosser les dents prend 3 minutes. Une nuit dure environ 10 heures.',
    },
    {
      id: 'maths-heure-pairs-1',
      kind: 'pairs',
      prompt: 'Retrouve la position de la grande aiguille et ce qu\'on dit',
      pairs: [
        { a: 'Grande aiguille sur le 12', b: 'Heure pile' },
        { a: 'Grande aiguille sur le 3', b: 'Et quart' },
        { a: 'Grande aiguille sur le 6', b: 'Et demie' },
        { a: 'Grande aiguille sur le 9', b: 'Moins le quart' },
      ],
      explain: 'La grande aiguille fait le tour en une heure : un quart au 3, la moitié au 6, trois quarts au 9.',
    },
    {
      id: 'maths-heure-fix-1',
      kind: 'fix',
      prompt: 'Gribouille s\'est trompé, corrige-le',
      words: ['Une', 'heure', '=', '100', 'minutes'],
      wrongIndex: 3,
      correct: '60',
      distractors: ['100', '30'],
      explain: 'Une heure, c\'est 60 minutes : la grande aiguille passe par 60 petits traits.',
    },
    {
      id: 'maths-heure-tf-2',
      kind: 'truefalse',
      statement: 'Il est 4 heures. Dans 2 heures, il sera 6 heures.',
      answer: true,
      explain: '4 + 2 = 6. On ajoute les heures qui passent.',
    },
    {
      id: 'maths-heure-choice-3',
      kind: 'choice',
      prompt: 'Le film commence à 2 heures et dure 1 heure. À quelle heure finit-il ?',
      options: ['3 heures', '4 heures', '2 heures et demie'],
      answer: 0,
      explain: 'Il commence à 2 heures, une heure passe : il finit à 3 heures.',
    },
    {
      id: 'maths-heure-card-1',
      kind: 'flashcard',
      prompt: 'Les deux aiguilles',
      front: 'Sur une horloge, à quoi sert la petite aiguille ?',
      back: 'Elle montre les heures. La grande aiguille montre les minutes.',
      explain: 'Petite aiguille, petite question : quelle heure ? Grande aiguille : combien de minutes ?',
    },
  ],
};

const MONNAIE: Lesson = {
  id: 'maths-monnaie',
  title: 'Euros et centimes',
  subject: 'maths',
  source: 'lecon',
  level: 'CE1',
  notion: 'Utiliser la monnaie : composer une somme en euros et centimes, rendre la monnaie',
  theme: 'grandeurs',
  attendu: 'Utiliser la monnaie : euros et centimes, rendre la monnaie.',
  attenduId: 'ce1-gm-monnaie',
  summary:
    'Il y a des pièces de 1 et 2 euros, des billets de 5, 10, 20 euros, et des centimes pour les petites sommes. 1 euro = 100 centimes. Rendre la monnaie, c\'est calculer ce qu\'on a donné en trop.',
  minutes: 7,
  exercises: [
    {
      id: 'maths-monnaie-choice-1',
      kind: 'choice',
      prompt: 'Combien de centimes dans 1 euro ?',
      options: ['10', '100', '1 000'],
      answer: 1,
      explain: '1 euro = 100 centimes, comme 1 mètre = 100 centimètres.',
    },
    {
      id: 'maths-monnaie-count-1',
      kind: 'count',
      prompt: 'Compte les pièces de 1 euro. Combien d\'euros ?',
      emoji: '🪙',
      answer: 7,
      options: [6, 7, 8],
      explain: 'Chaque pièce vaut 1 euro : 7 pièces, 7 euros.',
    },
    {
      id: 'maths-monnaie-choice-2',
      kind: 'choice',
      prompt: 'J\'ai un billet de 5 euros et deux pièces de 2 euros. Combien ai-je ?',
      options: ['7 euros', '9 euros', '10 euros'],
      answer: 1,
      explain: '5 + 2 + 2 = 9 euros.',
    },
    {
      id: 'maths-monnaie-blanks-1',
      kind: 'blanks',
      prompt: 'Complète',
      text: 'Un billet de 10 euros, c\'est {{5}} pièces de 2 euros, ou {{2}} billets de 5 euros.',
      distractors: ['10', '4'],
      explain: '2 + 2 + 2 + 2 + 2 = 10, et 5 + 5 = 10. Une même somme, plusieurs façons.',
    },
    {
      id: 'maths-monnaie-pairs-1',
      kind: 'pairs',
      prompt: 'Retrouve les sommes égales',
      pairs: [
        { a: '50 centimes + 50 centimes', b: '1 euro' },
        { a: '2 euros + 2 euros + 1 euro', b: '5 euros' },
        { a: '10 euros + 10 euros', b: '20 euros' },
        { a: '20 centimes + 20 centimes + 10 centimes', b: '50 centimes' },
      ],
      explain: 'Les centimes s\'ajoutent jusqu\'à 100 pour faire 1 euro.',
    },
    {
      id: 'maths-monnaie-tf-1',
      kind: 'truefalse',
      statement: 'Un pain coûte 1 euro 20. Je donne 2 euros. On me rend 80 centimes.',
      answer: true,
      explain: 'De 1 euro 20 à 2 euros, il manque 80 centimes : c\'est la monnaie rendue.',
    },
    {
      id: 'maths-monnaie-choice-3',
      kind: 'choice',
      prompt: 'Un jouet coûte 7 euros. Je paie avec un billet de 10 euros. Combien me rend-on ?',
      options: ['3 euros', '7 euros', '2 euros'],
      answer: 0,
      explain: '10 moins 7 = 3. On me rend 3 euros.',
    },
    {
      id: 'maths-monnaie-fix-1',
      kind: 'fix',
      prompt: 'Gribouille a compté sa tirelire, corrige-le',
      words: ['2 euros', '+', '2 euros', '+', '50 centimes', '=', '5 euros'],
      wrongIndex: 6,
      correct: '4 euros 50',
      distractors: ['5 euros', '4 euros'],
      explain: '2 + 2 = 4 euros, et 50 centimes en plus : 4 euros 50. Il manque 50 centimes pour faire 5 euros.',
    },
    {
      id: 'maths-monnaie-sort-1',
      kind: 'sort',
      prompt: 'Range chaque prix dans la bonne boîte',
      boxes: ['Moins de 5 euros', 'Plus de 5 euros'],
      items: [
        { word: '3 euros 50', box: 0 },
        { word: '8 euros', box: 1 },
        { word: '1 euro 20', box: 0 },
        { word: '5 euros 50', box: 1 },
        { word: '4 euros 99', box: 0 },
        { word: '12 euros', box: 1 },
      ],
      explain: 'Regarde d\'abord les euros. 4 euros 99, c\'est tout près de 5, mais encore en dessous.',
    },
    {
      id: 'maths-monnaie-speed-1',
      kind: 'speed',
      prompt: 'Calcul éclair : la monnaie, en euros',
      seconds: 45,
      target: 5,
      items: [
        { q: '10 € − 3 €', a: 7 },
        { q: '5 € − 2 €', a: 3 },
        { q: '2 € + 2 €', a: 4 },
        { q: '20 € − 15 €', a: 5 },
        { q: '5 € + 5 € + 2 €', a: 12 },
        { q: '50 € − 20 €', a: 30 },
        { q: '10 € − 8 €', a: 2 },
        { q: '2 € + 1 € + 1 €', a: 4 },
      ],
      explain: 'Pas grave : rendre la monnaie, c\'est une soustraction, et ça s\'entraîne.',
    },
  ],
};

const FIGURES: Lesson = {
  id: 'maths-figures',
  title: 'Carré, rectangle, triangle, cercle',
  subject: 'maths',
  source: 'lecon',
  level: 'CE1',
  notion: 'Reconnaître et décrire le carré, le rectangle, le triangle et le cercle',
  theme: 'geometrie',
  attendu: 'Reconnaître et décrire le carré, le rectangle, le triangle et le cercle.',
  attenduId: 'ce1-geo-figures',
  summary:
    'Une figure a des côtés (les traits) et des sommets (les coins). Le triangle a 3 côtés. Le carré a 4 côtés égaux. Le rectangle a 4 côtés, égaux deux à deux. Le cercle est tout rond, sans côté.',
  minutes: 6,
  exercises: [
    {
      id: 'maths-figures-choice-1',
      kind: 'choice',
      prompt: 'Quelle figure a 3 côtés ?',
      options: ['Le carré', 'Le triangle', 'Le cercle'],
      answer: 1,
      explain: '« Tri » veut dire trois : le triangle a 3 côtés et 3 sommets.',
    },
    {
      id: 'maths-figures-sort-1',
      kind: 'sort',
      prompt: 'Combien de côtés ? Range chaque figure',
      boxes: ['4 côtés', '3 côtés', 'Pas de côté'],
      items: [
        { word: 'carré', box: 0 },
        { word: 'triangle', box: 1 },
        { word: 'cercle', box: 2 },
        { word: 'rectangle', box: 0 },
        { word: 'une pièce de monnaie', box: 2 },
        { word: 'une feuille de cahier', box: 0 },
      ],
      explain: 'Le carré et le rectangle ont 4 côtés, le triangle 3, et le cercle n\'a aucun côté droit.',
    },
    {
      id: 'maths-figures-tf-1',
      kind: 'truefalse',
      statement: 'Un carré a 4 côtés de la même longueur.',
      answer: true,
      explain: 'Oui, c\'est ce qui fait un carré : 4 côtés égaux et 4 angles droits.',
    },
    {
      id: 'maths-figures-tf-2',
      kind: 'truefalse',
      statement: 'Un rectangle a 3 sommets.',
      answer: false,
      explain: 'Un rectangle a 4 sommets, un à chaque coin. C\'est le triangle qui en a 3.',
    },
    {
      id: 'maths-figures-blanks-1',
      kind: 'blanks',
      prompt: 'Complète',
      text: 'Le rectangle a {{4}} sommets et ses côtés en face ont la {{même}} longueur. Le triangle a {{3}} sommets.',
      distractors: ['5', '2'],
      explain: 'Dans un rectangle, les côtés qui se font face sont égaux. Compte les coins : 4 pour le rectangle, 3 pour le triangle.',
    },
    {
      id: 'maths-figures-pairs-1',
      kind: 'pairs',
      prompt: 'Retrouve chaque figure et sa description',
      pairs: [
        { a: 'Carré', b: '4 côtés tous égaux' },
        { a: 'Rectangle', b: '4 côtés, égaux deux à deux' },
        { a: 'Triangle', b: '3 côtés' },
        { a: 'Cercle', b: 'Tout rond, aucun côté' },
      ],
      explain: 'Compter les côtés, puis regarder s\'ils sont égaux : ça suffit pour nommer la figure.',
    },
    {
      id: 'maths-figures-fix-1',
      kind: 'fix',
      prompt: 'Gribouille s\'est trompé, corrige-le',
      words: ['Un', 'triangle', 'a', '4', 'sommets.'],
      wrongIndex: 3,
      correct: '3',
      distractors: ['4', '5'],
      explain: 'Tri, trois : un triangle a 3 côtés et donc 3 sommets.',
    },
    {
      id: 'maths-figures-choice-2',
      kind: 'choice',
      prompt: 'J\'ai 4 sommets et 4 angles droits, mais mes côtés ne sont pas tous égaux. Qui suis-je ?',
      options: ['Le carré', 'Le cercle', 'Le rectangle'],
      answer: 2,
      explain: 'Le rectangle : 4 angles droits comme le carré, mais deux côtés longs et deux côtés courts.',
    },
    {
      id: 'maths-figures-tap-1',
      kind: 'tapword',
      prompt: 'Touche le mot qui désigne le coin d\'une figure, là où deux côtés se rejoignent',
      words: ['côté', 'sommet', 'cercle', 'longueur'],
      answer: [1],
      explain: 'Le sommet, c\'est le coin. Le côté, c\'est le trait entre deux sommets.',
    },
    {
      id: 'maths-figures-card-1',
      kind: 'flashcard',
      prompt: 'Carré ou rectangle ?',
      front: 'Quelle est la différence entre un carré et un rectangle ?',
      back: 'Les deux ont 4 angles droits. Le carré a ses 4 côtés égaux ; le rectangle a seulement les côtés en face égaux.',
      explain: 'Un carré est un rectangle très particulier : tous ses côtés sont de la même longueur.',
    },
  ],
};

const ANGLE_DROIT: Lesson = {
  id: 'maths-angle-droit',
  title: 'Règle, équerre et angle droit',
  subject: 'maths',
  source: 'lecon',
  level: 'CE1',
  notion: 'Tracer avec la règle et l\'équerre, repérer un angle droit, reproduire sur quadrillage',
  theme: 'geometrie',
  attendu: 'Tracer avec la règle et l\'équerre, repérer un angle droit, reproduire sur quadrillage.',
  attenduId: 'ce1-geo-tracer',
  summary:
    'La règle sert à tracer des traits bien droits. L\'équerre sert à vérifier un angle droit : le coin d\'une feuille, le coin d\'un carré. Sur un quadrillage, on reproduit une figure en comptant les carreaux.',
  minutes: 6,
  exercises: [
    {
      id: 'maths-angle-droit-choice-1',
      kind: 'choice',
      prompt: 'Quel outil sert à vérifier un angle droit ?',
      options: ['La règle', 'L\'équerre', 'Le compas'],
      answer: 1,
      explain: 'L\'équerre a un coin en angle droit : on le pose sur l\'angle pour vérifier.',
    },
    {
      id: 'maths-angle-droit-tf-1',
      kind: 'truefalse',
      statement: 'Pour tracer un trait bien droit, j\'utilise une règle.',
      answer: true,
      explain: 'Oui : on tient la règle bien à plat et on suit son bord avec le crayon.',
    },
    {
      id: 'maths-angle-droit-sort-1',
      kind: 'sort',
      prompt: 'Angle droit ou pas ? Range chaque chose',
      boxes: ['A des angles droits', 'N\'a pas d\'angle droit'],
      items: [
        { word: 'un carré', box: 0 },
        { word: 'le coin d\'une feuille', box: 0 },
        { word: 'un cercle', box: 1 },
        { word: 'un rectangle', box: 0 },
        { word: 'un toit de maison pointu', box: 1 },
        { word: 'le coin d\'une porte', box: 0 },
      ],
      explain: 'Un angle droit, c\'est le coin d\'une feuille. Un cercle n\'a pas de coin, un toit pointu a un coin trop fermé.',
    },
    {
      id: 'maths-angle-droit-blanks-1',
      kind: 'blanks',
      prompt: 'Complète avec le bon outil',
      text: 'Pour tracer un segment, je place ma {{règle}} et je suis son bord. Pour vérifier un angle droit, je pose le coin de mon {{équerre}}.',
      distractors: ['gomme', 'compas'],
      explain: 'Règle pour tracer droit, équerre pour l\'angle droit.',
    },
    {
      id: 'maths-angle-droit-tf-2',
      kind: 'truefalse',
      statement: 'Un carré a 4 angles droits.',
      answer: true,
      explain: 'Oui : pose ton équerre dans chaque coin du carré, elle rentre pile.',
    },
    {
      id: 'maths-angle-droit-choice-2',
      kind: 'choice',
      prompt: 'Pour reproduire une figure sur un quadrillage, que dois-je compter ?',
      options: ['Les carreaux', 'Les couleurs', 'Les lettres'],
      answer: 0,
      explain: 'On compte les carreaux de chaque trait du modèle, puis on refait les mêmes sur son cahier.',
    },
    {
      id: 'maths-angle-droit-fix-1',
      kind: 'fix',
      prompt: 'Gribouille s\'est trompé, corrige-le',
      words: ['Un', 'rectangle', 'a', '2', 'angles', 'droits.'],
      wrongIndex: 3,
      correct: '4',
      distractors: ['2', '3'],
      explain: 'Un rectangle a 4 coins, et chaque coin est un angle droit.',
    },
    {
      id: 'maths-angle-droit-sentence-1',
      kind: 'sentence',
      prompt: 'Remets la phrase dans l\'ordre',
      words: ['Je', 'trace', 'un', 'trait', 'avec', 'ma', 'règle.'],
      explain: 'Je trace un trait avec ma règle : qui, puis ce qu\'il fait, puis avec quoi.',
    },
    {
      id: 'maths-angle-droit-tap-1',
      kind: 'tapword',
      prompt: 'Touche les deux outils de géométrie',
      words: ['règle', 'ballon', 'équerre', 'cuillère'],
      answer: [0, 2],
      explain: 'La règle et l\'équerre sont dans ta trousse de géométrie. Le ballon et la cuillère, non.',
    },
    {
      id: 'maths-angle-droit-pairs-1',
      kind: 'pairs',
      prompt: 'Retrouve chaque outil et ce qu\'il fait',
      pairs: [
        { a: 'Règle', b: 'Tracer un trait droit' },
        { a: 'Équerre', b: 'Vérifier un angle droit' },
        { a: 'Quadrillage', b: 'Reproduire une figure en comptant les carreaux' },
        { a: 'Gomme', b: 'Effacer un trait raté' },
      ],
      explain: 'Chaque outil a son travail. Et un trait raté, ce n\'est pas grave : la gomme est là pour ça.',
    },
  ],
};

const SOLIDES_ESPACE: Lesson = {
  id: 'maths-solides-espace',
  title: 'Solides et repérage',
  subject: 'maths',
  source: 'lecon',
  level: 'CE1',
  notion: 'Reconnaître le cube, le pavé, la boule, la pyramide et se repérer dans l\'espace',
  theme: 'geometrie',
  attendu: 'Reconnaître le cube, le pavé, la boule, et se repérer dans l\'espace.',
  attenduId: 'ce1-geo-solides',
  summary:
    'Les solides ont du volume : le cube a 6 faces carrées, le pavé 6 faces rectangles, la boule roule, la pyramide a une pointe. Pour se repérer, on dit devant, derrière, à gauche, à droite.',
  minutes: 6,
  exercises: [
    {
      id: 'maths-solides-espace-choice-1',
      kind: 'choice',
      prompt: 'Quel solide roule ?',
      options: ['Le cube', 'La boule', 'La pyramide'],
      answer: 1,
      explain: 'La boule n\'a aucune face plate, elle roule. Le cube et la pyramide se posent sur une face.',
    },
    {
      id: 'maths-solides-espace-sort-1',
      kind: 'sort',
      prompt: 'Cube, pavé ou boule ? Range chaque objet',
      boxes: ['Cube', 'Pavé', 'Boule'],
      items: [
        { word: 'un dé à jouer', box: 0 },
        { word: 'une boîte à chaussures', box: 1 },
        { word: 'un ballon', box: 2 },
        { word: 'une bille', box: 2 },
        { word: 'une brique', box: 1 },
        { word: 'un morceau de sucre', box: 0 },
      ],
      explain: 'Le cube a toutes ses faces carrées, comme un dé. Le pavé est allongé, comme une boîte. La boule est toute ronde.',
    },
    {
      id: 'maths-solides-espace-tf-1',
      kind: 'truefalse',
      statement: 'Un cube a 6 faces carrées.',
      answer: true,
      explain: 'Oui : regarde un dé, il a 6 faces, et chacune est un carré.',
    },
    {
      id: 'maths-solides-espace-blanks-1',
      kind: 'blanks',
      prompt: 'Complète',
      text: 'Le cube a {{6}} faces. La boule n\'a aucune {{face}} plate, c\'est pour ça qu\'elle roule.',
      distractors: ['4', 'sommet'],
      explain: 'Un cube, c\'est 6 faces, 8 sommets, 12 arêtes. La boule, elle, est lisse partout.',
    },
    {
      id: 'maths-solides-espace-tap-1',
      kind: 'tapword',
      prompt: 'Touche le solide qui a une pointe en haut',
      words: ['cube', 'boule', 'pyramide', 'pavé'],
      answer: [2],
      explain: 'La pyramide a une base et des faces qui se rejoignent en une pointe.',
    },
    {
      id: 'maths-solides-espace-choice-2',
      kind: 'choice',
      prompt: 'Je regarde le tableau, la porte est à ma gauche. Si je me retourne, où est la porte ?',
      options: ['À ma droite', 'Devant moi', 'À ma gauche'],
      answer: 0,
      explain: 'Quand je me retourne, la gauche et la droite s\'échangent : la porte passe à ma droite.',
    },
    {
      id: 'maths-solides-espace-tf-2',
      kind: 'truefalse',
      statement: 'Quand je lève la main droite, la main qui reste baissée est la main gauche.',
      answer: true,
      explain: 'Oui : on a une main droite et une main gauche. Astuce : la main gauche fait un L avec le pouce et l\'index.',
    },
    {
      id: 'maths-solides-espace-pairs-1',
      kind: 'pairs',
      prompt: 'Retrouve chaque solide et sa description',
      pairs: [
        { a: 'Cube', b: '6 faces carrées' },
        { a: 'Pavé', b: '6 faces rectangles' },
        { a: 'Boule', b: 'Roule, aucune face plate' },
        { a: 'Pyramide', b: 'Une pointe en haut' },
      ],
      explain: 'Cube et pavé ont tous les deux 6 faces : carrées pour le cube, rectangles pour le pavé.',
    },
    {
      id: 'maths-solides-espace-fix-1',
      kind: 'fix',
      prompt: 'Gribouille s\'est trompé, corrige-le',
      words: ['Un', 'cube', 'a', '4', 'faces.'],
      wrongIndex: 3,
      correct: '6',
      distractors: ['4', '8'],
      explain: 'Un cube a 6 faces : dessus, dessous, devant, derrière, à gauche, à droite.',
    },
    {
      id: 'maths-solides-espace-sentence-1',
      kind: 'sentence',
      prompt: 'Remets la phrase dans l\'ordre',
      words: ['Le', 'chat', 'est', 'devant', 'la', 'porte.'],
      explain: 'Le chat est devant la porte : la porte est derrière le chat.',
    },
  ],
};

export const LESSONS: Lesson[] = [
  NOMBRES_1000,
  CENTAINES,
  PAIRS_DOUBLES,
  ADDITION_POSEE,
  SOUSTRACTION,
  TABLES_3_4,
  PROBLEMES,
  LONGUEURS,
  MASSES_LITRES,
  HEURE,
  MONNAIE,
  FIGURES,
  ANGLE_DROIT,
  SOLIDES_ESPACE,
];
