/**
 * Poésies du domaine public, souvent apprises à l'école. Le parent donne le
 * titre ou l'auteur, Ardoiz retrouve le texte ici, sans internet ni serveur.
 * Seuls des auteurs morts depuis plus de 70 ans figurent dans cette liste :
 * les poètes encore protégés (Prévert, Carême, Desnos...) passent par la
 * photo ou la saisie du parent, pour un usage privé.
 */
export type Poem = {
  id: string;
  title: string;
  author: string;
  /** Pour le parent : à partir de quand on le voit en classe */
  hint: string;
  lines: string[];
};

export const POEMS: Poem[] = [
  {
    id: 'cigale',
    title: 'La Cigale et la Fourmi',
    author: 'Jean de La Fontaine',
    hint: 'dès le CE1',
    lines: [
      'La Cigale, ayant chanté',
      'Tout l\'été,',
      'Se trouva fort dépourvue',
      'Quand la bise fut venue :',
      'Pas un seul petit morceau',
      'De mouche ou de vermisseau.',
      'Elle alla crier famine',
      'Chez la Fourmi sa voisine,',
      'La priant de lui prêter',
      'Quelque grain pour subsister',
      'Jusqu\'à la saison nouvelle.',
      '« Je vous paierai, lui dit-elle,',
      'Avant l\'août, foi d\'animal,',
      'Intérêt et principal. »',
      'La Fourmi n\'est pas prêteuse :',
      'C\'est là son moindre défaut.',
      '« Que faisiez-vous au temps chaud ?',
      'Dit-elle à cette emprunteuse.',
      '— Nuit et jour à tout venant',
      'Je chantais, ne vous déplaise.',
      '— Vous chantiez ? j\'en suis fort aise.',
      'Eh bien ! dansez maintenant. »',
    ],
  },
  {
    id: 'corbeau',
    title: 'Le Corbeau et le Renard',
    author: 'Jean de La Fontaine',
    hint: 'dès le CE1',
    lines: [
      'Maître Corbeau, sur un arbre perché,',
      'Tenait en son bec un fromage.',
      'Maître Renard, par l\'odeur alléché,',
      'Lui tint à peu près ce langage :',
      '« Hé ! bonjour, Monsieur du Corbeau.',
      'Que vous êtes joli ! que vous me semblez beau !',
      'Sans mentir, si votre ramage',
      'Se rapporte à votre plumage,',
      'Vous êtes le Phénix des hôtes de ces bois. »',
      'À ces mots le Corbeau ne se sent pas de joie ;',
      'Et pour montrer sa belle voix,',
      'Il ouvre un large bec, laisse tomber sa proie.',
      'Le Renard s\'en saisit, et dit : « Mon bon Monsieur,',
      'Apprenez que tout flatteur',
      'Vit aux dépens de celui qui l\'écoute :',
      'Cette leçon vaut bien un fromage, sans doute. »',
      'Le Corbeau, honteux et confus,',
      'Jura, mais un peu tard, qu\'on ne l\'y prendrait plus.',
    ],
  },
  {
    id: 'grenouille',
    title: 'La Grenouille qui se veut faire aussi grosse que le Bœuf',
    author: 'Jean de La Fontaine',
    hint: 'CE2, CM1',
    lines: [
      'Une Grenouille vit un Bœuf',
      'Qui lui sembla de belle taille.',
      'Elle, qui n\'était pas grosse en tout comme un œuf,',
      'Envieuse, s\'étend, et s\'enfle, et se travaille,',
      'Pour égaler l\'animal en grosseur,',
      'Disant : « Regardez bien, ma sœur ;',
      'Est-ce assez ? dites-moi ; n\'y suis-je point encore ?',
      '— Nenni. — M\'y voici donc ? — Point du tout. — M\'y voilà ?',
      '— Vous n\'en approchez point. » La chétive pécore',
      'S\'enfla si bien qu\'elle creva.',
      'Le monde est plein de gens qui ne sont pas plus sages :',
      'Tout bourgeois veut bâtir comme les grands seigneurs,',
      'Tout petit prince a des ambassadeurs,',
      'Tout marquis veut avoir des pages.',
    ],
  },
  {
    id: 'manteau',
    title: 'Le temps a laissé son manteau',
    author: 'Charles d\'Orléans',
    hint: 'CE1, CE2',
    lines: [
      'Le temps a laissé son manteau',
      'De vent, de froidure et de pluie,',
      'Et s\'est vêtu de broderie,',
      'De soleil luisant, clair et beau.',
      'Il n\'y a bête ni oiseau',
      'Qu\'en son jargon ne chante ou crie :',
      'Le temps a laissé son manteau',
      'De vent, de froidure et de pluie.',
      'Rivière, fontaine et ruisseau',
      'Portent, en livrée jolie,',
      'Gouttes d\'argent d\'orfèvrerie ;',
      'Chacun s\'habille de nouveau :',
      'Le temps a laissé son manteau.',
    ],
  },
  {
    id: 'aube',
    title: 'Demain, dès l\'aube',
    author: 'Victor Hugo',
    hint: 'CM1, CM2',
    lines: [
      'Demain, dès l\'aube, à l\'heure où blanchit la campagne,',
      'Je partirai. Vois-tu, je sais que tu m\'attends.',
      'J\'irai par la forêt, j\'irai par la montagne.',
      'Je ne puis demeurer loin de toi plus longtemps.',
      'Je marcherai les yeux fixés sur mes pensées,',
      'Sans rien voir au dehors, sans entendre aucun bruit,',
      'Seul, inconnu, le dos courbé, les mains croisées,',
      'Triste, et le jour pour moi sera comme la nuit.',
      'Je ne regarderai ni l\'or du soir qui tombe,',
      'Ni les voiles au loin descendant vers Harfleur,',
      'Et quand j\'arriverai, je mettrai sur ta tombe',
      'Un bouquet de houx vert et de bruyère en fleur.',
    ],
  },
  {
    id: 'automne',
    title: 'Chanson d\'automne',
    author: 'Paul Verlaine',
    hint: 'CE2 à CM2',
    lines: [
      'Les sanglots longs',
      'Des violons',
      'De l\'automne',
      'Blessent mon cœur',
      'D\'une langueur',
      'Monotone.',
      'Tout suffocant',
      'Et blême, quand',
      'Sonne l\'heure,',
      'Je me souviens',
      'Des jours anciens',
      'Et je pleure ;',
      'Et je m\'en vais',
      'Au vent mauvais',
      'Qui m\'emporte',
      'Deçà, delà,',
      'Pareil à la',
      'Feuille morte.',
    ],
  },
  {
    id: 'toit',
    title: 'Le ciel est, par-dessus le toit',
    author: 'Paul Verlaine',
    hint: 'CM1 à 6e',
    lines: [
      'Le ciel est, par-dessus le toit,',
      'Si bleu, si calme !',
      'Un arbre, par-dessus le toit,',
      'Berce sa palme.',
      'La cloche, dans le ciel qu\'on voit,',
      'Doucement tinte.',
      'Un oiseau sur l\'arbre qu\'on voit',
      'Chante sa plainte.',
      'Mon Dieu, mon Dieu, la vie est là,',
      'Simple et tranquille.',
      'Cette paisible rumeur-là',
      'Vient de la ville.',
      '— Qu\'as-tu fait, ô toi que voilà',
      'Pleurant sans cesse,',
      'Dis, qu\'as-tu fait, toi que voilà,',
      'De ta jeunesse ?',
    ],
  },
  {
    id: 'pleure',
    title: 'Il pleure dans mon cœur',
    author: 'Paul Verlaine',
    hint: 'CM2, collège',
    lines: [
      'Il pleure dans mon cœur',
      'Comme il pleut sur la ville ;',
      'Quelle est cette langueur',
      'Qui pénètre mon cœur ?',
      'Ô bruit doux de la pluie',
      'Par terre et sur les toits !',
      'Pour un cœur qui s\'ennuie,',
      'Ô le chant de la pluie !',
      'Il pleure sans raison',
      'Dans ce cœur qui s\'écœure.',
      'Quoi ! nulle trahison ?...',
      'Ce deuil est sans raison.',
      'C\'est bien la pire peine',
      'De ne savoir pourquoi',
      'Sans amour et sans haine',
      'Mon cœur a tant de peine !',
    ],
  },
  {
    id: 'dormeur',
    title: 'Le Dormeur du val',
    author: 'Arthur Rimbaud',
    hint: 'collège',
    lines: [
      'C\'est un trou de verdure où chante une rivière,',
      'Accrochant follement aux herbes des haillons',
      'D\'argent ; où le soleil, de la montagne fière,',
      'Luit : c\'est un petit val qui mousse de rayons.',
      'Un soldat jeune, bouche ouverte, tête nue,',
      'Et la nuque baignant dans le frais cresson bleu,',
      'Dort ; il est étendu dans l\'herbe, sous la nue,',
      'Pâle dans son lit vert où la lumière pleut.',
      'Les pieds dans les glaïeuls, il dort. Souriant comme',
      'Sourirait un enfant malade, il fait un somme :',
      'Nature, berce-le chaudement : il a froid.',
      'Les parfums ne font pas frissonner sa narine ;',
      'Il dort dans le soleil, la main sur sa poitrine,',
      'Tranquille. Il a deux trous rouges au côté droit.',
    ],
  },
  {
    id: 'boheme',
    title: 'Ma Bohème',
    author: 'Arthur Rimbaud',
    hint: 'collège',
    lines: [
      'Je m\'en allais, les poings dans mes poches crevées ;',
      'Mon paletot aussi devenait idéal ;',
      'J\'allais sous le ciel, Muse ! et j\'étais ton féal ;',
      'Oh ! là ! là ! que d\'amours splendides j\'ai rêvées !',
      'Mon unique culotte avait un large trou.',
      '— Petit-Poucet rêveur, j\'égrenais dans ma course',
      'Des rimes. Mon auberge était à la Grande-Ourse.',
      '— Mes étoiles au ciel avaient un doux frou-frou',
      'Et je les écoutais, assis au bord des routes,',
      'Ces bons soirs de septembre où je sentais des gouttes',
      'De rosée à mon front, comme un vin de vigueur ;',
      'Où, rimant au milieu des ombres fantastiques,',
      'Comme des lyres, je tirais les élastiques',
      'De mes souliers blessés, un pied près de mon cœur !',
    ],
  },
  {
    id: 'mirabeau',
    title: 'Le Pont Mirabeau',
    author: 'Guillaume Apollinaire',
    hint: 'collège',
    lines: [
      'Sous le pont Mirabeau coule la Seine',
      'Et nos amours',
      'Faut-il qu\'il m\'en souvienne',
      'La joie venait toujours après la peine',
      'Vienne la nuit sonne l\'heure',
      'Les jours s\'en vont je demeure',
      'Les mains dans les mains restons face à face',
      'Tandis que sous',
      'Le pont de nos bras passe',
      'Des éternels regards l\'onde si lasse',
      'Vienne la nuit sonne l\'heure',
      'Les jours s\'en vont je demeure',
      'L\'amour s\'en va comme cette eau courante',
      'L\'amour s\'en va',
      'Comme la vie est lente',
      'Et comme l\'Espérance est violente',
      'Vienne la nuit sonne l\'heure',
      'Les jours s\'en vont je demeure',
      'Passent les jours et passent les semaines',
      'Ni temps passé',
      'Ni les amours reviennent',
      'Sous le pont Mirabeau coule la Seine',
      'Vienne la nuit sonne l\'heure',
      'Les jours s\'en vont je demeure',
    ],
  },
  {
    id: 'mignonne',
    title: 'Mignonne, allons voir si la rose',
    author: 'Pierre de Ronsard',
    hint: 'collège',
    lines: [
      'Mignonne, allons voir si la rose',
      'Qui ce matin avait déclose',
      'Sa robe de pourpre au soleil,',
      'A point perdu cette vesprée',
      'Les plis de sa robe pourprée,',
      'Et son teint au vôtre pareil.',
      'Las ! voyez comme en peu d\'espace,',
      'Mignonne, elle a dessus la place,',
      'Las, las ! ses beautés laissé choir !',
      'Ô vraiment marâtre Nature,',
      'Puisqu\'une telle fleur ne dure',
      'Que du matin jusques au soir !',
      'Donc, si vous me croyez, mignonne,',
      'Tandis que votre âge fleuronne',
      'En sa plus verte nouveauté,',
      'Cueillez, cueillez votre jeunesse :',
      'Comme à cette fleur, la vieillesse',
      'Fera ternir votre beauté.',
    ],
  },
];

/** Sans accents, sans majuscules, sans ponctuation : pour comparer ce que tape le parent */
export function fold(s: string): string {
  return s
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9 ]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

/** Cherche par titre ou auteur : tous les mots tapés doivent se retrouver dans le titre ou l'auteur */
export function searchPoems(query: string): Poem[] {
  const words = fold(query).split(' ').filter((w) => w.length > 1);
  if (words.length === 0) return POEMS;
  return POEMS.filter((p) => {
    const hay = `${fold(p.title)} ${fold(p.author)}`;
    return words.every((w) => hay.includes(w));
  });
}
